### DISCUSSION TITLE
Can't get blinking to work on both states

### DISCUSSION THREAD

**Discussion by ra-dave** [custom-cards/button-card#748] [Q&A]
I want my icon to blink some number of times whenever it changes state.  It works fine if I only blink on one state but when I try both states it doesn't blink at all.  I'm thinking the timer logic is not resetting or something like that.  Anything wrong with my YAML below or is this a bug?

```
aspect_ratio: 1.2/1
color_type: icon
entity: binary_sensor.front_door_contact
name: Front
show_name: true
show_state: false
state:
  - color: rgb(0, 255, 0)
    icon: mdi:door
    styles:
      icon:
        - animation: blink 1s ease 3
    value: 'off'
  - color: rgb(255, 0, 0)
    icon: mdi:door-open
    styles:
      icon:
        - animation: blink 1s ease 3
    value: 'on'
type: custom:button-card
```
