### DISCUSSION TITLE
Is it possible to have nested templates, use a variable that set in a previous template?

### DISCUSSION THREAD

**Discussion by andyblac** [custom-cards/button-card#767] [General]
by this i mean

```
template1:
  variables:
    ulm_card_room_color: "theme"
    ulm_card_room_sensor_color: "[[[ return variables.ulm_card_room_sensor_color ? variables.ulm_card_room_sensor_color : variables.ulm_card_room_color; ]]]"
    ulm_card_room_sensor_color_on: "[[[return variables?.ulm_card_room_sensor_color_on ? variables.ulm_card_room_sensor_color_on : variables.ulm_card_room_sensor_color; ]]]"

template2:
  template:
    - "template1"

template3:
  template:
    - "template1"
```

but if I change the value of `ulm_card_room_color` in template2, have it reflect the change in template3 as well. template3 is a card that is used inside template2.

**Comment by andyblac** [comment]
basically what I am after is a Global Variable, that can be used anywhere. from root down.

**Comment by andyblac** [comment]
to answer my own question incase any want to know i managed to pass the variable into the next by doing

the 3rd template is called `card_andyblac_room_sensor_icon`
```
  custom_fields:
    s1:
      card:
        type: "custom:button-card"
        icon: "[[[ return variables?.sensor_1?.icon ]]]"
        template: >
          [[[
            let templates = [ 'card_andyblac_room_sensor_icon' ];
            if (variables?.sensor_1?.templates?.length) {
              templates.push(...variables.sensor_1.templates);
            }
            return templates;
          ]]]
        variables: >
          [[[
            let variables_tmp = variables.sensor_1;
            if (variables?.sensor_1) {
              variables_tmp['ulm_card_room_color'] = variables.ulm_card_room_color;
            }
            return variables_tmp;
          ]]]
        state:
          - operator: "template"
            value: "[[[ return !variables.sensor_1; ]]]"
            styles:
              card:
                - display: "none"
        entity: "[[[ return variables?.sensor_1?.entity_id; ]]]"
```

**Comment by andyblac** [comment]
here is a template example:

```
---
custom_card_andyblac_scene:
  # 1.2
  template:
    - "ulm_translation_engine"
  variables:
    ulm_custom_card_andyblac_scene_color: "theme"
  tap_action:
    action: "more-info"
  show_icon: false
  show_name: true
  show_label: false
  show_state: true
  state_display: "[[[ return helpers.relativeTime(entity.state); ]]]"
  aspect_ratio: "1/0.35"
  styles:
    name:
      - position: "absolute"
      - font-weight: "bold"
      - font-size: "16px"
      - margin-top: "5%"
      - margin-left: "33%"
      - margin-right: "20px"
      - margin-bottom: "10%"
      - max-width: "65%"
      - text-overflow: "ellipsis"
      - overflow: "hidden"
      - align-self: start
    state:
      - position: "absolute"
      - font-weight: "bold"
      - font-size: "15px"
      - filter: "opacity(40%)"
      - margin-top: "17%"
      - margin-left: "33%"
      - margin-right: "20px"
      - margin-bottom: "7%"
      - max-width: "65%"
      - text-overflow: "ellipsis"
      - overflow: "hidden"
      - align-self: start
    grid:
      - grid-template-areas: "'i n' 'i l'"
      - grid-template-columns: "min-content auto"
      - grid-template-rows: "min-content min-content"
    card:
      - border-radius: "15px"
      - box-shadow: "var(--box-shadow)"
      - padding: "5px"
    custom_fields:
      icon: &custom_card_andyblac_scene_widget_styling
        - position: "absolute"
        - left: "-6%"
        - top: "18%"
        - width: "35%"

  custom_fields:
    icon:
      card:
        type: "custom:button-card"
        entity: "[[[ return entity.entity_id; ]]]"
        template: >
          [[[
            let templates = [ 'custom_card_andyblac_scene_widget' ];
            if (variables?.scene?.templates?.length) {
              templates.push(...variables.scene.templates);
            }
            return templates;
          ]]]
        variables: >
          [[[
            let variables_tmp = {};
            variables_tmp['ulm_custom_card_andyblac_scene_color'] = variables.ulm_custom_card_andyblac_scene_color;
            return variables_tmp;
          ]]]

custom_card_andyblac_scene_widget:
  tap_action:
    action: "call-service"
    service: "scene.turn_on"
    service_data:
      entity_id: "[[[ return entity.entity_id ]]]"
  size: "15px"
  show_icon: true
  show_name: false
  show_state: false
  aspect_ratio: "1/1"
  styles:
    icon:
      - color: "[[[ return 'rgba(var(--color-'+variables.ulm_custom_card_andyblac_scene_color+'),0.9)'; ]]]"
      - width: "50%"
      - place-self: "stretch:stretch"
    img_cell:
      - position: "absolute"
      - width: "100%"
      - height: "100%"
      - border-radius: "50%"
      - background-color: "[[[ return 'rgba(var(--color-'+variables.ulm_custom_card_andyblac_scene_color+'),0.2)'; ]]]"
    card:
      - height: "100%"
      - background: "none"
      - box-shadow: "none"
      - padding: "0px"
      - border-radius: "50%"
```

and a card to use it.
```
      - type: custom:button-card
        template: custom_card_andyblac_scene
        entity: scene.good_morning
        variables:
          ulm_custom_card_andyblac_scene_color: yellow
```
