### DISCUSSION TITLE
A little help needed on input_select and button cards

### DISCUSSION THREAD

**Discussion by jlucas090866** [custom-cards/button-card#775] [General]
Hi Newbie on the block - I've created via the helper input_select.housemode with options of Home, Away, Vacation & Night.

I've created a grid card with 4 custom buttons:

```
square: false
type: grid
cards:
  - type: custom:button-card
    tap_action:
      action: call-service
      service: input_select.select_option
      service_data:
        entity_id: input_select.housemode
        option: Home
    entity: input_select.housemode
    hold_action:
      action: none
    icon: mdi:home
    name: Home
    color: var(--paper-item-icon-color)
    state:
      - value: Home
        color: var(--paper-item-icon-active-color)
  - type: custom:button-card
    tap_action:
      action: call-service
      service: input_select.select_option
      service_data:
        entity_id: input_select.housemode
        option: Night
    entity: input_select.housemode
    icon: mdi:weather-night
    name: Night
    color: var(--paper-item-icon-color)
    state:
      - value: Night
        color: var(--paper-item-icon-active-color)
  - type: custom:button-card
    tap_action:
      action: call-service
      service: input_select.select_option
      service_data:
        entity_id: input_select.housemode
        option: Away
    entity: input_select.housemode
    icon: mdi:shield-lock
    name: Away
    color: var(--paper-item-icon-color)
    state:
      - value: Away
        color: var(--paper-item-icon-active-color)
  - type: custom:button-card
    tap_action:
      action: call-service
      service: input_select.select_option
      service_data:
        entity_id: input_select.housemode
        option: Vacation
    entity: input_select.housemode
    icon: mdi:beach
    name: Vacation
    color: var(--paper-item-icon-color)
    state:
      - value: Vacation
        color: var(--paper-item-icon-active-color)
columns: 4
```

However I'm getting the following error when selecting a button "Failed to call service inout_select/select_option. Invalid option: Night (possible options: Home)"

My error log shows:

Logger: homeassistant.components.websocket_api.http.connection
Source: components/input_select/__init__.py:304
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 10:09:55 (10 occurrences)
Last logged: 11:29:51

[548210288192] Invalid option: Home (possible options: Night)
[547764661312] Invalid option: Home (possible options: Night)
[547764661312] Invalid option: Night (possible options: Home)
[547764661312] Invalid option: Away (possible options: Home)
[547764661312] Invalid option: Vacation (possible options: Home)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 227, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1969, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2006, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/input_select/__init__.py", line 304, in async_select_option
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Invalid option: Home (possible options: Night)

Any thoughts?
