### DISCUSSION TITLE
multi_calls help! notify.mobile_app

### DISCUSSION THREAD

**Discussion by Bellavista** [custom-cards/button-card#776] [Q&A]
Hi all, I need help, I would like to send two service commands when I touch a button... 
I understand that it is possible with multiple calls using the javascript model but I'm a beginner. 
I would like to send first
```
tap_action:
  action: call-service
  service: notify.mobile_app_telefono_xxxxxxx
  data:
    message: command_volume_level
    data:
      media_stream: ring_stream
      command: 15
```
then

```
tap_action:
  action: call-service
  service: notify.mobile_app_telefono_xxxxxxx
  data:
    message: command_update_sensors
```
i'm trying, to start whit....but noting
```
tap_action:
  action: nothing
  multi_calls: |
    [[[
      hass.callService('notify', 'notify', { 
      entity_id: 'mobile_app_telefono_xxxxxxx' , message= 'command_update_sensors' }
      );
    ]]]
```
please help me
