### DISCUSSION TITLE
change the state of another entity

### DISCUSSION THREAD

**Discussion by alexblav** [custom-cards/button-card#780] [Q&A]
Hello,

First of all, thank you and congratulations on a job well done!

I'm trying to change the state of an entity according to the state of a first entity.
I've tried this:

``` YAML
type: custom:button-card
show_name: true
show_icon: false
variables:
  entity: input_boolean.volets_auto_matin_global
styles:
  card:
    - height: 25px
    - background-color: '#CCFFCC'
    - color: rgb(38, 128, 199)
    - width: 100px
tap_action:
  action: toggle
show_state: false
entity: '[[[ return variables.entity; ]]]'
state:
  - value: 'on'
    styles:
      card:
        - color: rgb(38, 128, 199)
  - value: 'off'
    styles:
      card:
        - color: '#FF0000'
name: |
  [[[
    if (entity.state == "on"){
      ['input_boolean.volets_auto_offset_matin_global'].state = "on";
      return "Matin offset";
    } else{
      ['input_boolean.volets_auto_offset_matin_global'].state = "off";
      return "Matin";
    }
  ]]]
hold_action:
  action: none
```
The button's name changes, but 'volets_auto_offset_matin_global's status doesn't. Which syntax should I use, if possible?

Thanks
