### DISCUSSION TITLE
How to display an HA timer countdown in a notification: section?

### DISCUSSION THREAD

**Discussion by danielbrunt57** [custom-cards/button-card#792] [Q&A] [answered]
HA timer entities states are either `active` or `idle `and when the entity is displayed via entities card the state is magically transformed into a countdown by some internal computation using `now()` and the attribute `finishes_at`, which is removed when timer is "idle".
I can get the button-card's overall state to display the countdown by using `entity: timer.bathroom_light_timer` & `show_state: true` but I do not want that!  I'd like to display the countdown in a notification are but can't figure out the javascript.
![image](https://github.com/custom-cards/button-card/assets/49846893/c0e37c5c-e246-4e35-8326-93a59edcf6ed)

![image](https://github.com/custom-cards/button-card/assets/49846893/8a82cde5-c250-40b6-ba5f-a881a22f804d)

My failed attempt thus far:
```
type: custom:button-card
name: Bathroom
icon: mdi:vanity-light
entity: light.bathroom_light
tap_action:
  action: navigate
  navigation_path: /lovelace/bathroom
show_state: false
styles:
  grid:
    - position: relative
  custom_fields:
    notification1:
      - background-color: |
          [[[
            if (states['binary_sensor.bathroom_occupancy'].state == 'off')
              return "";
            return "";
          ]]]
      - border-radius: 10%
      - position: absolute
      - left: 5%
      - top: 25%
      - height: 30px
      - width: 30px
      - font-size: 6px
      - line-height: 25px
    notification2:
      - background-color: |
          [[[
            if (states['timer.bathroom_light'].state == 'idle')
              return "";
            return "green";
          ]]]
      - border-radius: 50%
      - position: absolute
      - left: 75%
      - top: 10%
      - height: 25px
      - width: 25px
      - font-size: 8px
      - line-height: 25px
custom_fields:
  notification1: |
    [[[
      if (states['binary_sensor.bathroom_occupancy'].state == 'on')
        return `<ha-icon
        icon="mdi:motion-sensor"
        style="width: 22px; height: 22px; color: yellow;">
        </ha-icon>`
      return "";
    ]]]
  notification2: |
    [[[ 
      if (states['timer.bathroom_light'].attributes.finishes_at)
        return helpers.formatDateTime(timer.bathroom_light.attribute.finishes_at);
      return helpers.formatDateTime(timer.bathroom_light.attribute.finishes_at);
    ]]]
```
A simple text display works:
```
type: custom:button-card
name: Bathroom
icon: mdi:vanity-light
entity: light.bathroom_light
tap_action:
  action: navigate
  navigation_path: /lovelace/bathroom
show_state: false
styles:
  grid:
    - position: relative
  custom_fields:
    notification1:
      - background-color: |
          [[[
            if (states['binary_sensor.bathroom_occupancy'].state == 'off')
              return "";
            return "";
          ]]]
      - border-radius: 10%
      - position: absolute
      - left: 5%
      - top: 25%
      - height: 30px
      - width: 30px
      - font-size: 6px
      - line-height: 25px
    notification2:
      - background-color: |
          [[[
            if (states['timer.bathroom_light'].state == 'idle')
              return "";
            return "green";
          ]]]
      - border-radius: 50%
      - position: absolute
      - left: 75%
      - top: 10%
      - height: 25px
      - width: 25px
      - font-size: 8px
      - line-height: 25px
custom_fields:
  notification1: |
    [[[
      if (states['binary_sensor.bathroom_occupancy'].state == 'on')
        return `<ha-icon
        icon="mdi:motion-sensor"
        style="width: 22px; height: 22px; color: yellow;">
        </ha-icon>`
      return "";
    ]]]
  notification2: |
    [[[ 
      if (states['timer.bathroom_light'].state == 'idle')
        return ' ';
      return 'Active';
    ]]]
```

**Comment by ngocjohn** [comment, marked as answer]
there is a workaround for it, use another button card as a custom fields. here is an example, just play with css according to your needs. 

![CleanShot 2023-10-28 at 15 58 19](https://github.com/custom-cards/button-card/assets/96962827/77ebc481-7c8a-4463-8860-6553f425ff4a)
```

      custom_fields:
        timer:
          card:
            type: custom:button-card
            entity: timer.dishwasher_remaining
            aspect_ratio: 1/1
            show_icon: false
            show_state: true
            show_name: false
      styles:
        custom_fields:
          timer:
            - display: block
            - position: absolute
            - top: '-10%'
            - right: 0%
            - width: 45%
            - background-color: 'rgb(3, 169, 244)'
            - border-radius: 50%
```

**Reply by danielbrunt57** [reply]
Thank you!  That did the trick!

![image](https://github.com/custom-cards/button-card/assets/49846893/a1d3244d-af58-4f56-b9ab-8927c0af766c)

![image](https://github.com/custom-cards/button-card/assets/49846893/848eb5d6-05d5-4049-a9bf-41b466150777)

![image](https://github.com/custom-cards/button-card/assets/49846893/01c2c951-26a7-4773-9f57-60a2e8b0654f)
```
      - type: custom:button-card
        name: Bathroom
        icon: mdi:vanity-light
        entity: light.bathroom_light
        show_state: false
        tap_action:
          action: navigate
          navigation_path: /lovelace/bathroom
        custom_fields:
          motion: |
            [[[
              if (states['binary_sensor.bathroom_occupancy'].state == 'on')
                return `<ha-icon
                icon=mdi:motion-sensor
                style="width: 22px; height: 22px; color: yellow;">
                </ha-icon>`
              return "";
            ]]]
          timer:
            card:
              type: custom:button-card
              entity: timer.bathroom_light
              aspect_ratio: 1/1
              show_icon: false
              show_name: false
              show_state: |
                [[[
                  if (states['timer.bathroom_light'].state == 'active')
                    return true;
                  return false;
                ]]]
              styles:
                card:
                  - border: none
                state:
                  - font-size: 70%
                  - color: yellow
        styles:
          custom_fields:
            motion:
              - display: block
              - position: absolute
              - top: 30%
              - left: 2%
              - width: 30%
              - height: 30%
            timer:
              - display: block
              - position: absolute
              - top: 20%
              - right: 2%
              - width: 30%
              - height: 30%
```
