### DISCUSSION TITLE
show livestream as background of button card

### DISCUSSION THREAD

**Discussion by Nemesis24** [custom-cards/button-card#822] [Q&A] [answered]
```
- type: custom:button-card
   entity: camera.porte_sud
   show_live_stream: true
   show_name: false
```
![image](https://github.com/custom-cards/button-card/assets/25956796/4edd7770-22c7-4461-ac1c-7adc5b7aefd7)

how can i have the livestream getting 100% of the button card ?

tx for answers

**Comment by Mariusthvdb** [comment, marked as answer]
```
type: custom:button-card
entity: camera.buienradar
show_live_stream: true
show_name: false
size: 100%
styles:
  card:
    - padding: 0
```
