### DISCUSSION TITLE
Delayed click response or none at all!

### DISCUSSION THREAD

**Discussion by Trzinka** [custom-cards/button-card#857] [Q&A]
Hi!

I have made a switch (Shelly 1PM which isn't the only one I have) to turn on the air conditioner, which mostly does not work when clicked or is very delayed!
![StikaloKlima](https://github.com/user-attachments/assets/b8a94d89-5c1d-4b7a-9ee6-e4077ae855e0)

My settings:
```yaml
type: custom:button-card
entity: switch.me_kl
tap_action:
  action: toggle
name: Klima
label: |
  [[[
    if (states['switch.me_kl'].state === "on")
      return "Vklopljen";
    else if (states['switch.me_kl'].state === "off")
      return "Izklopljen";
  ]]]
show_state: false
show_label: true
show_entity_picture: true
state:
  - value: 'off'
    icon: mdi:power-plug-off-outline
    color: green
  - value: 'on'
    icon: mdi:power-plug
    color: red
card_mod:
  style: |
    ha-card {
      background: #ff813d !important;
    }
```

**What could be wrong?**
