### DISCUSSION TITLE
hold_action repeat in embedded button-card stops when icon color changes

### DISCUSSION THREAD

**Discussion by ll3141** [custom-cards/button-card#872] [Q&A]
I'm trying to build a button-card with embedded button-cards to control a esphome cover.
My final goal ist to create a button-card-template, but first things first :-)

tap_action is set to stop cover motion, double_tap_action to open it.
The hold_action is used to call a script on the esp starts opening the cover, waits 250ms, then stops the cover.
The script is set to restart when called repeatedly. That means that as long as the hold_action reruns the script fast enough, the cover stop command will not be reached. Therefore the cover is moving as long as the GUI-button is pressed.
Using this method is safer because it does not depend on a stop command from HA coming though.

There is only one embedded up-button in the moment to keep it simple, and the actions of the container button are only in place to demonstrate the differing handling of repeat in the embedded button.

Both buttons work as described ... mostly.
Holding the embedded button down runs the script only once, resulting in the Icon color of outer and embedded button flashing to yellow and the cover moving only for 250ms.
If the icon color change code in the embedded button is removed, repeat work for the embedded button.

I'm not sure if this is a bug or a feature.

**Update**
replacing
```
styles:
  icon:
    - color: '[[[ return (entity.state == "opening") ? "yellow" : "red"; ]]]'
```
with
```
styles:
  icon:
    - color: red
state:
  - value: opening
    styles:
      icon:
        - color: yellow
```
does the job ... even in the templated version

**updated update**
sadly the "workaround" only works for state related formating.

changing background style based on entity.attributes.current_position also brakes hold_action repeat in the embedded card
```
styles:
  card:
    - background: >-
        [[[ return `linear-gradient(180deg, gray 0 ${entity?.attributes.current_position}%, lightblue 0)`; ]]]
```
**update end**

```
type: custom:button-card
icon: mdi:arrow-up-thin
show_name: false
entity: cover.d1_mini_emp_cover_1
styles:
  icon:
    - color: '[[[ return (entity.state == "opening") ? "yellow" : "red"; ]]]'
tap_action:
  action: perform-action
  perform_action: cover.stop_cover
  target:
    entity_id: cover.d1_mini_emp_cover_1
double_tap_action:
  action: perform-action
  perform_action: cover.open_cover
  target:
    entity_id: cover.d1_mini_emp_cover_1
hold_action:
  repeat: 150
  action: call-service
  service: esphome.d1_mini_emp_cover_hold
custom_fields:
  sub_btn:
    card:
      type: custom:button-card
      icon: mdi:arrow-up-thin
      show_name: false
      styles:
        icon:
          - color: '[[[ return (entity.state == "opening") ? "yellow" : "red"; ]]]'
      tap_action:
        action: perform-action
        perform_action: cover.stop_cover
        target:
          entity_id: cover.d1_mini_emp_cover_1
      double_tap_action:
        action: perform-action
        perform_action: cover.open_cover
        target:
          entity_id: cover.d1_mini_emp_cover_1
      hold_action:
        repeat: 150
        action: call-service
        service: esphome.d1_mini_emp_cover_hold
```

**esphome**
```
api:
  services:
    - service: cover_hold
      variables:
        coverNr:   int
        direction: bool
      then:
      - script.execute:
          id: cover_hold_scr

script:
  - id: cover_hold_scr
    mode: restart
    then:
      - cover.open: cover_1
      - delay: 250ms
      - cover.stop: cover_1
```
