### DISCUSSION TITLE
Issue with displaying other cards inside of custom-button card

### DISCUSSION THREAD

**Discussion by JaroslawPrzybyl** [custom-cards/button-card#885] [Q&A]
From a long time Im using popular solution to group cards using custom-button card as a container. It's an easy way to keep entities it together, with styles, frames, backgrounds etc. Here is one of such a cards from my frontend as example:

![image](https://github.com/user-attachments/assets/0498feb0-fe3c-4800-8930-f1c18864cd8b)

Unfortunately near from the beginning of implementing this solution, I started experiencing issues with displaying my dashboard, on web page and android app the same: first tab is very often not fully downloaded. No errors in log, no errors on the page, just empty dashboard. Reload (or kill the android app and start again) and everything is ok. Or not. Sometimes one reload is enough, sometimes I have to do it few times. And always only first tab of frontend is affected. 
Last time i spent some time with this issue and as I found, it is connected with custom-button card used as a container. Simply: there is a container: there is an issue. No container - no issue. 
Especially for investigating I built simple dashboard without styles etc, it looks awful but issue still is visible. Here is a code:

```yaml
type: grid
cards:
  - type: custom:button-card
    custom_fields:
      sensor:
        card:
          type: vertical-stack
          cards:
            - type: custom:mushroom-title-card
              title: Hello
              alignment: center
            - type: horizontal-stack
              cards:
                - type: grid
                  columns: 4
                  square: true
                  cards:
                    - type: custom:mushroom-person-card
                      entity: person.jarek
                    - type: custom:mushroom-person-card
                      entity: person.asia
  - type: vertical-stack
    cards:
      - type: custom:mushroom-title-card
        title: Hello
        alignment: center
      - type: horizontal-stack
        cards:
          - type: grid
            columns: 4
            square: true
            cards:
              - type: custom:mushroom-person-card
                entity: person.jarek
                secondary_info: last-changed
              - type: custom:mushroom-person-card
                entity: person.asia

```

The same verical stack with the same content, first as a container in custom-button, second: standalone.
How it looks when everything is fine:

![image](https://github.com/user-attachments/assets/a6880320-f864-4a89-a579-9b6cabf50043)

And most often when page is opened at first time, or just after reloading:

![image](https://github.com/user-attachments/assets/205534d4-e9bb-4cce-8387-71ebf92df1ad)

As you see first half of code, where custom-button is used as a container is not displayed here. I can reload one more time and it will be again ok or I can also just wait. Sometimes a minute, sometimes 10 min and lacking content will be displayed also. 
And when I look at DevTool, Netowrk, I can see that everything is downloaded, but websocket is still in "waiting" ("oczekuje" in my language) state:

![image](https://github.com/user-attachments/assets/8759b553-a2ad-493a-878e-ce7c7ec13fe6)

and mentioned line 73:

![image](https://github.com/user-attachments/assets/54c6390c-27f2-4b17-8730-9f1d81da62dc)
 I haven't enough knowledge to investigate it deeper, any help would be appreciated.
