### DISCUSSION TITLE
States not updating when using template

### DISCUSSION THREAD

**Discussion by dmarkscouk** [custom-cards/button-card#889] [General]
Hello, I'm using the custom button card in a slightly unusual way and thus have turned it into a template so that I don't have to have reams repetition of code for each instance of it (20 or so).

In doing so I've found that the **states do not update for anything that is not listed as an entity** in the card.

So this card does not update the charge status:
```
type: custom:button-card
template: battery_status
name: _Car
variables:
  battery_entity: sensor.mirror_battery_level
  charging_entity: binary_sensor.mirror_is_charging
```

I can fix that by listing the entity in the card (I'd rather not, but this is ok):
```
type: custom:button-card
template: battery_status
entity: binary_sensor.mirror_is_charging
name: _Car
variables:
  battery_entity: sensor.mirror_battery_level
  charging_entity: binary_sensor.mirror_is_charging
```

The issue I'm now having is that I can only list a single entity per card, but want more than 1 state to be updated when things change. IE: I also want the card to display `sensor.mirror_battery_level` to update:

I tried this, but it breaks:
```
entities:
  - entity: binary_sensor.mirror_is_charging
  - entity: binary_sensor.mirror_is_charging
```

**Thankyou in advance for any help.**

I'm not sure if it's relevant, but this is my template code:
```
button_card_templates:
  battery_status:
    show_icon: false
    show_state: false
    show_label: false
    custom_fields:
      batterylevel: |
        [[[
          var batterylevel = states[variables.battery_entity].state
          if (batterylevel == 100) {
            return "_";
          } else {
            var batterylevel = parseFloat(batterylevel) / 100; 
            return batterylevel.toFixed(2).replace(/^0+/, '');
          }
        ]]]
      plugged: |
        [[[
          var plugged = states[variables.charging_entity].state
          if (plugged == 'on') {
            return ' - Charging';
          } else {
            return ' ';
          }
        ]]]
    styles:
      grid:
        - grid-template-areas: '"n batterylevel plugged"'
        - grid-template-rows: min-content
        - grid-template-columns: min-content min-content auto
      card:
        - border-radius: 0px
        - border: none
        - padding: 0px
        - margin: 0px
      name:
        - justify-self: start
        - align-self: end
        - color: var(--green-text-color)
        - font-size: var(--font-size)
        - font-weight: var(--font-weight)
        - text-align: left
      custom_fields:
        batterylevel:
          - justify-self: start
          - align-self: end
          - color: var(--green-text-color)
          - font-size: var(--font-size)
          - font-weight: var(--font-weight)
          - text-align: left
          - padding: var(--font-padding)
        plugged:
          - justify-self: start
          - align-self: end
          - color: var(--green-text-color)
          - font-size: var(--font-size)
          - font-weight: var(--font-weight)
          - text-align: left
          - padding: var(--font-padding)
```
