### DISCUSSION TITLE
Pass the variable into the code

### DISCUSSION THREAD

**Discussion by IncByteLC** [custom-cards/button-card#905] [General]
Greetings, sorry for the bump question first of all.
I am working person template and want to simplify the code for all family members.
I decided to template and just define a few variables for each person.. 

This is what I have in the template:
```
button_card_templates:
   face_card:
     variables:
        entity_person: person.person1
        name: Name1
        show_entity_picture: false
        show_name: true
        path: '#name1_details'
	badge: sensor.name1_badge
```

The issue is here:
```
custom_fields:
		icon:
		  - filter: |
			  [[[ var l = states['sensor.name1_badge'].state;
				if (l == 'Home') return;
				else return "grayscale(100%)"
			  ]]]
```
this part is hardcoded
`states['sensor.name1_badge'].state;`
, but I want to be there a variable from 
`badge: sensor.name1_badge`

So far I am not lucky, can't pass to...
