### DISCUSSION TITLE
Simple Kettle Button with Temperature from Sensor

### DISCUSSION THREAD

**Discussion by mike-kovacs** [custom-cards/button-card#918] [General]
For the life of me, I can't seem to get this Kettle icon to look half-decent!
Can anyone assist? I've been looking at the documentation and also trying to get Copilot help for over an hour...

![image](https://github.com/user-attachments/assets/d37c0136-d0e0-4a94-8fa7-4639f9dedffe)

```
type: custom:button-card
entity: switch.kettle_start
layout: icon_label
name: Kettle
aspect_ratio: 1/1
icon: mdi:kettle-steam-outline
size: 50%
show_state: false
custom_fields:
  state_temp: >
    [[[ return (states['switch.kettle_start'].state === 'on' ? 'On' : 'Off') + ' - ' + states['sensor.kettle_current_temperature'].state + '°C'; ]]]
styles:
  card:
    - height: 150px
    - width: 150px
  custom_fields:
    state_temp:
      - align-self: left
      - justify-self: start
      - font-size: 14px
      - font-weight: bold
```
