### DISCUSSION TITLE
Animation. Spinning fan

### DISCUSSION THREAD

**Discussion by immortalserg** [custom-cards/button-card#920] [Ideas]
![20241303](https://github.com/user-attachments/assets/f196684f-70d4-485f-9fa6-56ee28ef83a6)
```
type: custom:button-card
entity: switch.switch01
name: Туалет
icon: mdi:fan
styles:
  card:
    - width: 100px
    - height: 100px
  icon:
    - width: 100px
    - height: 100px
state:
  - value: "off"
    color: gray
    styles:
      icon:
        - animation: null
  - value: "on"
    color: blue
    styles:
      icon:
        - animation: rotating 2s linear infinite
  ```
