### DISCUSSION TITLE
Pictures

### DISCUSSION THREAD

**Discussion by immortalserg** [custom-cards/button-card#921] [Ideas]
![20241301](https://github.com/user-attachments/assets/b4d0eca1-555f-45dc-b7e4-d3fd0e6bebd9)
images: [img.zip](https://github.com/user-attachments/files/19824406/img.zip)
```
type: custom:button-card
entity: switch.prise05_relay
hold_action:
  action: more-info
show_icon: false
show_name: false
styles:
  card:
    - width: 100px
    - height: auto
    - display: flex
    - flex-direction: column
    - align-items: center
    - justify-content: center
  custom_fields:
    image:
      - align-self: center
    label:
      - font-size: 14px
      - margin-top: 70px
custom_fields:
  image: |
    [[[ 
      const state = entity.state === 'on' ? 'ON' : 'OFF';
      const imagePath = `/local/images/lamp2_${state}.png`; 
      return `&lt;img src="${imagePath}" width="80%" height="80%" /&gt;`;
    ]]]
  label: Кухня
tap_action:
  action: toggle
  ```
