### DISCUSSION TITLE
Full size button image. Example

### DISCUSSION THREAD

**Discussion by EliSchleifer** [custom-cards/button-card#973] [Ideas]
Love the project. I ended up tweaking my styling to provide a full image toggle button.
There wasn't any existing example. Thought it might be nice to include.

        - type: "custom:button-card"
          entity: switch.jasco_products_14288_duplex_receptacle_switch_4
          show_entity_picture: true
          show_name: false
          show_icon: true
          style:
            - padding: 0px
          styles:
            entity_picture:
              - width: 100%
              - padding-bottom: 0%            
          entity_picture: "/local/images/PatioLightsOff.jpg"
          state:
          - value: 'on'
            entity_picture: "/local/images/PatioLightsOn.jpg"

**Comment by RomRider** [comment]
Thanks, I'll integrate this into the documentation!

**Comment by RomRider** [comment]
@EliSchleifer, would you mind sharing a gif of the result please?

**Comment by dvbit** [comment]
[`[](url)`](url)

https://user-images.githubusercontent.com/6599039/203659318-679a84de-b170-47e4-b018-620a152f8583.mp4

here you go

**Comment by jarrah31** [comment]
@dvbit Could you share the code and animated gifs behind the video you've shown please? I'd like to do this too. Thanks.

**Comment by dcapslock** [comment]
@jarrah31 I know this is a bit old, but what I have is the following. This is the [animated image](https://dribbble.com/shots/787974-Switch-Animation). I split it and rotated and adjusted timings. Checking on the allowed usage I am not 100% sure if this can be used for an example. If this can be confirmed, or if we find another confimred royalty free animation, perhaps AI generated, then doco can be updated.

```yaml
type: custom:button-card
entity: light.bed_light
show_entity_picture: true
show_name: false
show_icon: true
styles:
  card:
    - padding: 0px
  entity_picture:
    - width: 100%
entity_picture: /local/media/off.gif
state:
  - value: "on"
    entity_picture: /local/media/on.gif
```

![off](https://github.com/user-attachments/assets/a83d97ca-a75e-4e4d-b3cf-002361dc4efa)

![on](https://github.com/user-attachments/assets/298b8455-1aa6-4d70-8761-6dfc4ddbe236)

## Example Dashboard Video

https://github.com/user-attachments/assets/8ad3bcbf-c6ad-4960-9c2a-44d9c3e846be
