### ISSUE TITLE
color_off is ignored and overriden by theme's color.

### ISSUE THREAD

**Issue by krasatos** [custom-cards/button-card#100]
I set up everything alright and declared `color:` and `color_off` on certain entities (switches)

It worked ok for a couple of days and then HA started ignoring my `color_off` setting. 
I have no idea what i changed but, before, the `font_size` was ignored, now it works (if this is of any help)
Color when on works as stated but color when off is being ignored and follows the theme's setting.

Here is an example of my code:
````
cards:
  - cards:
      - action: toggle
        color: 'rgb(228,94,101)'
        color_off: 'rgb(123,70,77)'
        entity: switch.saloni_1
        icon: 'mdi:spotlight-beam'
        name: 1
        style:
          - font-size: 12px
          - font-weight: lighter
        type: 'custom:button-card'
````

And my UI:
![image](https://user-images.githubusercontent.com/1773624/56426432-fda1e800-62c0-11e9-822b-ad9105157d3f.png)

The off switches are white instead of that off-red i chose in the code.
Any ideas as to where i should look at?

**Comment by SeanPM5** [comment]
Button was overhauled in the last few days, part of the changes is color_off is deprecated and no longer used. Here is how you would handle different colors for different states:

```
- type: "custom:button-card"
  entity: switch.saloni_1
  name: 1
  icon: mdi:spotlight-beam
  tap_action:
    action: toggle
  state:
    - value: 'on'
      color: 'rgb(228,94,101)'
    - value: 'off'
      color: 'rgb(123,70,77)'
  style:
    - font-size: 12px
    - font-weight: lighter
```
