### ISSUE TITLE
label-card styling tweaks

### ISSUE THREAD

**Issue by SeanPM5** [custom-cards/button-card#104]
Since the changes in HA 0.88 the label-card styling has been a little bit off. It doesn't quite look like the example image anymore:

Example Image from docs (prior to button-card 0.6):
![image](https://raw.githubusercontent.com/custom-cards/button-card/master/examples/scenes.png)

Using same config from docs page (then making it uppercase to match) here is how it looks:
![image](https://i.imgur.com/jyemePH.png)
(To be clear the second row of buttons 1,2,3,4 etc look fine - I am only referring to the actual label-card part that says "KITCHEN").

You can see there is more space on top and bottom of label name (padding I think is proper term). And it no longer seems to have the subtle rounded corners which looked nice. Font-weight is different too I think.

It would nice if this can be restored closer to how it was, because whole point of label card is to be minimal and decorative.

**Comment by iantrich** [comment]
Rounded corners have been restored in 1.2.0

**Comment by SeanPM5** [comment]
Yay rounded corners! 👍 

Here's an attempt I made with the padding, I think this gets it looking very close to how it did before. 

```
- type: "custom:button-card"
  color_type: label-card
  color: var(--primary-color)
  name: Label Card
  style:
    - padding-top: 5px
    - padding-bottom: 5px
    - text-transform: uppercase
```
