### ISSUE TITLE
more_info triggers toggle 

### ISSUE THREAD

**Issue by agrigo2s** [custom-cards/button-card#105]
Hi, 
ive got this in my ui-lovelace.yaml:
```
      - type: "custom:button-card"
        entity: light.lampe_schreibtisch
        icon: mdi:sofa
        color: auto
        action: 'more_info' 
```
But it still triggers the toogle and not the more-info-event. 
i added    `console.log(config.tap_action);` in line 488 of the button js and my js-console gives me this: `{action: "toggle"}`

regards,
Artur

**Comment by Norien** [comment]
Assuming you're on latest version you can try this
```
      - type: "custom:button-card"
        entity: light.lampe_schreibtisch
        icon: mdi:sofa
        color: auto
        tap_action:
          action: 'more-info
```
