### ISSUE TITLE
[FR] Confirmation Card Text

### ISSUE THREAD

**Issue by B3voholic** [custom-cards/button-card#109]
Would it be possible for to be able to make our own text for the confirmation popup?

**Comment by Norien** [comment]
Are you sure you want to restart Home Assistant?
Yes / No

**Comment by SeanPM5** [comment]
I'd be interested in this too. Here is a possible ideas of syntax (similar to `state` and `style`):

```
confirmation: true
confirmation_settings:
    - confirmation_message: Would you like to update your Home Assistant? Back up first!
    - confirm_text: Update Now
    - cancel_text: Maybe Later
```

or another perhaps easier way:
```
  confirmation:
    message: Would you like to remote start your car?
    confirm: Remote Start
    cancel: Nevermind
```
