### ISSUE TITLE
Styling doesn't seem to work if name or icon is hidden

### ISSUE THREAD

**Issue by SeanPM5** [custom-cards/button-card#118]
I have a light card with five custom button-cards underneath. Each button is simply responsible for setting color of my desk light strip.

This is what it looks like:  

![image](https://i.imgur.com/Q3mefXz.png)

I was attempting to experiment with styling and make the color buttons just a little bit taller. After experimenting I noticed that `style` option doesn't seem to work if you have both name and icon hidden. 

As you can see from screenshot I was going for a minimal look, so I had both name and icon hidden because the color gets that point across well enough. And I had `show_state: false` as well because light scenes don't have a true state, they just always report "scening" as state. 

This was the full config for the button (`style` option won't work unless you change `show_name` or `show_icon` to true):

```
- type: "custom:button-card"
  entity: scene.desk_strip_orange
  icon: mdi:led-strip
  show_state: true
  show_name: false
  show_icon: false
  tap_action:
    action: service
    service: scene.turn_on
    service_data:
      entity_id: scene.desk_strip_orange
  color_type: card
  color: "#f57d00"
  style:
    - line-height: 32px
```

I don't know whether this might be a bug, or just the way the card works in which case feel free to close this. I suspect this is more of a very unique / rare edge case anyway - 99% of the times it will have either a name, icon, or state.
