### ISSUE TITLE
Border clipping and can't use border-radius

### ISSUE THREAD

**Issue by RomRider** [custom-cards/button-card#125]
See post here:
https://community.home-assistant.io/t/lovelace-button-card/65981/689

With V1.0.0 I’m seeing behavior similar to issue #114, square points behind rounded corners.
Here’s what I see using card_type: card, color, and with a border in the style: (using an entity whose state is ‘on’). (Both Firefox and Chrome)
```yaml
  - type: custom:button-card
    color_type: card
    color: rgb(245,116,56)
    style:
  #    - background-color: rgba(245,116,56,1)
      - border-radius: 30px
      - border: solid 3px rgba(118,185,0,1)
    entity: light.office_ceiling
    icon: mdi:stop
    name: BUTTON only CType card
    tap_action:
      action: call-service
      service: androidtv.adb_command
      service_data:
        entity_id: media_player.firetv_living_room
        command: "input keyevent 86"
```
The color is applied out to the square corners, and the border is clipped on the right
![image](https://user-images.githubusercontent.com/21064206/56772384-1d05ad00-67ba-11e9-97bc-ad9af5c66fee.png)

Here’s what I see with no card_type or color, and background-color defined in style:
```yaml
  - type: custom:button-card
#    color_type: card
#    color: rgb(245,116,56)
    style:
      - background-color: rgba(245,116,56,1)
      - border-radius: 30px
      - border: solid 3px rgba(118,185,0,1)
    entity: light.office_ceiling
    icon: mdi:stop
    name: BUTTON only CType card
    tap_action:
      action: call-service
      service: androidtv.adb_command
      service_data:
        entity_id: media_player.firetv_living_room
        command: "input keyevent 86"
```
The color does not get applied out to the square corners, but the corners are visible and the border is clipped on the right.
button2
![image](https://user-images.githubusercontent.com/21064206/56772393-2858d880-67ba-11e9-83d2-c88e13d6ec20.png)
