### ISSUE TITLE
toggle state not changing

### ISSUE THREAD

**Issue by aptonline** [custom-cards/button-card#128]
I have buttons setup for lights, when I turn on the state changes to on (blue) but when I turn off the state doesn't change, the light does however toggle off.  If I refresh the page the states change and update to the expected state.

I'm running the latest version of HA (0.92.1) and Button-Card (1.1.0)

Heres a snippet of the code used:

```
  - cards:
      - color: var(--primary-color)
        color_type: card
        entity: light.shelf_lamp
        hold_action:
          action: more-info
        icon: 'mdi:lightbulb'
        name: Shelf
        state:
          - color: none
            value: 'off'
        type: 'custom:button-card'
```

![2019-04-27 12 26 59](https://user-images.githubusercontent.com/190136/56849075-e332c480-68e7-11e9-911d-1378b0015206.gif)

The above demo shows light turning on.. but when clicked the state doesn't turn off even though the light does.

**Comment by RomRider** [comment]
Looks very much like: 
https://github.com/home-assistant/home-assistant-polymer/issues/3060

I started the debug and the function that tests if the button should update is returning true (which is then catched by lit), however the button is not updated... It seems that this only affects light entities, which is really strange!
I'll continue to investigate.

**Comment by aptonline** [comment]
Sorry didn't see that on my search. Many thanks :)

**Comment by RomRider** [comment]
Okay, so the problem is that `color: none` is not valid in CSS :)
It works the first time, but then it keeps the old color because it can do anything with `none`.
You should specify a color (or a var) or just delete the state entry, and it will use `var(--paper-item-icon-color)` for the off color.

**Comment by aptonline** [comment]
Ok so it DOES work but the non value doesn't give the right effect as you can see with the button next to it. 

![2019-04-27 12 57 58](https://user-images.githubusercontent.com/190136/56849447-3eff4c80-68ec-11e9-8667-a84292092f3a.gif)

**Comment by RomRider** [comment]
That's expected. If you delete the state, the off color will be: `var(--paper-item-icon-color)`, which is in your case white.

What you want to achieve can be done with:
```yaml
  - cards:
      - color: var(--primary-color)
        color_type: card
        entity: light.shelf_lamp
        hold_action:
          action: more-info
        icon: 'mdi:lightbulb'
        name: Shelf
        state:
          - color: var(--paper-card-background-color)
            value: 'off'
        type: 'custom:button-card'
```
