### ISSUE TITLE
service api fundamentally broken since 1.1.0

### ISSUE THREAD

**Issue by a3xdev0** [custom-cards/button-card#133]
I build the following snippet just several days ago in 1.0 (at least i think so).

```
  - cards:
      - color: 'rgb(223, 0, 97)'
        color_type: card
        icon: 'mdi:power-off'
        name: 'OFF'
        style:
          - font-size: 10px
          - font-weight: bold
        tap_action:
          action: service
          service: mqtt.publish
          service_data:
            payload: 'off'
            topic: foobar/aerie/cantina/hifi
        type: 'custom:button-card'
```
Since 1.1.0 this piece should still be working according to the examples in the documentation, but it doesn't.
