### ISSUE TITLE
Vertically centering name/label

### ISSUE THREAD

**Issue by apop880** [custom-cards/button-card#138]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
Text doesn't vertically center at different font sizes

**Version of the card**
Version: 1.5.0

**To Reproduce**
This is the configuration I used:
```yaml
- type: 'custom:button-card'
  entity: light.kitchen_sink
  color_type: icon
  color: auto
  layout: icon_name_state2nd
  show_label: true
  state:
    - value: 'off'
      label: 'Off'
      icon: 'mdi:lightbulb-outline'
      styles:
        icon:
          - color: '#303741'
    - value: 'on'
      styles:
        icon:
          - color: 'rgb(250,218,94)'
      label_template: >
        return
        Math.round((states['light.kitchen_sink'].attributes.brightness/255)
        * 100) + "%";
  hold_action:
    action: more-info
  name: Sink
  styles:
    card:
      - font-size: 18px
      - background: 'rgba(255,255,255,0.45)'
    label:
      - font-size: 12px
```

**Screenshots**
![image](https://user-images.githubusercontent.com/41379678/57079524-1f826e00-6cb6-11e9-8767-46a881f31856.png)

**Expected behavior**
I'd expect for the top of "Sink" and the bottom of "Off" to be the same distance from the top/bottom of the card. But with the label at a smaller size, the rest of the text does not adjust vertically to center.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22] 74

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] LG V30
 - OS: [e.g. iOS8.1] Android Oreo
 - Browser [e.g. stock browser, safari] Chrome
 - Version [e.g. 22] 74

**Additional context**

**Comment by RomRider** [comment]
Unfortunately, that's how HTML works. :)
You should see the button as a table with 2 columns, and 2 rows. The name is in the 2nd column/1st row and the state 2nd column/2nd row. The size of each row is 50% of the height of the button. The name is aligned on the bottom of its row and the label is aligned on the top of its row. The row height is not modified based on the size of the content.

To "simulate it", what you could try is:
```yaml
- type: 'custom:button-card'
  entity: light.kitchen_sink
  color_type: icon
  color: auto
  layout: icon_name_state2nd
  show_label: true
  state:
    - value: 'off'
      label: 'Off'
      icon: 'mdi:lightbulb-outline'
      styles:
        icon:
          - color: '#303741'
    - value: 'on'
      styles:
        icon:
          - color: 'rgb(250,218,94)'
      label_template: >
        return
        Math.round((states['light.kitchen_sink'].attributes.brightness/255)
        * 100) + "%";
  hold_action:
    action: more-info
  name: Sink
  styles:
    card:
      - font-size: 18px
      - background: 'rgba(255,255,255,0.45)'
    label:
      - padding: 3px 0px 0px 0px # <-------- Added this
      - font-size: 12px
```
