### ISSUE TITLE
Ability to align icon along either side of name/label/state

### ISSUE THREAD

**Issue by jarrah31** [custom-cards/button-card#140]
Taking your “TEST LIGHT” example, I attempted to align the icon to the left of the text so that it wasn’t just stuck on top as seen below, (changing all justify-self to end) and using `layout: icon_state_name2nd`. It didn’t quite have the desired outcome though: 

![](https://community-home-assistant-assets.s3.dualstack.us-west-2.amazonaws.com/original/3X/4/1/418c5f84d1b500768a284481514f5aabf4a292fd.png)

![](https://community-home-assistant-assets.s3.dualstack.us-west-2.amazonaws.com/original/3X/4/c/4c9180bfcdd94fa2975b3bc54ea815ca49fde3de.png)

Preferably though, would it be possible to have a new layout option so that the icon can be to the right of the text please? It would be nice to fit the icon in that handy space on the right (or left as above), as seen using my mockup below:

![](https://community-home-assistant-assets.s3.dualstack.us-west-2.amazonaws.com/original/3X/9/0/900174087a84e5a7b0b7a0d39c6c488ef4b492c9.png)

Thanks!

**Comment by RomRider** [comment]
With the custom layout options which will be in the next release, you'll be able to do this (and a lot more):
![image](https://user-images.githubusercontent.com/21064206/57212206-43f68700-6fe3-11e9-8d57-6f60d1beb5b3.png)

```yaml
- type: "custom:button-card"
  entity: sensor.sensor1
  layout: icon_state_name2nd
  show_state: true
  show_name: true
  show_label: true
  label: label
  styles:
    grid:
      - grid-template-areas: '"n i" "s i" "l i"'
      - grid-template-columns: 1fr 40%
```
