### ISSUE TITLE
Icon colour to match bulb colour (warm/cool white)

### ISSUE THREAD

**Issue by jarrah31** [custom-cards/button-card#141]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
I am attempting to make the icon colour match the bulb colour. I have a Philips Hue White Ambiance bulb that can do warm and cool white, and it's this colour temperature I'd like to see reflected in the icon please.

Looking at the GitHub guide, I see that using `color: auto` should "set the color based on the color of a light." if I have `colour_type` set to `icon` right? In my case though, the icon turns green when off and yellow when on (see screenshots below)

**Version of the card**
Version: 1.5.0

**To Reproduce**
This is the configuration I used:
```yaml
              - type: "custom:button-card"
                entity: light.study_desk_lamp
                color_type: icon
                color: auto
                show_name: false
                size: 50%
                hold_action:
                  action: more-info
                styles:
                  card:
                    - width: 100px
                    - height: 100px
```
These are the bulb attributes when switched on:
```
min_mireds: 153
max_mireds: 500
brightness: 254
color_temp: 153
friendly_name: Study desk lamp
supported_features: 43
```
**Screenshots**
Card when Off:
![image](https://user-images.githubusercontent.com/3072303/57152459-7af25000-6dcb-11e9-810f-6841620968a4.png)
Card when On:
![image](https://user-images.githubusercontent.com/3072303/57152478-85ace500-6dcb-11e9-8443-32e52fbcfa70.png)
Colour temp currently set to White:
![image](https://user-images.githubusercontent.com/3072303/57152497-965d5b00-6dcb-11e9-9025-b72284f0475b.png)

**Expected behavior**
I would like the icon colour to turn white or yellow to match the colour temperature please.

**Desktop (please complete the following information):**
 - Browser - Safari
 - Version - 12.1
