### ISSUE TITLE
[Feature] Label like text above the icon

### ISSUE THREAD

**Issue by spali** [custom-cards/button-card#143]
**Is your feature request related to a problem? Please describe.**
No, not a problem

**Describe the solution you'd like**
ability to have text above the icon.
Due the flexibility of the label functionality (template, etc) I would suggest to have a copy of "label" that can be optionally displayed above the icon.

**Describe alternatives you've considered**
hacking with custom style to reorder the elements with CSS, but that would be a mess.

**Additional context**
This would allow to have the name, value or even the new last_changed above the icon.

**Comment by RomRider** [comment]
That will be possible with custom layouts.
I won't be able to handle all the different layout requests, so I'll give this possibility to the user, even if it's advanced CSS stuff...
![image](https://user-images.githubusercontent.com/21064206/57212379-d5fe8f80-6fe3-11e9-93d1-6032b68b5626.png)
```yaml
- type: horizontal-stack
  cards:
  - type: "custom:button-card"
    entity: sensor.sensor1
    show_state: true
    show_name: true
    show_label: true
    label: label
  - type: "custom:button-card"
    entity: sensor.sensor1
    show_state: true
    show_name: true
    show_label: true
    label: label
    styles:
      grid:
        - grid-template-areas: '"l" "i" "n" "s"'
        - grid-template-rows: min-content 1fr min-content min-content

```
