### ISSUE TITLE
Ability to centre the horizontal layout 

### ISSUE THREAD

**Issue by jarrah31** [custom-cards/button-card#144]
From the discussion found here on the forum:
https://community.home-assistant.io/t/lovelace-button-card/65981/819?u=jarrah
![image](https://user-images.githubusercontent.com/3072303/57192095-9f157480-6f24-11e9-8e77-72bd5d71ea20.png)
It would be nice to be able to centre the icon and label within the button please.

```
          - type: horizontal-stack
            cards:
              - type: "custom:button-card"
                entity: input_boolean.window_is_open
                color_type: card
                show_name: false
                show_label: true
                layout: icon_label
                size: 20px
                styles:
                  label:
                    - justify-self: start
                    # - padding-right: 30%
                  card:
                    - height: 50px
                    - border-radius: 10px
                label_template: >
                  return 'Windows: ' + states['sensor.windows_open'].state;
                state:
                  - value: "on"
                    color: rgb(71,39,45) #Red
                    icon: mdi:window-open
                    styles:
                      label:
                        - color: rgb(220,69,121)
                      icon:
                        - color: rgb(220,69,121)
                  - value: "off"
                    color: rgb(49,68,42) #Green
                    icon: mdi:window-closed
                    styles:
                      label:
                        - color: rgb(134,219,85)
                      icon:
                        - color: rgb(134,219,85)
```
