### ISSUE TITLE
Navigation button

### ISSUE THREAD

**Issue by slusken** [custom-cards/button-card#145]
```
    - type: "custom:button-card"
      color_type: card
      color: white
      tap_action: 
        action: navigate
        navigation_path: /lovelace/1
      name: Kitchen
      icon: mdi:food-fork-drink
      size: 40px
      styles:
        name:
          - text-transform: none
          - font-size: 14px
          - font-weight: normal
```

The link is affected on the phone using Chrome on Android and a visited link will be darker and darker every time you visit it until its completely black.
I don't know it it has anything with a:visited to do? 
https://imgur.com/a/wWJEzPM
// Rondom
