### ISSUE TITLE
cant use call scene.turn_on service, undefined entity error

### ISSUE THREAD

**Issue by mkono87** [custom-cards/button-card#149]
Unable to get scene working with a button card. I used the example in the readme but im getting an undefined error. Am I missing something or is there an issue?
```              - type: horizontal-stack
                   cards:
                     - type: "custom:button-card"
                        icon: mdi:lightbulb
                        name: Office Dark
                        tap_action:
                        action: call-service
                        service: scene.turn_on
                        service_data:
                          entity_id: scene.office_dark```

```Log Details (ERROR)
Thu May 09 2019 21:46:52 GMT-0400 (Eastern Daylight Time)
https://ha.mydomain.ca/local/button-card.js?v=1:235:30 Uncaught TypeError: Cannot read property 'entity_id' of undefined```

**Comment by apop880** [comment]
You need to indent this portion further:

```
action: call-service
service: scene.turn_on
service_data:
    entity_id: scene.office_dark
```

**Comment by RomRider** [comment]
Your indentation is broken :
```yaml
                   cards:
                     - type: "custom:button-card"
                       icon: mdi:lightbulb
                       name: Office Dark
                       tap_action:
                         action: call-service
                         service: scene.turn_on
                         service_data:
                           entity_id: scene.office_dark
```
