### ISSUE TITLE
State-dependent Actions

### ISSUE THREAD

**Issue by apop880** [custom-cards/button-card#155]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
For entities that don't support the toggle action, it would be nice to be able to customize the button action based on the entity's current state or an attribute. Use cases I can think of would include mute/unmute or play/pause on a media player, or opening/closing a cover. 

**Describe alternatives you've considered**
Could be done via a conditional card or state switch in all likelihood, but putting it in the single button would simplify the configuration. 

**Additional context**
N/A

**Comment by RomRider** [comment]
Opening and closing a cover works with toggle ;)
For the other stuff, I use scripts and in the script I simulate the toggle. Example:
```yaml
script:
  mute_unmute_entity:
    sequence:
    - condition: template
      value_template: "{{ states[entity_id].state != 'off' }}"
    - service: media_player.volume_mute
      data_template:
        entity_id: "{{ entity_id }}"
        is_volume_muted: "{{ state_attr(entity_id, 'is_volume_muted') == false }}"
```
