### ISSUE TITLE
Help with timer

### ISSUE THREAD

**Issue by mclaudiopt** [custom-cards/button-card#156]
Hello
i have a button. i have an automation assossiated so that when it is turn on, a timer starts
is there anyway to make the change as per the picture?
basiccaly, if the started starts it is showed on a second line of the button
check:
![image](https://user-images.githubusercontent.com/48178294/57618488-7112de80-757b-11e9-9a67-e3e1502b65e4.png)

**Comment by RomRider** [comment]
Add this to your config to have the result you expect:
```yaml
show_label: true
## Change the entity to your timer entity below
label_template: >
          return states['timer.your_timer'].state;
```

**Comment by mclaudiopt** [comment]
great. thanks...altough shows active of idle...i want to have "IDLE= " " and active =Timer itself.
is it possible? thanks

**Comment by RomRider** [comment]
```yaml
show_label: true
## Change the entity to your timer entity below
label_template: >
  if (states['time.your_timer'].state == 'idle') return undefined;
  return states['timer.your_timer'].state;
```

**Comment by mclaudiopt** [comment]
thanks !
i have it like this:

````
type: vertical-stack
cards:
  - type: 'custom:button-card'
    color_type: label-card
    color: 'rgb(44, 109, 214)'
    name: TOALHEIROS
  - type: horizontal-stack
    cards:
      - type: 'custom:button-card'
        entity: switch.toalheiro_wc_visitas
        name: WC Visitas
        icon: 'mdi:power'
        tap_action:
          action: toggle
        dbltap_action:
          action: more-info
        color_type: card
        color: 'rgb(66, 134, 244)'
        show_label: true
        label_template: >
          if (states['time.your_timer'].state == 'idle') return undefined;
          return states['timer.wcrctoalheiro'].state;        
      - type: 'custom:button-card'
        entity: switch.toalheiro_wc_1a
        name: WC 1ºAndar
        color_type: card
        color: 'rgb(66, 134, 244)'
        icon: 'mdi:power'
        tap_action:
          action: toggle
        dbltap_action:
          action: more-info
        show_label: true
        label_template: |
          return states['timer.1atoalheiro'].state;
      - type: 'custom:button-card'
        entity: switch.toalheiro_wc_suite
        name: Suite
        color_type: card
        color: 'rgb(66, 134, 244)'
        icon: 'mdi:power'
        tap_action:
          action: toggle
        dbltap_action:
          action: more-info
        show_label: true
        label_template: |
          return states['timer.suitetoalheiro'].stat
```e;

but the icon disappears :-(
![image](https://user-images.githubusercontent.com/48178294/57621668-f39f9c00-7583-11e9-9daa-b5f287115d6a.png)

**Comment by mclaudiopt** [comment]
sorry for the questions

**Comment by RomRider** [comment]
Try this:
```yaml
show_label: true
## Change the entity to your timer entity below
label_template: >
  if (states['time.your_timer'].state == 'idle') return '&nbsp;';
  return states['timer.your_timer'].attributes.remaining;
```
