### ISSUE TITLE
Card space

### ISSUE THREAD

**Issue by mclaudiopt** [custom-cards/button-card#158]
Hello
is there anyway to remove the empty area and leave it free for other cards?

![image](https://user-images.githubusercontent.com/48178294/57636823-dbd71080-75a1-11e9-9733-ee4afaea41de.png)
```
type: vertical-stack
cards:
  - type: 'custom:button-card'
    styles:
      card:
        - width: 150px
        - height: 40px
    color_type: label-card
    color: 'rgb(44, 109, 214)'
    name: INFORMAÇÃO
  - type: horizontal-stack
    cards:
      - type: 'custom:button-card'
        entity: sensor.riscoincendio
        size: 70%
        name: Risco de Incendio
        show_label: true
        label_template: |
          return states['sensor.riscoincendio'].state;
        styles:
          card:
            - height: 150px
            - width: 150px
```
