### ISSUE TITLE
Help with conditional formatting

### ISSUE THREAD

**Issue by mclaudiopt** [custom-cards/button-card#159]
hello
i have the following code

type: vertical-stack
```
cards:
  - type: 'custom:button-card'
    styles:
      card:
        - width: 150px
        - height: 40px
    color_type: label-card
    color: 'rgb(44, 109, 214)'
    name: INFORMAÇÃO
  - type: horizontal-stack
    cards:
      - type: 'custom:button-card'
        color: auto
        entity: sensor.riscoincendio
        size: 70%
        name: Risco de Incendio
        show_label: true
        label_template: |
          return states['sensor.riscoincendio'].state;
        styles:
          card:
            - height: 150px
            - width: 150px
```

sensor.riscoincendio can five result "HIGH","MODERATE", AND OTHERS

how can i setup so that if HIGH ICON is yellow or blinking and background red
IF MODERATE, than color of icon is x and background is ....

thanks in advance
regards

**Comment by Petro31** [comment]
This is all handled through the state attribute.  The styles section documentation covers all of this.  Also, there is a way to show the state without requiring the need to use a label_template.  Again, I strongly urge you to read the documentation and all it's attributes.  This card has some of the best documentation in all of home assistant.

**Comment by mclaudiopt** [comment]
thanks
how can i change the background of the card in idle state? i tried but cannot find the right code
i want all the cards in grey
![image](https://user-images.githubusercontent.com/48178294/57654424-063dc380-75cc-11e9-9e5d-6363a6cf7674.png)

**Comment by RomRider** [comment]
```yaml
state:
  - value: idle
    style:
      card:
        - background-color: gray
```
