### ISSUE TITLE
what am i doing wrong? conditional format

### ISSUE THREAD

**Issue by mclaudiopt** [custom-cards/button-card#161]
![image](https://user-images.githubusercontent.com/48178294/57696223-2a3eea80-7648-11e9-88df-cc59b3f6d0e8.png)
type: vertical-stack
cards:
  - type: horizontal-stack
    cards:
      - type: 'custom:button-card'
        entity: sensor.riscoincendio
        label_template: >
          var risco = states['sensor.riscoincendio'].attributes.state; return
          states['sensor.riscoincendio'].state;
        size: 70%
        name: Risco de Incendio
        show_label: true
        styles:
          card:
            - height: 170px
            - width: 150px
        state:
          - value: REDUZIDO
            styles:
              state:
                - color: green

**Comment by RomRider** [comment]
Please use proper formatting when pasting configuration using https://help.github.com/en/articles/creating-and-highlighting-code-blocks

And I suggest that you read the card documentation [here](https://github.com/custom-cards/button-card/blob/master/README.md), everything is there.

Here's your solution
```
- type: horizontal-stack
  cards:
  - type: 'custom:button-card'
    entity: sensor.riscoincendio
    show_state: true
    size: 70%
    name: Risco de Incendio
    show_label: true
    styles:
      card:
        - height: 170px
        - width: 150px
  state:
    - value: REDUZIDO
      styles:
        state:
          - color: green
```

**Comment by mclaudiopt** [comment]
```
type: vertical-stack
cards:
  - type: horizontal-stack
    cards:
      - type: 'custom:button-card'
        entity: sensor.riscoincendio
        label_template: >
          var risco = states['sensor.riscoincendio'].attributes.state; return
          states['sensor.riscoincendio'].state;
        size: 70%
        name: Risco de Incendio
        show_label: true
        styles:
          card:
            - height: 170px
            - width: 150px
        state:
          - value: REDUZIDO
            styles:
              state:
                - color: green
```

**Comment by mclaudiopt** [comment]
thanks. i read the documentation but cannot make it work. 
i copied your solution but does no work also:
```
type: horizontal-stack
cards:
  - type: 'custom:button-card'
    entity: sensor.riscoincendio
    show_state: true
    size: 70%
    name: Risco de Incendio
    show_label: true
    styles:
      card:
        - height: 170px
        - width: 150px
    state:
      - value: REDUZIDO
        styles:
          state:
            - color: green
```
![image](https://user-images.githubusercontent.com/48178294/57696864-cd443400-7649-11e9-9fb0-fb6796062f9a.png)

sorry for requesting help

**Comment by RomRider** [comment]
See my previous message, the solution is inside :)
It's fine to request for help, you don't have to be sorry for that but it's also good to read the documentation ;)

If you think something's missing in the documentation, let me know.

**Comment by mclaudiopt** [comment]
thanks. 
i have read the documentation...but i cannot understand why it is not working :-(

**Comment by RomRider** [comment]
Are you sure that the state is in capital letters in your sensor?

**Comment by mclaudiopt** [comment]
yes
this is how it shows to me
![image](https://user-images.githubusercontent.com/48178294/57697459-2c567880-764b-11e9-95a2-80af0b6e119e.png)

**Comment by RomRider** [comment]
Did you clear your browser's cache and restarted it?

**Comment by mclaudiopt** [comment]
yes i just cleaned cache and restarted...
maybe you can try installing this sensor...
```
  - platform: scrape
    resource: 'https://fogos.icnf.pt/rif/Stat_Global_Sensibilizacao_Riscolist2.asp?cmd=search&t=Stat_Global_Sensibilizacao_Risco&z_Distrito=%3D&x_Distrito=Leiria&x_Concelho=Caldas da Rainha'
    name: riscoincendio
    select: "FONT"
    index: 1
```

**Comment by mclaudiopt** [comment]
Made like this..card color does not change:((
```
cards:
  - color: 'rgb(107, 140, 150)'
    color_type: label-card
    name: INFORMAÇÃO
    styles:
      card:
        - height: 5px
        - border-radius: 5px
    type: 'custom:button-card'
  - cards:
      - color: auto
        entity: sensor.riscoincendio
        name: Risco de Incendio
        show_label: true
        show_state: true
        size: 70%
        styles:
          card:
            - height: 170px
            - width: 150px
              color_type: label-card
            - color: GREEN
              value: REDUZIDO
            - color: RED
              value: ELEVADO
        type: 'custom:button-card'
    type: horizontal-stack
type: vertical-stack
```

**Comment by RomRider** [comment]
I'll have a look tomorrow, I can't before that I'm sorry, I'm nowhere near a home-assistant instance right now.

**Comment by RomRider** [comment]
This should fix it.
```yaml
  - platform: scrape
    resource: 'https://fogos.icnf.pt/rif/Stat_Global_Sensibilizacao_Riscolist2.asp?cmd=search&t=Stat_Global_Sensibilizacao_Risco&z_Distrito=%3D&x_Distrito=Leiria&x_Concelho=Caldas da Rainha'
    name: riscoincendio
    select: "FONT"
    index: 1
    value_template: "{{ value | trim }}"  # I added this.
```
