### ISSUE TITLE
is this template correct?

### ISSUE THREAD

**Issue by mclaudiopt** [custom-cards/button-card#164]
```
cards:
  - name: ILUMINAÇÃO
    template: label
    type: 'custom:button-card'
  - cards:
      - dbltap_action:
          action: more-info
        entity: light.luz_cozinha
        icon: 'mdi:ceiling-light'
        name: COZINHA
        template: cards
        size: 40%
        tap_action:
          action: toggle
        type: 'custom:button-card'
    type: horizontal-stack
type: vertical-stack
```

**Comment by mclaudiopt** [comment]
```
button_card_templates:
  header:
    styles:
      card:
        - padding: 5px 15px
        - font-size: 120px
        - font-weight: bold
        - border-radius: 12px<
        - color: green
      name:
        - text-transform: uppercase
        - color: var(--primary-background-color)
        - justify-self: start
        - font-weight: bold
      label:
        - color: var(--red)
        - justify-self: start
        - font-weight: bold
  header_red:
    template: header
    styles:
      card:
        - background-color: '#FF1000'
```
