### ISSUE TITLE
image rotation

### ISSUE THREAD

**Issue by mclaudiopt** [custom-cards/button-card#168]
i would like to request to be possible to rotate images
for example 90 degrees, 180 degrees

thanks

**Comment by RomRider** [comment]
It is already possible by applying this style to an element (`entity_picture` probably in your case):
```yaml
styles:
  entity_picture:
    - transform: rotate(90deg)
```
