### ISSUE TITLE
Button colour being forced by entity state

### ISSUE THREAD

**Issue by dakaix** [custom-cards/button-card#169]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser

**Describe the bug**
The "show_state" and "color" options are being ignored, with a switch entity's state being used instead to colour the button background as either Green or Red. This doesn't occur when using script entity's.

**Version of the card**
Version: 1.9.0

**To Reproduce**
This is the configuration I used:
```yaml
card_settings:
  title: Remote
columns: 3
entities:
  - column: 2
    entity: switch.lg_tv_mute
    color: blue
    color_off: blue
    show_state: false
    icon:
      color: white
      value: 'mdi:volume-off'
    row: 8
```

**Screenshots**
![ss](https://user-images.githubusercontent.com/8070376/58216845-fe7ecd00-7cf7-11e9-87c9-827fab1c3249.png)

**Expected behavior**
The abridged configuration shown above is reflected in context in the screenshot. Most buttons are using script's (and colour correctly), however the Mute button should be appearing as Blue rather than Red.

**Desktop (please complete the following information):**
 - Browser Brave
 - Version 0.64.75 Chromium: 74.0.3729.131

**Additional information**
This colour appears to be being set by the CSS "class='off'" attribute being applied to the paper-button HTML tag, as removing this puts the colour back as expected.
