### ISSUE TITLE
add external entity in action:, preferably with templatable entities

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/button-card#187]
**Is your feature request related to a problem? Please describe.**
trying to have an other entity serviced in the tap-action than the button entity, I can only do that hard coded right now:
```
    - type: custom:button-card
        template: button_motion
        name: Corridor <br> office
        entity: binary_sensor.corridor_office_motion_sensor
        tap_action:
          action: call-service
          service: switch.toggle
          service_data:
            entity_id: switch.corridor_office_motion_sensor_switch
```

please create a template in the action field to be able to do this:
```
      - type: custom:button-card
        template: button_motion
        name: Corridor
        entity: binary_sensor.name
        tap_action:
          action: call-service
          service: switch.toggle
          service_data_template:
            entity_id: >
              'switch.' + entity.object_id + '_switch'
```

maybe make it even shorter like:

```
        tap-action:
          action: toggle
          entity_id: switch.corridor_office_motion_sensor_switch
```
and with template:
```
        tap-action:
          action: toggle
          data_template:
            entity_id: >
              'switch.' + entity.object_id + '_switch'
```

**
**Additional context**
Please see https://community.home-assistant.io/t/lovelace-button-card/65981/1715?u=mariusthvdb

thanks for considering !
