### ISSUE TITLE
Vibrate the Cellphone

### ISSUE THREAD

**Issue by tenkaibr** [custom-cards/button-card#190]
Would it be possible to add a variable which plays a sound or vibrate the cellphone when you press a button?

**Comment by wedone** [comment]
I want it,too

**Comment by RomRider** [comment]
Already possible with the `haptic` field in each `*_action`, please check the documentation.
Example:
```yaml
tap_action:
  action: xxxx
  haptic: medium
```
