### ISSUE TITLE
State for other than on and off

### ISSUE THREAD

**Issue by YamiFrankc** [custom-cards/button-card#193]
Hello, 
I have a fan with many speed states that I want to display differently depending on the fan speed/state. However, only "on" and "off" seem to work.
The speed are listed both in the "speed" and "fan_mode" attributes. Is there a way to do this?

```
speed: medium
speed_list: off,low,medium,high,on,auto,smart
state: ON
linkquality: 110
brightness: 254
fan_mode: medium
fan_state: ON
friendly_name: Ventilador Frank
supported_features: 1
```

**Comment by RomRider** [comment]
Yes, with for example:
```
show_label: true
state:
- operator: template
  value: >
    rerurn entity.state === 'medium'
  label: Medium speed
  style:
    label:
      - color: orange
```

**Comment by YamiFrankc** [comment]
Hello, Thanks!
With your help and after reading the documentation a little more, I was able to do it. 
```
      - color_type: card
        entity: fan.0x0022a3000020ce19_fan
        hold_action:
          action: more-info
        name: Ventilador
        state:
          - operator: template
            value: >
              return states['fan.0x0022a3000020ce19_fan'].attributes.fan_mode ==
              'smart'
            color: purple
            spin: 'yes'
          - operator: template
            value: >
              return states['fan.0x0022a3000020ce19_fan'].attributes.fan_mode ==
              'on'
            color: blue
            spin: 'yes'
          - operator: template
            value: >
              return states['fan.0x0022a3000020ce19_fan'].attributes.fan_mode ==
              'high'
            color: blue
            spin: 'yes'
          - operator: template
            value: >
              return states['fan.0x0022a3000020ce19_fan'].attributes.fan_mode ==
              'low'
            color: green
            spin: 'yes'
          - icon: 'mdi:fan-off'
            value: 'off'
          - operator: template
            value: >
              return states['fan.0x0022a3000020ce19_fan'].attributes.fan_mode ==
              'medium'
            color: orange
            spin: 'yes'
        styles:
          card:
            - height: 100px
        type: 'custom:button-card'
```
