### ISSUE TITLE
IOS13 Bug: tap requires hold for 1 second

### ISSUE THREAD

**Issue by JesseWebDotCom** [custom-cards/button-card#195]
When clicking on a button within safari desktop, the button toggles the entity properly. When clicking on a button within safari IOS 12, the button toggles the entity properly.  When clicking on a button within safari iOS 13, the button only toggles the entity properly if the tap is held for 1 second.  Simply tapping on the button will cause the button to toggle on and then quickly off.

**Comment by RomRider** [comment]
That's why it's called a beta :)
Plus I don't have a device I'm willing to update to IOS13 beta to test. Let's wait for the definitive version, I'll fix it then if it still happens.

**Comment by JesseWebDotCom** [comment]
Yep, no rush - just wanted to let you know.

**Comment by fmonday** [comment]
This issue appears to have recurred... I'm seeing this exact behavior on iOS 13.2 on both an iPad Pro and an iPhone XS Max, and on both mobile Safari and the HA iOS companion app. As described above, the issue doesn't exist on Safari desktop. I tried explicitly defining the action as toggle, but that didn't help. 
Button card version 3.0.0. 
```
              - type: horizontal-stack
                cards:
                  - type: custom:button-card
                    entity: light.half_dome
                    name: 'halfdome'
                    icon: mdi:ceiling-light
                    aspect_ratio: 1.67/1
                    size: 30%
                    color_type: icon
                    color: yellow
                    tap_action:
                      action: toggle
                    hold_action:
                      action: more-info
                  - type: custom:button-card
                    icon: mdi:floor-lamp
                    entity: switch.big_lamp
                    aspect_ratio: 1.67/1
                    name: 'big lamp'
                    color_type: icon
                    color: yellow
                    size: 30%
                    tap_action:
                      action: toggle
                    hold_action:
                      action: more-info
                  - type: custom:button-card
                    icon: mdi:car-light-fog
                    entity: light.lightstrip
                    aspect_ratio: 1.67/1
                    name: 'lightstrip'
                    color_type: icon
                    color: yellow
                    size: 30%
                    tap_action:
                      action: toggle
                    hold_action:
                      action: more-info
```
