### ISSUE TITLE
button color not working as aspected

### ISSUE THREAD

**Issue by IIIdefconIII** [custom-cards/button-card#197]
**Checklist**
- [ X] I updated the card to the latest version available
- [X ] I cleared the cache of my browser

**Describe the bug**
Whenever i have a invalid entity the color works:

```
  - cards:
      - card_style: ''
        color: 'rgb(245, 100, 0)'
        color_off: 'rgb(0, 150, 255)'
        color_type: icon
        default_color: var(--primary-text-color)
        **entity: script.ple <------------- INVALDIG ENTITY missing x here**
        icon: 'mdi:plex'
        name: Plex
        size: 30%
        type: 'custom:button-card'
```
![image](https://user-images.githubusercontent.com/9917659/60772532-1b306200-a0f8-11e9-8ca4-c3ce04ca5411.png)

but when its valid the color becomes grey:
```
  - cards:
      - card_style: ''
        color: 'rgb(245, 100, 0)'
        color_off: 'rgb(0, 150, 255)'
        color_type: icon
        default_color: var(--primary-text-color)
        **entity: script.plex**
        icon: 'mdi:plex'
        name: Plex
        size: 30%
        type: 'custom:button-card'
```

![image](https://user-images.githubusercontent.com/9917659/60772543-2b484180-a0f8-11e9-87ad-533a6d8e54ef.png)

**Version of the card**
Version: 

**Expected behavior**
That whenever a correct entity is choosen, the color works.

**Desktop (please complete the following information):**
 - Chrome, latest

**Additional context**
Thank you for this great card!

**Comment by RomRider** [comment]
Please check the documentation, neither color_off nor default_color are valid configuration entries.

**Comment by IIIdefconIII** [comment]
Thanks for the quick answer, i removed both lines (took it from  example somewhere on the web) but its still behaving the same.

**Comment by RomRider** [comment]
`color` only works when it's on.
If you want to change the color when off you'll have to use the `state` object.
Again, please read the documentation: https://github.com/custom-cards/button-card/blob/master/README.md#state

**Comment by IIIdefconIII** [comment]
Thank, you got it kinda, not using states cause there script but this works if anyone else is in the same boat:

```
cards:
  - card:
      content: |
        #### ACTIVITIES
      type: markdown
    cards: null
    style:
      '--paper-card-background-color': 'rgba(255, 0, 0, 0.6)'
      height: 50px
    type: 'custom:card-modder'
  - entities:
      - entity: sensor.harmony_activity
    type: entities
  - cards:
      - card_style: ''
        color: 'rgb(245, 100, 0)'
        color_type: icon
        entity: script.plex
        icon: 'mdi:plex'
        name: Plex
        size: 30%
        state:
          - value: 'off'
            color: 'rgb(217, 147, 40)'
        type: 'custom:button-card'
      - card_style: ''
        color: 'rgb(255, 141, 0)'
        color_type: icon
        entity: script.ziggo_tv_living_room
        icon: 'mdi:television'
        name: Ziggo TV
        size: 30%
        state:
          - value: 'off'
            color: 'rgb(255, 141, 0)'
        type: 'custom:button-card'
    type: horizontal-stack
  - cards:
      - card_style: ''
        color: 'rgb(255, 100, 0)'
        color_type: icon
        entity: script.netflix_living_room
        icon: 'mdi:netflix'
        name: Netflix
        size: 30%
        state:
          - value: 'off'
            color: 'rgb(177, 6, 15)'
        type: 'custom:button-card'
      - card_style: ''
        color: 'rgb(0, 255, 0)'
        color_type: icon
        entity: script.spotify
        icon: 'mdi:spotify'
        name: Spotify
        size: 30%
        state:
          - value: 'off'
            color: 'rgb(30, 215, 96)'
        type: 'custom:button-card'
      - card_style: ''
        color: 'rgb(255, 0, 0)'
        color_type: icon
        entity: script.youtube_living_room
        icon: 'mdi:youtube'
        name: Youtube
        size: 30%
        state:
          - value: 'off'
            color: 'rgb(251, 0, 7)'
        type: 'custom:button-card'
    type: horizontal-stack
  - cards:
      - card_style: ''
        color: 'rgb(150, 150, 150)'
        color_off: 'rgb(150, 150, 150)'
        color_type: icon
        default_color: var(--primary-text-color)
        entity: script.shutdown
        icon: 'mdi:power'
        name: Shutdown
        size: 10%
        state:
          - value: 'off'
            color: 'rgb(255, 0, 0)'
        type: 'custom:button-card'
    type: horizontal-stack
type: vertical-stack
```

![image](https://user-images.githubusercontent.com/9917659/60827484-9bb29980-a1b0-11e9-8b7d-f46f5fce5267.png)
