### ISSUE TITLE
Icon Colors not set correct when theme is switched.

### ISSUE THREAD

**Issue by n3PH1lim** [custom-cards/button-card#201]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
I change themes on sunset. Using 2 themes for day and night.
When I change the theme the icon colors are not set correct see screenshots.
After reloading the page it is schon correct.

I have a wall mounted tablet where reload is really frustrating.

**Version of the card**
Version: 1.11.1

**To Reproduce**
This is the configuration I used:
```yaml
cards:
  - cards:
      - card: null
        color: auto
        color_type: card
        entity: light.arbeitszimmer_ambiente
        icon: 'mdi:desktop-mac'
        name: Arbeitszimmer
        styles:
          card:
            - font-size: 20px
            - font-weight: bold
            - height: 230px
        tap_action:
          action: toggle
        type: 'custom:button-card'
      - card: null
        color: auto
        color_type: card
        entity: switch.the_vault
        icon: 'mdi:server'
        name: THE-VAULT
        styles:
          card:
            - font-size: 20px
            - font-weight: bold
            - height: 230px
        tap_action:
          action: toggle
        type: 'custom:button-card'
    type: horizontal-stack
  - cards:
      - align_icon: state
        animate: true
        color_thresholds:
          - color: '#29b6f6'
            value: 0
          - color: '#66bb6a'
            value: 19
          - color: '#ec407a'
            value: 25
        entities:
          - sensor.temp_arbeitszimmer_2
        font_size: 80
        line_width: 5
        name: Temperatur
        show:
          graph: bar
          icon_adaptive_color: true
          name: false
        type: 'custom:mini-graph-card'
      - align_icon: state
        animate: true
        color_thresholds:
          - color: '#29b6f6'
            value: 0
          - color: '#66bb6a'
            value: 40
          - color: '#ec407a'
            value: 60
        entities:
          - sensor.temp_arbeitszimmer_3
        font_size: 80
        line_width: 5
        name: Temperatur
        show:
          graph: bar
          icon_adaptive_color: true
          name: false
        type: 'custom:mini-graph-card'
    type: horizontal-stack
type: vertical-stack
```

**Screenshots**
<img width="1595" alt="Bildschirmfoto 2019-07-26 um 09 42 47" src="https://user-images.githubusercontent.com/14540322/61935386-af207b80-af8a-11e9-8178-30d9777408fe.png">
after reload
<img width="1595" alt="Bildschirmfoto 2019-07-26 um 09 42 57" src="https://user-images.githubusercontent.com/14540322/61935387-af207b80-af8a-11e9-8b2e-e1e397639d38.png">

<img width="1594" alt="Bildschirmfoto 2019-07-26 um 09 52 28" src="https://user-images.githubusercontent.com/14540322/61935615-28b86980-af8b-11e9-94e0-0815406753a7.png">
after reload
<img width="1596" alt="Bildschirmfoto 2019-07-26 um 09 52 35" src="https://user-images.githubusercontent.com/14540322/61935614-28b86980-af8b-11e9-931e-261b53beb86b.png">

**Expected behavior**

**Desktop (please complete the following information):**
Browser i have tested chrome, firefox and safari on desktop and android and ios.
