### ISSUE TITLE
swipe-card causing errors

### ISSUE THREAD

**Issue by iantrich** [custom-cards/button-card#206]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

Throwing an error when a swipe card is inside a `browser_mod` popup action since the change to templating. I haven't taken the time to try to debug it much, but the difference appears to be the `swipe-card` as I have other popups via `browser_mod` that are working fine that don't include `swipe-card`

```
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at s (button-card.js:1733)
    at button-card.js:1734
    at Array.forEach (<anonymous>)
    at s (button-card.js:1733)
    at button-card.js:1734
    at Array.forEach (<anonymous>)
    at s (button-card.js:1733)
    at button-card.js:1734
    at Array.forEach (<anonymous>)
```

**Version of the card**
Version: 2.02

**To Reproduce**
This is the configuration I used:
```yaml
                tap_action:
                  action: call-service
                  service: browser_mod.command
                  service_data:
                    command: popup
                    title: 'Weather'
                    deviceID:
                      - this
                    card:
                      type: custom:swipe-card
                      parameters:
                        draggable: true
                        hide: false
                        pagination:
                          type: bullets
                        scrollbar: null
                        snapOnRelease: true
                        spaceBetween: 8
                      cards:
                        - type: iframe
                          aspect_ratio: 90%
                          url: https://embed.windy.com/embed2.html?lat=41.273&lon=-96.002&zoom=5&level=surface&overlay=rain&menu=&message=true&marker=&calendar=now&pressure=&type=map&location=coordinates&detail=true&detailLat=41.273&detailLon=-96.002&metricWind=mph&metricTemp=%C2%B0F&radarRange=-1
                        - type: weather-forecast
                          entity: weather.hourly
                        - type: weather-forecast
                          entity: weather.dark_sky
```

**Desktop (please complete the following information):**
 - Browser: Vivaldi
 - Version 2.6.1566.44 (Stable channel) (32-bit)
