### ISSUE TITLE
Any card inside button-card

### ISSUE THREAD

**Issue by LbDab** [custom-cards/button-card#209]
This feature request might be too much or even might be a separate card

Button card specially in new version is easily and highly customizable so the idea is to use it not only as button but also as wrapper for another card.

Now we can embed and style any HTML into buttons, if we could use it also to wrap and style other cards into button this could be an UI style.

Is it realistic to add ability to card so we can do something like this?

```
-  type: custom:button-card
   custom_fields:
      temp:
         card:
           type: entities
           entities:
              - sensor.temp

```
