### ISSUE TITLE
Color of last_changed field is not visible when state changed: it does after refresh (F5) or view change.

### ISSUE THREAD

**Issue by MarsWarrior** [custom-cards/button-card#212]
**Checklist**
- [x ] I updated the card to the latest version available
- [x ] I cleared the cache of my browser

**Describe the bug**
I use the button to display a state change: it does this with a color.
Say a door opens, I change the color of the "Label" and "Status" field to red. As I have enabled the "last_changed" field, this field is displayed in the label area of the card.

If the door is closed again, both "Label" and "Status" fields are reset again to white.
The "Status" field is correctly and directly updated to this new color, however the "Label" field remains red.

The "Label" shows the correct color if I hit refresh/F5, or change to another view and back. So the value seems to have been set, but isn't displayed correctly.

**Version of the card**
Version: 2.05 according to HACS

**To Reproduce**
This is the configuration I used:
```yaml
  state:
    - value: "on" 
      styles:
        state:
          - color: var(--state-color-state-on)
        label:
          - color: var(--label-color-state-on)
        
    - value: "off"
      styles:
        state:
          - color: var(--state-color-state-off)
        label:
          - color: var(--label-color-state-off)
```

**Screenshots**
After movement detection:
![image](https://user-images.githubusercontent.com/1220775/62824115-a094af80-bb99-11e9-938a-af8329ec0751.png)

After timeout (ie, no movement anymore):
![image](https://user-images.githubusercontent.com/1220775/62824120-c3bf5f00-bb99-11e9-96ee-2c5f0aa53515.png)

After refresh:
![image](https://user-images.githubusercontent.com/1220775/62824127-d76ac580-bb99-11e9-80bd-95a6b8c675f8.png)

**Expected behavior**
As described: the label/last_changed field should also change color after setting it.

**Desktop (please complete the following information):**
 - Browser [chrome]
 - Version [76.0.3809.100]

**Smartphone (please complete the following information):**
 - Device: [iPhone6]
 - OS: [e.g. iOS12]
 - Browser [safari]

**Hass version:**
- 0.96

**Additional context**
I can see in the code that the last_changed field is handled differently from the label field, but as I have little javascript knowledge, I can't figure it out from the source code...
