### ISSUE TITLE
Color auto-no-temperature not always behaving HA default

### ISSUE THREAD

**Issue by tommyjlong** [custom-cards/button-card#214]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
Using color: auto-no-temperature, when changing the light's color from blue back to neutral (center of the color wheel/nearly white) the button-card icon continues to track the lights color rather than following the HA default.  Turning the light off and back on does not fix.  Only fix is to change the color temperature.
**Version of the card**
Version: 
2.05
**To Reproduce**
This is the configuration I used:
```yaml
    cards:
      - type: custom:button-card
        template: bc_template_test
        name: test
        entity: light.br30_1
        color: auto-no-temperature
        hold_action:
          action: more-info
        state:
          - value: 'on'
            spin: false
            id: my_id
      - type: entity-button
        entity: light.br30_1
        name: HA Entity Button
        tap_action: #optional default more-info
          action: toggle
        hold_action: #optional default more-info
          action: more-info
```
Not shown is theme set to slate.  Same problem using theme set to default.
**Screenshots**

**Expected behavior**
Goal: Have button-card icon color match default HA icon color when using colored lights, and in particularly when using "Slate" theme.
  Compare button-card icon (color: auto-no-temperature) vs. HA entity-button card icon.
1) Turn light on: button-card icon and HA entity-button both have correct icon color which is gold.
  - HA icon:
    color: #b58e31;
    _Note: --paper-item-icon-active-color: #b58e31;_
  - Button card icon has color: 
    --button-card-light-color: rgb(197, 225, 254);
    --button-card-light-color-no-temperature: rgb(181, 142, 49)
_The icons shown on the front end for both cards is a gold color as xb5 =>181, x8e=>142, x31=>49_
2) When changing color of the light, both icons follow the color of the light as expected.
 - HA icon
    color: rgb(83, 0, 255);
 - Button card icon:
    --button-card-light-color: rgb(82, 0, 254);
    --button-card-light-color-no-temperature: rgb(82, 0, 254);

3) Subsequently when changing the color back to neutral (center of the color wheel which is nearly white), the button-card continues to track the color of the light (nearly white) while the HA icon goes back to gold color.
 - HA icon:
   color: #b58e31;
 - Button card icon:
    --button-card-light-color: rgb(254, 253, 253);
    --button-card-light-color-no-temperature: rgb(254, 253, 253);
4) turn light off, both icons are the same color (white)
 - HA icon:
   color: #FFFFFF;
 - Button card icon:
    --button-card-light-color: var(--paper-item-icon-color);
    --button-card-light-color-no-temperature: var(--paper-item-icon-color);
   where --paper-item-icon-color: var(--primary-text-color);
   where --primary-text-color: #FFFFFF;
5) turn light back on, button-card icon nearly white.  HA Icon gold.
    - HA icon: same as 3) above
    - Button card icon: same as 3) above
6) Work around: change the temperature of the light, and the button-card icon goes back to gold.
 - HA icon:
    color: #b58e31;
 - Button card icon:
    --button-card-light-color: rgb(232, 243, 254);
    --button-card-light-color-no-temperature: rgb(181, 142, 49);

**Desktop (please complete the following information):**
   Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RomRider** [comment]
Hi,

Thanks for the detailed report.

The way it works in button-card is:
* If the light has the attribute `rgb_color`, then it will always use that as the color for the icon (with brightness applied if the attribute is defined)
* if not, then it will use `color_temp` if it exists (with brightness applied if the attribute is defined)
* if not then it will compute a default value based on the state

A light shouldn't have a `rgb_color` attribute anymore when using the temperature slider. In this case, with `color: auto-no-temperature`, it will default to `var(--paper-item-icon-active-color)` for `on` and `var(--paper-item-icon-color)` for off.

Actually, I don't understand why the HA icon would fall back to "gold" if the selected color is white... white is white, not gold, right? 🤷‍♂

**Comment by tommyjlong** [comment]
Here are the attributes for the light in step 3) (I hope this is what you were after):
```
min_mireds: 153
max_mireds: 500
effect_list: colorloop,random
brightness: 254
hs_color: 0,0.392
rgb_color: 255,254,254
xy_color: 0.324,0.329
effect: none
friendly_name: Bonus Room Tall Lamp
supported_features: 63
```

As for HA falling back to gold, what I can say in my particular case, and may be the reason HA does what it does, is that when using Slate theme which uses a black background, when the light is OFF the icon is WHITE.  So you don't want the icon showing white when the light is ON (so I think that's why it shows as gold).
Similarly using Default theme which uses a white background, you don't want the icon showing white (it shows as Yellow when ON and set to white, or Blue when turned off).

Would it be possible to do something like compare R G and B and if all three are nearly the same value then use
`var(--paper-item-icon-active-color)` for `on ` instead of rgb_color?

**Comment by RomRider** [comment]
I see, those are the culprits for home-assistant's core button:
https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/panels/lovelace/cards/hui-entity-button-card.ts#L209-L211

I don't quite like the idea honestly... Something I'd suggest to reproduce how HA core's button is behaving:
```
state:
- operator: template
  value: >
    [[[ return entity.attributes.hs_color && entity.attributes.hs_color[1] <= 10 ]]]
  styles:
    card:
      - '--button-card-light-color-no-temperature': YOUR_COLOR_HERE
    icon:
      - color: YOUR_COLOR_HERE
```

**Comment by tommyjlong** [comment]
Your suggestion works!! 
As I was only concerned with the icon (no issues with the card's color), 
I substituted `state: -value: 'on' ` shown above for the following:
```
        state:
          - operator: template
            value: >
              [[[ return entity.attributes.hs_color && entity.attributes.hs_color[1] <= 10 ]]]
            styles:
             #card:
             #  - '--button-card-light-color-no-temperature': YOUR_COLOR_HERE
              icon:
                - color: var(--paper-item-icon-active-color)
```
In step #3, the icon goes back to gold (Slate Theme) or Yellow (Default theme)
I will leave it to you whether to incorporate into your code or not.
You may close this.

Thanks!
