### ISSUE TITLE
Change icon from condition of other sensor

### ISSUE THREAD

**Issue by alverman** [custom-cards/button-card#216]
it is possible to change the icon, in a custom button card, based on the status of a binary sensor when the custom button card is the command to turn on a light?

I tried the various examples but I couldn’t find it and I couldn’t do it myself
Would it be useful to add this possibility?
Thanks, Alberto

**Comment by iantrich** [comment]
Yes. Use a template

**Comment by alverman** [comment]
thanks Ian.
The problem is that every event happens only if I press the button.
I would need the icon to change based on an external event.
I practically have lights that I switch on through a relay step by step with the modbus protocol. The relay has 4 contacts two for ignition and two for the control of the light state.
The relay activates it with a light command. and check the status of the relay with a binary_sensor.
Turning on / off works in HA but when I turn on the light from the home button the HA button does not update.
A real-time control in the custom button would be needed independent of the pressure of the same

**Comment by alverman** [comment]
I managed to enter a state that changes color when the light is turned on by a physical button, but I would like to change the button icon and I wouldn't know how to do it

`type: 'custom:button-card'
icon: 'mdi:lightbulb'
aspect_ratio: .5/.2
entity: light.cmdscala
color_type: card
tap_action:
  action: toggle
name: Scala
styles:
  grid:
    - position: relative
  custom_fields:
    notification:
      - background-color: |
          [[[
            if (states['binary_sensor.stato_scala'].state == 'on')
              return "yellow";
            return "red"
          ]]]
      - border-radius: 50%
      - position: absolute
      - left: 60%
      - top: 10%
      - height: 50px
      - width: 50px
      - font-size: 13px
      - line-height: 50px
custom_fields:
  notification: |
    [[[ return (states['binary_sensor.stato_scala'].state) ]]]
`

**Comment by iantrich** [comment]
Try a [state template](https://github.com/custom-cards/button-card#state-templates)

**Comment by iantrich** [comment]
Also, since everything except for the tap_action seems to be dependent on the `binary_sensor`, why not just make that your `entity` and then for your `tap_action` use `call-service` to toggle `light.cmdscala`. That makes more sense to me

**Comment by RomRider** [comment]
Icon works the same, with templates, you can do:
```
icon: >
  [[[ if (states['sensor.other_sensor'].state === 'on') return "mdi:icon_on"; return "mdi:icon_off"; ]]]
```

**Comment by alverman** [comment]
thanks thanks thanks guys.
Both solutions work.
Great !!
Thanks again
````
aspect_ratio: .5/.2
color: black
custom_fields:
  notification: |
    [[[ return (states['binary_sensor.stato_pilastro_0'].state) ]]]
entity: light.cmdpilastro
icon: >
  [[[ return states['binary_sensor.stato_pilastro_0'].state === 'on' ?
  'mdi:lightbulb-on' : 'mdi:lightbulb-off'; ]]]
name: Pilastro
tap_action:
  action: toggle
type: 'custom:button-card'
````

**Comment by PrzemekSkw** [comment]
Hello @RomRider and @iantrich. I don't want to open new issue because I have similar idea but don't know how to do that. I'm new to HA and I'm not any programmer. So forgive me but I really weak at this.
I have made some buttons that change icon like this:
```
type: custom:button-card
entity: binary_sensor.czujnik_ruchu_occupancy
name: Korytarz
show_state: false
state:
  - color: red
    icon: mdi:motion-sensor
    value: 'on'
  - color: green
    icon: mdi:human-male
    value: 'off'
styles:
  card:
    - height: 100px
    - width: 90px
```
Now I want to do something similar but too difficult for me. I have washing machine and dryer on gosund sp211 smart plug. It shows only one common power state for two sockets. I noticed that washing machine get above 2000W when is working and dryer about 500-600W when is working. 
Is it possible to make button with that power entity that will change icon to washing machine when power is above 2000W and change to dryer when is below 1000W (or something like that)?
Regards,
Przemek
