### ISSUE TITLE
add lock (permanent-not switchable) and differentiate allow-lock

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/button-card#220]
**Is your feature request related to a problem? Please describe.**

Not really a problem, this is an enhancement of the current lock. Which is in fact a lock-allow,and is much used in my setup
I'd love to have a lock(-not-allowed), short lock, or lock-permanent. Several switches should never be allowed to be switched off and currently there is no way in HA/button-card to assure that (other than not linking the entity).

**Describe the solution you'd like**

Since we already have the `lock: true`, this might come close to a breaking change, which is what I would like to prevent. Hence the addition of a `lock-permanent: true` would seem appropriate.

Starting anew, Id propose `lock: true` to be the permanent lock, and `lock_allow: true` the lock we currently use with a blinking lock for 5 seconds.

**Describe alternatives you've considered**

Only other way I think would be of not entering an entity for the button, so the button can't interact at all with that switch. That would have a whole set of undesired consequences regarding templates for label, name, state, so is not a preferred solution.

there's also https://github.com/thomasloven/lovelace-toggle-lock-entity-row but that still doesnt make it unlockable.

**Additional context**

Not much to add, other than maybe differentiate the icon of the lock-permanent to be mdi:lock-alert

thanks for considering.

**Comment by iantrich** [comment]
So the button does nothing? Just set tap action to none.

**Comment by Mariusthvdb** [comment]
yes, thanks, done that now, also following suggestions by @RomRider in community https://community.home-assistant.io/t/lovelace-button-card/65981/2240?u=mariusthvdb

```
button_body_lock:
  lock: true
  unlock_users: nobody
  color: auto
  size: 30%
  aspect_ratio: 1/1
  show_state: true
  show_label: true
  tap_action:
    action: none
    haptic: light
  hold_action:
    action: more-info
    haptic: success
  styles:
    lock:
      - color: red
      - icon: 'mdi:lock-alert'
```

is the main button config. 2 issues:

no icon is set, the lock:true apparently overrides styles: lock: icon (unless i have configured that incorrectly?)

tap action is none, but so is hold action, which Id like to be more-info.

so still some hope this can be adjusted/added as possibility
