### ISSUE TITLE
Fails when used in "conditional" card

### ISSUE THREAD

**Issue by alexandery** [custom-cards/button-card#223]
**Checklist**
- [ x] I updated the card to the latest version available
- [ x] I cleared the cache of my browser

**Describe the bug**
When used inside a "conditional" card, the "button-card" (one or more) is/are not displayed and the following error is logged:

```
frontend_latest/chunk.50df245c618076611dbb.js:3890:234 TypeError: t.parentElement is null
```

**Version of the card**
Version: 2.0.5 (latest as of Oct 3, 2019)

**To Reproduce**
I've used somewhat complex card, which I simplified to the following, while still maintaining the nesting of "conditional" -> "vertical stack" -> "horizontal stack" -> "button card":

```yaml
- type: conditional
  conditions:
    - entity: binary_sensor.water_leak
      state: "on"
  card:
    type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: "custom:button-card"
            entity: binary_sensor.kitchen_sink_water_leak
            show_state: true
            name: Kitchen
      - type: horizontal-stack
        cards:
          - type: entities
            entities:
              - binary_sensor.laundry_water_leak
```

This is the most simple configuration that still fails:

```yaml
- type: conditional
  conditions:
    - entity: binary_sensor.water_leak
      state: "on"
  card:
    type: "custom:button-card"
    entity: binary_sensor.kitchen_sink_water_leak
    show_state: true
    name: Kitchen

```

**Desktop (please complete the following information):**
 - Browser Firefox
 - Version 69.0.1

**Additional context**
HA version 0.99.3
