### ISSUE TITLE
Problem with navigate action

### ISSUE THREAD

**Issue by matisaul** [custom-cards/button-card#227]
**Checklist**
- [X ] I updated the card to the latest version available
- [ X] I cleared the cache of my browser

**Describe the bug**
After update to version 2.0.5, Navigate action doesn't work, change to new page and return to lovelace main page almost instantaneously .
This problem only happen in Windows Web Browsers (I didn't try in Mac or linux).
Works in my smartphone web browsers (Chrome and Ariela APP). 

**Version of the card**
Version: Lastest (2.0.5)

**To Reproduce**
This is the configuration I used:
```yaml
          - type: custom:button-card
            template: boton_menu
            name: Info
            icon: mdi:information-variant
            tap_action: 
              action: navigate
              navigation_path: '/lovelace/info'

```

**Screenshots**
N/A

**Expected behavior**
Switch to another lovelace page

**Desktop (please complete the following information):**
 - Browser: Chrome 77.0.3865 and Opera 63.0.3368

**Smartphone (please complete the following information):**
Works in Smartphone web browsers (Chrome and Ariela APP). 

**Additional context**
