### ISSUE TITLE
Support for Dimable Light Control

### ISSUE THREAD

**Issue by f00dagi** [custom-cards/button-card#229]
Thanks for a fantastic job!

**Is your feature request related to a problem? Please describe.**
I get very frustrated when I can do almost anything with the Button Card but lack the possibility to add a dimable light controller on the card.

**Describe the solution you'd like**
The Button Card is very versatile but I lack the native function of having it a dimable light controller. For inspiration please look at \\Light Card. Unfortunately \\Light Card is very limited in many ways where the Button Card shines. Another option would be to have a vertical slider for on/off/dim.

**Describe alternatives you've considered**
I have looked for others cards like \\Light Card and Light Entity Card but then are far from Button Card when it comes to customization.

**Additional context**
With this feature the Button Card would provide a complete feature set for easy visualization of home automation functions.
![IMG_6918](https://user-images.githubusercontent.com/56124786/66775992-a4102400-eec5-11e9-9979-f8421665ad34.PNG)
![IMG_6919](https://user-images.githubusercontent.com/56124786/66775994-a5d9e780-eec5-11e9-955f-bd83362f0f30.PNG)

**Comment by RomRider** [comment]
I'd use `vertical-stack-in-card` to achieve that and display a slider under the button.

**Comment by f00dagi** [comment]
Thanks for the reply, I combined with slider-entity-row and got the desired functionality. Layoutwise it is not looking that nice though since the slider-entity-row in not that customizable. I will wait for your next release and see what that brings. Thanks.

**Comment by johntdyer** [comment]
@f00dagi  - Do you have an example of where you landed on this ? I/m trying to accomplish the same thing right now

**Comment by f00dagi** [comment]
Using a combination of different cards.

![18919875-3023-44E7-819A-9EAB2343D9D5](https://user-images.githubusercontent.com/56124786/71314262-3c3a0480-2445-11ea-8662-61d8977b87c6.png)
![D0EC9BFB-5D15-4121-B7F2-4475B1FD5858](https://user-images.githubusercontent.com/56124786/71314263-3cd29b00-2445-11ea-952e-8ce1b67a8995.png)

**Comment by Mariusthvdb** [comment]
Would you please also share the template_switch_slider template ? Thanks looking quite the card👍

**Comment by f00dagi** [comment]
[cid:DACA6E49-223D-4B51-B6E5-30A91EB4655B-L0-001]

-Daniel

On 22 Dec 2019, at 13:10, Marius <notifications@github.com> wrote:

﻿

Would you please also share the template_switch_slider template ? Thanks looking quite the card👍

**Comment by f00dagi** [comment]
![5850210E-58C5-428C-9CCB-CB03369FF27C](https://user-images.githubusercontent.com/56124786/71322059-076c9280-24c3-11ea-827b-3c8430ac71c7.png)

**Comment by Mariusthvdb** [comment]
not to be a pain, but could you simply copy and paste the code, instead of showing screenshots? Makes it so much easier... ;-)

**Comment by f00dagi** [comment]
Not that easy on a mobile device but here we go...

```
 button_card_templates:
  switch_slider:
    styles:
 card:
 - background-color: rgb(3, 169, 244)
 - box-shadow: none;
 - overflow: unset
 name:
 - color: white
 label:
 - color: yellow
 custom_fields:
 slider:
 - filter: opacity(80%)
 - overflow: unset
 - color: rgb(3, 169, 244)
 grid:
 - grid-template-areas: '"n" "i" "l" "slider"'
 - grid-template-columns: 1fr
 - grid-template-rows: min-content fr min-conten>    size: 40%
    state:
    - value: "off"
 styles:
 icon:
 - color: white
    - value: "on"
 styles:
 icon:
 - color: yellow
    - value: "unavailable"
 styles:
 icon:
 - color: red

```

**Comment by johntdyer** [comment]
@f00dagi  - Any chance you can paste w/o the unicode ?  I am having a hard time getting it to work w/ those replaced w/ spaces... thinking something got lost in translation :)

**Comment by johntdyer** [comment]
@f00dagi  just to follow up.. I am asking because I am getting this 

<img width="239" alt="PNG image" src="https://user-images.githubusercontent.com/58234/71768836-2ff38400-2ee8-11ea-943e-748753944b35.png">

Using your template code w/ the following yaml and not seeing any slider and I dont understand why ... 




```yaml

    - type: vertical-stack
        title: Kitchen
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                template: switch_slider
                custom_fields:
                  slider:
                    card:
                      full_row: true
                      hide_state: true
                      type: custom:slider-entity-row
                      entity: light.breakfast_table_level
                entity: light.breakfast_table_level
                name: Breakfast
                icon: mdi:hanger
          
```

**Comment by f00dagi** [comment]
The button code on ui-lovelace.yaml
```
cards:
- type: custom:button-card
  template: template_switch_slider
  custom_fields:
	slider:
	  card:
		full_row: true
		hide_state: true
		type: custom:slider-entity-row
		entity: light.entre_tak
  entity: light.entre_tak
  name: tak
  icon: mdi:hanger
```
and the template code in ui-lovelace.yaml
```
button_card_templates:
  switch_slider:
    styles:
      card:
        - background-color: rgb(3, 169, 244)
        - box-shadow: none;
        - overflow: unset
      name:
        - color: white
      label:
        - color: yellow
      custom_fields:
        slider:
          - filter: opacity(80%)
          - overflow: unset
          - color: rgb(3, 169, 244)
      grid:
        - grid-template-areas: '"n" "i" "l" "slider"'
        - grid-template-columns: 1fr
        - grid-template-rows: min-content fr min-content min-content
    size: 40%
    state:
    - value: "off"
      styles:
        icon:
          - color: white
    - value: "on"
      styles:
        icon:
          - color: yellow
    - value: "unavailable"
      styles:
        icon:
          - color: red

  template_switch_slider:
    template: switch_slider
```

and in paths to custom components in ui-lovelace.yaml (these are the ones I have I dont think you need them all)
```
resources:
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /local/plugins/card-tools.js?v=1
    type: js
  - url: /local/plugins/layout-card.js?v=1
    type: js
  - url: /local/vertical-stack-in-card.js?v=0.1.3
    type: js
  - url: /local/slider-entity-row.js
    type: module
  - url: /local/card-mod.js
    type: module
  - url: /community_plugin/light-entity-card/light-entity-card.js
    type: js
```
and of course you need the custom components installed onto your system, either manually or via HACS if they are available there.

I would guess you need
https://github.com/custom-cards/vertical-stack-in-card
https://github.com/thomasloven/lovelace-slider-entity-row
https://github.com/custom-cards/button-card
