### ISSUE TITLE
styles key-value pair values not interpreted as javascript

### ISSUE THREAD

**Issue by daniel-stockhausen** [custom-cards/button-card#234]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
The values for `styles` key-value pairs don't seem to be interpreted. There is no console output/errors - I got interpreter error logs from `_evalTemplate` other times when using templates in other places/properties, but not in this case.

**Version of the card**
Version: 3.0.0

**To Reproduce**
This is the configuration I used:
```yaml
- entity: binary_sensor.window_laundry_room
  type: custom:button-card
  styles:
    card:
    - background-color: >
        [[[ return 'red'; ]]]
    icon:
    - color: >
        [[[ return 'green'; ]]]
  icon: mdi:window-closed
```

**Screenshots**
<img width="223" alt="no" src="https://user-images.githubusercontent.com/1905359/67246169-ff11c000-f45d-11e9-935c-d8592695182b.png">

**Desktop (please complete the following information):**
Chrome Version 77.0.3865.120 (Official Build) (64-bit) on MacOS

**Additional context**
Works as expected when not using templates:
```
- entity: binary_sensor.window_laundry_room
  type: custom:button-card
  styles:
    card:
    - background-color: >
        red
    icon:
    - color: >
        green
  icon: mdi:window-closed
```

<img width="223" alt="yes" src="https://user-images.githubusercontent.com/1905359/67246178-0638ce00-f45e-11e9-9699-723198e9cda5.png">

But not using templates makes me very sad 🥺
Could you please cheer me up? 🥰
