### ISSUE TITLE
Light not showing correctly in frontend

### ISSUE THREAD

**Issue by MTrab** [custom-cards/button-card#235]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
When viewing the example in the editor window, the light entity (only on/off lights without dimming or color options have this issue) is shown correctly - when viewed in the frontend, the light entity is not showing the current "state" (coloring the icon and the shadow)

**Version of the card**
Version: 

**To Reproduce**
This is the configuration I used:
```yaml
      - entity: light.livingroom_corner
        icon: 'mdi:ceiling-light'
        name: Stue
        type: 'custom:button-card'
```

**Screenshots**
![image](https://user-images.githubusercontent.com/14296463/67312363-83694f00-f501-11e9-8613-a73941b9cea9.png)

**Expected behavior**
Expected behavior is to have the icon and shadow border show the state, just as it does in the preview window

**Desktop (please complete the following information):**
 - Browser Chrome, Edge Developer Preview
 - Version Chrome: 77.0.3865.120, Edge Dev: 79.0.301.2
