### ISSUE TITLE
Opens an unnecessary entity more-info dialog

### ISSUE THREAD

**Issue by Limych** [custom-cards/button-card#236]
**Checklist**
- [*] I updated the card to the latest version available
- [*] I cleared the cache of my browser

**Describe the bug**
Then the button is used inside the entities card, the default action (toggle), in addition to this action, also opens an more-info dialog for the entity. This greatly interferes with use of button.

This happens on both the computer and the phone.

**Version of the card**
Version: 3.0.0

**To Reproduce**
This is the configuration I used:
```yaml
          - type: entities
            show_header_toggle: false
            style: |
              ha-card {
                background-image: url("/local/lovelace/home/bg_sound.jpg");
                background-size: cover;
                background-position: center;
              }
            entities:
              - type: custom:mini-media-player
                entity: media_player.kitchen
                name: "Кухня"
                group: true
                source: icon
                hide:
                  power: true
                  source: true
              - type: custom:mini-media-player
                entity: media_player.living_room
                name: "Гостиная"
                group: true
                source: icon
                hide:
                  power: true
                  source: true
              - type: custom:button-card
                entity: input_boolean.play_radio
                color: rgb(117, 189, 111)
                color_type: card
                layout: icon_name
                styles:
                  card:
                    - height: 50px
                state:
                  - value: "off"
                    color: rgba(255, 255, 255, 0.1)
              - input_select.radio_station
```
