### ISSUE TITLE
State not overloading in button_card_templates when in include file

### ISSUE THREAD

**Issue by kirbyschapman** [custom-cards/button-card#237]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
I have two templates that reflect the state of a binary sensor. The purpose is to show a specific icon in a specific color when the binary sensor is on. A different icon in a different color is shown when the binary sensor is off.

The first template does the above. The second template is simply the reverse of the above. The second template uses the first template as a template, and then overloads the icon and state parameters. 

The bug is that the icon overloads as expected, but the state does not. 
**Version of the card**
Version: 3.0.0

**To Reproduce**
Following are the two templates that are under ```button_card_templates:```. The first is the primary template, and then the second depends on the first with ```template:``` command:
```yaml
  binary_sensor_name_label_stateformat:
    template: name_bold_label_gray
    color_type: icon
    show_entity_picture: false
    show_icon: true
    show_name: true
    show_state: false
    show_label: true
    show_units: false
    show_last_changed: false
    icon: >
       [[[
                                if (entity.state == 'on')
                                  return 'mdi:circle-slice-8';
                                  return 'mdi:checkbox-blank-circle-outline';
       ]]]
    state:
      - color: 'rgb(0, 102, 204)'
        value: 'off'
      - color: 'rgb(255, 153, 51)'
        value: 'on'
    hold_action:
      action: more-info
    tap_action:
      action: more-info

  # Use: Regular binary sensor icon that needs to be off as a gate for something else to be true
  #      The icon turns ON when the sensor is OFF (reversed)
  binary_sensor_name_label_stateformat_lastaction_reverse:
    template: binary_sensor_name_label_stateformat
    show_last_changed: true
    icon: >
       [[[
                                if (entity.state == 'on')
                                  return 'mdi:checkbox-blank-circle-outline';
                                  return 'mdi:circle-slice-8';
       ]]]
    state:
      - color: 'rgb(0, 102, 204)'
        value: 'on'
      - color: 'rgb(255, 153, 51)'
        value: 'off'
    hold_action:
      action: more-info
    tap_action:
      action: more-info
```
The way I use it in lovelace is:
```yaml
              - type: 'custom:button-card'
                template: binary_sensor_name_label_stateformat_lastaction_reverse
                entity: binary_sensor.extended_away
                name: NOT Ext Away
```

**Screenshots**

**Expected behavior**
In this case, when ```binary_sensor.extended_away``` is OFF, the icon should be an orange mdi:circle-slice-8. WHen it is ON, is should be a blue mdi:checkbox-blank-circle-outline.

As it is, the icon changes as expected, but the color remains blue.

If I modify the second (dependent) template so it is stand-alone and does not depend on the first template, then the colors in state work as expected.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari]: Chrome on WIN 10

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Android
 - Browser [e.g. stock browser, safari]: Stock Chrome browser

**Additional context**
I hope I'm not doing something stupid and wasting everyone's time...
