### ISSUE TITLE
operator in between

### ISSUE THREAD

**Issue by broyuken** [custom-cards/button-card#238]
I have a sensor in my car that will open my garage door when my car pulls up to it, or starts in the garage. This sensor also provides signal strength so I know if my car is coming or going. If the signal strength is 40-50 the car is in the garage, if it's 50-75 it's in the driveway, if it's above that the car has left the driveway and is away. 

I want to have an operator in the button card to show the state of "in driveway" if the signal strength is between 50 and 75. Looking at the documentation I haven't found a way to do this yet. If it's not possible, is this something that could be added? If it is possible, how would it be done? With a template?

**Comment by RomRider** [comment]
Something like this would cover your use case (order is important):
```yaml
state:
- operator: '<'
  value: 40
  # Do something for anything below 40
- operator: '<='
  value: 50
  # Do something for 40 <= value <= 50
- operator: '<='
  value: 75
  # Do something for anything 50 < value <= 75
- operator: default
  # Everything else
```
