### ISSUE TITLE
Weird behavior in conjuction with custom:vertical-stack-in-card

### ISSUE THREAD

**Issue by aleksandar-todorovic** [custom-cards/button-card#248]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**

When used from within [vertical-stack-in-card](https://github.com/custom-cards/vertical-stack-in-card), the buttons don't get their background color applied until after I refresh the page.

**Version of the card**
Version: 3.0.0

**To Reproduce**
The configuration of the entire card:
```yaml
cards:
  - entities:
      - entity: light.bedroom
        type: 'custom:slider-entity-row'
    type: entities
  - cards:
      - color: 'rgb(163, 83, 255)'
        color_type: card
        styles:
          card:
            - height: 75px
        tap_action:
          action: call-service
          service: script.hue_purple
        type: 'custom:button-card'
      - color: 'rgb(255, 188, 85)'
        color_type: card
        styles:
          card:
            - height: 75px
        tap_action:
          action: call-service
          service: script.hue_nightlight
        type: 'custom:button-card'
    type: horizontal-stack
show_header_toggle: false
title: Bedroom
type: 'custom:vertical-stack-in-card'
```

**Screenshots**

Before the page reload:

![Screenshot from 2019-11-24 14-09-56@2x](https://user-images.githubusercontent.com/4890548/69495194-84a4e780-0ec4-11ea-90da-d4a5dfd2c0c1.png)

After I press F5:

![Screenshot from 2019-11-24 14-13-27@2x](https://user-images.githubusercontent.com/4890548/69495206-9f775c00-0ec4-11ea-9622-d115d5b0d62b.png)

**Expected behavior**

What happens after page refresh, but without a page refresh.

**Desktop (please complete the following information):**
 - Browser: Firefox 71.0b10 (64-bit), Chromium 78.0.3904.97.

**Smartphone (please complete the following information):**
I have experienced the identical behavior from within Chrome (78.0.3904.108) and within [Home Assistants' new Android app](https://play.google.com/store/apps/details?id=io.homeassistant.companion.android).

**Additional context**

I have some cards in a different view arranged using the traditional horizontal- and vertical-stack cards. I never had a problem with those, which makes me believe that this issue only appears when the button-card is located within vertical-stack-in-card. I see no errors in my browser console or anything like that.
