### ISSUE TITLE
Support for data_template in call-service

### ISSUE THREAD

**Issue by houseautomated** [custom-cards/button-card#252]
**Is your feature request related to a problem? Please describe.**
I'd like to pass a sensor attribute through as part of the data of my call-service action

**Describe the solution you'd like**
Either support of a new `data_template` or `service_data_template` function that would pass the sensor data through as it does with `data_template` [here](https://www.home-assistant.io/docs/automation/templating/)

**Describe alternatives you've considered**
I could build what I need with individual scripts, but that would mean duplicating the scripts over and over rather than passing a sensor value to the same call.

**Additional context**
```
  - type: custom:button-card
    color_type: icon
    show_name: true
    show_entity_picture: true
    entity_picture: |
      [[[ return states['sensor.kodi_movie_1'].attributes.thumbnail ]]]
    tap_action:
      action: call-service
      service: script.kodi_movie
      service_data:
        video_id: "{{states['sensor.kodi_movie_1'].attributes.video_file}}"
```

**Comment by RomRider** [comment]
You can already use templates in `service_data`:
```yaml
    tap_action:
      action: call-service
      service: script.kodi_movie
      service_data:
        video_id: "[[[ return states['sensor.kodi_movie_1'].attributes.video_file ]]]"
```
