### ISSUE TITLE
Strange behavior when calling a service and accidentally using wrong yaml syntax.

### ISSUE THREAD

**Issue by przemo** [custom-cards/button-card#253]
I stumbled upon weird behavior when calling a service executing a script.

Example code of mine Lovelace configuration:
```
- type: "custom:button-card"
            name: BLAH BLAH
            icon: mdi:sofa
            color: auto
            tap_action:
                action: call-service
                service: script.turn_on
                service_data:
                   entity_id: script.some_script (mine was to turn on hue lights)
```

I accidentally typed instead of `service_data:` - `data:` and all mess happened when I pressed the button. Believe me or not, but it turned on my vacuum cleaner, some random set of lights and turn on my TV set (via Harmony) . I guess it runs all the scripts that were recently used???
I tested it couple times but this happened when I used "button-card" . Calling the `script.some_script` alone did not trigger any side effects.

 Can anyone try this with their own script?
