### ISSUE TITLE
Color depending on state stopped working after update.

### ISSUE THREAD

**Issue by YamiFrankc** [custom-cards/button-card#255]
Hello. Im having a problem with a card for a ceiling fan that changes color depending on the fan speed.
I had this working before(months ago) and I just now have time to fix it. The card is stuck in a state forever. I tried looking at it and changes in the yaml for the updates, but cant really find what is wrong.

```

      - color_type: card
        dbltap_action:
          action: more-info
        double_tap_action:
          action: more-info
        entity: fan.0x0022a3000020ce19_fan
        hold_action:
          action: more-info
        name: Ventilador
        state:
          - color: 'rgb(171,39,79)'
            label: Inteligente
            operator: template
            spin: 'yes'
            value: >
              return states['fan.0x0022a3000020ce19_fan'].attributes.fan_mode ==
              'smart'
          - color: 'rgb(124,185,232)'
            name: Rapido
            operator: template
            spin: 'yes'
            value: >
              return states['fan.0x0022a3000020ce19_fan'].attributes.fan_mode ==
              'on'
          - color: 'rgb(61,222,54)'
            name: Alto
            operator: template
            spin: 'yes'
            value: >
              return states['fan.0x0022a3000020ce19_fan'].attributes.fan_mode ==
              'high'
          - color: 'rgb(239,222,205)'
            name: Lento
            operator: template
            spin: 'yes'
            value: >
              return states['fan.0x0022a3000020ce19_fan'].attributes.fan_mode ==
              'low'
          - icon: 'mdi:fan-off'
            name: Apagado
            value: 'off'
          - color: 'rgb(255,92,0)'
            name: Medio
            operator: template
            spin: 'yes'
            value: >
              return states['fan.0x0022a3000020ce19_fan'].attributes.fan_mode ==
              'medium'
        styles:
          card:
            - height: 100px
        type: 'custom:button-card'


```

**Comment by RomRider** [comment]
Which state is it stuck in?
Are you sure about the value of `fan_mode`? Can you show me a screenshot of the state of your entity from the dev panel?

**Comment by YamiFrankc** [comment]
![image](https://user-images.githubusercontent.com/153349/71808600-d4361180-3033-11ea-8884-419a88e8390e.png)
Hi, yes.  Its stuck on "Inteligente", which is the first one of the states. If I try to delete that then it gets stuck on Rapido and so on

**Comment by RomRider** [comment]
oh I see... Templates needs to be enclosed in `[[[ ]]]`. You probably updated from a very old version...
So for example:
```yaml
          - color: 'rgb(171,39,79)'
            label: Inteligente
            operator: template
            spin: 'yes'
            value: >
              [[[ return states['fan.0x0022a3000020ce19_fan'].attributes.fan_mode ==
              'smart' ]]]
```
