### ISSUE TITLE
button-card resizing shows dot above label 

### ISSUE THREAD

**Issue by elsingaa** [custom-cards/button-card#258]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser

**Describe the bug**
Button-card is showing a dot above label text when the available width of the card gets smaller than a certain size.

**Version of the card**
Version: 3.0.0

**To Reproduce**
This is the configuration I used:
```yaml
cards:
  - cards:
      - color: var(--paper-item-icon-active-color)
        color_type: label-card
        entity: light.woonkamer
        name: Woonkamer
        styles:
          card:
            - height: 50px
        type: 'custom:button-card'
    type: horizontal-stack
  - cards:
      - entity: light.staande_lamp
        icon: 'mdi:floor-lamp'
        type: 'custom:button-card'
      - entity: light.tradfri_driver
        icon: 'mdi:book-open-page-variant'
        type: 'custom:button-card'
      - entity: light.achterdebank
        icon: 'mdi:floor-lamp-dual'
        type: 'custom:button-card'
      - entity: light.schilderij
        icon: 'mdi:aspect-ratio'
        type: 'custom:button-card'
    type: horizontal-stack
type: vertical-stack
```

**Screenshots**
<img width="334" alt="Screenshot 2019-12-22 at 16 12 11" src="https://user-images.githubusercontent.com/859598/71323686-39d3bb00-24d6-11ea-9fe9-3d5763435695.png">

**Expected behavior**
I expected no '.' to appear above the label text.

**Desktop (please complete the following information):**
 - Safari
 - 13.0.3

It seems that an icon is shown when the card is smaller than a certain width. It shows when the sidebar is closed and four columns are shown, as well as when reducing the size of the browser window. Adding `show_icon: false` to the card hides the dot.

**Additional context**
It seems that an icon is shown when the card is smaller than a certain width. It shows when the sidebar is closed and four columns are shown, as well as when reducing the size of the browser window. The dot appears to fade in and out when resizing the browser.

Workaround: Adding `show_icon: false` to the card hides the dot.
