### ISSUE TITLE
Automatic button width

### ISSUE THREAD

**Issue by inspire1989** [custom-cards/button-card#259]
Hi!
I'm using the button card in several places - thanks a lot for the awesome work! :)

In one case I try align the image and label next to each other which indeed works thanks to the layout: icon_label feature. However, the width of the card is not adjusted properly - or I have no clue how to do it:

```
entity: binary_sensor.i3_120_lids
label: This is my new button card
layout: icon_label
show_label: true
show_name: false
show_state: false
size: 80%
style:
  top: 75%
  left: 85%
  transform: 'translate(-50%,-50%)'
styles:
  card:
    - border-radius: 6px
  label:
    - font-size: 70%
type: 'custom:button-card'
```
Shows it like this: 
![image](https://user-images.githubusercontent.com/2980934/71670948-e4b76500-2d71-11ea-901a-24ccb8a2d5ab.png)

The label is cut off ... which I don't want. In fact I'd like to have the card adjust its width dynamically based on the shown content/text.

I tried playing around with the grid - for example by adding:
```
styles:
  grid:
    - grid-template-areas: '"l i"'
    - grid-template-rows: min-content
    - grid-template-columns: min-content
```
but this did not solve it.

Is there a way to solve this?

Thanks!
inspire
