### ISSUE TITLE
Icon color difference

### ISSUE THREAD

**Issue by Alexxander0** [custom-cards/button-card#260]
**Checklist**
- [x ] I updated the card to the latest version available
- [ x] I cleared the cache of my browser

**Describe the bug**
I have 2 cards, but both Icon color are different

The icon of the first button gets the color from --paper-item-icon-color
The secon one from --primary-text-color

Do I have any errors in my configuration? Tried a lot of configurations, but always behaved the same for me

**Version of the card**
Version: 3.0.0

**To Reproduce**
This is the configuration I used:
```
       - color_type: icon
        entity: variable.washingmachine_running
        name: Waschmaschine
        state:
          - icon: 'mdi:washing-machine'
            operator: default
          - icon: 'mdi:washing-machine'
            value: 'on'
        tap_action:
          action: more-info
        type: 'custom:button-card'
      - aspect_ratio: 1.68/1
        icon: 'mdi:flash'
        color_type: icon
        entity: sensor.washingmachine_current_consumption
        name: |
          [[[
            if (states["variable.washingmachine_running"].state == "on") return (states["sensor.washingmachine_current_consumption"].state + ' W');
            else return states["variable.washingmachine_last_consumption"].state + ' kWh';
          ]]]
        tap_action:
          action: more-info
        type: 'custom:button-card'
```

**Screenshots**

**Expected behavior**
Icon color should be the same for both buttons

**Desktop (please complete the following information):**
 - Chrome
 - Version 79.0.3945.88

**Additional context**
-
![image](https://user-images.githubusercontent.com/26937883/71682606-8352be80-2d90-11ea-80e0-7615285d348b.png)
![image](https://user-images.githubusercontent.com/26937883/71682728-cad94a80-2d90-11ea-8681-74528b2a9a6d.png)
![image](https://user-images.githubusercontent.com/26937883/71682777-ed6b6380-2d90-11ea-9c1c-f61c33a07456.png)

**Comment by RomRider** [comment]
That's probably because of the `variable` entity type. I've never tried with that custom element. Can't you use a sensor instead? Like a sensor template?

Anyway, I'll test and report back.

**Comment by Alexxander0** [comment]
Hi, 

i think the problem is the sensor. Its a template sensor:

```
sensor:
  - platform: template
    sensors:
      washingmachine_current_consumption:
        device_class: power
        unit_of_measurement: 'W'
        friendly_name: "Waschmaschine Stromverbrauch"
        value_template: "{{ float(state_attr('switch.fritz_dect_200_2', 'current_consumption')) }}"
#        icon_template: mdi:flash
```
It doenst matter if i set the icon with icon_template or with the icon property in the frontend.
The color always looks different compare to all other entities (like switches etc., the variable.* entities seem to be the correct one)
Am i missing something in my template_sensor? Already tried deviceclass, and so on. Doenst seem to have an influence
