### ISSUE TITLE
Lock / Confirmation option showing up depending on state

### ISSUE THREAD

**Issue by drthanwho** [custom-cards/button-card#263]
**Is your feature request related to a problem? Please describe.**
The lock or confirmation option is available at any given state of an entity (unless I haven't worked out how to do it). For example, a 'sensitive' button should be locked or give you a popup to confirm action, but there's no reason for this if you're turning entity state to 'off'. 

E.g. 

- Turning on an alarm/buzzer/garage door --> Locked/confirmation dialogue asking if you really want to do
- Turning off said alarm/buzzer/garage door --> No need for confirmation. You are just turning it off

**Describe the solution you'd like**
Be able to define lock/confirmation under specific state

```yaml
type: 'custom:button-card'
entity: switch.doorbell_sound
show_name: false
show_state: false
icon: 'mdi:alarm-bell'
state:
  - value: 'off'
    color: 'rgb(255, 77, 77)'
    icon: 'mdi:alarm-bell'
 - value: 'on'
   color: 'rgb(46, 184, 46)'
   lock:
     enable: true

```
