### ISSUE TITLE
Icon replaced for garage door cover

### ISSUE THREAD

**Issue by broyuken** [custom-cards/button-card#265]
**Checklist**
- [ x] I updated the card to the latest version available
- [ x] I cleared the cache of my browser

**Describe the bug**
Using this card, it changes the icon of my cover (garage door) from a garage door to some weird rectangle icon that maybe sort of looks like a garage door.

**Version of the card**
Version: 3.1.1

**To Reproduce**
This is the configuration I used:
```
cards:
  - entity: lock.front_door_lock
    hold_action:
      action: more-info
    name: Front Door
    tap_action:
      action: toggle
    type: 'custom:button-card'
    color: var(--state-icon-active-color)
    state:
      - color: var(--state-icon-color)
        value: locked
  - entity: cover.left_garage_door
    hold_action:
      action: more-info
    tap_action:
      action: toggle
    name: Left Garage
    type: entity-button
  - entity: cover.right_garage_door
    hold_action:
      action: more-info
    tap_action:
      action: toggle
    name: Right Garage
    type: 'custom:button-card'
    color: var(--state-icon-color)
    state:
      - color: var(--state-active-icon-color)
        value: open
type: horizontal-stack

```

**Screenshots**
![image](https://user-images.githubusercontent.com/1593391/72232539-b7e42880-358f-11ea-9f57-ce755e16fe0f.png)
Left, my lock (works fine) 
middle, one garage door with expected garage icon using entity-button
right, other garage door with unknown icon using custom:button-card 

**Expected behavior**
Use the icon that is on the entity, not some other random icon

**Desktop (please complete the following information):**
 - Chrome
 - Latest, issue occurs on all

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iphone xs max
 - OS: [e.g. iOS8.1] 13.3
 - Browser HA app
 - Version 2

**Additional context**

**Comment by RomRider** [comment]
You probably didn't set the icon in the entity configuration in HA.
button-card doesn't invent the icon by itself.

**Comment by broyuken** [comment]
Then why does the entity button work just fine, just this card doesn’t?

**Comment by RomRider** [comment]
It's not displaying the same entity, so I can't say :)

**Comment by broyuken** [comment]
If I change the entity to be the same it still does it. Need another screenshot for proof?

**Comment by RomRider** [comment]
Can you share the configuration of both of your entities (from the ha config, not from lovelace).
Else you can redefine the icon in button card with `icon: xxx` or a template.

**Comment by broyuken** [comment]
They are both from the chamberlain integration, not much of a config. 

It looks like your card doesn't take into consideration the device_class

friendly_name: Left Garage Door
supported_features: 3
device_class: garage
![image](https://user-images.githubusercontent.com/1593391/72307317-e02f5e00-3647-11ea-957f-977dc77f7306.png)

```
# Enable MyQ Garage Door Opener
cover: 
  - platform: myq
    username: !secret myq_username
    password: !secret myq_password
    type: chamberlain
```
These are all cards with 0 config. The only thing I changed from default was the icon size on the entity button just to make it fit a little better.

![image](https://user-images.githubusercontent.com/1593391/72307111-410a6680-3647-11ea-8a30-8259c5c78e2e.png)

```
      - entities:
          - entity: cover.left_garage_door
        type: entities
      - entity: cover.left_garage_door
        hold_action:
          action: more-info
        show_icon: true
        show_name: true
        tap_action:
          action: toggle
        type: entity-button
        icon_height: 50px
      - entities:
          - entity: cover.left_garage_door
        type: glance
      - entity: cover.left_garage_door
        hold_action:
          action: more-info
        show_icon: true
        show_name: true
        tap_action:
          action: toggle
        type: 'custom:button-card'
```

**Comment by broyuken** [comment]
Hello,

Is this something that could be taking into account?

**Comment by RomRider** [comment]
I'll work on that for the next release ;)

**Comment by ThirteenTX** [comment]
I have the same issue in Firefox with a garage door cover. I get the same icon even though I am calling out different icons in the config based on state.

**Comment by ThirteenTX** [comment]
Here is my config:
```
type: 'custom:button-card'
entity: cover.right_garage_door
show_state: true
tap_action:
  action: call-service
  service: cover.close_cover
  service_data:
    entity_id: cover.right_garage_door
double_tap_action:
  action: call-service
  service: cover.open_cover
  service_data:
    entity_id: cover.right_garage_door
state:
  - value: locked
    icon: 'mdi:garage'
  - value: unlocked
    icon: 'mdi:garage-open'
    color: var(--accent-color)

```
and here is what it shows:
![image](https://user-images.githubusercontent.com/51967002/73690775-ba213a80-4696-11ea-94bc-e205ac5098ce.png)
