### ISSUE TITLE
allow state (Display) template

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/button-card#266]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

to display a ':' after the entity state on the button

**Describe alternatives you've considered**
 tried something like this:
```
  state:
    - value: 'on'
      state:
        - value: >
            [[[ return state +': ']]]
```
**Additional context**

current:
<img width="101" alt="Schermafbeelding 2020-01-15 om 11 00 39" src="https://user-images.githubusercontent.com/33354141/72426237-a6667080-3789-11ea-8280-31e233440cff.png">

hope to establish:

On: 82%
thanks for considering!
