### ISSUE TITLE
button's color doesn't change correctly after frontend.set_theme

### ISSUE THREAD

**Issue by basnijholt** [custom-cards/button-card#267]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
Upon running `frontend.set_theme` the buttons do not correctly change colors.
Only upon refreshing the page will correctly set the button's colors.

###  -----> [This video shows the problem](https://imgur.com/jDspCmh). <-----

**Version of the card**
Version: 3.1.1

**To Reproduce**
Use
```
input_boolean:
  dark_mode:
    name: Dark mode

automation:
  - alias: "Frontend: turn on dark mode"
    trigger:
      - platform: time
        at: "20:00"
      - platform: state
        entity_id: input_boolean.dark_mode
        from: "off"
        to: "on"
    action:
      - entity_id: input_boolean.dark_mode
        service: input_boolean.turn_on
      - service: frontend.set_theme
        data:
          name: ios-dark-mode

  - alias: "Frontend: turn on light mode"
    trigger:
      - platform: time
        at: "06:00"
      - platform: state
        entity_id: input_boolean.dark_mode
        from: "on"
        to: "off"
    action:
      - entity_id: input_boolean.dark_mode
        service: input_boolean.turn_off
      - service: frontend.set_theme
        data:
          name: ios-light-mode
```
and install [`lovelace-ios-dark-mode-theme`](https://github.com/basnijholt/lovelace-ios-dark-mode-theme) and [`lovelace-ios-light-mode-theme`](https://github.com/basnijholt/lovelace-ios-light-mode-theme).

Then use the `input_boolean.dark_mode` to toggle between the themes.

**Screenshots**
See [this video](https://imgur.com/jDspCmh) on imgur
![](https://imgur.com/jDspCmh.gif)

**Expected behavior**
The buttons should look like this in one theme:
<img width="239" alt="Screenshot 2020-01-18 at 17 31 45" src="https://user-images.githubusercontent.com/6897215/72667106-839dbb80-3a18-11ea-8a9a-7d615e0e1449.png">

and this in the other theme:
<img width="350" alt="Screenshot 2020-01-18 at 17 32 03" src="https://user-images.githubusercontent.com/6897215/72667107-839dbb80-3a18-11ea-9939-69e2dd502881.png">

**Desktop (please complete the following information):**
 - Happens in latest Chrome, Brave, Firefox, and Safari

**Smartphone (please complete the following information):**
 - Device: tested on iPhone
 - OS: latest

**Comment by RomRider** [comment]
It seems to only concern the icon color, correct?

**Comment by basnijholt** [comment]
Correct!

**Comment by RomRider** [comment]
There's not much I can do as I don't think I can catch when the theme is changing (and the color of the icon and the text is automatically calculated based on the background luminance, thus not updating when the CSS variable value is update)
What I'd suggest is for you to use a variable from your theme for the icon and the text. Something like:
```yaml
styles:
  icon:
    - color: var(--paper-item-icon-color)
  name:
    - color: var(--primary-text-color)
```

Could you try that and report back please?
