### ISSUE TITLE
Possible to call more-info for a different entity_id?

### ISSUE THREAD

**Issue by krasatos** [custom-cards/button-card#269]
What i am trying to do is bring the more-info page of a different entity when long pressing.
In my case, tap-action enables the radiator with a 90 minute timer, and i would like to bring up the more-info page of the input_number that defines the timer.
Something like this:

```
...
      - tap_action:
          action: toggle
        entity: switch.radiator_upstairs_timer
        hold_action:
          action: more-info
          entity_id: input_number.radiator_timer_upstairs
...
```
Would that be possible somehow?
Perhaps there's a service i can manipulate to bring the more-info screen?

**Comment by mrand** [comment]
Have you checked this out?  https://github.com/thomasloven/hass-browser_mod#replacing-more-info-dialogs

**Comment by RomRider** [comment]
This is already possible (it's just not `entity_id` it's simply `entity`):
```yaml
...
      - tap_action:
          action: toggle
        entity: switch.radiator_upstairs_timer
        hold_action:
          action: more-info
          entity: input_number.radiator_timer_upstairs
...
```
