### ISSUE TITLE
double_tap_action and hold_action break tap_action on iOS 13

### ISSUE THREAD

**Issue by SamLewis0602** [custom-cards/button-card#270]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
If I have double_tap_action and tap_action set on a button, the double_tap_action is executed on both single and double taps.
If I have hold_action and tap_action set on a button, single tap events seem to trigger twice. It will turn lights on and immediately off again on a single tap.

Both of the above scenarios work fine in Chrome on MacOS.

**Version of the card**
Version: 3.1.1

**To Reproduce**
This is the configuration I used:
```yaml
cards:
  - cards:
      - color: auto
        entity: light.key_light
        hold_action:
          action: more-info
        icon: 'mdi:desk-lamp'
        name: Key Light
        type: 'custom:button-card'
      - color: auto
        entity: light.yeelight_lamp
        hold_action:
          action: more-info
        icon: 'mdi:floor-lamp'
        name: Living Room
        type: 'custom:button-card'
    type: horizontal-stack
  - cards:
      - entity: switch.sunroom_lamp
        icon: 'mdi:lamp'
        name: Sunroom
        type: 'custom:button-card'
      - color: auto
        entity: light.living_room_back_level
        hold_action:
          action: more-info
        icon: 'mdi:wall-sconce-flat'
        name: Living Room
        tap_action:
          action: toggle
        type: 'custom:button-card'
    type: horizontal-stack
type: vertical-stack
```

**Screenshots**

**Expected behavior**
hold_action and double_tap_action should not interfere with tap_action. The issue only exists on iOS in the Home Assistant app.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 13.3
 - Browser: Home Assistant app, latest version
 - Version 2019.1

**Additional context**
Moving this thread here from https://github.com/home-assistant/home-assistant-polymer/issues/4419
