### ISSUE TITLE
No pictures displayed on Cast

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/button-card#271]
**Checklist**
- [ ] I updated the card to the latest version available
- [ ] I cleared the cache of my browser

**Describe the bug**

None of the pictures configured in the button cards are displayed when using Cast, all showing empty placeholders.

**Version of the card**
Version: 
3.1.1
**To Reproduce**
This is the configuration I used:
```yaml

```

**Screenshots**

![20200120_065846623_iOS](https://user-images.githubusercontent.com/33354141/72705255-4d1c8980-3b5b-11ea-96bf-ff005f5c09cd.jpg)

**Expected behavior**

**Desktop (please complete the following information):**

Chrome obviously, no matter which version, but latest.... MacBook , Hassio 103.5
**Smartphone (please complete the following information):**

**Additional context**

seems Cast has more issues with pictures, but since buttons used the predominantly in my setup, hope this can be solved.

**Comment by mcfrojd** [comment]
Same problem when casting my status view to my Google hub.

<img width="765" alt="Screenshot McDesktop 2020-02-03 17_20_31" src="https://user-images.githubusercontent.com/7395495/73670600-cd89d100-46a9-11ea-9420-322a6928a030.png">
(Image from desktop showing the images.)


![IMG_20200203_172058](https://user-images.githubusercontent.com/7395495/73670726-0f1a7c00-46aa-11ea-9d8e-d32b28cf7f0c.jpg)
(Photo from my Google hub.)

```
        - type: "custom:button-card"
          color_type: label-card
          show_entity_picture: true
          entity_picture: /local/lovelace/home/icon_home_assistant.png
          styles:
            card:
              - background-color: rgba(56,60,69,1)
              - border-radius: 30px
              - padding: 5px
              - height: 60px
              - width: 60px
            entity_picture:
              - height: 100%
              - width: 100%
              - padding: 5px
```
