### ISSUE TITLE
Haptics not working

### ISSUE THREAD

**Issue by SamB-GB** [custom-cards/button-card#276]
Haptic doesn't seem to be working. It works fine if I use an entity-button but switching to custom-button I get no haptic feedback.

Version: 3.1.1
App Version: 2019.1 (2.0)

This is the configuration I used:
```
  - entity: lock.front_door_lock
    hold_action:
      action: more-info
    show_icon: true
    show_name: true
    state:
      - styles:
          card:
            - background-color: '#bd2a36'
            - height: 100px
        value: locked
      - styles:
          card:
            - background-color: '#2cb851'
            - height: 100px
        value: unlocked
    tap_action:
      action: toggle
    haptic: success
    type: 'custom:button-card'
```
