### ISSUE TITLE
Embedded map card keeps refreshing when using templates in custom fields

### ISSUE THREAD

**Issue by jarrah31** [custom-cards/button-card#279]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
I'm experimenting with grids now that I understand how they work, and I'm tying to include the official map card within the button.

If one of the custom fields has template code, the map keeps refreshing as seen in the animated gif. If the custom field just has text, the map display is fine.

**Version of the card**
Version: 3.1.1

**To Reproduce**
This is the configuration I used:
```yaml
      - type: custom:button-card
        entity: zone.london
        show_entity_picture: true
        name: Test
        tap_action: more-info
        styles:
          card:
            - font-size: 17px
            - height: 200px
            - width: 400px
            - padding: 0px
          grid:
            - grid-template-rows: 75% min-content min-content
            - grid-template-columns: 1fr 1fr 50% 
            - grid-template-areas: '"i i map" "n n map" "speed speed map"'
        custom_fields:
          map:
            card:
              type: map
              style: |
                ha-card {
                  box-shadow: none;
                }
              default_zoom: 16
              entities:
                - zone.london
          speed: >
            [[[
              return `
              <span>speed</span>`
            ]]]
```
If the speed custom field just has the following, the map displays ok:
```
          speed: Custom Field
```
**Screenshots**
![button-card-embedded-map](https://user-images.githubusercontent.com/3072303/73980897-097e9980-4929-11ea-8f39-09c4704e8503.gif)

**Expected behavior**
I'd like to use templates within the custom fields and not have the map keep refreshing please.

**Desktop (please complete the following information):**
 - Browser:  safari
 - Version: 13.05

**Smartphone (please complete the following information):**
N/A

**Additional context**
I love this button card, thank you so much for all your hard work!
