### ISSUE TITLE
Tap action doesn't work if no entity in main config

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/button-card#284]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**

Seems on a button card without entity, tap-action: more-info doesn't work, with an entity defined in the action fields options

I realize we can set the entity in the main config, but that shouldn't really be necessary

**Version of the card**
Version: 
3.1.1

**To Reproduce**
This is the configuration I used:
```yaml
  - type: 'custom:button-card'
    name: Family Presence
    # template: button_default_title
    tap_action:
      action: more-info
      entity: sensor.family_home
    hold_action:
      action: navigate
      navigation_path: phones_tablets
```

**Screenshots**

**Expected behavior**

Have tap-action respond to a defined entity in the tap-action field, when no entity is configured in the main button config section.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

see https://community.home-assistant.io/t/lovelace-button-card/65981/3063?u=mariusthvdb for more info on this
