### ISSUE TITLE
Custom Fields Relative position

### ISSUE THREAD

**Issue by PierreScerri** [custom-cards/button-card#286]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser

**Describe the bug**
Not sure that it is a bug, but when a custom field is used and the browser window changes size on my iMac and iPad (much less on the iPhone), the custom field looses its position relative to the main icon.

**Version of the card**
Version: 3.1.1

**To Reproduce**
This is the configuration I used:

```yaml
entity: sensor.garage_door_position
state:
  - color: green
    value: Closed
  - color: red
    value: Open
  - color: orange
    styles:
      icon:
        - animation: blink 2s ease infinite
    value: Moving
tap_action:
  action: call-service
  service: switch.turn_on
  service_data:
    entity_id: switch.garage_control
type: 'custom:button-card'
custom_fields:
  car_home: |
    [[[
      if (states["binary_sensor.car"].state =="on")
        return `<ha-icon
          icon="mdi:car"
          style="height: 70px; width: 70px; color: deepskyblue">
          </ha-icon>`
    ]]]
styles:
  custom_fields:
    car_home:
      - position: absolute
      - left: 42%
      - top: 40%

```

**Screenshots**
![Screenshot 2020-03-03 at 21 21 13](https://user-images.githubusercontent.com/34303331/75816238-14e0ab80-5d95-11ea-8955-dd7aaab52cfd.png)
![Screenshot 2020-03-03 at 21 21 35](https://user-images.githubusercontent.com/34303331/75816241-1611d880-5d95-11ea-8027-b274e9cc61d9.png)

**Expected behavior**

The custom field should maintain its relative position to the main icon when the browser window is resized.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Safari
 - Version [e.g. 22] 13.0.5

**Smartphone (please complete the following information):**
N/A

**Additional context**
