### ISSUE TITLE
Help request: buttons for things that don't really have on/off states

### ISSUE THREAD

**Issue by DeeBeeKay** [custom-cards/button-card#288]
Hi,

Sorry if this isn't the right place to ask. I'm trying to set up some buttons for things that are triggered by a Broadcom IR blaster device. The integration with Home Assistant requires that you set these things up as switches, but the reality is that there isn't any state feedback from the devices being triggered (eg Vol+ on an amplifier). 

This being the case, the button changing colour isn't useful, and also isn't necessarily true, since the IR code isn't always received - eg if there are a lot of bodies in a room blocking the receiver. Thus, having the button change colour to be on or off isn't super useful for me.

Is it possible to configure a button so that it won't change colour when pressed? If so, how would I do that? I am a bear of very little brain.

**Comment by RomRider** [comment]
Can you try:
```
state:
  - operator: default
     color: THE COLOR YOU WANT
```

**Comment by DeeBeeKay** [comment]
Thanks! That worked. I used a screenshot of my buttons in MS Paint to get the RGB value of the normal, unpressed button (which is white, 255 255 255), and using your code, it's solved.

For anyone that finds this post via search, the yaml code for one of my button rows looks like this:
```

cards:
  - color_type: blank-card
    type: 'custom:button-card'
  - color_type: card
    entity: switch.hdmi1
    icon: 'mdi:play-box'
    type: 'custom:button-card'
    state:
      - operator: default
        color: 'rgb(255, 255, 255)'
  - color_type: card
    entity: switch.hdmi2
    icon: 'mdi:gamepad-variant'
    type: 'custom:button-card'
    state:
      - operator: default
        color: 'rgb(255, 255, 255)'
  - color_type: card
    entity: switch.hdmi3
    icon: 'mdi:cctv'
    type: 'custom:button-card'
    state:
      - operator: default
        color: 'rgb(255, 255, 255)'
  - color_type: blank-card
    type: 'custom:button-card'
type: horizontal-stack
```
