### ISSUE TITLE
No "click" in iOS homeassistant app

### ISSUE THREAD

**Issue by bkupidura** [custom-cards/button-card#291]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser

**Describe the bug**
When clicking button, there is no "click" effect on iOS homeassistant app.
`tap_action` is executed properly, but its hard to tell if button was really clicked on iOS from user perspective.
This is only happening on iOS homeassistant app (not tested on android), in desktop browser everything is working. It also works as expected from mobile web browser.

It may be connected to missing `entity` in main body, but not sure.

**Version of the card**
Version: latest (07-01-2020), 51b29edc64aa32676dfb75a73f8af2074694ceb7

**To Reproduce**
This is the configuration I used:
```
          - type: "custom:button-card"
            name: "test"
            tap_action:
              action: call-service
              service: light.turn_off
              service_data:
                entity_id: all
```

**Screenshots**
Hard to catch click (shading) effect.

**Expected behavior**
Click efect visible in iOS app.

**Desktop (please complete the following information):**
 - Browser firefox
 - Version 73.0.1 (64-bit) (macos)

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: 13.3.1
 - Homeassistant app version 2.0.0 (69)

**Additional context**
Other buttons in iOS app are working correctly.
Ex.
```
              - type: "custom:button-card"
                double_tap_action:
                  action: more-info
                entity: light.living_room
                size: 20%
                show_icon: true
                show_name: true
                state_color: true
                tap_action:
                  action: toggle
```

**Comment by RomRider** [comment]
The web rendered of the home assistant app is the same as the safari browser on your phone. There shouldn't be any difference between them.

**Comment by bkupidura** [comment]
I check that and its not true. Both safari and firefox on my phone have shading effect. But its missing from homeassistant app.

**Comment by RomRider** [comment]
Can you try the latest version please and report back?

**Comment by bkupidura** [comment]
I bump button-card to 16.03.2020 (8015916858194a8b666779a47aee9339076ca34c), nothing changed regarding "click" effect.

**Comment by RomRider** [comment]
It seems related to the home assistant app, all the core components have the same issue (I just tried with the core button and I have the same issue)
I'm going to close this, please open an issue on the IOS app's github repo.

**Comment by bkupidura** [comment]
Can you share core button config you tested?

I checked with below button and it works as expected (click effect available).

```
      - type: button
        name: test
        entity: input_boolean.dummy
        tap_action:
            action: call-service
            service: light.turn_off
            service_data:
                entity_id: all
```
