### ISSUE TITLE
implement icon mdi helper classes

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/button-card#293]
**Is your feature request related to a problem? Please describe.**

I am limited by the options Home-assistant offers for the mdi icons, while a helper class is available at mdi https://dev.materialdesignicons.com/getting-started/webfont#helper-classes

**Describe the solution you'd like**

Since you already offer the 'spin' for the icon, I would hope it to be possible to add the other options rotate and flip too.

This would allow for a much more creative use of the current fixed icons on the buttons.

**Describe alternatives you've considered**

**Additional context**

this says it all:

<img width="204" alt="Schermafbeelding 2020-03-14 om 17 01 22" src="https://user-images.githubusercontent.com/33354141/76685618-7a465f00-6615-11ea-957b-3e378006cec4.png">
could be solved by using flip ;=)

thanks for considering (btw, Thomas Loven has a [PR for this in HA](https://github.com/home-assistant/frontend/pull/4855), but Balloob is still hesitant, if not opposed, while many users have applauded it. Might soon arrive in Card-mod, so maybe that could be of help?

thanks!

**Comment by RomRider** [comment]
You can already do that 🙂 :
* rotate:
```yaml
          styles:
            icon:
              - transform: rotate(45deg)
```
* flip
```yaml
          styles:
            icon:
              - transform: scaleX(-1)
```
