### ISSUE TITLE
Templating inside variables

### ISSUE THREAD

**Issue by dwainscheeren** [custom-cards/button-card#294]
Would it be possible to add templating to variables?

**Comment by dwainscheeren** [comment]
Something like (example):
```YAML
header_states_door:
  show_state: true
  show_label: true
  name: Doors
  icon: mdi:door
  variables:
    test_one: >
      [[[
        var test = 'test';

        return test;
      ]]]
  label: '[[[ return variables.test_one ]]]'
  name: '[[[ return variables.test_one ]]]'
```
