### ISSUE TITLE
new background animation behaves unexpectedly

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/button-card#295]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**

the new animation (for which a big thanks is in order: thanks!) doesnt work 100% just yet
After a few cache clearances, it seems to start off well, but after a little while blacks out, and stops all together so it seems.

**Version of the card**
Version: 3.2.0

**To Reproduce**
This is the configuration I used:
```yaml
extra_styles: |
  @keyframes bgswap1 {
    0% {
      background-image: url("/local/mijnafvalwijzer/kliko_geen.png");
    }
    25% {
      background-image: url("/local/mijnafvalwijzer/kliko_geen.png");
    }
    50% {
      background-image: url("/local/mijnafvalwijzer/plastic.png");
    }
    75% {
      background-image: url("/local/mijnafvalwijzer/plastic.png");
    }
    100% {
      background-image: url("/local/mijnafvalwijzer/kliko_geen.png");
    }
  }

styles:
  label:
    - text-transform: capitalize
    - font-size: 13px
    - font-weight: bold
    - color: var(--paper-card-background-color) #var(--primary-background-color)
#    - background-color: >
#       [[[ return states['sensor.trash_color'].state ]]]
#    - align-self: end
    - position: absolute
    - bottom: 1%
    - right: 50%
    - transform: translateX(+50%)
  card:
#    - background-image: >
#        [[[ return `url("${entity.attributes.entity_picture}")`; ]]]
#        [[[ return `url("/local/mijnafvalwijzer/kliko_geen.png,/local/mijnafvalwijzer/plastic.png")`; ]]]
#        [[[ return `url("${entity.attributes.entity_picture}")`; ]]]
#        [[[ return `url("${states['sensor.saver_trash_today'].attributes.entity_picture}",url("${states['sensor.saver_trash_tomorrow'].attributes.entity_picture}")`; ]]]
#    - animation: >
#        [[[ if (states['persistent_notification.trash_notification']) return 'blink 2s ease infinite';
#            return 'none';
#        ]]]
#    - background-repeat: no-repeat
    - animation: bgswap1 10s linear infinite
    - background-size: cover
```

**Screenshots**

![Mar-15-2020 22-56-25](https://user-images.githubusercontent.com/33354141/76711464-9e3a9b00-6710-11ea-8139-c1314d3e2c3a.gif)

**Expected behavior**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Safari Mac 13.05, Chrome seems better at it
 - Version [e.g. 22] 3.05

**Smartphone (please complete the following information):**

**Additional context**

additional questions:

1- can I still add the (now commented animation) for the blink on persistent_notification added to this new background animation?

2- I need to template these pictures to be the picture for today (entity) and tomorrow, (sensor.saver_trash_tomorrow). How can I add templates to these picture in the new extra_styles keyframe section, which for now is hard coded?

Ive tried to use the working code now commented in the card: background-image template, like this:
```
extra_styles: |
  @keyframes bgswap1 {
    0% {
      background-image: `url("${entity.attributes.entity_picture}")`;
    }
    25% {
      background-image: `url("${entity.attributes.entity_picture}")`;
    }
    50% {
      background-image: `url("${entity['sensor.saver_trash_tomorrow'].attributes.entity_picture}")`;
    }
    75% {
      background-image: `url("${entity['sensor.saver_trash_tomorrow'].attributes.entity_picture}")`;
    }
    100% {
      background-image: `url("${entity.attributes.entity_picture}")`;
    }
  }

```
but that doesnt work
thanks for having a look

**Comment by RomRider** [comment]
To apply multiple animation you have to do like this:
`animation: blink 2s ease infinite, bgswap1 10s linear infinite`

Regarding the other problem, I can't reproduce chrome, FF, safari, ipad and android work as expected with this CSS.

**Comment by Mariusthvdb** [comment]
thanks for the template! I knew I was close.... 

I'll try with the multiple animation, and report back if necessary... ;-)
magic.

**Comment by RomRider** [comment]
Cool! true, I didn't check your code, just made it work as a template :)

**Comment by Mariusthvdb** [comment]
haha, cool indeed. Trying to make things even cooler (because now I can morph the background, I want to morph a whole button):

Could we (you...) somehow morph multiple buttons into one another?

Use case: be able to have a single button position show multiple other defined buttons of the same size. 

I know this is another matter all together, but this issue made me think of that, so will post a new FR if you even remotely think this could be feasible..

**Comment by Mariusthvdb** [comment]
finalizing this issue, Ill share my button config, which, depending on the state of 2 sensors (the button entity and a second entity) shows either a background-image, or the new background swapper, and depending on 'Today' s state being trash day, shows a persistent_notification until it's dismissed, and while not being dismissed, flashes the button ;-)

```
type: custom:button-card
entity: sensor.saver_trash_today
aspect_ratio: 1/1
show_icon: false
show_name: false
show_label: true
tap_action:
  action: more-info
hold_action:
  action: navigate
  navigation_path: tijd_agenda
label: >
    [[[ if (entity.state == 'plastic verpakkingsafval') return 'plastic';
        return entity.state;
    ]]]
extra_styles: |
  [[[
  return `@keyframes bgswap1 {
    0% {
      background-image: url("${entity.attributes.entity_picture}");
    }
    25% {
      background-image: url("${entity.attributes.entity_picture}");
    }
    50% {
      background-image: url("${states['sensor.saver_trash_tomorrow'].attributes.entity_picture}");
    }
    75% {
      background-image: url("${states['sensor.saver_trash_tomorrow'].attributes.entity_picture}");
    }
    100% {
      background-image: url("${entity.attributes.entity_picture}");
    }
  }`
  ]]]
styles:
  label:
    - text-transform: capitalize
    - font-size: 13px
    - font-weight: bold
    - color: var(--paper-card-background-color) #var(--primary-background-color)
    - position: absolute
    - bottom: 1%
    - right: 50%
    - transform: translateX(+50%)
  card:
    - background-image: >
        [[[ if (states['sensor.saver_trash_tomorrow'].state == 'Geen') return `url("${entity.attributes.entity_picture}")`; ]]]
    - animation: >
        [[[ if (states['persistent_notification.trash_notification']) return 'blink 2s ease infinite';
            if (states['sensor.saver_trash_tomorrow'].state != 'Geen') return 'bgswap1 10s linear infinite';
            return 'none'; ]]]
    - background-size: cover
```

**Comment by Mariusthvdb** [comment]
> I'd use the state-switch card for that. There are already some effects included in there.

don't think that will do what I want, since I dont have a state to switch on. Let me explain with an image:

<img width="460" alt="Schermafbeelding 2020-03-16 om 19 57 52" src="https://user-images.githubusercontent.com/33354141/76791108-7276ee00-67c0-11ea-89c0-3a40ad0af6ec.png">

My hope was to have these 8 buttons cycled on 1 button placeholder. So I'd need 1 button screen real estate in stead of 8.  
Hoped to be able to use swipe card, and some sot of auto-swipe, but that seems deprecated/archived https://github.com/bramkragten/custom-ui/tree/master/swipe-card

**Comment by RomRider** [comment]
That seems very complex to achieve with button card.
However swipe-card exists for Lovelace: https://github.com/bramkragten/swipe-card

**Comment by Mariusthvdb** [comment]
yeah, I had found that already, but the documentation is somewhat lacking... still I managed to do so, and still needed to use your button card, because the swiper card-width setting wouldn't stick, either in px or %.

Now using this (didn't yet investigate all swipers options of course, so hope to get it even better):

![slider](https://user-images.githubusercontent.com/33354141/76839159-53ff0a00-6835-11ea-96f4-acfa9404f444.gif)

Note even the animations show nicely ;=)
```
  - type: horizontal-stack
    cards:

      - type: custom:swipe-card
        parameters:
          effect: coverflow #flip
          slideShadows: true
          autoplay:
            delay: 3000
            disableOnInteraction: false
    #      speed: 300
#          pagination:
#            type: 'bullets'
          scrollbar:
            hide: true
            draggable: true
            snapOnRelease: true
        cards:
          - !include /config/lovelace/includes/include_button_sensor_home.yaml
          - !include /config/lovelace/includes/include_button_alarmclock.yaml
          - !include /config/lovelace/includes/include_button_trash_today.yaml
          - !include /config/lovelace/includes/include_button_espresso.yaml
          - !include /config/lovelace/includes/include_button_vijverpomp.yaml
          - !include /config/lovelace/includes/include_button_animated_weather.yaml
          - !include /config/lovelace/includes/include_button_wind_direction.yaml
          - !include /config/lovelace/includes/include_button_levering_verbruik.yaml
```
