### ISSUE TITLE
Swipe (scroll or refresh) bad work

### ISSUE THREAD

**Issue by AndroVet** [custom-cards/button-card#302]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
The "swipe function" on any mobile devices always leads to a button press.

If the button type is specified as "type: custom: button-card" "swipe" always results in a button click.

**Version of the card**
Version: Installed: 3.2.2

**To Reproduce**
This is the configuration I used:
```yaml
- type: "custom:button-card"
  icon: mdi:chevron-triple-left
  color_type: card
  name: Prev
  entity: script.vsx_tune_prev
  hold_action: none
  tap_action:
    action: call-service
    service: script.vsx_tune_prev
  styles: *btn_steel_blue
```

**Expected behavior**
Behavior is like if the button type is assigned as usual “type: entity-button”, everything works well, the “swipe” function changes (scroll or refresh) the screen of the mobile device WITHOUT PRESSING button touched by a finger.

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version: 80.0.3987.122 (x64)

**Smartphone (please complete the following information):**
 - Device: Huawei Mate 8
 - OS: Android 6.0
 - Browser: Chrome
 - Version: 80.0.3987.119
