### ISSUE TITLE
tap-action for lock doesn't work after update

### ISSUE THREAD

**Issue by fribse** [custom-cards/button-card#303]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser

**Describe the bug**
Tap-action doesn't work for lock

**Version of the card**
Version: 3.2.2
HA: 0.107.0

**To Reproduce**
This is the configuration I used:
```yaml
cards:
  - cards:
      - color_type: blank-card
        type: 'custom:button-card'
      - entity: lock.poly_control_danalock_v3_btze_locked
        name: Hoveddør
        show_entity_picture: true
        state:
          - entity_picture: /local/images/lock-locked.png
            tap_action:
              action: call-service
              service: lock.unlock
              service_data:
                entity_id: lock.poly_control_danalock_v3_btze_locked
            value: locked
          - entity_picture: /local/images/lock-unlocked.png
            tap_action:
              action: call-service
              service: lock.lock
              service_data:
                entity_id: lock.poly_control_danalock_v3_btze_locked
            value: unlocked
        style: |
          ha-card{background:transparent;box-shadow: none;}
        type: 'custom:button-card'
      - color_type: blank-card
        type: 'custom:button-card'
    type: horizontal-stack
  - camera_view: live
    entity: camera.front_door
    show_name: false
    show_state: false
    type: picture-entity
  - camera_view: live
    entity: camera.front
    show_name: false
    show_state: false
    type: picture-entity
type: vertical-stack
```

**Screenshots**

**Expected behavior**
I would expect the tap action for the lock to lock/unlock the door.

**Desktop (please complete the following information):**
 - Firefoxn 74.0
 - Chrome 80.0.3987.132

**Smartphone (please complete the following information):**
 - Device: Sony Xperia XZ2
 - OS: Android 10
 - Browser Android HA App

**Additional context**
I have tried creating the card with only a vertical stack, and also with just the button itself, no joy on either of them.

**Comment by RomRider** [comment]
Your configuration is wrong.

Any `*_action` should be set at the root of the config, not in the state array.

All the `*_action` fields support templates so you can do what you are trying to do.

**Comment by fribse** [comment]
I see, very interesting, this is an old card, and have worked flawlessly for I guess a year, and I have several button cards built like this that all fail now. I must have missed that in an changelog.
I currently have no idea how to do this with templates.

**Comment by fribse** [comment]
And I don't see any examples on how to call two differenent services depending on the state in the examples, and no explanation of it in the docs.

**Comment by RomRider** [comment]
It was never an option to define the tap action as part of the state array, it's not related to an update.

This should work:
```yaml
cards:
  - cards:
      - color_type: blank-card
        type: 'custom:button-card'
      - entity: lock.poly_control_danalock_v3_btze_locked
        name: Hoveddør
        show_entity_picture: true
        tap_action:
          action: call-service
          service: '[[[ return entity.state === "locked" ? "lock.unlock" : "lock.lock" ]]]'
          service_data:
            entity_id: entity
        state:
          - entity_picture: /local/images/lock-locked.png
            value: locked
          - entity_picture: /local/images/lock-unlocked.png
            value: unlocked
        style: |
          ha-card{background:transparent;box-shadow: none;}
        type: 'custom:button-card'
      - color_type: blank-card
        type: 'custom:button-card'
    type: horizontal-stack
  - camera_view: live
    entity: camera.front_door
    show_name: false
    show_state: false
    type: picture-entity
  - camera_view: live
    entity: camera.front
    show_name: false
    show_state: false
    type: picture-entity
type: vertical-stack
```
