### ISSUE TITLE
Tap action not working on older iPad

### ISSUE THREAD

**Issue by PierreScerri** [custom-cards/button-card#309]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser

**Describe the bug**
Tap action not working on older iPad (iOS 10) when using Safari or the Companion App.  
Works with chrome when a service call is used.
Double-Tap action works fine.

**Version of the card**
Version: 3.2.3

**To Reproduce**
This is the configuration I used:

```yaml
double_tap_action:
  action: more-info
entity: switch.garden_lights
name: Garden
tap_action:
  action: toggle
type: 'custom:button-card'

or

double_tap_action:
  action: more-info
entity: switch.garden_lights
name: Garden
tap_action:
  action: call-service
  service: switch.toggle
  service_data:
    entity_id: witch.garden_lights
type: 'custom:button-card'

```

**Screenshots**

**Expected behavior**
It is expected that it works in the same way as it does on newer iOS devices.
ie the action should be triggered.

**Desktop (please complete the following information):**
 - Browser N/A
 - Version N/A

**Smartphone (please complete the following information):**
 - Device: iPad
 - OS: iOS10.3.3
 - Browser Safari, HA companion App, Chrome
 - Version [??,   2.0.0,   71]

**Additional context**
