### ISSUE TITLE
Button as a link

### ISSUE THREAD

**Issue by slusken** [custom-cards/button-card#31]
Feature Request
Can the feature that a button can work as a link to a specific site be implemented? 
Like:
action: navigate
navigation_path: /lovelace/0

Like the function you have in Picture Elements Card.
Thx for the good work!

**Comment by kuuji** [comment]
Thanks for the feedback, I'll have a look at that.

**Comment by SeanPM5** [comment]
I would really love this feature too. I just made a pretty nifty "update available" button that shows on my default_view, but then realized "navigate" function wasn't supported. 

I was trying to link the button to the Hassio update page. I have this working through the built-in glance card, but this custom button-card is way more pretty: https://i.imgur.com/6OXerZe.png

```
      - type: horizontal-stack
        cards:
          - type: "custom:button-card"
            name: Update Available
            entity: input_boolean.update_available
            icon: mdi:home-assistant
            color_type: card
            style:
              - font-size: 18px
              - font-weight: bold
              - color: var(--primary-color)
            action: navigate
            navigation_path: /hassio/dashboard
```
