### ISSUE TITLE
[ show_live_stream ] Stream freezes after a few hours using 

### ISSUE THREAD

**Issue by friendodevil** [custom-cards/button-card#312]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser

**Describe the bug**
Stream freezes after a few hours

**Version of the card**
3.2.3

**To Reproduce**
This is the configuration I used:
```
          - type: custom:button-card
            entity: camera.gate
            show_live_stream: true
            name: Gate
            size: 100%
            styles:
              card:
              - font-size: 12px
```

**Expected behavior**
Button to continue to elegantly displaying the live stream without stream getting stuck

**Smartphone (please complete the following information):**
 - Device: Fire 7 tablet
 - OS: Fire OS 6.3.1.5
 - Browser WallPanel
 - Version 0.8.7 build 4

**Additional context**
After resetting the WallPanel app, the stream resumes... but gets stuck again after 3-4 hrs. Steam is coming from an onvif camera with the following configuration

```
  - platform: onvif
    name: Gate
    host: !secret_gatecam
    profile: 0
    username: !secret gbl_pl960_username
    password: !secret gbl_pl960_password
    port: 2000
```
