### ISSUE TITLE
Action to fire Javascript command

### ISSUE THREAD

**Issue by cgarwood** [custom-cards/button-card#314]
**Is your feature request related to a problem? Please describe.**
I use Fully Kiosk Browser on wall-mounted tablets for my Home Assistant UI. Fully has custom javascript functions (like `fully.setScreenBrightness(123)`) you can call to manipulate the device, such as setting screen brightness, turning the screen off, etc. I would like to make use of some of these functions from the HA UI.

**Describe the solution you'd like**
A new type of `action` that will fire a specified javascript function when the button is tapped

**Describe alternatives you've considered**
Have not seen any alternatives. Currently using TileBoard which has this capability, but am trying to migrate over to Lovelace for my wall-mounted tablets.

**Additional context**

**Comment by RomRider** [comment]
You can already do that, but it's kind of an undocumented hack :)
```yaml
tap_action:
  action: put_any_thing_here_but_an_official_value
  whatever_literaly: |
    [[[
      fully.setScreenBrightness(123);
    ]]]
```

for example:
```yaml
  - type: custom:button-card
    name: test-js
    tap_action:
      action: nothing
      log_me: '[[[ console.log(hass) ]]]'
```
