### ISSUE TITLE
Strange icon dimension after updating to HA 0.109.0b0

### ISSUE THREAD

**Issue by mgiako** [custom-cards/button-card#316]
**Checklist**
- [X] I updated the card to the latest (stable) version available
- [X] I cleared the cache of my browser

**Describe the bug**
Since I upgraded to HA 0.109.0b0 the icons in some of my custom button card behave strangely.
I use the state of the button to display a timer. When the timer is active the font is 9px and when the timer is idle the font is 0px. The icon dimension used to adapt, so in HA 0.108.8 I had

![image](https://user-images.githubusercontent.com/44270368/80124275-50774500-8590-11ea-9506-e2b87dec64f9.png)

respectively when the timer is off and on
In 0.109.0b0 I have this:

![image](https://user-images.githubusercontent.com/44270368/80124470-992efe00-8590-11ea-929f-5a90e0ed47c3.png)
because the icon remains the same (too tiny) dimension.

**Version of the card**
Version: 3.2.3

**To Reproduce**
This is the configuration I used:
```
              - type: custom:button-card
                entity: timer.taverna
                icon: mdi:lightbulb
                name: taverna
                tap_action: 
                  action: call-service
                  service: light.toggle
                  service_data:
                    entity_id: light.luce_taverna
                hold_action: 
                  action: call-service
                  service: automation.toggle
                  service_data:
                    entity_id: automation.luce_taverna_spegni_su_fine_timer
                show_state: true
                show_name: true
                show_icon: true
                color_type: icon

                styles:
                  img_cell:
                    - justify-content: middle
                    - align-items: middle
                    - margin: none 
                  state:
                    - font-size: >
                          [[[
                             if (states['timer.taverna'].state == 'idle')
                              return "0px";
                             else
                              return "9px";
                          ]]]

                  card:
                  - height: 64px
                  icon:
                    - color: >
                          [[[
                             if (states['light.luce_taverna'].state == 'on')
                              return "var(--paper-item-icon-active-color)";
                             return "var(--paper-item-icon-color)";
                          ]]]
                  grid:
                    - position: relative
                    - grid-template-areas: '"i" "s" "n" "l"'
```

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari]: chrome 
 - Version [e.g. 22] latest

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]: Iphone 8
 - OS: [e.g. iOS8.1] iOS 13.4
 - Browser [e.g. stock browser, safari] chrome and safari
 - Version [e.g. 22] latest

**Comment by mgiako** [comment]
Same problem with HA 0.109.0b1

**Comment by mynameisdaniel32** [comment]
Also seeing weird behaviour on the beta.

Displays the layout/sizing okay, but the larger text is cropped, can include my config if it will help (it's pretty messy). One is using label, the other name, should say "7:53 AM" and "25*C".

![image](https://user-images.githubusercontent.com/24840952/80261591-03978980-86ca-11ea-9de5-140fb8abd4b1.png)

**Comment by RomRider** [comment]
I can't seem to reproduce with the latest dev code. Let's see if it still happens after the release and I'll fix it then.

**Comment by mgiako** [comment]
I updated to 3.3.1 and the issue remains.
But since the problem was born with the transition to HA 0.109.0b0, and if I reinstall 0.108.8 the problem disappears, something must have changed in HA and the problem is not in your custom card or in my configuration. 
In my opinion something has changed in 0.109 beta that affects your card.

**Comment by mgiako** [comment]
Since I read that there was a bug with timer entities in horizontal stack (even if I didn't have any issue with 3.2.3 card on HA 0.108.8), I post my entire horizontal stack cards config. Hope this can help you!
```
      - type: vertical-stack
        cards:

          - type: horizontal-stack
            cards:

              - type: custom:button-card
                entity: light.luce_cantina
                name: cantina
                hold_action: 
                  action: more-info 
                custom_fields: #binary_sensor.motion_sensor_158d00029a96f9
                  sensor: >
                    [[[
                     if (states['binary_sensor.xiaomimovimentocantina'].state == 'on')
                      return `<ha-icon
                        icon="mdi:run"
                        style="width: 15px; height: 15px; color: orange;">
                        </ha-icon>`;
                     return `<ha-icon
                      icon="mdi:run"
                      style="width: 15px; height: 15px; color: var(--paper-card-background-color);">
                      </ha-icon>`;
                    ]]]
                styles:
                  img_cell:
                    - justify-content: middle
                    - align-items: middle
                    - margin: none 
                  card:
                  - height: 64px
                  grid:
                    - position: relative
                    - grid-template-areas: '"i" "s" "n" "l"'
                  custom_fields:
                    sensor:
                      - position: absolute
                      - align-self: start
                      - justify-self: end


              - type: custom:button-card
                triggers_update: all
                entity: timer.garage
                icon: mdi:lightbulb
                name: garage
                tap_action: 
                  action: call-service
                  service: light.toggle
                  service_data:
                    entity_id: light.luce_garage  
                hold_action: 
                  action: call-service
                  service: automation.toggle
                  service_data:
                    entity_id: automation.luce_garage_spegni_su_fine_timer
                show_state: false
                show_name: true
                show_icon: true
                color_type: icon
                custom_fields:
                  sensor: >
                    [[[
                     if (states['binary_sensor.microonde_garage'].state == 'on')
                      return `<ha-icon
                        icon="mdi:run"
                        style="width: 15px; height: 15px; color: red;">
                        </ha-icon>`;
                     return `<ha-icon
                      icon="mdi:run"
                      style="width: 15px; height: 15px; color: var(--paper-card-background-color);">
                      </ha-icon>`;
                    ]]]
                  xiaomi: >
                    [[[
                     if (states['binary_sensor.xiaomimovimentogarage'].state == 'on')
                      return `<ha-icon
                        icon="mdi:run"
                        style="width: 15px; height: 15px; color: orange;">
                        </ha-icon>`;
                     return `<ha-icon
                      icon="mdi:run"
                      style="width: 15px; height: 15px; color: var(--paper-card-background-color);">
                      </ha-icon>`;
                    ]]]
                  timer: >
                    [[[
                     if (states['automation.luce_garage_spegni_su_fine_timer'].state == 'on')
                      return `<ha-icon
                        icon="mdi:timer-off"
                        style="width: 15px; height: 15px; color: var(--paper-card-background-color);">
                        </ha-icon>`;
                     return `<ha-icon
                      icon="mdi:timer-off"
                      style="width: 15px; height: 15px; color: red;">
                      </ha-icon>`;
                    ]]]
                styles:
                  img_cell:
                    - justify-content: middle
                    - align-items: middle
                    - margin: none 
                  state:
                    - font-size: >
                          [[[
                             if (states['timer.garage'].state == 'idle')
                              return "0px";
                             else
                              return "9px";
                          ]]]
                  card:
                  - height: 64px
                  icon:
                    - color: >
                          [[[
                             if (states['light.luce_garage'].state == 'on')
                              return "var(--paper-item-icon-active-color)";
                             return "var(--paper-item-icon-color)";
                          ]]]
                  grid:
                    - position: relative
                    - grid-template-areas: '"i" "s" "n" "l"'
                  custom_fields:
                    sensor:
                      - position: absolute
                      - align-self: start
                      - justify-self: end
                    xiaomi:
                      - margin: none
                      - position: absolute
                      - align-self: middle
                      - justify-self: end                      
                    timer:
                      - position: absolute
                      - align-self: start
                      - justify-self: start


              - type: custom:button-card
                triggers_update: all
                entity: timer.taverna
                icon: mdi:lightbulb
                name: taverna
                tap_action: 
                  action: call-service
                  service: light.toggle
                  service_data:
                    entity_id: light.luce_taverna
                hold_action: 
                  action: call-service
                  service: automation.toggle
                  service_data:
                    entity_id: automation.luce_taverna_spegni_su_fine_timer
                show_state: true
                show_name: true
                show_icon: true
                color_type: icon
                custom_fields: #binary_sensor.motion_sensor_158d00029a96f9
                  sensor: >
                    [[[
                     if (states['binary_sensor.microonde_taverna'].state == 'on')
                      return `<ha-icon
                        icon="mdi:run"
                        style="width: 15px; height: 15px; color: red;">
                        </ha-icon>`;
                     return `<ha-icon
                      icon="mdi:run"
                      style="width: 15px; height: 15px; color: var(--paper-card-background-color);">
                      </ha-icon>`;
                    ]]]
                  timer: >
                    [[[
                     if (states['automation.luce_taverna_spegni_su_fine_timer'].state == 'on')
                      return `<ha-icon
                        icon="mdi:timer-off"
                        style="width: 15px; height: 15px; color: var(--paper-card-background-color);">
                        </ha-icon>`;
                     return `<ha-icon
                      icon="mdi:timer-off"
                      style="width: 15px; height: 15px; color: red;">
                      </ha-icon>`;
                    ]]]
                styles:
                  img_cell:
                    - justify-content: middle
                    - align-items: middle
                    - margin: none 
                  state:
                    - font-size: >
                          [[[
                             if (states['timer.taverna'].state == 'idle')
                              return "0px";
                             else
                              return "9px";
                          ]]]

                  card:
                  - height: 64px
                  icon:
                    - color: >
                          [[[
                             if (states['light.luce_taverna'].state == 'on')
                              return "var(--paper-item-icon-active-color)";
                             return "var(--paper-item-icon-color)";
                          ]]]
                  grid:
                    - position: relative
                    - grid-template-areas: '"i" "s" "n" "l"'
                  custom_fields:
                    sensor:
                      - position: absolute
                      - align-self: start
                      - justify-self: end
                    timer:
                      - position: absolute
                      - align-self: start
                      - justify-self: start

              - type: custom:button-card #entity-button
                entity: light.lab
                name: lab
                styles:
                    card:
                      - height: 64px
                hold_action: 
                  action: more-info
```
And this is the result while the garage timer is idle and taverna timer is active:

![image](https://user-images.githubusercontent.com/44270368/80321535-1327e700-881e-11ea-8eee-fc06071efe81.png)

**Comment by mynameisdaniel32** [comment]
Config for one of my simpler ones doing this, pretty much anything bigger than 1em causes cropping.
```          - type: "custom:button-card"
            entity: sensor.friendly_time
            show_label: true
            show_icon: false
            show_name: false
            label: >
              [[[
                return states['sensor.friendly_time'].state
              ]]]
            aspect_ratio: 16/10
            tap_action:
              action: none
            styles:
              card:
                - color: '#DADADB'
              label:
                - font-size: 6em
```

**Comment by RomRider** [comment]
I see they've changed the style of the default ha-card. Could you try this please ?
```yaml
styles:
  card:
    - line-height: normal
```

I'm going to integrate this change as a default in the next release if it works well.

**Comment by mgiako** [comment]
With that line everything is good as before!
![image](https://user-images.githubusercontent.com/44270368/80496377-6b1f3480-8969-11ea-924f-526a1941ba04.png)
Thank you very much!

**Comment by mynameisdaniel32** [comment]
Can confirm adding that line fixed mine up to behave as it was before too! Thank you!

**Comment by ArkadiuszNiemiec** [comment]
I have just updated to 0.110.* and have similar problem. My icons are now way smaller and not vertically centred:

![Capture](https://user-images.githubusercontent.com/12136404/81815493-55456e00-952a-11ea-884e-ff0a8f2a887d.PNG)

```
                        - type: 'custom:button-card'
                          entity: switch.kitchen_wall_right # button kitchen
                          icon: 'mdi:stove'
                          show_icon: true
                          show_name: false
                          state:
                            - styles:
                                icon:
                                  - color: 'var(--paper-item-icon-active-color)  '
                              value: 'on'
                          styles:
                            card:
                              - height: 70px
                              - border-radius: 4px
                              - background-color: var(--primary-background-color)
                            icon:
                              - width: 80%
                              - color: var(--primary-text-color)
                          tap_action:
                            action: toggle
                            haptic: light
                          hold_action:
                            action: more-info
```
The `height` in icon style normally set the icon size, and they were centred by default.
I have found that the `ha-svg-icon` element has these properties:
```
width: var(--mdc-icon-size, 24px);
height: var(--mdc-icon-size, 24px);
```
But what about centring? @RomRider can you please check what they changed?
