### ISSUE TITLE
Is there a way to control word wrapping?

### ISSUE THREAD

**Issue by poldim** [custom-cards/button-card#317]
**Checklist**
- [x ] I updated the card to the latest version available
- [x ] I cleared the cache of my browser

**Describe the bug**
The two sconce cards don't word wrap at the same time because `Right` is longer than `Left`.  Can I force them to do it at the same time or always wrap to two lines?

**Version of the card**
Version: 3.2.3

**To Reproduce**
This is the configuration I used:
```yaml
      - type: horizontal-stack
        cards:
          - type: "custom:button-card"
            template: light_button
            entity: light.window_lights
            name: Window Lights
            vertical:
            icon: mdi:wall-sconce-variant
            hold_action:
              action: more-info
              entity: light.window_lights
          - type: "custom:button-card"
            template: light_button
            entity: light.crown_molding
            name: Crown Molding
            icon: mdi:crown
            hold_action:
              action: more-info
              entity: light.crown_molding
          - type: "custom:button-card"
            template: light_button
            entity: light.sconce_left
            name: |
              Sconce
              Left
            icon: mdi:wall-sconce
            hold_action:
              action: more-info
              entity: light.sconce_left
          - type: "custom:button-card"
            template: light_button
            entity: light.sconce_right
            name: Sconce Right
            icon: mdi:wall-sconce
            hold_action:
              action: more-info
              entity: light.sconce_right
```

**Screenshots**
![image](https://user-images.githubusercontent.com/16869713/80271648-01f0a600-8677-11ea-9830-ed4b723b045f.png)

**Expected behavior**
Force them to split to two lines at the same time.

**Desktop (please complete the following information):**
Google Chrome is up to date
Version 81.0.4044.122 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: iPhone Xs
 - OS: Latest
 - Browser Chrome
 - Version Latest
