### ISSUE TITLE
show_units does not work anymore

### ISSUE THREAD

**Issue by hwmland** [custom-cards/button-card#321]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
After upgrading HA from 0.107.x to 0.109.2 show_units does not work anymore. 
- When set to false it does show original unit regardless of presence or value of 'units' attribute. 
- When set to true 'units' attribute is shown (correct) or original unit when attribute not specified

**Version of the card**
Version: 3.3.2

**To Reproduce**
This is the configuration I used:
```yaml
          - type: "custom:button-card"
            entity:  sensor.owm_pressure
            template: bedtoom_entity_card
            icon: mdi:gauge
            name: Tlak hPa
            styles:
              card:
                - height: 165px

#### definition of template elsewhere ###

bedtoom_entity_card:
  show_state: true
  show_units: false
  styles:
    grid:
      - grid-template-areas: '"i n" "s s"'
      - grid-template-columns: 90px 1fr
      - grid-template-rows: 30px min-content
    state:
      - font-size: 5em
```

**Screenshots**

**Expected behavior**

**Desktop (please complete the following information):**
 - Chrome
 - Version 81.0.4044.129
(the same behavior on my Android tablet)

**Smartphone (please complete the following information):**

**Additional context**
