### ISSUE TITLE
show_state has stopped working

### ISSUE THREAD

**Issue by jarrah31** [custom-cards/button-card#322]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
If I set `show_state` to true, I see the following error:
![image](https://user-images.githubusercontent.com/3072303/81060625-c356b900-8eca-11ea-933f-da149f422993.png)

This happens with any entity, be it lights, switches, etc. If I set it to false, the error goes away.

If it helps I also see this in the browser dev view:
![image](https://user-images.githubusercontent.com/3072303/81061028-8808ba00-8ecb-11ea-9a9d-861cd97e10ec.png)

The entity looks like this:
![image](https://user-images.githubusercontent.com/3072303/81061437-42002600-8ecc-11ea-9bc4-a51e75d3e9c6.png)

It started after I upgraded from 3.3.0-1 to 3.3.2.
**Version of the card**
Version: 3.3.2
HA version: 106.6

**To Reproduce**
This is the configuration I used:
```yaml
      - type: "custom:button-card"
        entity: light.study_desk_lamp
        name: Light
        color_type: icon
        color: auto
        show_label: true
        show_state: true
        show_name: true
```

**Desktop (please complete the following information):**
 - Browser [Chrome 81.0.4044.122 and Safari]
