### ISSUE TITLE
Size of icon doesn't change on Cast

### ISSUE THREAD

**Issue by jer78** [custom-cards/button-card#323]
**Checklist**
- [ x] I updated the card to the latest version available
- [x ] I cleared the cache of my browser

**Describe the bug**
When using cast on my Google Home display, I cannot get the size of the icon to change. The changes are correctly reflected on any other device. Not sure which version this changed, but it was working correctly in an earlier version.

**Version of the card**
Version: 3.3.3

**To Reproduce**
This is the configuration I used:
```yaml
                          - type: 'custom:button-card'
                            entity: switch.office_macbook_pro
                            show_icon: true
                            show_name: false
                            color_type: card
                            name: MACBOOK
                            icon: mdi:apple
                            size: 80px
                            state:
                              - value: 'on'
                                color: '#abcc65' #green
                            tap_action:
                              action: toggle
                            style: |
                              ha-card {
                                background-color: var(--primary-background-color);
                                margin: 5px 5px 5px 5px;
                                box-shadow: 
                                  {% if is_state('binary_sensor.dark_mode', 'off') and is_state('switch.office_macbook_pro', 'on') %}
                                    inset -4px -4px 8px 0 rgba(255,255,255,.5), inset 4px 4px 8px 0 rgba(0,0,0,.03);
                                  {% elif is_state('binary_sensor.dark_mode', 'off') and is_state('switch.office_macbook_pro', 'off') %}                      
                                    -8px -8px 8px 0 rgba(255,255,255,.5),8px 8px 8px 0 rgba(0,0,0,.03);
                                  {% elif is_state('binary_sensor.dark_mode', 'on') and is_state('switch.office_macbook_pro', 'on') %}                      
                                    inset -4px -4px 10px 0 rgba(50, 50, 50,.5), inset 4px 4px 12px 0 rgba(0,0,0,.3); 
                                  {% elif is_state('binary_sensor.dark_mode', 'on') and is_state('switch.office_macbook_pro', 'off') %}   
                                    -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
                                  {% endif %}                        
                              }
                            styles:
                              card:
                                - width: 80px
                                - height: 80px
                                - border-radius: 15px
                              name: 
                                - font-size: 0.9em
```

**Screenshots**
![comparision button-card](https://user-images.githubusercontent.com/1253286/81693199-9441c980-942d-11ea-96c2-6d83c4bc920d.png)

**Expected behavior**
As seen in the picture attached, there's a difference between the google cast view and the view from Safari browser on my Mac

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RomRider** [comment]
Could you please try with 3.3.4?

**Comment by RomRider** [comment]
Now with 3.3.5 😊

**Comment by wackyshan** [comment]
Facing the same issue as @jer78  with 3.3.5. 

![image](https://user-images.githubusercontent.com/33682501/82780276-476de200-9e74-11ea-97f5-5d03eaf94823.png)

```
aspect_ratio: 1/1
color: 'rgb(181,141,49)'
color_type: icon
entity: light.545768784c11ae10190c
hold_action:
  action: more-info
name: Light
show_name: false
size: 80%
styles:
  card:
    - border-radius: 5px
type: 'custom:button-card'
```
