### ISSUE TITLE
No button animations in HA 0.110.x

### ISSUE THREAD

**Issue by VDRainer** [custom-cards/button-card#325]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
In HA 0.110 beta the tap and hold animations are missing.

**Version of the card**
Version: 3.3.4

**To Reproduce**
This is the configuration I used:
```yaml
cards:
  - entity: switch.mqtt_test
    hold_action:
      action: more-info
    name: Core
    show_icon: true
    show_name: true
    tap_action:
      action: toggle
    type: button
  - entity: switch.mqtt_test
    hold_action:
      action: more-info
    name: Custom
    tap_action:
      action: toggle
    type: 'custom:button-card'
type: horizontal-stack
```

**Screenshots**
HA 0.109.6 - works as expected
![button-card_01096](https://user-images.githubusercontent.com/26381449/82254503-39d7ca00-9953-11ea-9959-f0cd3dead74c.gif)

HA 0.110.0b3 - animations on tap and hold missing
![button-card_0110b](https://user-images.githubusercontent.com/26381449/82254534-4a884000-9953-11ea-9835-210bddc7ebac.gif)

**Expected behavior**
See the animations to get feedback from the button.

**Desktop (please complete the following information):**
 - Browser: Firefox and Chrome
 - Version: Latest on Ubuntu 18.04

**Smartphone (please complete the following information):**
 - Device: iPhone6s
 - OS: 13.4.1
 - Browser: Companion App

**Additional context**
