### ISSUE TITLE
Icon size for font-awesom

### ISSUE THREAD

**Issue by corvis** [custom-cards/button-card#328]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
The size of font-awesome icons is wrong. Basically the small icon remains in the top of container and the style controlling icon size applies to container only.   

It seems like recent icon size fix applies only to MDI icons and font-awesome icons are broken now.  

**Version of the card**
Version: 3.3.4

**To Reproduce**
Update to HASS 0.110 and just use any [font-awesome icon](https://github.com/thomasloven/hass-fontawesome) e.g.:

```yaml
    type: custom:button-card
    template: room_action_button
    entity: "my-entity-id"
    icon: fas:temperature-low
    name: HVAC Control
    tap_action:
      action: toggle
    variables:
      active_state: 'on'
    styles:
        card:
          - box-shadow: none
          - background: transparent
        img_cell:
          - background: transparent
          - border: '1px solid var(--ct-grey)'
          - border-radius: 5px
          - width: 80px
          - height: 80px
        icon:
          - color: var(--ct-accent)
          - height: 55px
```

**Screenshots**
![Selection_096](https://user-images.githubusercontent.com/5593615/82530092-2db35e80-9b45-11ea-9909-30ef29a7fd4a.png)

**Expected behavior**
Font awesome icon should be sized according to the width and height properties specified in the styles config.

**Desktop (please complete the following information):**
 - Browser: Chrome on Linux
 - Version: 77.0

**Additional context**
I thing all needs to be done is setting `height: 100%` somehow of the `iron-icon` element generated by font-awesome integration. Please see screenshot below.

![Selection_097](https://user-images.githubusercontent.com/5593615/82530460-04df9900-9b46-11ea-869f-9a6c387af947.png)

**Comment by RomRider** [comment]
You should be able to fix this with:
```yaml
styles:
  icon:
    - --iron-icon-width: 100%
    - --iron-icon-height: 100%
```
