### ISSUE TITLE
Style: Icon: Animation not working in button_card_templates.

### ISSUE THREAD

**Issue by PierreScerri** [custom-cards/button-card#333]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser

**Describe the bug**
The 'State' configuration in main options stops working when button_card_templates are used.
Button 'Tap' and 'Double-Tap' actions work.

**Version of the card**
Version: 3.3.5

**To Reproduce**
This is the configuration I used:
```yaml
button_card_templates:
  open_cover:
    variables:
      var_shutter: ''
    double_tap_action:
      action: call-service
      service: cover.stop_cover
      service_data:
        entity_id: '[[[return variables.var_shutter]]]'
    entity: '[[[return variables.var_shutter]]]'
    icon: 'mdi:arrow-up'
    show_icon: true
    show_name: false
    state:
      - color: orange
        styles:
          icon:
            - animation: blink 2s ease infinite
        value: opening
    tap_action:
      action: call-service
      service: cover.open_cover
      service_data:
        entity_id: '[[[return variables.var_shutter]]]'
```
and the button-card configuration is

```yaml
type: 'custom:button-card'
template: open_cover
variables:
  var_shutter: cover.master_bedroom_shutter

```

**Screenshots**

**Expected behavior**
The arrow-icon is set to blink when the shutter state is opening.  This is working with this card configuration:

```yaml
        double_tap_action:
          action: call-service
          service: cover.stop_cover
          service_data:
            entity_id: cover.master_bedroom_shutter
        entity: cover.master_bedroom_shutter
        icon: 'mdi:arrow-up'
        show_name: false
        state:
          - color: orange
            styles:
              icon:
                - animation: blink 2s ease infinite
            value: opening
        tap_action:
          action: call-service
          service: cover.open_cover
          service_data:
            entity_id: cover.master_bedroom_shutter
        type: 'custom:button-card'
```
**Desktop (please complete the following information):**
 - Browser N/A
 - Version N/A

**Smartphone (please complete the following information):**
 - Device: N/A

**Additional context**

**Comment by RomRider** [comment]
It doesn't work because `entity` is not configuration entry which supports templates.

**Comment by PierreScerri** [comment]
OK.  Got it.  `entity` has to be defined in the card not the template.  Thanks.  Working now.

```yaml
type: 'custom:button-card'
template: open_cover
variables:
  var_shutter: cover.master_bedroom_shutter
entity: cover.master_bedroom_shutter
```
