### ISSUE TITLE
Label with sensor information

### ISSUE THREAD

**Issue by anglrus** [custom-cards/button-card#338]
Hello, thank you for module. 
I use your example to show value on button.
It is correct part:
          entities:
            - entity: sensor.xiaomi_air_purifier_3_temp
          label: >
            [[[
              var temp = states['fan.xiaomi_air_purifier_3'].attributes.temperature;
              return 'Temp: ' + (temp ? temp : '0');              
            ]]]
          show_label: true

Please, could you help with sensor value:
I tried different variant. One is:
          entities:
            - entity: sensor.temperature_bedroom
          label: >
            [[[
              var temp = value_template: {{ states['sensor.temperature_bathroom'].state }}
              return 'Temp: ' + (temp ? temp : '0');              
            ]]]
          show_label: true

Thank you

**Comment by RomRider** [comment]
Please use the forum for those kind of request:
```yaml
          entities:
            - entity: sensor.temperature_bedroom
          label: >
            [[[
              var temp = states['sensor.temperature_bathroom'].state;
              return 'Temp: ' + (temp ? temp : '0');              
            ]]]
          show_label: true
```
