### ISSUE TITLE
Button Card state option to include entity?

### ISSUE THREAD

**Issue by jarrah31** [custom-cards/button-card#34]
Would it be possible to make the button colour change based on the state of another entity please? For example, can the State option be expanded to include entities?
```
- type: "custom:button-card"
  entity: sensor.windows_open
  name: "Windows"
  show_state: yes
  state:
    - entity_id: input_boolean.window_is_open
      value: 'on'
      color: rgb(5, 147, 255)
    - entity_id: input_boolean.window_is_open
      value: 'off'
      color: rgb(189, 255, 5)
```
The would allow me to show the number of open windows based on the sensor.windows_open state, but have the button colour as green if all are closed, and red if more than one is open. 

This would work when using the following automation:
```
automation:
  - alias: "Windows Open"
    trigger:
      platform: numeric_state
      entity_id: sensor.windows_open
      above: 0
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.window_is_open
```
Thanks in advance!

**Comment by krasatos** [comment]
Came here for exactly the same thing, but for a different application:
I want a switch for my motion detection automations. 
On/Off would indicate if the automations are enabled, 
Different icons would show me if motion is actually detected.
```
      - type: 'custom:button-card'
        entity: script.md_stairs_saloni_8_automation #turns automations on/off
        color: 'rgb(228,94,101)'
        color_off: 'rgb(123,70,77)'
        icon: 'mdi:motion-sensor'
        name:  Automatic Lights
        state:
          - entity_id: binary_sensor.livingroom_pir
            value: 'on'
            icon: 'mdi:motion-sensor'
          - entity_id: binary_sensor.livingroom_pir
            value: 'off'
            icon: 'mdi:walk'
```
Would you consider implementing something like this?
Thanks in advance :)
