### ISSUE TITLE
Templating on entities

### ISSUE THREAD

**Issue by kloggy** [custom-cards/button-card#340]
**Is your feature request related to a problem? Please describe.**
"I'm always frustrated when" I can't template an entity :-)

**Describe the solution you'd like**
I would like the templating feature to be added to the entity

**Describe alternatives you've considered**
Currently I can use `config-template-card` to get around this but firstly, this gives problems with  the entity being watched for updates, and secondly it would be great not to need two cards to do this.

**Additional context**

**Comment by RomRider** [comment]
I don't see the use case for that, could you share what you are trying to achieve?
I don't like the idea of templating something that templates depends on...

**Comment by kloggy** [comment]
Ok, I hope I can explain this clearly...

I have created a system that uses various sensors. I have coded it to allow users to choose what sensor they want to use and to configure this from inside the UI.

So, internally to my package I have an `input_text` into which users can enter the name of their (external) sensor.

My Lovelace can't know what that sensor is except by looking at the state of the `input_text`.

So I would like to be able to do (e.g.)....

```
entity: >
  [[
    var my_entity = state['input_text.sensor_name'].states
    return state[my_entity].states
  ]]]
```

Currently I do something like this this:
```
      - type: custom:config-template-card
        variables:
          - states['input_text.irrigation_external_sensor_controller_wifi'].state
        entities:
          - input_text.irrigation_external_sensor_controller_wifi
        card:
          !include
            - item_settings_controller_wifi_signal.yaml
            - entity: "${vars[0]}"
              name: Irrigation Controller WiFi Signal Strength
```

But this means that the UI doesn't see state changes because `config-template-card` doesn't template entities either (although iantrich did intimate that it was a change he would consider) and it takes an extra card.

I hope that all makes sense. Ask me if you want any more info.
