### ISSUE TITLE
State changes not reflected in frontend until page refresh

### ISSUE THREAD

**Issue by GatoPharaoh** [custom-cards/button-card#344]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
Labels returning the state of e.g. a template sensor won't show the correct label until the page is refreshed.

I for example have a button to switch an input_boolean. If the input_boolean is off, the button shows "Aus". 

When I switch it on, it should show the time of the template sensor. Instead it shows "AUS" (now capitalized) which is the off-value of the same template sensor. The button won't show the real on-value of the template sensor (in this case the time) until the page is refreshed.

Also, whenever an icon, a label or its color or the color of a button is dependent on a state that changes in the background (so NOT switched via a button card button) , those won't change color or show the changed icon until the page is refreshed.
Color change is NOT affected, when I switch the button via a button card button.

**Version of the card**
Version: 3.3.6

**To Reproduce**
This is the configuration I used:
```
time_template:
    show_label: true
    show_icon: false
    color_type: card
    color: rgb(66, 134, 244) 
    state:
      - value: "off"
        label: Aus
      - value: "on"
        color: rgb(50, 205, 50)
        label: > 
          [[[ return states[variables.var_timelove].state; ]]]
    tap_action:
      action: call-service
      service: input_boolean.toggle
      service_data:
        entity_id: '[[[ return variables.inputboolean_timexvx; ]]]'
    hold_action:
      action: more-info
      entity: '[[[return variables.inputdatetime_waterxvx; ]]]'

```
This is the configuration of said template sensor:
```
- platform: template
    sensors:
      time2v1_timelove:
        friendly_name: "Time2v1 Template"
        value_template: >-
          {% if is_state('input_boolean.time2v1', 'off') %}
            AUS
          {% else %}
            {{ states.input_datetime.water2v1.attributes.timestamp | int | timestamp_custom('%H:%M', False) }}
          {% endif %}

```

**Screenshots**
Here you can see that the time in the label is not shown until the page is refreshed
![pATFLTHFJi](https://user-images.githubusercontent.com/12106737/85328153-82dde980-b4d0-11ea-9899-a0e3c6ba6168.gif)

The icon in this second gif is dependent on the state change of the time button. Only when the page is refreshed, the icon changes to the right icon.
![QVgsNvDp5c](https://user-images.githubusercontent.com/12106737/85329420-c9344800-b4d2-11ea-8c69-137b7849cab2.gif)

**Expected behavior**
Values, icon changes, label changes or color changes should be visible without needing to refresh.

**Desktop (please complete the following information):**
 - Browser [Firefox 77.0.1 and Brave 1.10.93]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 6S and Galaxy S10]
 - OS: [e.g. iOS 13 and Android 10]
 - Browser [Both with latest Home Assistant Official Apps]

**Additional context**
Problem seems to have started after updating to Home Assistant Core 0.111.x
Maybe related to #341
