### ISSUE TITLE
Spin and animate

### ISSUE THREAD

**Issue by Mike144007** [custom-cards/button-card#347]
At the suggestion of the awesome DrZZs, I am asking for help here. I'm not sure this is really an issue, so forgive me if I have put this in the wrong place.
I have been trying to set up a custom button to give me the status of my Tesla. The icon changes colour based on the level of charge (which works), but I am also trying to get it to animate if the charge level hits a certain low level, and also spin if the charger is connected and charging. I cannot get either of these two things to function - probably because of my incredibly poor understanding of Home Assistant coding. If anyone can help, please let me know. The code I have so far is as follows (sorry the indentation has not come through correctly):

```
entity: sensor.mike_s_tesla_range_sensor
icon: 'mdi:car-electric'
name: Tesla Range Sensor
show_state: true
styles:
  card:
    - border-radius: 10%
    - '--paper-card-background-color': 'rgba(0, 0, 0, 0.4)'
    - box-shadow: none
  icon:
    - color: |
        [[[
          if (entity.state >= 175) return 'green';
          if (entity.state >= 125 && entity.state < 175) return 'yellow';
          else return 'red';
         ]]]
    - animation:
        - - - if (entity.state <= 100) blink 2s ease infinite
    - spin: |
        [[[ 
          if (states["binary_sensor.mike_s_tesla_charger_sensor"].state =
          "Charging") return true
          else return false
        ]]]
  name:
    - color: white
  state:
    - color: white
type: 'custom:button-card'
```

**Comment by roopesh** [comment]
I haven't tried this, but this looks similar:  https://github.com/custom-cards/button-card#blink.  Please post your config if you figure it out.  I would like to do something similar for taps.

**Comment by Mike144007** [comment]
Hi Roopesh
I am really a beginner at all of this, so need help before I can progress it. Thanks for pointing to the page, but I am just not good enough yet to use this to try to adapt to what I need. If I do get it working (or rather if someone else can help me to get it to work, I will definitely post the results

**Comment by Mariusthvdb** [comment]
I was just about to create a feature request to be able to do what yo want: spin based on a template. Dont think that is possible. We have to do it like this for now:
```
        state:
          - operator: template
            value: >
              [[[ return (states['sensor.count_alerts_notifying'].state > 0) ]]]
            spin: true
#        spin: >
#            [[[ return (states['sensor.count_alerts_notifying'].state > 0)
#                ? true : false; ]]]
```

for animation, set in under styles, like this:
```
  styles:
    icon:
      - color: >
          [[[ if (entity.state == 'on') return 'green'; return 'grey'; ]]]
      - animation: >
          [[[
            if (entity.state == 'on') return 'blink 2s ease infinite';
          ]]]
```
of course, use the template of you liking ;-)

**Comment by Mike144007** [comment]
Hi Marius
Thank you so much for taking the time to look at this. I still have a problem with the state operator template. No errors showing, but nothing is spinning if the charger is disconnected. Would you mind having one more look and see if you can spot 
my error.

```
entity: sensor.mike_s_tesla_range_sensor
icon: 'mdi:car-electric'
name: Tesla Range Sensor
show_state: true
state:
  - operator: template
    value: >
      [[[ return (states['binary_sensor.mike_s_tesla_charger_sensor'].state =
      'off') ]]]
    spin: true
styles:
  card:
    - border-radius: 10%
    - '--paper-card-background-color': 'rgba(0, 0, 0, 0.4)'
    - box-shadow: none
  icon:
    - color: |
        [[[
          if (entity.state >= 175) return 'green';
          if (entity.state >= 125 && entity.state < 175) return 'yellow';
          else return 'red';
        ]]]
    - animation: |
        [[[
          if (entity.state <= 100) return 'blink 2s ease infinite';
        ]]]
  name:
    - color: white
  state:
    - color: white
type: 'custom:button-card'

```

**Comment by Mariusthvdb** [comment]
- operator: template
    value: >
      [[[ return (states['binary_sensor.mike_s_tesla_charger_sensor'].state ==
      'off') ]]]

**Comment by Mike144007** [comment]
Still no spin if charger disconnected

**Comment by RomRider** [comment]
If you want to have spin and blink at the same time, you'll need to make 2 animations directly and not use the `spin` attribute since one erases the other.
```yaml
entity: sensor.mike_s_tesla_range_sensor
icon: 'mdi:car-electric'
name: Tesla Range Sensor
show_state: true
styles:
  card:
    - border-radius: 10%
    - '--paper-card-background-color': 'rgba(0, 0, 0, 0.4)'
    - box-shadow: none
  icon:
    - color: |
        [[[
          if (entity.state >= 175) return 'green';
          if (entity.state >= 125 && entity.state < 175) return 'yellow';
          else return 'red';
        ]]]
    - animation: |
        [[[
          if (entity.state <= 100) {
            if (states['binary_sensor.mike_s_tesla_charger_sensor'].state == 'off')
              return 'blink 2s ease infinite, rotating 2s ease infinite';
            return 'blink 2s ease infinite';
          }
          return null;
        ]]]
  name:
    - color: white
  state:
    - color: white
type: 'custom:button-card'
```
