### ISSUE TITLE
more-info does not work in firefox on android

### ISSUE THREAD

**Issue by xMariusz** [custom-cards/button-card#348]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
Holding the bottom card should display the menu of that card. This option works in a browser on a PC, does not work on an android device in a firefox browser. The problem occurred after updating Home Assistant from version 0.109 to version 0.111.4.

**Version of the card**
Version: Last one

**To Reproduce**
This is the configuration I used:

```yaml
cards:
  - cards:
      - aspect_ratio: 1/1.1
        color: 'rgb(66, 134, 244)'
        color_type: card
        custom_fields:
          cpu: |
            [[[
              return `<ha-icon
                icon="mdi:thermometer"
                style="width: 16px; height: 16px; color: #000044;">
                </ha-icon><span>Temp: <span style="color: var(--text-color-sensor);">${states['sensor.sonoff_switch_02_temperature'].state} °C</span></span>`
            ]]]
          ram: |
            [[[
              return `<ha-icon
                icon="mdi:water-percent"
                style="width: 16px; height: 16px; color: #000044;">
                </ha-icon><span>Wilgo: <span style="color: var(--text-color-sensor);">${states['sensor.sonoff_switch_02_humidity'].state} %</span></span>`
            ]]]
          test: |
            [[[
              return `<ha-icon
                icon="mdi:water-percent"
                style="width: 16px; height: 16px; color: #000044;">
                </ha-icon><span>Ciśn: <span style="color: var(--text-color-sensor);"> - </span></span>`
            ]]]
        entity: switch.sonoff_switch_02
        hold_action:
          action: more-info
        icon: 'mdi:fan'
        name: Kuchnia
        styles:
          card:
            - padding: 5%
            - color: ivory
            - font-size: 12px
            - text-shadow: 0px 0px 0px black
            - text-transform: capitalize
          custom_fields:
            cpu:
              - padding-bottom: 2px
              - align-self: middle
              - justify-self: start
              - '--text-color-sensor': >-
                  [[[ if (states["sensor.sonoff_switch_02_temperature"].state >
                  80) return "white"; ]]]
            ram:
              - padding-bottom: 2px
              - align-self: middle
              - justify-self: start
              - '--text-color-sensor': >-
                  [[[ if (states["sensor.sonoff_switch_02_humidity"].state > 80)
                  return "white"; ]]]
            test:
              - padding-bottom: 2px
              - align-self: middle
              - justify-self: start
              - '--text-color-sensor': >-
                  [[[ if (states["sensor.sonoff_switch_02_humidity"].state > 80)
                  return "white"; ]]]
          grid:
            - grid-template-areas: '"i temp" "n n" "cpu cpu" "ram ram" "sd sd" "test test"'
            - grid-template-columns: 1fr 1fr
            - grid-template-rows: 1fr min-content min-content min-content min-content
          icon:
            - color: |
                [[[
                  if (states['switch.sonoff_switch_02'].state == 'on') return 'white';
                  else return 'grey';
                ]]]
            - width: 100%
          img_cell:
            - justify-content: start
            - align-items: start
          name:
            - font-weight: bold
            - font-size: 20px
            - align-self: middle
            - justify-self: start
            - color: white
            - padding-bottom: 4px
        type: 'custom:button-card'
      - aspect_ratio: 1/1.1
        color: 'rgb(66, 134, 244)'
        color_type: card
        custom_fields:
          cpu: |
            [[[
              return `<ha-icon
                icon="mdi:thermometer"
                style="width: 16px; height: 16px; color: #000044;">
                </ha-icon><span>Temp: <span style="color: var(--text-color-sensor);">${states['sensor.sonoff_switch_01_temperature'].state} °C</span></span>`
            ]]]
          ram: |
            [[[
              return `<ha-icon
                icon="mdi:water-percent"
                style="width: 16px; height: 16px; color: #000044;">
                </ha-icon><span>Wilgo: <span style="color: var(--text-color-sensor);">${states['sensor.sonoff_switch_01_humidity'].state} %</span></span>`
            ]]]
          test: |
            [[[
              return `<ha-icon
                icon="mdi:water-percent"
                style="width: 16px; height: 16px; color: #000044;">
                </ha-icon><span>Ciśn: <span style="color: var(--text-color-sensor);"> - </span></span>`
            ]]]
        entity: switch.sonoff_switch_01
        hold_action:
          action: more-info
        icon: 'mdi:fan'
        name: Łazienka
        styles:
          card:
            - padding: 5%
            - color: ivory
            - font-size: 12px
            - text-shadow: 0px 0px 0px black
            - text-transform: capitalize
          custom_fields:
            cpu:
              - padding-bottom: 2px
              - align-self: middle
              - justify-self: start
              - '--text-color-sensor': >-
                  [[[ if (states["sensor.sonoff_switch_01_temperature"].state >
                  80) return "white"; ]]]
            ram:
              - padding-bottom: 2px
              - align-self: middle
              - justify-self: start
              - '--text-color-sensor': >-
                  [[[ if (states["sensor.sonoff_switch_01_humidity"].state > 80)
                  return "white"; ]]]
            test:
              - padding-bottom: 2px
              - align-self: middle
              - justify-self: start
              - '--text-color-sensor': >-
                  [[[ if (states["sensor.sonoff_switch_01_humidity"].state > 80)
                  return "white"; ]]]
          grid:
            - grid-template-areas: '"i temp" "n n" "cpu cpu" "ram ram" "sd sd" "test test"'
            - grid-template-columns: 1fr 1fr
            - grid-template-rows: 1fr min-content min-content min-content min-content
          icon:
            - color: |
                [[[
                  if (states['switch.sonoff_switch_01'].state == 'on') return 'white';
                  else return 'grey';
                ]]]
            - width: 100%
          img_cell:
            - justify-content: start
            - align-items: start
          name:
            - font-weight: bold
            - font-size: 20px
            - color: white
            - align-self: middle
            - justify-self: start
            - padding-bottom: 4px
        type: 'custom:button-card'
      - aspect_ratio: 1/1.1
        color: grey
        color_type: card
        custom_fields:
          cpu: |
            [[[
              return `<ha-icon
                icon="mdi:thermometer"
                style="width: 16px; height: 16px; color: #000044;">
                </ha-icon><span>Temp: <span style="color: var(--text-color-sensor);">${states['sensor.0x00158d0002387ae7_temperature'].state} °C</span></span>`
            ]]]
          ram: |
            [[[
              return `<ha-icon
                icon="mdi:water-percent"
                style="width: 16px; height: 16px; color: #000044;">
                </ha-icon><span>Wilgo: <span style="color: var(--text-color-sensor);">${states['sensor.0x00158d0002387ae7_humidity'].state} %</span></span>`
            ]]]
          test: |
            [[[
              return `<ha-icon
                icon="mdi:water-percent"
                style="width: 16px; height: 16px; color: #000044;">
                </ha-icon><span>Ciśn: <span style="color: var(--text-color-sensor);">${states['sensor.0x00158d0002387ae7_pressure'].state} hPa</span></span>`
            ]]]
        entity: fan.xiaomi_smart_fan
        hold_action:
          action: more-info
        icon: 'mdi:fan'
        name: Sypialnia
        state:
          - color: grey
            icon: 'mdi:alert-circle-outline'
            id: fan.xiaomi_smart_fan
            value: unavailable
        styles:
          card:
            - padding: 5%
            - color: ivory
            - font-size: 12px
            - text-shadow: 0px 0px 0px black
            - text-transform: capitalize
          custom_fields:
            cpu:
              - padding-bottom: 2px
              - align-self: middle
              - justify-self: start
              - '--text-color-sensor': >-
                  [[[ if (states["sensor.sonoff_switch_02_temperature"].state >
                  80) return "white"; ]]]
            ram:
              - padding-bottom: 2px
              - align-self: middle
              - justify-self: start
              - '--text-color-sensor': >-
                  [[[ if (states["sensor.sonoff_switch_02_humidity"].state > 80)
                  return "white"; ]]]
            test:
              - padding-bottom: 2px
              - align-self: middle
              - justify-self: start
              - '--text-color-sensor': >-
                  [[[ if (states["sensor.sonoff_switch_02_humidity"].state > 80)
                  return "white"; ]]]
          grid:
            - grid-template-areas: '"i temp" "n n" "cpu cpu" "ram ram" "sd sd" "test test"'
            - grid-template-columns: 1fr 1fr
            - grid-template-rows: 1fr min-content min-content min-content min-content
          icon:
            - color: white
            - width: 100%
          img_cell:
            - justify-content: start
            - align-items: start
          name:
            - font-weight: bold
            - font-size: 20px
            - align-self: middle
            - justify-self: start
            - color: white
            - padding-bottom: 4px
        title: Światło
        type: 'custom:button-card'
    type: horizontal-stack
  - cards:
      - color: 'rgb(66, 134, 244)'
        color_type: card
        entity: light.sypialnia
        hold_action:
          action: more-info
        icon: 'mdi:ceiling-light'
        name: Sypialnia
        styles:
          icon:
            - color: |
                [[[
                  if (states['light.sypialnia'].state == 'on' ) return 'orange';
                  else return 'white';
                ]]]
        type: 'custom:button-card'
      - color: 'rgb(66, 134, 244)'
        color_type: card
        entity: light.sypialnia_nightlight
        hold_action:
          action: more-info
        icon: 'mdi:weather-night'
        off_icon_color: '#000'
        state:
          - color: grey
            icon: 'mdi:alert-circle-outline'
            id: light.sypialnia_nightlight
            value: unavailable
        styles:
          icon:
            - color: |
                [[[
                  if (states['light.sypialnia_nightlight'].state == 'on' ) return 'orange';
                  else return 'white';
                ]]]
        type: 'custom:button-card'
      - color: 'rgb(66, 134, 244)'
        color_type: card
        entity: group.biurko_led
        hold_action:
          action: more-info
        icon: 'mdi:led-strip'
        name: Biurko LED
        styles:
          icon:
            - color: |
                [[[
                  if (states['group.biurko_led'].state == 'on' ) return 'orange';
                  else return 'white';
                ]]]
        type: 'custom:button-card'
    type: horizontal-stack
  - cards:
      - color: 'rgb(66, 134, 244)'
        color_type: card
        entity: light.kuchnia
        hold_action:
          action: more-info
        icon: 'mdi:ceiling-light'
        state:
          - color: grey
            icon: 'mdi:alert-circle-outline'
            id: light.kuchnia
            value: unavailable
        styles:
          icon:
            - color: |
                [[[
                  if (states['light.kuchnia'].state == 'on' ) return 'orange';
                  else return 'white';
                ]]]
        type: 'custom:button-card'
      - color: 'rgb(66, 134, 244)'
        color_type: card
        entity: light.kuchnia_nightlight
        hold_action:
          action: more-info
        icon: 'mdi:weather-night'
        off_icon_color: '#000'
        state:
          - color: grey
            icon: 'mdi:alert-circle-outline'
            id: light.kuchnia_nightlight
            value: unavailable
        styles:
          icon:
            - color: |
                [[[
                  if (states['light.kuchnia_nightlight'].state == 'on' ) return 'orange';
                  else return 'white';
                ]]]
        type: 'custom:button-card'
      - color: 'rgb(66, 134, 244)'
        color_type: card
        entity: light.led_kuchnia
        hold_action:
          action: more-info
        icon: 'mdi:led-strip'
        name: Kuchnia LED
        state:
          - color: grey
            icon: 'mdi:alert-circle-outline'
            id: light.led_kuchnia
            value: unavailable
        styles:
          icon:
            - color: |
                [[[
                  if (states['light.led_kuchnia'].state == 'on' ) return 'orange';
                  else return 'white';
                ]]]
        type: 'custom:button-card'
    type: horizontal-stack
type: vertical-stack

```
**Expected behavior**
Holding the bottom card should display the menu of this card

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Mi9t
 - OS: Android 10
 - Browser Firefox 68.10.0
