### ISSUE TITLE
Variables not working in browser_mod popups

### ISSUE THREAD

**Issue by roflcoopter** [custom-cards/button-card#353]
**Checklist**
- [X ] I updated the card to the latest version available
- [ X] I cleared the cache of my browser

**Describe the bug**
I have one button-card whos tap_action is to display another card with stacks of button-cards.
This stack of button-card is using variables to control some things in the templates.
However, when i go to tap the main button-card, the cards in the popup error out saying that variables is undefined.
It appears to me that the nested card gets the variables that the parent card has defined.
I will try to explain in a serie of configs below.

**Version of the card**
Version: 3.3.6

**To Reproduce**
This configuration errors out when clicked:
```yaml
    - type: custom:button-card
      name: Parent Name
      entity: fan.living_room
      tap_action:
        haptic: heavy
        action: call-service
        service: browser_mod.popup
        service_data:
          title: ' '
          card:
            type: custom:button-card
            variables:
              name: Popup Name
            entity: fan.living_room
            name: >
              [[[ return variables.name; ]]]
          deviceID:
            - this
```

This configuration doesnt throw an error, but as you can see the popup has gotten the parents name
```yaml
    - type: custom:button-card
      variables:
        name: Parent Name
      name: >
        [[[ return variables.name; ]]]
      entity: fan.living_room
      tap_action:
        haptic: heavy
        action: call-service
        service: browser_mod.popup
        service_data:
          title: ' '
          card:
            type: custom:button-card
            variables:
              name: Popup Name
            entity: fan.living_room
            name: >
              [[[ return variables.name; ]]]
          deviceID:
            - this
```
**Screenshots**

**Expected behavior**
I expect button-cards that are shown by a browser-mod popup gets the correct varaibles assigned to them.

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version 83.0.4103.116

**Additional context**
