### ISSUE TITLE
make spin templatable

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/button-card#355]
**Is your feature request related to a problem? Please describe.**

I have to use the state: operator: template, if a quicker way if spin: would have been available.

**Describe the solution you'd like**

```
        spin: >
          [[[ return (states['sensor.count_alerts_notifying'].state > 0) ? true : false; ]]]
```
instead of what we need to do now:
```
        state:
          - operator: template
            value: >
              [[[ return (states['sensor.count_alerts_notifying'].state > 0) ]]]
            spin: true
```

**Describe alternatives you've considered**

**Additional context**
