### ISSUE TITLE
Override css injection

### ISSUE THREAD

**Issue by UmbeMont** [custom-cards/button-card#357]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
Unfortunaterly i miseed the part to not place css in the main yaml  , all my yaml i create now react to have lamp rgb folowing the color of the lamp.
I would understand how to roll back , clean or cancel this config or just set all the elements in yellow

**Version of the card**
Version: 

**To Reproduce**
This is the configuration I used:
```yaml
resources:
  - type: js
    url: /hacsfiles/bar-card/bar-card.js

  - type: module
    url: /hacsfiles/button-card/button-card.js

  - url: /hacsfiles/slider-entity-row/slider-entity-row.js
    type: module

  - type: module
    url: /hacsfiles/custom-header/custom-header.js

  - url: /hacsfiles/decluttering-card/decluttering-card.js
    type: module

  - type: module
    url: /hacsfiles/flex-table-card/flex-table-card.js

  - url: /hacsfiles/light-entity-card/light-entity-card.js
    type: module

  - url: /hacsfiles/light-popup-card/light-popup-card.js
    type: module

  - type: module
    url: /hacsfiles/lovelace-auto-entities/auto-entities.js

  - type: module
    url: /hacsfiles/lovelace-battery-entity/battery-entity.js

  - type: module
    url: /hacsfiles/lovelace-card-mod/card-mod.js

  - type: module
    url: /hacsfiles/lovelace-layout-card/layout-card.js

  - type: module
    url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js

  - type: module
    url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js

  - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
    type: module

  - type: module
    url: /hacsfiles/rgb-light-card/card.js

  - type: module
    url: /hacsfiles/simple-weather-card/simple-weather-card-bundle.js

  - url: /hacsfiles/swipe-card/swipe-card.js
    Type: module

  - url: /hacsfiles/switch-popup-card/switch-popup-card.js
    type: module

  - type: module
    url: /hacsfiles/upcoming-media-card/upcoming-media-card.js

  - type: module
    url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js

  - type: module
    url: /hacsfiles/weather-card/weather-card-bundle.js

background: linear-gradient(32deg, rgba(131,58,180,1) 0%, rgba(55,127,226,1) 35%, rgba(255,137,137,1) 64%, rgba(252,176,69,1) 100%)

custom_header:
  background: 'rgba(0, 0, 0, 0.3);'
  compact_mode: true
  elements_color: rgba(10, 10, 10, 0.8)
  button_text:
    options: '{{ hours24 }}:{{ minutesLZ }}'

title: Home
views:
  # Here I'm defining the my View (my tab)
  - badges:
    icon: mdi:home
    cards:

########################################################################
#                                                                      #
#                   Lights Living room                                 #
#                                                                      #
########################################################################


      - type: vertical-stack
        # column_num: 3
        cards:
          - type: custom:decluttering-card
            template: header
            variables:
              - content: Living Room

          - type: vertical-stack
            cards:

            - type: custom:button-card
              template: light_slim_tile
              entity: light.living_room
              icon: mdi:sofa

            - type: horizontal-stack
              cards:
              - entity: light.light2
                template: light_button_style
                type: 'custom:button-card'
                icon: mdi:sofa

              - entity: light.light1
                template: light_button_style
                type: 'custom:button-card'
                icon: mdi:ceiling-light
                name: Table
```

**Screenshots**
<img width="471" alt="image" src="https://user-images.githubusercontent.com/60969724/87227834-4b5ab280-c395-11ea-919e-f08748eda3cf.png">

<img width="470" alt="image" src="https://user-images.githubusercontent.com/60969724/87227850-60cfdc80-c395-11ea-9cfc-014fd32e03f8.png">

**Expected behavior**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
