### ISSUE TITLE
State based CSS issues: either bug or missing documentation

### ISSUE THREAD

**Issue by smugleafdev** [custom-cards/button-card#358]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
I am having _state based_ styling issues. I switched from a picture-entity to this button card, and failed to migrate this code:

```yaml
state_filter:
  Away: grayscale(75%) brightness(25%)
  Home: brightness(100%)
  Just Arrived: blur(4px)
  Just Left: brightness(50%)
```

**Version of the card**
Version: 3.3.6

**To Reproduce**
This is the configuration I used:

```yaml
state:
  - value: Home
    styles:
      card:
        - filter: opacity(50%)
      entity-picture:
        - padding-left: 100px
        - filter: grayscale(100%)
```

I do have this working, but it's not STATE related so it's not relevant other than to show I have some inkling of how proper styling syntax should work:

```yaml
styles:
  card:
    - padding: 0px
```

**Comment by RomRider** [comment]
It's neither a bug, nor a documentation issue.
`entity-picture` doesn't exist as an entry in `styles`. It's either `icon` (if you have an icon) or `entity_picture` (if you have a picture). Note the `_`.

**Comment by smugleafdev** [comment]
> `entity-picture` doesn't exist as an entry in `styles`. It's either `icon` (if you have an icon) or `entity_picture` (if you have a picture). Note the `_`.

```yaml
state:
  - value: Home
    styles:
      entity_picture:
        - padding-left: 100px
        - filter: grayscale(100%)
        - filter: opacity(50%)
```

I see no effect with this either, though nice catch. I might have not noticed the - vs _ in another hour of staring at it.

I am also sure the current state of this entity is "Home" because I have my picture-entity card next it.
