### ISSUE TITLE
Home Assistant 0.113.0b3 white cards on mobile

### ISSUE THREAD

**Issue by Piston-Broke** [custom-cards/button-card#362]
**Checklist**
- [y ] I updated the card to the latest version available
- [ y] I cleared the cache of my browser

**Describe the bug**
cards work fine on PC with transparent backgrounds using ios dark theme on ios in both safari and mobile app the background turns white and obscures the text using Home Assistant 0.113.0b3

**Version of the card**
Version: 3.3.6

**To Reproduce**
This is the configuration I used:
```yaml
cards:
  - cards:
      - color-type: label-card
        name: Switches
        type: 'custom:button-card'
    type: horizontal-stack
  - cards:
      - color: 'rgb(28, 128, 199)'
        entity: switch.stairs
        icon: 'mdi:stairs'
        state:
          - color: 'rgb(200,200,208)'
            value: 'off'
          - color: 'rgb(255,255,0)'
            value: 'on'
        type: 'custom:button-card'
      - color: 'rgb(28, 128, 199)'
        entity: switch.ziva_light
        icon: 'mdi:hotel'
        name: Ziva Bedroom
        state:
          - color: 'rgb(200, 200, 208)'
            value: 'off'
          - color: 'rgb(255,255,0)'
            value: 'on'
        type: 'custom:button-card'
    type: horizontal-stack
  - cards:
      - color: 'rgb(28, 128, 199)'
        entity: switch.computer_lights
        icon: 'mdi:desktop-classic'
        name: Computer Illumination
        state:
          - color: 'rgb(200,200,208)'
            value: 'off'
          - color: 'rgb(255,255,0)'
            value: 'on'
        type: 'custom:button-card'
      - color: 'rgb(28, 128, 199)'
        entity: group.main_light
        hold_action:
          action: more-info
        icon: 'mdi:lightbulb'
        state:
          - color: 'rgb(200,200,208)'
            value: 'off'
          - color: 'rgb(255,255,0)'
            value: 'on'
        type: 'custom:button-card'
    type: horizontal-stack
  - cards:
      - color: 'rgb(28, 128, 199)'
        entity: switch.effect_switch
        hold_action:
          action: more-info
        icon: 'mdi:desktop-classic'
        name: Computer Effect
        state:
          - color: 'rgb(200, 200, 208)'
            value: 'off'
          - color: 'rgb(255,255,0)'
            value: 'on'
        type: 'custom:button-card'
      - color: 'rgb(28, 128, 199)'
        entity: light.wled_window
        hold_action:
          action: more-info
        icon: 'mdi:window-open-variant'
        name: Window Lights
        state:
          - color: 'rgb(200, 200, 208)'
            value: 'off'
          - color: 'rgb(255,255,0)'
            value: 'on'
        type: 'custom:button-card'
    type: horizontal-stack
  - cards:
      - color: 'rgb(28, 128, 199)'
        entity: light.colour_light
        hold_action:
          action: more-info
        icon: 'mdi:desktop-classic'
        name: Computer Colour
        state:
          - color: 'rgb(200,200,208)'
            value: 'off'
          - color: 'rgb(255,255,0)'
            value: 'on'
        type: 'custom:button-card'
      - color: 'rgb(28, 128, 199)'
        entity: light.wled_pc
        hold_action:
          action: more-info
        icon: 'mdi:desktop-classic'
        name: PC Light
        state:
          - color: 'rgb(200, 200, 208)'
            value: 'off'
          - color: 'rgb(255,255,0)'
            value: 'on'
        type: 'custom:button-card'
    type: horizontal-stack
  - cards:
      - color: 'rgb(28, 128, 199)'
        entity: light.bottle
        hold_action:
          action: more-info
        icon: 'mdi:bottle-wine'
        name: Bottle Light
        state:
          - color: 'rgb(200, 200, 208)'
            value: 'off'
          - color: 'rgb(255,255,0)'
            value: 'on'
        type: 'custom:button-card'
      - color: 'rgb(28, 128, 199)'
        entity: light.wled_miner_r
        hold_action:
          action: more-info
        icon: 'mdi:coach-lamp'
        name: Miner Light
        state:
          - color: 'rgb(200, 200, 208)'
            value: 'off'
          - color: 'rgb(255,255,0)'
            value: 'on'
        type: 'custom:button-card'
    type: horizontal-stack
  - color: 'rgb(28, 128, 199)'
    entity: switch.switch_3
    hold_action:
      action: more-info
    icon: 'mdi:fan'
    name: Fan
    state:
      - color: 'rgb(200, 200, 208)'
        value: 'off'
      - color: 'rgb(255,255,0)'
        spin: true
        value: 'on'
    type: 'custom:button-card'
  - entity: media_player.living_room_speaker
    type: media-control
  - entity: media_player.zivas_bedroom_speaker
    type: media-control
  - entity: media_player.bedroom_echo_dot
    type: media-control
type: vertical-stack


```

**Screenshots**
![Screenshot 2020-07-20 at 16 07 06](https://user-images.githubusercontent.com/45214457/87953787-68813680-caa3-11ea-9ba7-5ace85cae5c9.png)

**Expected behavior**
the styling to be the same on desktop and mobile

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Vivaldi
 - Version [e.g. 22]   3.1.1929.45

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Iphone 11
 - OS: [e.g. iOS8.1] ios14
 - Browser [e.g. stock browser, safari] safari

**Additional context**
