### ISSUE TITLE
--button-card-light-color does not update light groups in HA 0.113

### ISSUE THREAD

**Issue by h-parks** [custom-cards/button-card#364]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
Light groups' color no longer changes in lovelace cards.

My single-bulb entities update properly but light groups do not display any color at all. Toggling the button on and adjusting RGBW still displays the same color as when it is off.

**Version of the card**
Version: 

**To Reproduce**
This is the configuration I used:
```yaml
type: 'custom:button-card'
aspect_ratio: 1/1
entity: light.office_lights
icon: 'mdi:briefcase'
name: OFFICE
styles:
  card:
    - '-webkit-box-shadow': 0px 0px 9px 3px var(--button-card-light-color)
    - box-shadow: 0px 0px 9px 3px var(--button-card-light-color)
  icon:
    - color: var(--button-card-light-color)
  name:
    - color: var(--button-card-light-color)
tap_action:
  action: call-service
  service: light.toggle
  service_data:
    entity_id: light.office_lights
    transition: 0
```

**Screenshots**

**Expected behavior**
--button-card-light-color updates in light groups

**Desktop (please complete the following information):**
Tested on Firefox 79.0 (64-bit) and Chrome 84.0.4147.105 (Official Build) (64-bit)
