### ISSUE TITLE
Action call service not working

### ISSUE THREAD

**Issue by PoVPoV29** [custom-cards/button-card#369]
Action call service not working
It's working with a simple button

Version: 3.3.6

Code : 

type: vertical-stack
cards:
  - type: 'custom:button-card'
    color_type: label-card
    color: auto
    name: Commandes TV
  - type: horizontal-stack
    cards:
      - type: 'custom:button-card'
        name: Volume +
        action: call-service
        service: remote.send_command
        service_data:
          command: VolumeUp
          delay_secs: 0.25
          device: 48031714
          entity_id: remote.harmony_hub
          num_repeats: 1
        icon: 'mdi:volume-plus'
      - type: 'custom:button-card'
        name: Volume -
        action: call-service
        service: remote.send_command
        service_data:
          command: VolumeDown
          delay_secs: 0.25
          device: 48031714
          entity_id: remote.harmony_hub
          num_repeats: 1
        icon: 'mdi:volume-minus'
      - type: 'custom:button-card'
        name: Chaine +
        action: call-service
        service: remote.send_command
        service_data:
          command: ChannelUp
          delay_secs: 0.25
          device: 47469767
          entity_id: remote.harmony_hub
          num_repeats: 1
        icon: 'mdi:plus'
      - type: 'custom:button-card'
        name: Chaine -
        action: call-service
        service: remote.send_command
        service_data:
          command: ChannelDown
          delay_secs: 0.25
          device: 47469767
          entity_id: remote.harmony_hub
          num_repeats: 1
        icon: 'mdi:minus'
      - type: 'custom:button-card'
        action: call-service
        service: remote.send_command
        service_data:
          command: PowerToggle
          delay_secs: 0.25
          device: 48031714
        entity_id: remote.harmony_hub
        icon: 'mdi:power-standby'
        name: Power Sony

**Comment by RomRider** [comment]
Your code is missing quite some stuff (for eg: `tap_action`) and is not formatted so it's quite hard to read. 
Please read the documentation of this card on github you'll find plenty of examples.

**Comment by PoVPoV29** [comment]
I try with this but no succcess too: 
`
type: vertical-stack
  cards:
    - color: auto
      color_type: label-card
      name: Commandes TV
      type: 'custom:button-card'
    - type: horizontal-stack
      cards:
      - tap_action: 
            action: call-service
            icon: 'mdi:volume-plus'
            name: Volume +
            service: remote.send_command
            service_data:
              command: VolumeUp
              delay_secs: 0.25
              device: 48031714
              entity_id: remote.harmony_hub
              num_repeats: 1
            type: 'custom:button-card'
      - tap_action:
          action: call-service
          icon: 'mdi:volume-minus'
          name: Volume -
          service: remote.send_command
          service_data:
            command: VolumeDown
            delay_secs: 0.25
            device: 48031714
            entity_id: remote.harmony_hub
            num_repeats: 1
          type: 'custom:button-card'
      - tap_action:  
          icon: 'mdi:plus'
          name: Chaine +
          action: call-service
          service: remote.send_command
          service_data:
            command: ChannelUp
            delay_secs: 0.25
            device: 47469767
            entity_id: remote.harmony_hub
            num_repeats: 1
          type: 'custom:button-card'
      - tap_action:
          action: call-service
          icon: 'mdi:minus'
          name: Chaine -
          service: remote.send_command
          service_data:
            command: ChannelDown
            delay_secs: 0.25
            device: 47469767
            entity_id: remote.harmony_hub
            num_repeats: 1
          type: 'custom:button-card'
      - tap_action:
          action: call-service
          entity_id: remote.harmony_hub
          icon: 'mdi:power-standby'
          name: Power Sony
          service: remote.send_command
          service_data:
            command: PowerToggle
            delay_secs: 0.25
            device: 48031714
          type: 'custom:button-card`
`

**Comment by RomRider** [comment]
I'm sorry but I can't read this code.
Enclose it in triple backquotes, like that:
````
```
code
```
````

**Comment by PoVPoV29** [comment]
```
type: vertical-stack
  cards:
    - color: auto
      color_type: label-card
      name: Commandes TV
      type: 'custom:button-card'
    - type: horizontal-stack
      cards:
      - tap_action: 
            action: call-service
            icon: 'mdi:volume-plus'
            name: Volume +
            service: remote.send_command
            service_data:
              command: VolumeUp
              delay_secs: 0.25
              device: 48031714
              entity_id: remote.harmony_hub
              num_repeats: 1
            type: 'custom:button-card'
      - tap_action:
          action: call-service
          icon: 'mdi:volume-minus'
          name: Volume -
          service: remote.send_command
          service_data:
            command: VolumeDown
            delay_secs: 0.25
            device: 48031714
            entity_id: remote.harmony_hub
            num_repeats: 1
          type: 'custom:button-card'
      - tap_action:  
          icon: 'mdi:plus'
          name: Chaine +
          action: call-service
          service: remote.send_command
          service_data:
            command: ChannelUp
            delay_secs: 0.25
            device: 47469767
            entity_id: remote.harmony_hub
            num_repeats: 1
          type: 'custom:button-card'
      - tap_action:
          action: call-service
          icon: 'mdi:minus'
          name: Chaine -
          service: remote.send_command
          service_data:
            command: ChannelDown
            delay_secs: 0.25
            device: 47469767
            entity_id: remote.harmony_hub
            num_repeats: 1
          type: 'custom:button-card'
      - tap_action:
          action: call-service
          entity_id: remote.harmony_hub
          icon: 'mdi:power-standby'
          name: Power Sony
          service: remote.send_command
          service_data:
            command: PowerToggle
            delay_secs: 0.25
            device: 48031714
          type: 'custom:button-card'

```

**Comment by RomRider** [comment]
Your indentation is all wrong that's why it doesn't work:
```
- tap_action: 
    action: call-service
    service: remote.send_command
    service_data:
      command: VolumeUp
      delay_secs: 0.25
      device: 48031714
      entity_id: remote.harmony_hub
      num_repeats: 1
  icon: 'mdi:volume-plus'
  name: Volume +
  type: 'custom:button-card'
```
