### ISSUE TITLE
Style, width for Lock changes overlay width

### ISSUE THREAD

**Issue by akarpenkoua** [custom-cards/button-card#373]
**Checklist**
- [ ] I updated the card to the latest version available
- [ ] I cleared the cache of my browser

**Describe the bug**
I'm using this template for the card with lock function
After adding style for lock - width it changes a width of the lock overlay, so the lock does not act as it expected. 

**Version of the card**
Version: 
3.3.6

**To Reproduce**
This is the configuration I used:
```
btc_gates:
    aspect_ratio: 3.5/1
    show_icon: true
    show_name: false
    lock:
      enabled: true
      duration: 10 # duration in seconds
      unlock: tap
    styles:
      card:
        - align-self: center
        - padding: 2%
        - border-top-right-radius: 0
        - border-top-left-radius: 0
        - border-top: var(--paper-item-icon-color)
        - border-top-style: solid
        - border-top-width: 0.5px
# this is the problem
      lock:
        - width: 16px
```
**Screenshots**
![image](https://user-images.githubusercontent.com/31918294/93913619-02689800-fd0e-11ea-9829-21b3a5789ef7.png)

**Expected behavior**
After adding at Styles - Lock - Width only icon width is affected

**Desktop (please complete the following information):**
Chrome Version 85.0.4183.102 (Official Build) (64-bit)
