### ISSUE TITLE
Smallest Heigh

### ISSUE THREAD

**Issue by thib5** [custom-cards/button-card#374]
Hi, I'm trying to create horizontal separator so I removed, name, icon, etc of the button card and put it between two horizontal stack

But I stil found it to big... is there a limitation in home assistant ? what is the smallest heigh I can put on a button ? 

Thanks

**Comment by RomRider** [comment]
There's a default padding which add height, so if you want to modify that you have to remove it and just use height:
```
styles:
  card:
    - padding: 0px
    - height: 5px
```
