### ISSUE TITLE
Ignore brightness for turned off light

### ISSUE THREAD

**Issue by andreypolyak** [custom-cards/button-card#378]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
I have a horizontal stack with two buttons to control lights (please see below YAML configuration and screenshot). The first light doesn't have a brightness attribute when it is turned off:
![image](https://user-images.githubusercontent.com/7446762/95212541-7b7beb00-07f6-11eb-97b1-5c864db82695.png)
The second one has it:
![image](https://user-images.githubusercontent.com/7446762/95212625-8f275180-07f6-11eb-9c79-965b8d833eca.png)

Because of that, the button for the second light is filled in black color when in fact they don't have any difference in their real state -- they are both turned off:
![image](https://user-images.githubusercontent.com/7446762/95212275-3061d800-07f6-11eb-98e7-9d540df60f1b.png)

The style for the first button:
```style="--button-card-light-color:var(--paper-card-background-color); --button-card-light-color-no-temperature:var(--paper-card-background-color);"```

The style for the second button:
```style="--button-card-light-color:rgb(16, 16, 18); --button-card-light-color-no-temperature:rgb(16, 16, 18);"```

If I manually update the state for the second light and delete the brightness attribute:
![image](https://user-images.githubusercontent.com/7446762/95213587-a581dd00-07f7-11eb-81e4-d8ce365acac1.png)

Both buttons start to have the same color:
![image](https://user-images.githubusercontent.com/7446762/95213537-97cc5780-07f7-11eb-95ad-a21857fd540b.png)

And the same style:
```style="--button-card-light-color:var(--paper-card-background-color); --button-card-light-color-no-temperature:var(--paper-card-background-color);"```

**Version of the card**
Version: 3.3.6

**To Reproduce**
This is the configuration I used:
```yaml
    - type: custom:button-card
      name: Theo
      entity: light.group_bedroom_top_theo
      color: auto
      color_type: card
      icon: mdi:lightbulb
      show_label: false
      show_name: true
      hold_action:
        action: more-info
        entity: light.group_bedroom_top_theo
        haptic: success
      tap_action:
        action: call-service
        service: script.fire_custom_event
        service_data:
          custom_event_data: group_bedroom_top_theo_virtual_switch_individual_toggle
        haptic: success
      styles:
        card:
          - height: 72px
    - type: custom:button-card
      name: Bedroom
      entity: light.bedroom_wardrobe
      color: auto
      color_type: card
      icon: mdi:wardrobe-outline
      show_label: false
      show_name: false
      hold_action:
        action: more-info
        entity: light.bedroom_wardrobe
        haptic: success
      tap_action:
        action: call-service
        service: script.fire_custom_event
        service_data:
          custom_event_data: bedroom_wardrobe_virtual_switch_individual_toggle
        haptic: success
      styles:
        card:
          - height: 72px
```

**Expected behavior**
Ignore the brightness of the turned-off light when computing the color for the button.

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version 85.0.4183.121 (Official Build) (64-bit)
