### ISSUE TITLE
Button-card intermittently disappears

### ISSUE THREAD

**Issue by frankiboy1** [custom-cards/button-card#381]
I've been using the custom button-card to control the lock to my door for a long time, with great success. However, after updating home assistant to version 0.116.0, the button-card occasionally disappears. This happens both when using a browser on my computer and when using the android app. The button-card addon is already running on the latest version (as far as I can see).

If I reload the page, the button re-appear. The same happens if I select the "Edit dashboard" option. This is a bit more problematic when I use the android app as I haven't found a way to reload the page.

The button is using a fairly simple configuration:

```
entity: light.danalock
name: Ytterdør
show_state: true
state:
  - color: red
    icon: 'mdi:lock'
    value: 'on'
  - color: green
    icon: 'mdi:lock-open'
    value: 'off'
type: 'custom:button-card'
```

Not sure if you can reproduce this. or give me some instructions on how to debug this locally.
