### ISSUE TITLE
how to get icon right-aligned to its grid area

### ISSUE THREAD

**Issue by ktownsend-personal** [custom-cards/button-card#386]
I thought I could solve this with CSS, but I don't think I can reach the elements I need to adjust. I have a card with a wide button showing icon and name horizontally. I want to have the icon and name close together in the center of the button. The problem I am having is that the icon's width is expanding to fill the grid area and cannot be justified in any direction. There is a little gap between `ha-svg-icon` and `img-cell`, but not enough to work with. What I really need is to turn off the 100% width on 3 elements, but some of the child elements aren't reachable via button-card config as far as I can tell. 

If I do these changes using the Chrome dev tool, I can get the desired width and position of the icon:
1. `div#name` set `justify-self:flex-start`
2. `div#img-cell` set `justify-content:flex-end`
3. `ha-icon#icon` set `width:unset`
4. `ha-svg-icon` set `--iron-icon-width:unset`
5. `svg` set `width:unset`

Example of my button:
![image](https://user-images.githubusercontent.com/22361432/96665765-45bd2300-131b-11eb-94e7-208f8a7cf410.png)

Showing the grid area `div#container` (dashed lines):
![image](https://user-images.githubusercontent.com/22361432/96666049-f297a000-131b-11eb-810f-60b9cf2d5dfd.png)

Showing the `div#img-cell`:
![image](https://user-images.githubusercontent.com/22361432/96665912-9df42500-131b-11eb-96bc-76aeb67d4c75.png)

Showing `ha-svg-icon` and `svg`:
![image](https://user-images.githubusercontent.com/22361432/96665964-bcf2b700-131b-11eb-9a99-999efc624da5.png)

I can do 1, 2 and 3 from that list in the `styles` config, but I can't seem to reach items 4 & 5 with `extra_styles`. I suspect it has something to do with the fact they are in `#shadow-root`. Is there a way for me to reach them to set their CSS, or is it something your button-card could do while building the content? The settings in #4 and #5 don't appear to affect your default layout in any way, at least in my case, so this could be a safe default for your button-card.

Here is the yaml that I tried:
```yaml
type: 'custom:button-card'
template: container
name: Game Room
color: '#F4BC78'
custom_fields:
  buttons:
    card:
      type: horizontal-stack
      cards:
        - type: 'custom:button-card'
          template: wide
          entity: light.ge_14294_in_wall_smart_dimmer_level_4
          icon: 'mdi:ceiling-light'
          aspect_ratio: 4.3/1
          name: Ceiling Light
          styles:
            name:
              - justify-self: flex-start
            img_icon:
              - justify-content: flex-end
            icon:
              - width: unset
          extra_styles: |
            ha-svg-icon {
              --iron-icon-width:unset;
            }
            svg {
              width: unset;
            }
```

**Comment by ktownsend-personal** [comment]
I couldn't sleep, so I researched shadow-dom and also remembered seeing Thomas Loven's `card-mod` mention something about accessing shadow-root a while back. I found that I _can_ affect those shadow root elements using `card-mod`. 

I'm still wondering if this width change can be handled natively by your `button-card` to make it easier, so please let me know your thoughts on that. It seems like this would be useful to more than just my scenario.

To achieve what I needed using `card-mod` I added this to your `button-card` config instead of `extra_styles` in my previous attempt:
```yaml
          style: 
            ha-icon:
              $: |
                ha-svg-icon {
                  --iron-icon-width:unset;
                }
            'ha-icon#icon':
              $:
                ha-svg-icon:
                  $: |
                    svg {
                      width: unset !important;
                    }
```

**Comment by ktownsend-personal** [comment]
It turns out I need to do more experimenting to get the CSS right for all widths. In some cases the icon disappeared with these settings, such as in the iOS app. I still welcome some thoughts on this, but I will close the request.

**Comment by ktownsend-personal** [comment]
As a follow-up, I got really close to the effect I wanted with a different approach. 

To achieve the icon and name being adjacent and both being centered in the button I used `display:contents` to effectively negate the grid and img_cell and make the icon and name `position:relative`. I had to use a fixed-width for the icon to keep it from trying to be 100% of the container width. That unfortunately kills the responsive autosizing, but CSS is a fickle beast when it comes to autosizing both height and width. 

```yaml
    styles:
      grid:
        - display: contents
      img_cell:
        - display: contents
      icon:
        - margin: 0
        - margin-right: 0.1em
        - width: 40px
        - position: relative
      name:
        - font-size: 0.8em
```
