### ISSUE TITLE
Configuration Templates and array overload

### ISSUE THREAD

**Issue by thomasgermain** [custom-cards/button-card#387]
**Is your feature request related to a problem? Please describe.**
When using an array inside a `template1` and using a the same array in `template2`( inheriting `template1`), the array is not overloaded, but merged (so there is 2 elements in the array). let's see my use case above.

**Describe the solution you'd like**
I don't want to duplicate code 😛 

**Describe alternatives you've considered**
To be honest, I don't know, I understand the current behavior and I can imagine that can be quite hard to change it (do you really want to change it actually ?)

**Additional context**
I have the `zigbee2mqtt` template:
```yaml
zigbee2mqtt:
  style: |
    ha-card {
      padding: 0 !important
    }

  variables:
    entity_id: ""
  custom_fields:
    device_status:
      card:
        style: |
          ha-card {
            box-shadow: none;
            text-align: left
          }
        type: entities
        entities:  #<-- this is the array
        - entity: '[[[ return variables.entity_id ]]]'
          type: custom:multiple-entity-row
          secondary_info:
            attribute: last_seen
  styles:
    custom_fields:
      device_status:
      - overflow: unset
    card:
    - overflow: unset
    grid:
    - grid-template-areas: '"i" "n" "device_status"'
    - grid-template-columns: 1fr
    - grid-template-rows: 1fr min-content min-content
```
I'm using it like this:
```yaml
...
      - type: 'custom:button-card'
        template: zigbee2mqtt
        variables:
          entity_id: sensor.cars_outlet_linkquality
```
and it generates:
![image](https://user-images.githubusercontent.com/12560542/97008303-ee010080-1542-11eb-9350-8adad07914b1.png)
And this is wonderful 😲 

Now I have the `zigbee2mqtt_battery` (inheriting from `zigbee2mqtt`)
```yaml
zigbee2mqtt_battery:
  template: zigbee2mqtt
  custom_fields:
    device_status:
      card:
        entities: #<-- i'm expecting to overload the array defined inside zigbee2mqtt
        - entity: '[[[ return variables.entity_id ]]]'
          type: custom:multiple-entity-row
          secondary_info:
            attribute: last_seen
          entities:
          - attribute: battery
            unit: "%"
```

I'm using it like this:
```yaml
...
      - type: 'custom:button-card'
        template: zigbee2mqtt_battery
        variables:
          entity_id: sensor.living_room_lamp_switch_linkquality
```
and it generates: 😢 
![image](https://user-images.githubusercontent.com/12560542/97009303-3967de80-1544-11eb-8238-4ff7f05d42ce.png)

And I would like (note the battery percentage added):
![image](https://user-images.githubusercontent.com/12560542/97008734-85665380-1543-11eb-9b17-689179ee3af6.png)

So I would expect the array to be _overloaded_ instead of being _merged_

Maybe somebody have an alternative to make it work ?

By the way, I take the advantage of this feature request to thank you for that incredible card 👍 

Thomas

**Comment by thomasgermain** [comment]
Hmm not sure how I fixed it, but it's working as expected. I introduced a `base` template:

```yaml
base:
  style: |
    ha-card {
      padding: 0 !important;
      font-size: 1.0rem !important;
    }
  variables:
    entity_id: ""
  custom_fields:
    device_status:
      card:
        style: |
          ha-card {
            box-shadow: none;
            text-align: left
          }
        type: entities
  styles:
    custom_fields:
      device_status:
      - overflow: unset
    card:
    - overflow: unset
    grid:
    - grid-template-areas: '"i" "n" "device_status"'
    - grid-template-columns: 1fr
    - grid-template-rows: 1fr min-content min-content
  show_icon: false
  show_name: false
``` 

And now here is  `zigbee2mqtt`
```yaml
zigbee2mqtt:
  template: base
  custom_fields:
    device_status:
      card:
        entities:
        - entity: '[[[ return variables.entity_id ]]]'
          type: custom:multiple-entity-row
          secondary_info:
            attribute: last_seen
            format: relative
  state:
  - operator: template
    value: >
      [[[
        return states[variables.entity_id].state < 26
        || states[variables.entity_id].attributes.battery < 11
        || states[variables.entity_id].state == 'unavailable'
      ]]]
    styles:
      card:
      - box-shadow: "0 0 5px red"
  - operator: template
    value: >
      [[[
        return states[variables.entity_id].state < 51
        || states[variables.entity_id].attributes.battery < 21
      ]]]
    styles:
      card:
      - box-shadow: "0 0 5px #FF8C00"
```

and `zigbee2mqtt_battery`
```yaml
zigbee2mqtt_battery:
  template: base
  custom_fields:
    device_status:
      card:
        entities:
        - entity: '[[[ return variables.entity_id ]]]'
          type: custom:multiple-entity-row
          secondary_info:
            attribute: last_seen
            format: relative
          entities:
          - attribute: battery
            unit: "%"
```

(There is a red or range shadow on the card based on link quality, battery level and if the entity is available).

I still have few duplicated lines, but this is acceptable.

Thanks again for the card 😃 

Thomas
