### ISSUE TITLE
wrong entity in javascript template

### ISSUE THREAD

**Issue by ktownsend-personal** [custom-cards/button-card#389]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
A `button-card` nested inside another `button-card` using `custom_fields` is not getting the correct entity variable in javascript templates. _**It is receiving the parent card's entity.**_ 

**Version of the card**
Version: 3.3.6

**To Reproduce**
This is the configuration I used:
```yaml
type: 'custom:button-card'
entity: switch.office_neon
show_name: false
show_icon: false
styles:
  grid:
    - display: contents
custom_fields:
  child:
    card:
      type: 'custom:button-card'
      entity: sensor.aqualink_run_mode
      name: '[[[ return entity.entity_id ]]]'
```

**Screenshots**
The yaml above gives this result. The icon is from the correct local entity, but the name is from the parent card's entity.
![image](https://user-images.githubusercontent.com/22361432/97261709-625ecc80-17ed-11eb-8849-e0d5b6494159.png)

**Expected behavior**
The javascript should receive the entity for the local card. It may be ok to inherit entity from the parent card if the local card does not define an entity, but only if not defined. If an entity is defined on the local card but does not exist then the javascript should get undefined.
