### ISSUE TITLE
Button with long text support

### ISSUE THREAD

**Issue by rolfberkenbosch** [custom-cards/button-card#393]
**Is your feature request related to a problem? Please describe.**
I want to create a button to auto adjust the height of the button on the size of the long text.
For example if i have a text that is 2 rows long, the button would be 2 rows. And not "This is a lon....."

**Describe the solution you'd like**
Make an option that make a long text, or it will auto cut off text (default)

**Describe alternatives you've considered**
I have also looked to https://github.com/Savjee/button-text-card. But the button-card has more options with icons for example.

**Comment by RomRider** [comment]
If you want to have the text over 2 lines, you can modify the CSS already.
```yaml
styles:
  card: #or any other field
    - white-space: normal
    - text-overflow: unset
```

**Comment by RomRider** [comment]
Closing due to inactivity.

**Comment by Anton-Ka** [comment]
> If you want to have the text over 2 lines, you can modify the CSS already.
> 
> ```yaml
> styles:
>   card: #or any other field
>     - white-space: normal
>     - text-overflow: unset
> ```


I tried to do it like this, but it doesn't work.
```yaml
              - type: custom:button-card
                icon: mdi:dome-light
                name: Ванная верхний свет
                entity: switch.0x158d000421c612_switch
                styles:
                  card:
                    - height: 100px 
                    - white-space: normal
                    - text-overflow: unset
```
![image](https://user-images.githubusercontent.com/74901464/123634731-7bf46000-d823-11eb-872b-b56085706dff.png)
