### ISSUE TITLE
Toggle inserted in button card does not work on touch screen (mouse click works)

### ISSUE THREAD

**Issue by hcoohb** [custom-cards/button-card#394]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
When inserting an entities card with a switch inside a button-card, the toggle is not working on touch-screen but works fine with mouse click on desktop

**Version of the card**
Version: 3.3.6

**To Reproduce**
This is the configuration I used (simplified version for demo purpose):
```yaml
type: 'custom:button-card'
custom_fields:
  onecard:
    card:
      type: entities
      entities:
        - switch.myswitch
styles:
  grid:
    - grid-template-areas: '"onecard"'
    - grid-template-columns: 1fr
    - grid-template-rows: 1fr
```

**Expected behavior**
I would expect the toggle from the entities card to work with a tap on touchscreen, same as a click on desktop

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 86.0.4240

**Smartphone (please complete the following information):**
 - Device: Oneplus
 - OS: Android 10
 - Browser: HA app or chrome tested. 

**Additional context**
Touchscreen tested on HA app and browser on mobile as well as laptop touchscreen.

Let me know if you need more details!
Thanks
