### ISSUE TITLE
"flex: 1 1 auto" needed for proper auto-sizing

### ISSUE THREAD

**Issue by ktownsend-personal** [custom-cards/button-card#396]
**Is your feature request related to a problem? Please describe.**
There is a situation where I have 2 of these cards in a horizontal-stack and I need one of these cards to be 75% width and the other to be 25% width. Using styles to set the width of the cards almost works, in that the widths are indeed what I need...except each one has a margin added that makes it take 100% width (doubling the intended width). 

In this example, the Office and Game cards are in their own nested horizontal-stack with the card widths set to 75% and 25%. 
![image](https://user-images.githubusercontent.com/22361432/98338456-d52b2d00-1fcf-11eb-81de-4e02481af9db.png)

Here I have highlighted the automatic margin being applied when I set a % width:
![image](https://user-images.githubusercontent.com/22361432/98338703-34893d00-1fd0-11eb-9172-9afdfb7efdda.png)
![image](https://user-images.githubusercontent.com/22361432/98338755-4bc82a80-1fd0-11eb-8d60-f672d4a36f78.png)

Just for reference, here is what it looks like without trying to change the widths:
![image](https://user-images.githubusercontent.com/22361432/98341240-2dfcc480-1fd4-11eb-9d97-e995eb279842.png)

**Describe the solution you'd like**
What I have found by poking around in the developer menu of Chrome is not setting % sizes and instead the `<button-card>` elements need to have `flex: 1 1 auto` instead of the `flex: 1 1 0px` that is inherited from `#root > *`.  _Unfortunately I can't seem to reach that element with card-mod styling._ Would it be possible to add a boolean setting to `button-card` to apply `flex: 1 1 auto` to the `<button-card>` element, or even better: enhancing the styles to allow targeting the `<button-card>` element for maximum flexibility?

Example of using `flex: 1 1 auto` for both of the button cards that need to be different sizes:
![image](https://user-images.githubusercontent.com/22361432/98339680-b7f75e00-1fd1-11eb-93cf-da0fce806a1e.png)

**Describe alternatives you've considered**
Setting pixel widths on the cards avoids the weird giant margin problem, but it is not viable because the widths need to be different depending on what device is displaying them.

**Comment by RomRider** [comment]
I could introduce that feature but this is not standard in lovelace and will not work along side other cards (unless you use card-mod of course)

**Comment by ktownsend-personal** [comment]
I definitely understand your points, and I'm all for being consistent when possible. It would be great if I could reach that CSS with card-mod. I have an [open question in the community forum](https://community.home-assistant.io/t/need-card-mod-help-how-to-reach-button-card/242638) to see if it may be possible, but so far no suggestions. I'm going to keep trying different things over the weekend to see if I can find a workaround. I'll reply here with whatever I come up with, if anything. If I can't find a workaround by the end of the weekend I would like to proceed with this feature request if possible.

**Comment by ktownsend-personal** [comment]
🎉  I had an epiphany and found a very effective workaround. Instead of using a `horizontal-stack` to contain the 2 button cards I used a button card with `custom_fields`. Initially I was thinking this would allow me to set styles on the custom fields to set the `flex: 1 1 auto`, but it turns out that wasn't even necessary because they are no longer inheriting `flex: 1 1 0px` from `#root > *`. All I had to do was reproduce the gap between them with margin-left and margin-right. 

```yaml
  - type: custom:button-card
    styles:
      card: 
        - padding: 0
      grid:
        - display: contents
      custom_fields:
        button1:
          - margin-right: 4px
        button2:
          - margin-left: 4px
    custom_fields:
      button1:
        card:
          #...nested config omitted for brevity...
      button2:
        card:
          #...nested config omitted for brevity...
```
