### ISSUE TITLE
Only show confirmation when lock is enabled

### ISSUE THREAD

**Issue by excalbian** [custom-cards/button-card#398]
**Is your feature request related to a problem? Please describe.**
I have a button that turns off my 3D printer. It's protected by a lock, and I'd like to show the confirmation, but only when the printer is currently on (not when the printer is off and the button isn't locked). IE: Somehow to tie the lock.enabled to the confirmation.

**Describe the solution you'd like**
Ideally, if the button has a confirmation and a lock, when the lock is disabled, the confirmation should also be disabled. Alternatively (not to introduce any regression issues) add an option to the confirmation either to enable it (similar to the lock object) or to tie it to the lock being enabled?

**Describe alternatives you've considered**
I actually assumed this would work 😳 but then when it didn't, tried to control the confirmation using a template 👎, and tried putting the confirmation into the lock object 👎.

**Additional context**
Here's what my card currently looks like:
``` yaml
type: 'custom:button-card'
tap_action:
  action: toggle
name: Power
confirmation: 
  text: 'Are you locking me?'
icon: 'mdi:power'
lock:
  enabled: '[[[ return entity.state === "on"; ]]]'
  unlock: 'double_tap'

entity: switch.ender3pro_power
```
