### ISSUE TITLE
Tap_action works as double_tap and double_tap does it double [3.4.0-3, 3.4.0-4 and 3.4.0-5]

### ISSUE THREAD

**Issue by ASNNetworks** [custom-cards/button-card#399]
**Checklist**
- [ X] I updated the card to the latest version available
- [X ] I cleared the cache of my browser

**Describe the bug**
Updates 3.4.0-3, 3.4.0-4 and 3.4.0-5 have a bug when a button has a double_tap action in it. Double_action actually does it twice. And tap_action works as a double_tap action. This bug is not present on 3.4.0-2 and previous versions. Buttons that only have tap_acion are not affected, so the tap_action command does work. But then double_tap action is added, then it will get bugged.
**Version of the card**
Version: 

**To Reproduce**
This is the configuration I used (template):
```
  media_appletv:
    template: media
    state:
      - styles:
          card:
            - background-color: var(--card-background-media)
          icon:
            - color: var(--media-entity-color)
          name:
            - color: var(--button-text-color)
        value: playing
      - styles:
          card:
            - background-color: var(--card-background-media)
            - filter: opacity(50%)
          icon:
            - color: var(--media-entity-color)
          name:
            - color: var(--button-text-color)
        value: paused
      - styles:
          name:
            - color: var(--button-text-color)
          card:
            - background-color: var(--sensor-accent-color)
          icon:
            - color: var(--media-entity-color)
            - animation: 
        value: 'off'
    double_tap_action:
      action: toggle
    tap_action:
      action: call-service
      haptic: medium
      service: remote.send_command
      service_data:
        command: menu
        entity_id: remote.appletv_4k
```

**Screenshots**

**Expected behavior**
It should work like on 3.4.0-2 and before. 

**Desktop (please complete the following information):**
 - Browser Edge Chromium
 - Version  86.0.622.63

**Smartphone (please complete the following information):**
 - Device: iPhone XS Max
 - OS: iOS 14
 - Browser Safari
 - Version: Stock

**Additional context**

**Comment by RomRider** [comment]
Not sure I understand but I'm surprised as I use the exact same code as core and it does work on all my devices, including the crApple ones.

Let me ask you some questions:
* what is/are exactly the executed action(s) when you:
  * tap
  * double tap
* does that happen on the desktop also?

**Comment by ASNNetworks** [comment]
Hi Romrider! In this case: 
tap =
```
    tap_action:
      action: call-service
      haptic: medium
      service: remote.send_command
      service_data:
        command: menu
        entity_id: remote.appletv_4k
```
So it sends a remote command 'menu' to my AppleTV.

double tap = toggle media player power. In this case the AppleTV becomes available/unavailable when toggling. 

But with the updates since x.-3 when tapping the icon, it sends a double_tap command. So it toggles the power instead of sending the remote command. And when doing a double_tap, it actually sends the command twice (so in this case it toggles the power twice). When there is no double_tap action setup, the single tap works normal. 

This is tested on iPhone XS Max running latest HA mobile app and iOS 14. 

edit: I tested some more and this is very strange: this issue it not present on Windows browsers (Edge Chromium), Android Tablet (Fully Kiosk Browser) and even not on iPad running iOS14 and official app. 

edit 2: upon even some more testing I figured out what the issue is. This occurs when the button uses the [deep_press](https://github.com/roflcoopter/deep-press) variable. That's why only that button has this issue (it has tap_action, double_tap_action and deep_press). 

So something has changed with button card that causes it to have issues with deep_press, which is a different component. I don't know if this is something you can fix (though it work fine on all versions prior to x.-2) or somehting that roflcoopter can fix.

Should I send him this ticket as well, maybe it needs changing of code by both?

**Comment by RomRider** [comment]
Would you mind trying with a standard button from HA core? Since I'm using the same code as core, you should have the issue there also. If it is the case, then the fix should probably happen on the deep_press side.
I don't know how deep_press works though :)

**Comment by ASNNetworks** [comment]
> Would you mind trying with a standard button from HA core? Since I'm using the same code as core, you should have the issue there also. If it is the case, then the fix should probably happen on the deep_press side.
> I don't know how deep_press works though :)
> 
> EDIT: As a side note, I checked the code of deep_press and if you are using templates in hold_action it will fail to evaluate the templates since it replaces how the card handle the action.

I just tried it with the core button card. That has the same behaviour as you expected. The thing is, I don't use templates in hold_action. Just more-info, nothing more. Also tap_action and double_tap_action I don't use templates. Right now I created the most simple button card with core and it also does it. 

```
type: button
tap_action:
  action: toggle
entity: light.woonkamer_bollen
hold_action:
  action: more-info
double_tap_action:
  action: call-service
  service: light.turn_off
  service_data:
    entity: light.woonkamer_bollen
deep_press: true
```
I hope roflcoopter can update his code. I'll create a ticket at his repo, thanks RomRider!

P.S. If you have the chance and time: can you take a look at stack-in-card? It's broken with the latest 0.2.0 update (I created a ticket).
