### ISSUE TITLE
Unable to sort a list of entities from lowest to highest

### ISSUE THREAD

**Issue by exeljb** [custom-cards/button-card#404]
**Checklist**
- [x ] I updated the card to the latest version available
- [x ] I cleared the cache of my browser

**Describe the bug**
Unable to sort a list of entities from lowest to highest.  I have a list of entities that i want to sort from the lowest battery level to the highest but it just won't sort.  The card will display values in lovelace but the entities will not be sorted in any particular way.

**Version of the card**
Version:  1.7.0

**To Reproduce**
This is the configuration I used:
```
card:
  type: entities
  title: Sensor Batteries
  show_header_toggle: false
type: 'custom:auto-entities'
entities:
  - entity: sensor.a_door_sensor_bat
  - entity: sensor.another_door_sensor_bat
  - entity: sensor.another2_door_sensor_bat
  - entity: sensor.another3_door_sensor_bat
  - entity: sensor.another4_door_sensor_bat
  - entity: sensor.another5_door_sensor_bat
  - entity: sensor.pir_sensor_bat
show_empty: true
unique: true
sort:
  method: state
  reverse: true
  numeric: true


```

**Expected behavior**
Sort battery entities from lowest to highest

**Desktop (please complete the following information):**
 - Browser: all

**Comment by exeljb** [comment]
I changed the way I picked the entities to a filter instead of just plain listing them like I did originally and now the list will sort correctly.  It also has a benefit of making the code look a bit simpler and condensed as well.  Is that expected behavior though?  I had originally thought it would rearrange my list of entities but that's not what it was doing.

```
card:
  type: entities
  title: Sensor Batteries
  show_header_toggle: false
type: 'custom:auto-entities'
filter:
  include:
    - entity_id: '*sensor_bat*'
show_empty: true
unique: true
sort:
  method: state
  reverse: false
  numeric: true

```
