### ISSUE TITLE
media_player.select_source fails but same call works in Developer tools->Services

### ISSUE THREAD

**Issue by setdetnet** [custom-cards/button-card#405]
**Checklist**
- [YES ] I updated the card to the latest version available
- [YES ] I cleared the cache of my browser

**Describe the bug**
Config for sending **select_source** to a **media_player** entity , results in an error:
`Nov 30 12:21:19 Pi 6879e7f42d83[862]: 2020-11-30 12:21:19 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities media_player.rouku_player_lounge
Nov 30 12:21:19 Pi docker-compose[19391]: homeassistant    | 2020-11-30 12:21:19 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities media_player.rouku_player_lounge
`

**Version of the card**
Version: 3.3.6

**To Reproduce**
This is the configuration I used:
```
  - type: 'custom:button-card'
    entity: media_player.roku_player_lounge
    show_icon: false
    entity_picture: /local/roku/my5.png
    show_entity_picture: true
    show_state: false
    tap_action:
      action: call-service
      service: media_player.select_source
      service_data:
        entity_id: media_player.rouku_player_lounge
        source: My5
```

**Screenshots**
![image](https://user-images.githubusercontent.com/62568953/100610433-9efb7780-3307-11eb-8afb-ab93942c40c8.png)

**Expected behavior**
Expected to reproduce ability to select media source on a Roku media player. This can be done by the HA **Developer Tools->Services** page, which works fine and changes the media source.

![image](https://user-images.githubusercontent.com/62568953/100610554-da964180-3307-11eb-84e6-8f7878cd7328.png)

**Desktop (please complete the following information):**
 - Chrome 
 - Version 87.0.4280.66 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
Problem same in all:-
 - Device: Samsungs (various)
 - OS: Android 8, 9 and 10.
 - Browser: Stock and Chrome and Duck

**Additional context**
