### ISSUE TITLE
State template stopped working as before

### ISSUE THREAD

**Issue by ArkadiuszNiemiec** [custom-cards/button-card#406]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
I have a state template based on fan attribute called `speed`. Exmaple:
```
                state:
                  - operator: template
                    value: >
                      [[[ return states['fan.bedroom_air_purifier'].attributes.speed == 'Silent' ]]]
                    styles:
                      icon:
                        - color: 'var(--paper-item-icon-active-color)'
```
Few months ago (I don't remember what I have changed in the setup) it stopped working as intended. The button is `on` when the fan is `on` and `off` when the fan is `off`.  The `speed` attribute changes between `Auto`, `Silent` and `Favorite`. The code works in template editor in Developer Tools.

**Version of the card**
Version: 3.3.6

**To Reproduce**
This is the configuration I used:
```yaml
              - entity: fan.bedroom_air_purifier # purifier silent
                icon: 'mdi:weather-night'
                show_icon: true
                show_name: false
                state:
                  - operator: template
                    value: >
                      [[[ return states['fan.bedroom_air_purifier'].attributes.speed == 'Silent' ]]]
                    styles:
                      icon:
                        - color: 'var(--paper-item-icon-active-color)'
                styles:
                  card:
                    - height: 80px
                    - box-shadow: none
                tap_action:
                  action: call-service
                  service: fan.set_speed
                  service_data:
                    entity_id: fan.bedroom_air_purifier
                    speed: Silent
                  haptic: light
                hold_action:
                  action: more-info
                type: 'custom:button-card'
```

**Screenshots**

![Screenshot from 2020-12-01 22-33-04](https://user-images.githubusercontent.com/12136404/100799373-3c000280-3425-11eb-9910-379e8819d20b.png)

**Expected behavior**
I expect the button to light up when speed is `Silent` and light off when any other.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] FF
 - Version [e.g. 22] 83.0
