### ISSUE TITLE
entity undefined in icon template

### ISSUE THREAD

**Issue by andvikt** [custom-cards/button-card#409]
**Checklist**
- [*] I updated the card to the latest version available
- [*] I cleared the cache of my browser

**Describe the bug**
When i add some templating for icon based on current state there is an error: undefined is not an object (evualating 'entity.state')

**Version of the card**
Version: 3.4.0

**To Reproduce**
This is the configuration I used:
```yaml
- type: horizontal-stack
  cards:
    - type: 'custom:button-card'
      entity: input_boolean.vent_vca_cinema
      icon: |
        [[[
          if (entity.state === 'on')
            return 'mdi:valve-open';
          else
            return 'mdi:valve-open';
        ]]]
      show_name: false
      size: 80%
      styles:
        card:
          - height: 60px
```

**Screenshots**
<img width="520" alt="Снимок экрана 2020-12-16 в 10 30 12" src="https://user-images.githubusercontent.com/39195436/102318049-bbdfae00-3f89-11eb-8cd9-856adbf67153.png">

**Expected behavior**
Have a working templated icon based on entity.state

**Desktop (please complete the following information):**
 - Browser safari
 - Version 13.1.1
