### ISSUE TITLE
Add support for RGBA

### ISSUE THREAD

**Issue by thib5** [custom-cards/button-card#41]
Hi ! it could be really cool if we could play with the transparency. so have a fancy background and set the buttons with a 50% transparent when off for exemple

**Comment by ammmze** [comment]
For something like that, you'd probably want the entire button to have transparency rather than just card background, icon, or label (the `color_type` values). So you can get transparency using the `style` property like this...

```yaml
- type: custom:button-card
  entity: remote.master_bedroom
  icon: mdi:power
  color_type: card
  color: "#CE2841"
  style:
    - opacity: 0.5
```

But that doesn't quite get us all the way to what you want...what we need is to be able to set style per state. Currently I think it only supports setting the `color` per state. But what we need would be configured something like this...

```yaml
- type: custom:button-card
  entity: remote.master_bedroom
  icon: mdi:power
  color_type: card
  color: "#CE2841"
  state:
    - value: 'off'
      style:
        - opacity: 0.5
```
