### ISSUE TITLE
Action: Fire (custom) event

### ISSUE THREAD

**Issue by rr326** [custom-cards/button-card#411]
**Is your feature request related to a problem? Please describe.**
I would like to trigger an AppDaemon service call. Right now I'm forced to use  `action: call-service; service: mqtt.publish`  which works for me, but it's cumbersome (requiring MQTT). I'd also like my appdaemon app to be more useful for others, and having MQTT just for signaling is a high hurdle. 

**Describe the solution you'd like**
```
    tap_action:
      action: fire-event
      service_data:
        event_name: "event.do_something_important"
        payload: 
            field1: val1
            field2: val2
```
**Describe alternatives you've considered**
I've implemented this with MQTT and it works fine. But it requires a lot of setup (MQTT) for a trivial feature. 
Also, `call_service` does not seem to work for AppDaemon-created services. 

**Additional context**
If you think this is a valid suggestion and would likely accept a PR, I'll implement it.

**Comment by RomRider** [comment]
You can call a script which fires the event, no need for mqtt.
Events are not supported in frontend and that is not related to button-card.

**Comment by rr326** [comment]
@RomRider Thank you. That works.

For anyone else who finds this thread. Included is a little trick so you don't need to create different scripts for different events.

```yaml
# dashboard.yaml
...
tap_action:
  action: call-service
  service: script.fire_event_myapp
  service_data:
      sub_event: the_event_I_really_want

# scripts.yaml
fire_event_myapp:
  alias: "Fire Event - myapp"
  sequence:
  - event: myapp_event
    event_data: 
      sub_event: "{{sub_event}}"
```

```python
# myapp.py
self.listen_event(self.test_event, event="myapp_event", sub_event="the_event_I_really_want")
```
