### ISSUE TITLE
Controlling layering order of grid items in the card?

### ISSUE THREAD

**Issue by poldim** [custom-cards/button-card#412]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser

**Describe the bug**
The pop-up bubble that shows the % position of the slider displays normally as a regular entity, but when placed inside the custom button card, the grid-template cell on top of the slider seems to cover up the pop-up.  Is it possible to have the pop-up or the entire slider have "upper layer" priority?

**Version of the card**
Version:  3.4.0  _b5de991_

**To Reproduce**
This is the configuration I used:
```yaml
views:
- title: Main
  path: main
  cards:
  - type: 'vertical-stack'
    cards:
    - type: horizontal-stack
      show_header_toggle: false
      cards:
        - type: 'custom:button-card'
          template: curtain_slider_button
          entity: cover.curtain_master_bedroom
          name: Master
        - type: 'custom:button-card'
          template: curtain_slider_button
          entity: cover.curtain_guest_bedroom
          name: Guest
    - type: horizontal-stack
      show_header_toggle: false
      cards:
        - type: 'custom:button-card'
          template: curtain_slider_button
          entity: cover.curtain_living_room
          name: Living
        - type: 'custom:button-card'
          template: curtain_slider_button
          entity: cover.curtain_dining_room
          name: Dining

button_card_templates:
  curtain_slider_button:
    size: 25px
    styles:
      grid:
        - grid-template-areas: '"i n ." "slider slider slider"'
        - grid-template-columns: 55px min-content 1fr
        - grid-template-rows: 1fr 1fr
      card:
        - padding-top: 10px
        - padding-bottom: 10px
      icon:
        - color: var(--primary-color)
      name:
        - font-size: 16px
        - color: var(--primary-text-color)
        - padding-left: 1px
        - padding-right: 1px
      label:
        - color: var(--primary-text-color)
    custom_fields:
      slider:
        card:
          full_row: true
          hide_state: true
          type: custom:slider-entity-row
          entity: '[[[ return entity.entity_id]]]'
```

**Screenshots**
![image](https://user-images.githubusercontent.com/16869713/103106042-1a8ad480-45e7-11eb-94d7-dffad42e6dfc.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/16869713/103106037-0a72f500-45e7-11eb-93a0-0059757f2975.png)

**Desktop (please complete the following information):**
 - Browser: Chrome 
 - Version: 87.0.4280.88 (Official Build) (x86_64)

**Additional context**
Recording of the issue:  

https://user-images.githubusercontent.com/16869713/103106254-98031480-45e8-11eb-8cdd-e2dc90b05edf.mov

**Comment by RomRider** [comment]
That's not a problem of layer but of overflow.
Adding `overflow: visible` to the css of your custom field should fix the issue:
```yaml
button_card_templates:
  curtain_slider_button:
    size: 25px
    styles:
      grid:
        - grid-template-areas: '"i n ." "slider slider slider"'
        - grid-template-columns: 55px min-content 1fr
        - grid-template-rows: 1fr 1fr
      card:
        - padding-top: 10px
        - padding-bottom: 10px
      icon:
        - color: var(--primary-color)
      name:
        - font-size: 16px
        - color: var(--primary-text-color)
        - padding-left: 1px
        - padding-right: 1px
      label:
        - color: var(--primary-text-color)
      custom_fields:
        slider:
          - overflow: visible
    custom_fields:
      slider:
        card:
          full_row: true
          hide_state: true
          type: custom:slider-entity-row
          entity: '[[[ return entity.entity_id]]]'
```
