### ISSUE TITLE
"lock: true" does not lock the button if "tooltip" specified

### ISSUE THREAD

**Issue by ildar170975** [custom-cards/button-card#416]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
If tooltip is added, then the tap_action is performed even if the button is locked.

**Version of the card**
Version: 
3.4.1

**To Reproduce**
This is the configuration I used:
```
type: 'custom:button-card'
entity: input_boolean.test_boolean
name: some name
size: 30%
icon: 'mdi:car'
lock:
  enabled: true
  duration: 7
  unlock: hold
tooltip: Some tooltip
```

**Screenshots**
![изображение](https://user-images.githubusercontent.com/71872483/103456125-5b2fcf80-4d04-11eb-8ce2-a23f605f9d83.png)

**Expected behavior**
The "tap_action" should not be performed if the button is locked.

**Desktop (please complete the following information):**
 - Browser - Chrome 
 - Version - 87.0.4280.88
 - Windows 10x64
