### ISSUE TITLE
Multiple icons on button card

### ISSUE THREAD

**Issue by mpejstrup** [custom-cards/button-card#417]
Hi
Is it possible to put in multiple icons on a button card. I have a button for vacuuming the different rooms in our house, but I want some extra buttons where I have combined the rooms. Ex. Kitchen and Hall mdi: silverware + mdi: hanger.

**Comment by RomRider** [comment]
You can do that using `custom_fields`.
There's an example [here](https://github.com/custom-cards/button-card/blob/master/README.md#custom-fields) using `<ha-icon>`

**Comment by mpejstrup** [comment]
Tried this, but no sure I'm on the right track?
```
                              - type: custom:button-card
                                name: Bryggers + Gang
                                triggers_update:
                                  ['vacuum.gerda']
                                tap_action:
                                  action: call-service
                                  service: script.turn_on
                                  service_data:
                                    entity_id: script.bryggers_gang
                                styles:
                                  icon:
                                    [width: 1.8em]
                                  card:
                                    [width: 8em, height: 4em]
                                custom_fields:
                                  washing-machine:
                                    - align-self: center
                                    - justify-self: start
                                    <ha-icon icon="mdi:washing-machine"></ha-icon>
                                  hanger:
                                    - align-self: center
                                    - justify-self: end
                                    <ha-icon icon="mdi:hanger"></ha-icon>   
```
