### ISSUE TITLE
Merging state by id into two states not working

### ISSUE THREAD

**Issue by kongo09** [custom-cards/button-card#418]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser

**Describe the bug**
Merging state configuration by `id:` only works for one state, not for more. Merging for more leads to unexpected results of state not matching.

**Version of the card**
Version: 3.4.1

**To Reproduce**
This is the configuration I used for Lovelace
```
button_card_templates:
  activated_state:
    state:
      - id: activated_state
        styles:
          card:
            - background-color: var(--primary-text-color)
            - color: var(--card-background-color)
          name:
            - color: 'var(--mmp-accent-color, var(--accent-color))'
            - font-weight: bold
          icon:
            - color: 'var(--mmp-accent-color, var(--accent-color))'
```

Idea is to apply these styles to whichever state I apply the `id:` to. In the button-card it looks like this:

```
      - type: 'custom:button-card'
        template:
          - buttons
          - activated_state
        icon: 'philips:power_button'
        entity: fan.air_ac2729
        show_name: false
        tap_action:
          action: call-service
          service: script.toggle_ac_two_in_one_mode
          service_data:
            entity_id: entity
        state:
          - operator: template
            value: |
              [[[
                return (entity.attributes.function == "Purification and Humidification" &&
                entity.state == 'on')
              ]]]
            icon: 'philips:two_in_one_mode'
            id: activated_state
          - operator: template
            value: |
              [[[
                return (entity.attributes.function == "Purification" &&
                entity.state == 'on')
              ]]]
            icon: 'philips:purification_only_mode'
            id: activated_state
```

As can be seen, I've used the `id: activated_state` twice. I would expect the styling from the template to be applied to both states. What is happening is, that the first condition never is true. The second condition matches and the `id:` template is merged in, so the styling applies. When I remove the `id:` in the first condition, the state starts to match (which can be seen by the icon that changes with the state).

**Expected behavior**
I would expect that the template with the styles with a matching `id:` is merged into / appended to whatever is configured for the respective state where the corresponding `id:` is used. I don't see a reason to only let this work with the last occurance of the `id:`. I couldn't find any reference to this in the documentation.

**Desktop (please complete the following information):**
 - Edge
 - Version 87.0.664.75 (Official build) (64-bit)

**Comment by RomRider** [comment]
That is not possible unfortunately. An id is meant to be unique.

You can use a `variables` entry to achieve the same thing with both your states in one template. See here for an example: https://community.home-assistant.io/t/lovelace-button-card/65981/4085?u=romrider

**Comment by kongo09** [comment]
Thanks for the swift reply. What from my perspective still is a bug is that the first condition never comes true. This should at least produce some sort of an error when ids are not meant to be used twice. It also might make sense to update the documentation in order to be very explicit on intended behaviour.

As for my expected behaviour: I can see some power in this as this makes states more easily templetable. The variables approach feels like jumping through some extra loop. Would it make sense to consider this as a feature request?

**Comment by RomRider** [comment]
I understand your request but I don't think I'll implement this. As I said an `id` is meant to be unique (I'll update the doc and maybe throw an error if it's not as you suggested) and allowing what you want will lead to other usage and strange behaviors that I want to avoid (eg: twice the same `id` in both the template and the button).
Merging state by id is already an edge case feature, I'd like to avoid adding edge case features to edge case features ;)

**Comment by kongo09** [comment]
Understood. Thanks for considering and overall for the great contribution to the community!

**Comment by kongo09** [comment]
I tried to follow your advice and intended to post it here for future reference for other people running into the same thing. But funny enough, the following code worked once inside the card configuration preview, and now that I saved it, it only produces errors, as if the saving had changed something:

```
type: 'custom:button-card'
entity: fan.air_ac2729
variables:
  is_on: '[[[ return entity && entity.state == "on" ]]]'
  is_off: '[[[ return entity && entity.state == "off" ]]]'
  is_pur: '[[[ return entity && entity.attributes.function == "Purification" ]]]'
  icon: >-
    [[[ return variables.is_pur ? "philips:purification_only_mode" :
    "philips:two_in_one_mode" ]]]
state:
  - operator: template
    value: '[[[ return variables.is_on ]]]'
    icon: '[[[ return variables.icon ]]]'
  - operator: template
    value: '[[[ return variables.is_off ]]]'
    icon: '[[[ return variables.icon ]]]'
```
results in:

> ButtonCardJSTemplateError: TypeError: Cannot read property 'is_pur' of undefined in 'return variables.is_pur ? "philips:purification_only_mode" : "philips:two_in_one_mode"'

I'm lost.

**Comment by kongo09** [comment]
Sticking code for `icon:` down into the state makes it work:

```
type: 'custom:button-card'
entity: fan.air_ac2729
variables:
  is_on: '[[[ return entity && entity.state == "on" ]]]'
  is_off: '[[[ return entity && entity.state == "off" ]]]'
  is_pur: '[[[ return entity && entity.attributes.function == "Purification" ]]]'
state:
  - operator: template
    value: '[[[ return variables.is_on ]]]'
    icon: >-
      [[[ return variables.is_pur ? "philips:purification_only_mode" :
      "philips:two_in_one_mode" ]]]
  - operator: template
    value: '[[[ return variables.is_off ]]]'
    icon: >-
      [[[ return variables.is_pur ? "philips:purification_only_mode" :
      "philips:two_in_one_mode" ]]]

```
