### ISSUE TITLE
Reduce Button Size For Margin on All Sides?

### ISSUE THREAD

**Issue by ZacharyHarrisNC** [custom-cards/button-card#421]
I'm very new to HA and Lovelace. I am trying to create a row of buttons, which are square, resize based on screen size, remain centered in the screen, and have a margin between each button. So far, the best way I can think to do this is to horizontal row with however many buttons added. I do the configuration, set aspect ratio to 1/1 and we're mostly good to go. The issue I still have is size/margin. The buttons are too big and close together for my styling. I thought about hardcoding a fixed width, but for whatever reason when I have a fixed aspect ratio, a fixed width or does not work. I also tried adding margin to the code, but this ends up shifting the card any given direction, eventually pushing cards off screen. Basically, I want lovelace to see the card as 10px bigger on each size than it actually is.

Any help would be much appreciated. Current code:

```yaml
entity: input_boolean.sleep_mode
icon: 'mdi:weather-sunset-up'
aspect_ratio: 1/1
show_icon: true
show_name: false
styles:
  card:
    - border-radius: 15px
    - box-shadow: |
        [[[ return states['sun.sun'].state == 'below_horizon'
          ? '-5px -5px 8px rgba(0, 0, 0, .05), 5px 5px 8px rgba(0, 0, 0, .05)'
          : '-4px -4px 8px rgba(255, 255, 255, .5), 5px 5px 8px rgba(0, 0, 0, .03)';
        ]]]
    - background-color: var(--primary-background-color)
  icon:
    - color: var(--primary-text-color)
state:
  - value: 'on'
    styles:
      card:
        - box-shadow: |
            [[[ return states['sun.sun'].state == 'below_horizon'
              ? 'inset -3px -3px 5px rgba(50, 50, 255, .2), inset 3px 3px 5px rgba(0, 0, 255, .2)'
              : 'inset -3px -3px 5px rgba(255, 255, 255, .65), inset 3px 3px 5px rgba(0, 0, 0, .035)';
            ]]]
      icon:
        - color: var(--paper-item-icon-active-color)
tap_action:
  action: toggle
  haptic: light
hold_action:
  action: more-info
  haptic: medium
type: 'custom:button-card'
```

**Comment by RomRider** [comment]
I'd suggest looking at `card-mod` to increase the gap between the items in a `horizontal-stack`.
Lovelace resizes automatically cards to fit a full row.
`aspect_ratio: 1/1` is not compatible with fixed width unfortunately.

What you can also try is to introduce an invisible card between each of your buttons:
```yaml
type: custom:button-card
color_type: blank-card
styles:
  card:
    - width: 20px
```
