### ISSUE TITLE
Bug - On press button returns error

### ISSUE THREAD

**Issue by Claw256** [custom-cards/button-card#425]
**Is your feature request related to a problem? Please describe.**
Yes, I'm trying to use the confirmation option to only show a confirmation message when the entity (MQTT plug) is on, to stop me accidentally turning off my PC when I'm using it in HA. I don't want the confirmation popup to show when the entity if off.

**Describe the solution you'd like**
Add support for enabling or disabling confirmation, with template support, same as the lock option.

**Describe alternatives you've considered**
I tried using the text option for confirmation to show the confirmation text when the entity is on, but that only controls text and not the actual pop up. If there was an option to disable the confirmation popup based on entity state, I would use that.

**Additional context**
What I currently have at the moment:
```
- type: "custom:button-card"
  entity: switch.my_smart_plug
  icon: mdi:power-plug
  color: auto
  confirmation:
    text: >
      [[[
        if (entity.state === "on")
          return `Are you sure you want to turn off ${entity.attributes.friendly_name}?`;
      ]]]
```

If there is another way of doing this, or if I missed something that I should be using, please let me know.

**Comment by RomRider** [comment]
Hey,

You can achieve that already:
```yaml
- type: "custom:button-card"
  entity: switch.my_smart_plug
  icon: mdi:power-plug
  color: auto
  confirmation: |
    [[[
        if (entity.state === "on")
          return { text: `Are you sure you want to turn off ${entity.attributes.friendly_name}?`} ;
    ]]]
```
