### ISSUE TITLE
Button templates cannot override state from parent templates

### ISSUE THREAD

**Issue by gry** [custom-cards/button-card#428]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
When defining a state in a button template, it is not possible to replace that state in a template that inherits it. See the example yaml of 2 templates and example card. Is there a workaround possible?

**Version of the card**
Version: 3.4.1

**To Reproduce**
This is the configuration I used:
```yaml
button_card_templates:
  test1:
    state:
      - value: on
        icon: 'mdi:virus'
        styles:
          card:
            - background-color: 'yellow'
  test2:
    template: test1
    state:
      - value: on
        icon: 'mdi:needle'
        styles:
          card:
            - background-color: 'red'
      - value: off
        icon: 'mdi:needle'
        styles:
          card:
            - background-color: 'green'  

[...]
# Code of example card
type: horizontal-stack
cards:
  - type: 'custom:button-card'
    name: test1
    entity: light.xiaomi_bombilla_salon
    template: test1
  - type: 'custom:button-card'
    name: test2
    entity: light.xiaomi_bombilla_salon
    template: test2
```

**Screenshots**
Entity off (inherits off state correctly)
![image](https://user-images.githubusercontent.com/3475654/107161635-3f23eb80-699e-11eb-88c6-3f00d7221c4b.png)

Entity on (does not inherit on state from test2 template)
![image](https://user-images.githubusercontent.com/3475654/107161661-7397a780-699e-11eb-899f-51aad2b2540b.png)

**Expected behavior**
Expected to inherit the new on state from test2, overriding the test1 behavior. 

**Desktop (please complete the following information):**
 - Browser chrome, android companion app
 - Version 88

**Comment by RomRider** [comment]
That's intended because you don't do it the right way. There's a section in the documentation about that. Look for merging states by id for how to make this work like you want.

**Comment by gry** [comment]
Thanks! As said by @RomRider , just adding an id attribute to the state that you want to merge solves this.

My example would be fixed adding "id: 'on'" to both states like this:

```
button_card_templates:
  test1:
    state:
      - value: 'on'
        id: 'on'
        icon: 'mdi:virus'
        styles:
          card:
            - background-color: yellow
  test2:
    template: test1
    state:
      - value: 'on'
        id: 'on'
        icon: 'mdi:needle'
        styles:
          card:
            - background-color: red
      - value: 'off'
        icon: 'mdi:needle'
        styles:
          card:
            - background-color: green
  background:
    styles:
      card:
        - background-color: 'rgba(0,0,0,0.3)'
    state:
      - value: onbck
        styles:
          card:
            - background-color: '#03a9f4'
```
