### ISSUE TITLE
allow entity override for tap_action

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/button-card#431]
**Is your feature request related to a problem? Please describe.**

have a button with an entity, and want the tap_action to act on another entity, so I need to create some nifty (complicated) templating

**Describe the solution you'd like**

a simple entity override like

```
type: custom:button-card
entity: sensor.espresso
tap_action:
  action: toggle
  entity: switch.espresso_keuken
```
**Describe alternatives you've considered**

a bit of a hacky solution:

```
tap_action:
  action: call-service
  service: '[[[ return states["switch.espresso_keuken"].state === "off"? "switch.turn_on" : "switch.turn_off" ]]]'
  service_data:
    entity_id: switch.espresso_keuken
```

**Additional context**

see community: https://community.home-assistant.io/t/lovelace-button-card/65981/5118?u=mariusthvdb

not sure if you saw my final edit on that, so please allow me this FR. If only for getting your final view on the request, thanks for considering!
