### ISSUE TITLE
Fire-dom-event still not working in 3.4.2

### ISSUE THREAD

**Issue by anubisg1** [custom-cards/button-card#432]
Upgrade to 3.4.2 and cleared cache and cookies. 

Fire-dom-event is still not working and I'm not the only one reporting the same https://github.com/thomasloven/hass-browser_mod/issues/189#issuecomment-781093039 

**To Reproduce**
This is the configuration I used:
```yaml

old configuration

    hold_action:
      action: call-service
      service: browser_mod.popup
      service_data:
        title: '[[[ return entity.attributes.friendly_name ]]]'
        deviceID: this


new configuration:

  hold_action:
    action: fire-dom-event
    browser_mod:
      command: popup
      title: "[[[ return entity.attributes.friendly_name ]]]"

```
