### ISSUE TITLE
Changeable size for lock icon

### ISSUE THREAD

**Issue by dmatik** [custom-cards/button-card#433]
There is a fixed size on the lock icon, 24px if I'm not mistaken. It does not always work well with every design.
In would be nice to have a property under lock style for example "icon_size" where we could specify any size.

**Comment by edenhaus** [comment]
As workaround `extra_styles` can be used.

Example set the size to 50px:
```yaml
extra_styles: |
  #lock {
    width: 50px;
  }
```
