### ISSUE TITLE
Strange behaviour on mobile app (Android) when styling card height

### ISSUE THREAD

**Issue by TTLucian** [custom-cards/button-card#434]
**Checklist**
- [x ] I updated the card to the latest version available
- [x ] I cleared the cache of my browser

**Describe the bug**
Strange behaviour on mobile app (Android) when styling card height. Some buttons display incorrectly at home assistant startup. They return to normal on state changes. I don't know where this bug comes from but it only happens on mobile app (works ok in browser). See screen shot (a 4 column grid card containing only custom:button-card). If I remove the style: height object, they appear fine. Tried force closing the app and deleting app's cache. No errors appear in log.

**Version of the card**
Version: 3.4.2

**To Reproduce**
This is the configuration I used:
```yaml
    styles:
      card:
        - height: 60px
```

**Screenshots**
![Screenshot_20210219-171042_Home_Assistant (Phone)](https://user-images.githubusercontent.com/1855276/108524267-86cc4080-72d7-11eb-967c-29b604add95f.png)

**Expected behavior**
All content visible

**Smartphone (please complete the following information):**
 - Device: Lenovo P2
 - OS: Android 10
 - Browser Home Assistant app
 - Version 2021.1.1-full

**Comment by Qpernicus** [comment]
My Lovelace shows the same behavior. On iOS and in Librewolf (Firefox variant) on Manjaro. So I think it is not specifically mobile related.

**Comment by TTLucian** [comment]
You're right. Cleared browser cache and it happens in every browser. 😞

**Comment by RomRider** [comment]
Is this behavior happening in a grid only?

**Comment by Qpernicus** [comment]
> Is this behavior happening in a grid only? 

No, on a horizontal stack as well. But I presume the cause could be related to what happens both in a stack and in a grid.

**Comment by RomRider** [comment]
You are not using aspect_ratio at the same time, right?

**Comment by TTLucian** [comment]
No. This is what I use:
```yaml
    styles:
      card:
        - height: 60px
      name:
        - font-size: 13px
      icon:
        - height: 25px
```
Shows correctly only after removing "height"

**Comment by Qpernicus** [comment]
In case it might help, this is the code i used succesfully on a LOT of cards:

```
type: 'custom:button-card'
styles:
  card:
    - width: 110px
    - height: 110px
    - margin: 10px
    - font-size: 12px
    - border-radius: 15px
    - box-shadow: |
        [[[ return states['sun.sun'].state == 'below_horizon'
          ? '-5px -5px 8px rgba(50, 50, 50, .2), 5px 5px 8px rgba(0, 0, 0, .08)'
          : '-4px -4px 8px rgba(255, 255, 255, .5), 5px 5px 8px rgba(0, 0, 0, .03)';
        ]]]
    - background-color: var(--primary-background-color)
  icon:
    - color: var(--primary-text-color)
state:
  - value: 'on'
    styles:
      card:
        - box-shadow: |
            [[[ return states['sun.sun'].state == 'below_horizon'
              ? 'inset -3px -3px 5px rgba(50, 50, 50, .5), inset 3px 3px 5px rgba(0, 0, 0, .3)'
              : 'inset -3px -3px 5px rgba(255, 255, 255, .65), inset 3px 3px 5px rgba(0, 0, 0, .035)';
            ]]]
      icon:
        - color: var(--paper-item-icon-active-color)
```


Which all works, accept for the height of the card.
