### ISSUE TITLE
Allow show_state to be templatable

### ISSUE THREAD

**Issue by kenlasko** [custom-cards/button-card#435]
I have a custom button card that I use to show a countdown timer when I press another related button. The countdown only shows properly when you set show_state: true. When the countdown isn't active, I would like to show alternate text without showing the state of the timer (which is "Idle")

It would be great if show_state allowed us to use Javascript templates like many other options. This would allow me to only show the countdown timer when it is active. 

I'm considering using a conditional card, but it would be so nice to do this all in a single card.

![image](https://user-images.githubusercontent.com/44060527/108578576-129e9680-72f1-11eb-887f-8ba09c234ce7.png)
![image](https://user-images.githubusercontent.com/44060527/108578601-1af6d180-72f1-11eb-8c11-774454d3ead6.png)

**Comment by RomRider** [comment]
You can do that using `state_display`. If the code in `state_display` returns null, it will display the default state, else what `state_display` returns.

**Comment by kenlasko** [comment]
Thanks for the tip! It gets me closer to what I want, but still shows the colon when the timer is idle. I know its nitpicky, but....
![image](https://user-images.githubusercontent.com/44060527/108597646-0e599400-7358-11eb-844d-51200624d042.png)
![image](https://user-images.githubusercontent.com/44060527/108597660-20d3cd80-7358-11eb-990f-5a2d548de1c4.png)

Here's my current code. I couldn't return null without an error. Had to use an empty string:
```
color_type: card
entity: timer.camera_disable
layout: name_state
show_state: true
state_display: >-
  [[[ if (entity.state == 'idle') return ' '; ]]]
show_icon: false
name: >-
  [[[ if (entity.state == 'idle') return 'Disable Front Door Camera'; else
  return 'Camera disabled for';]]]
styles:
  card:
    - background-color: 'rgb(49, 49, 49)'
    - color: white
state:
  - styles:
      card:
        - background-color: darkred
    value: active
type: 'custom:button-card'
```
