### ISSUE TITLE
Wrong card color after state change / Only refresh of browser is helping

### ISSUE THREAD

**Issue by AdmiralRaccoon** [custom-cards/button-card#439]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
I don´t know weather it´s a Browser, a HA or button-card issue. I experience this problem a couple of weeks now with almost every card: After a state change, the card doesn´t refresh it´s color as it should. Only after refreshing the page with F5, the color is correct. I tried is with several browsers (Edge, Chrome) and also with the office HA App for Android / iOS. It´s the same on every device.

Below is a simple example, which shows me if my iPad is Wifi connected or not.

Screenshot 1 : iPad is in home- looks good
Screenshot 2 : iPad is not_home - looks weird, as it should look like in screenshot 3
Screenshot 3 : iPad is not_home - After refreshing with F5 - looks good

**Version of the card**
Version: 3.4.2

**To Reproduce**
This is the configuration I used:
```
      - color_type: card
        entity: device_tracker.ipad_philipp
        show_name: true
        name: iPad Philipp
        show_state: false
        state:
          - color: 'rgb(223, 116, 12)'
            icon: 'mdi:apple'
            value: home
          - color: default
            icon: 'mdi:apple'
            value: not_home
            styles:
              icon:
                - filter: opacity(5%)
              name:
                - filter: opacity(5%)
        type: 'custom:button-card'


```

**Screenshots**

![c0](https://user-images.githubusercontent.com/41727850/108988436-bfcc3280-7694-11eb-8c54-dfe4bd20ea17.png)
![1](https://user-images.githubusercontent.com/41727850/108988440-c2c72300-7694-11eb-98c7-404adbebafcf.png)
![2](https://user-images.githubusercontent.com/41727850/108988453-c5c21380-7694-11eb-8066-feaab472d1ea.png)

**Expected behavior**
The cards should like like weeks ago with the correct color.

**Desktop (please complete the following information):**
 - Browser: Chrome 88, Edge  88.0.705.74

**Smartphone (please complete the following information):**
 - Device:  pixel 5
 - OS: Android 11]
 - Browser: HA App
 - Version: 2021.2.2-full

**Additional context**
I hope this helps - Thank you for your help
