### ISSUE TITLE
Allow template on show_last_changed

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/button-card#442]
**Is your feature request related to a problem? Please describe.**

we need the show_last_changed only in a certain situation (state of an entity).

**Describe the solution you'd like**

```
        show_last_changed: >
          [[[ return 'true' if entity.state == 'on'; ]]] 
```
or probably even better:
```
[[[ return entity.state == 'on'; ]]]
```

**Describe alternatives you've considered**

```
        state:
          - value: 'on'
            show_last_changed: true
          - value: 'off'
            show_last_changed: false
```
would be a 'stated' alternative
maybe a clever workaround using state_display, but that would be much more complex and less obvious

**Additional context**
please see community post: https://community.home-assistant.io/t/lovelace-button-card/65981/5218?u=mariusthvdb

**Comment by dcapslock** [comment]
All `show_*` are not templatable.

`last_changed` is put in the label slot so you can template display of `label:` via 'state:` 

e.g.

```yaml
        state:
          - value: 'off'
            styles:
              label:
                - display: nne
```
