### ISSUE TITLE
introduce default action 'trigger' on an automation

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/button-card#443]
**Is your feature request related to a problem? Please describe.**

we need to set a full action object on a button with a trigger

**Describe the solution you'd like**

introduce default action 'trigger' on a button with an automation  entity

**Describe alternatives you've considered**

right now we need:
```
tap_action:
  action: call-service
  service: automation.trigger
  service_data:
    entity_id: >
      [[[ return entity.entity_id; ]]]
```

which could be left out if default action for automation was trigger.

**Additional context**
