### ISSUE TITLE
Button card in stack doesn't work

### ISSUE THREAD

**Issue by azrael783** [custom-cards/button-card#445]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
I added multiple button cards in a horizontal and vertical stack to control my covers, but it throws me the following error:

```
Logger: frontend.js.latest.202103024
Source: components/system_log/__init__.py:190
First occurred: 10:45:45 (48 occurrences)
Last logged: 13:41:19

http://192.168.0.120:8123/hacsfiles/button-card/button-card.js:547:3849 TypeError: 0 is read-only
http://192.168.0.120:8123/frontend_latest/chunk.3140e3a75c4de14c5580.js:1:0 NS_ERROR_FAILURE:
http://192.168.0.120:8123/frontend_latest/chunk.bcc24dc7f2504ad36740.js:114:114 TypeError: can't convert undefined to object
http://192.168.0.120:8123/hacsfiles/button-card/button-card.js:547:3843 Uncaught TypeError: Cannot assign to read only property '0' of string 'call-service'
```
I am using the latest HA version core-2021.3.1

**Version of the card**
Version: 3.4.2

**To Reproduce**
This is the configuration I used:
```yaml
title: Rollo Steuerung
type: vertical-stack
cards:
  - cards:
      - icon: 'mdi:window-shutter'
        name: GäZi
        service: cover.close_cover
        service_data:
          entity_id: cover.rollos_gastezimmer
        tap_action: call-service
        type: 'custom:button-card'
      - icon: 'mdi:window-shutter-open'
        name: GäZi
        service: cover.open_cover
        service_data:
          entity_id: cover.rollos_gastezimmer
        tap_action: call-service
        type: 'custom:button-card'
    type: horizontal-stack
  - cards:
      - icon: 'mdi:window-shutter'
        name: WoZi
        service: cover.close_cover
        service_data:
          entity_id: cover.rollos_wohnzimmer
        tap_action: call-service
        type: 'custom:button-card'
      - icon: 'mdi:window-shutter-open'
        name: WoZi
        service: cover.open_cover
        service_data:
          entity_id: cover.rollos_wohnzimmer
        tap_action: call-service
        type: 'custom:button-card'
    type: horizontal-stack
```

**Screenshots**

**Expected behavior**
It works if a add a single button card to my UI. I would expect that it works also in a stack.

**Desktop (please complete the following information):**
 - Browser chrome v89.0.4389.72 and firefox v86.0
 - Version see above

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RomRider** [comment]
That's because your config is wrong:
```yaml
        
        tap_action:
          action: call-service
          service: cover.close_cover
          service_data:
            entity_id: cover.rollos_gastezimmer
```
