### ISSUE TITLE
Custom icon & background based on state

### ISSUE THREAD

**Issue by szyszyla** [custom-cards/button-card#448]
Hi!
Is there a way to customize **both** icon and background based on state? Using `color_type` i can only define one.

**Comment by RomRider** [comment]
Please head over to the forum with that kind of question next time.
```yaml
state:
  - value: xxx
    styles:
      icon:
        - color: rgb(x, y, z)
      card:
        - background-color: rgb(x, y, z)
```
