### ISSUE TITLE
Hold action - example?

### ISSUE THREAD

**Issue by FillHK** [custom-cards/button-card#451]
Any example of hold_action?
I have this code working:
```
              tap_action: 
                  action: call-service
                  service: script.executa_hisense_volume_up
                  service_data:
                    entity_id: script.executa_hisense_volume_up
```
How to add hold for Volume up?

**Comment by RomRider** [comment]
What do you mean by `hold_action`? You want it to repeat the action while you hold the button?

**Comment by FillHK** [comment]
Yes, exactly.
I want to hold the Volume Up (etc) and increase volume.

**Comment by RomRider** [comment]
Then it's by using `repeat`:
```yaml
hold_action: 
    action: call-service
    service: script.executa_hisense_volume_up
    repeat: 500 # will run the action every 500ms
    service_data:
      entity_id: script.executa_hisense_volume_up
```

**Comment by FillHK** [comment]
```
              # Volume up      
            - type: 'custom:button-card'
              entity: script.executa_hisense_volume_up
              icon: mdi:volume-plus
              name: Volume up
              show_name: false
              show_label: false
              font-size: 12px
              styles:
                card:
                  - width: 50px
                  - height: 70px
                  - background-color: '#333'
                  - margin-left: 10px
                  - margin-top: 10px
                  - border-top-right-radius: 40px
                  - border-top-left-radius: 40px
                name:
                  - font-size: 12px
                  - color: '#999'
                  - align-self: middle
                  - justify-self: center
                  - padding-bottom: 4px 
                icon: 
                  - color: '#999'
                  - width: 40%
              tap_action: 
                  action: call-service
                  service: script.executa_hisense_volume_up
                  service_data:
                    entity_id: script.executa_hisense_volume_up
              hold_action: 
                  action: call-service
                  service: script.executa_hisense_volume_up
                  repeat: 200 # will run the action every 500ms
                  service_data:
                    entity_id: script.executa_hisense_volume_up
```
This is my full code, but it doesn't work ;(

**Comment by RomRider** [comment]
Can you be a bit more explicit than "it doesn't work"?

**Comment by FillHK** [comment]
Yes, sorry.

I press Volume UP - and in just a few seconds seems volume increasing.
Issues:
* It works just for a few seconds of holding - then it stops increasing volume
* Increasing is too slow, like 1 point per half-second

**Comment by RomRider** [comment]
Then you need to modify your script to make bigger increments in volume each time it's fired.

**Comment by mark007** [comment]
I'm facing the same issue. The repeat does work but only runs a handful of times before it stops. My guess is some other javascript hold event is taking over and preventing subsequent increments from happening? If this is the case, if it could be reproduced on the developers side, is there a possibility to fix it by somehow not bubbling the hold event up to the browser or whatever might be 'taking over' and stopping the nth repeat from kicking in. For me it feels like maybe 2 or 3 repeats usually work but after that none fire.

**Comment by dcapslock** [comment]
Can't replicate. Below is test yaml and video showing repeat working.

is this still an issue? If so I suggest testing what happens if you repeatedly call the volume service from a script to make sure it keeps functioning as expected. It could be that the integration has an issue with repeated service calls.

Closing for now but wiull reopen on further infomration.

```yaml
type: custom:button-card
entity: input_number.increment_test
show_label: true
show_icon: false
label: |
  [[[
    return entity.state;
  ]]]
name: Repeat Increment
tap_action:
  action: call-service
  service: input_number.increment
  repeat: 250
  target:
    entity_id: input_number.increment_test
hold_action:
  action: call-service
  service: input_number.increment
  repeat: 250
  target:
    entity_id: input_number.increment_test

```

https://github.com/user-attachments/assets/40444f6e-60a7-4f3d-a50f-50fd443a266d
