### ISSUE TITLE
Card frame exceeds the lovelace area

### ISSUE THREAD

**Issue by exeljb** [custom-cards/button-card#452]
I'm having an issue that's kind of hard to explain so I'm posting some pics to show what's going on.
![Screen Shot 2021-03-19 at 7 35 35 PM](https://user-images.githubusercontent.com/59851334/111854465-6cdd4800-88ed-11eb-9871-5dfc76852aab.png)

![Screen Shot 2021-03-19 at 7 39 04 PM](https://user-images.githubusercontent.com/59851334/111854477-78c90a00-88ed-11eb-9221-bda2cdea3de1.png)

I'm having a hard time figuring out why the button card is extending outside the area that lovelace is expecting it to be.  I've tried messing around with padding: and margin: in the config, but I haven't been able to figure out how to get this formatted correctly.  The code that I'm using was based off of the sample code for the grid-area provided here (the area where it shows an example card for HassOS cpu and memory usage). 

The next level of cards shown in my screenshots above use this custom button card and aren't having any of the same issues, granted they're formatted much more simply than these bottom cards are.

I am stumped. Can anyone help?  Here's the code that I'm using.

```
type: horizontal-stack
cards:
  - aspect_ratio: 4/1
    custom_fields:
      temp: |
        [[[
          return `<ha-icon
            icon="mdi:thermometer"
            style="width: 12px; height: 12px; color: deepskyblue;">
            </ha-icon><span>  <span style="color: var(--text-color-sensor);">${states['sensor.livingroom_temperature'].state}F</span></span>`
        ]]]
      hum: |
        [[[
          return `<ha-icon
            icon="mdi:water-percent"
            style="width: 12px; height: 12px; color: deepskyblue;">
            </ha-icon><span>  <span style="color: var(--text-color-sensor);">${states['sensor.livingroom_humidity'].state}%</span></span>`
        ]]]
    entity: sensor.livingroom_temperature
    icon: 'mdi:raspberry-pi'
    name: '  LR'
    tap_action:
      action: more-info
    styles:
      card:
        - background-color: '#1d1e20'
        - border-radius: 10%
        - padding: 01%
        - color: ivory
        - font-size: 10px
        - text-shadow: 0px 0px 5px black
        - text-transform: capitalize
        - height: 45px
      custom_fields:
        temp:
          - align-self: middle
          - justify-self: center
          - '--text-color-sensor': >-
              [[[ if (states["sensor.livingroom_temperature"].state > 80) return
              "red"; ]]]
        hum:
          - align-self: middle
          - justify-self: center
          - '--text-color-sensor': >-
              [[[ if (states["sensor.livingroom_humidity"].state > 80) return
              "red"; ]]]
      grid:
        - grid-template-areas: '"n n" "temp temp" "hum hum"'
        - grid-template-columns: 1fr 1fr
        - grid-template-rows: 1fr min-content min-content
      icon:
        - color: |
            [[[
              if (entity.state < 60) return 'lime';
              if (entity.state >= 60 && entity.state < 80) return 'orange';
              else return 'red';
            ]]]
        - width: 70%
        - margin-top: 0%
      img_cell:
        - justify-content: start
        - align-items: start
        - margin: none
      name:
        - font-weight: bold
        - font-size: 13px
        - color: white
        - align-self: end
        - justify-self: middle
        - padding-bottom: 4
    type: 'custom:button-card'
  - aspect_ratio: 4/1
    custom_fields:
      temp: |
        [[[
          return `<ha-icon
            icon="mdi:thermometer"
            style="width: 12px; height: 12px; color: deepskyblue;">
            </ha-icon><span>  <span style="color: var(--text-color-sensor);">${states['sensor.mb_temperature'].state}F</span></span>`
        ]]]
      hum: |
        [[[
          return `<ha-icon
            icon="mdi:water-percent"
            style="width: 12px; height: 12px; color: deepskyblue;">
            </ha-icon><span>  <span style="color: var(--text-color-sensor);">${states['sensor.mb_humidity'].state}%</span></span>`
        ]]]
    entity: sensor.mb_temperature
    icon: 'mdi:raspberry-pi'
    name: MB
    tap_action:
      action: more-info
    styles:
      card:
        - background-color: '#1d1e20'
        - border-radius: 10%
        - padding: 0%
        - color: ivory
        - font-size: 10px
        - text-shadow: 0px 0px 5px black
        - text-transform: capitalize
        - height: 45px
      custom_fields:
        temp:
          - align-self: middle
          - justify-self: center
          - '--text-color-sensor': >-
              [[[ if (states["sensor.mb_temperature"].state > 80) return "red";
              ]]]
        hum:
          - align-self: middle
          - justify-self: center
          - '--text-color-sensor': '[[[ if (states["sensor.mb_humidity"].state > 80) return "red"; ]]]'
      grid:
        - grid-template-areas: '"n n" "temp temp" "hum hum"'
        - grid-template-columns: 1fr 1fr
        - grid-template-rows: 1fr min-content min-content
      icon:
        - color: |
            [[[
              if (entity.state < 60) return 'lime';
              if (entity.state >= 60 && entity.state < 80) return 'orange';
              else return 'red';
            ]]]
        - width: 70%
        - margin-top: 0%
      img_cell:
        - justify-content: start
        - align-items: start
        - margin: none
      name:
        - font-weight: bold
        - font-size: 13px
        - color: white
        - align-self: end
        - justify-self: middle
        - padding-bottom: 4
    type: 'custom:button-card'
  - aspect_ratio: 4/1
    custom_fields:
      temp: |
        [[[
          return `<ha-icon
            icon="mdi:thermometer"
            style="width: 12px; height: 12px; color: deepskyblue;">
            </ha-icon><span>  <span style="color: var(--text-color-sensor);">${states['sensor.basement_temperature'].state}F</span></span>`
        ]]]
      hum: |
        [[[
          return `<ha-icon
            icon="mdi:water-percent"
            style="width: 12px; height: 12px; color: deepskyblue;">
            </ha-icon><span>  <span style="color: var(--text-color-sensor);">${states['sensor.basement_humidity_2'].state}%</span></span>`
        ]]]
    entity: sensor.basement_temperature
    icon: 'mdi:raspberry-pi'
    name: Basement
    tap_action:
      action: more-info
    styles:
      card:
        - background-color: '#1d1e20'
        - border-radius: 10%
        - padding: 0%
        - color: ivory
        - font-size: 10px
        - text-shadow: 0px 0px 5px black
        - text-transform: capitalize
        - height: 45px
      custom_fields:
        temp:
          - align-self: middle
          - justify-self: center
          - '--text-color-sensor': >-
              [[[ if (states["sensor.basement_temperature"].state > 80) return
              "red"; ]]]
        hum:
          - align-self: middle
          - justify-self: center
          - '--text-color-sensor': >-
              [[[ if (states["sensor.basement_humidity_2"].state > 80) return
              "red"; ]]]
      grid:
        - grid-template-areas: '"n n" "temp temp" "hum hum"'
        - grid-template-columns: 1fr 1fr
        - grid-template-rows: 1fr min-content min-content
      icon:
        - color: |
            [[[
              if (entity.state < 60) return 'lime';
              if (entity.state >= 60 && entity.state < 80) return 'orange';
              else return 'red';
            ]]]
        - width: 70%
        - margin-top: 0%
      img_cell:
        - justify-content: start
        - align-items: start
        - margin: none
      name:
        - font-weight: bold
        - font-size: 13px
        - color: white
        - align-self: end
        - justify-self: middle
        - padding-bottom: 4
    type: 'custom:button-card'
  - aspect_ratio: 4/1
    custom_fields:
      temp: |
        [[[
          return `<ha-icon
            icon="mdi:thermometer"
            style="width: 12px; height: 12px; color: deepskyblue;">
            </ha-icon><span>  <span style="color: var(--text-color-sensor);">${states['sensor.garage_temperature_2'].state}F</span></span>`
        ]]]
      hum: |
        [[[
          return `<ha-icon
            icon="mdi:water-percent"
            style="width: 12px; height: 12px; color: deepskyblue;">
            </ha-icon><span>  <span style="color: var(--text-color-sensor);">${states['sensor.garage_humidity_2'].state}%</span></span>`
        ]]]
    entity: sensor.garage_temperature_2
    icon: 'mdi:raspberry-pi'
    name: Garage
    tap_action:
      action: more-info
    styles:
      card:
        - background-color: '#1d1e20'
        - border-radius: 10%
        - padding: 0%
        - color: ivory
        - font-size: 10px
        - text-shadow: 0px 0px 5px black
        - text-transform: capitalize
        - height: 45px
      custom_fields:
        temp:
          - align-self: middle
          - justify-self: center
          - '--text-color-sensor': >-
              [[[ if (states["sensor.garage_temperature_2"].state > 80) return
              "red"; ]]]
        hum:
          - align-self: middle
          - justify-self: center
          - '--text-color-sensor': >-
              [[[ if (states["sensor.garage_humidity_2"].state > 80) return
              "red"; ]]]
      grid:
        - grid-template-areas: '"n n" "temp temp" "hum hum"'
        - grid-template-columns: 1fr 1fr
        - grid-template-rows: 1fr min-content min-content
      icon:
        - color: |
            [[[
              if (entity.state < 60) return 'lime';
              if (entity.state >= 60 && entity.state < 80) return 'orange';
              else return 'red';
            ]]]
        - width: 70%
        - margin-top: 0%
      img_cell:
        - justify-content: start
        - align-items: start
        - margin: none
      name:
        - font-weight: bold
        - font-size: 13px
        - color: white
        - align-self: end
        - justify-self: middle
        - padding-bottom: 4
    type: 'custom:button-card'
```
