### ISSUE TITLE
Inconsistent icon brightness setting

### ISSUE THREAD

**Issue by ishioni** [custom-cards/button-card#454]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser

**Describe the bug**
I am pretty new to button-card, so please correct me if I'm wrong on this, but I'm trying to set up buttons for my house lights, and I can't get them to all behave the same way. I'm using the noctis theme, and I want the buttons to have the blue background (--paper-item-icon-active-color) as the button background, and the icon to correspond to the brightness, starting from white when 100% to dark when 1%. Right now the behaviour is inverted, and I'm not sure how to calculate the inversion. 

However, I've noticed that even ignoring the above, the brightness of the icon behaves in a weird way - it turns into active white when brightness is < 186, and turns inactive dark when above >=186, instead of gradually changing the shade
**Version of the card**
Version: 3.4.2

**To Reproduce**
This is the configuration I used:
```yaml
button_card_templates:
  light:
    show_name: false
    color_type: card
    size: 30%
    color: auto-no-temperature
    hold_action:
      action: more-info
    state:
      - value: 'on'
        styles:
          card:
            - background-color: var(--paper-item-icon-active-color)
[..]
type: 'custom:button-card'
entity: light.kitchen_light
template: light
```

**Screenshots**
<img width="627" alt="Screenshot 2021-03-22 at 23 28 26" src="https://user-images.githubusercontent.com/50323052/112066278-5988e180-8b66-11eb-9083-257598389e83.png">

**Expected behavior**
I would imagine the icon changing it's brightness gradually, according to the brightness
**Desktop (please complete the following information):**
 - Browser: Safari
 - Version: 14.0.3
