### ISSUE TITLE
returns error on input_select.select when selecting string

### ISSUE THREAD

**Issue by gmcaesar** [custom-cards/button-card#455]
**Checklist**
- [Yes ] I updated the card to the latest version available
- [ yes] I cleared the cache of my browser

**Describe the bug**
when triggering a input select it returns an error:
TypeError: sequence item 0: expected str instance, Optional found

same code in default button works fine

**Version of the card**
Version: 3.4.2

**To Reproduce**
This is the configuration I used:
```
type: 'custom:button-card'
entity: input_select.living_room_dashboard
icon: 'mdi:video'
name: Cast Kids Room Camera
show_state: false
tap_action:
  action: call-service
  service: input_select.select_option
  service_data:
    option: kidsroom
  target:
    entity_id: input_select.living_room_dashboard
```
