### ISSUE TITLE
Inconsistent template behavior, cannot override some styles

### ISSUE THREAD

**Issue by rogersmj** [custom-cards/button-card#456]
I'm reasonably sure I'm doing something wrong, and this isn't really a bug, but I can't figure out what the problem is.

I have several configuration templates that I use as my base styles so I can implement multiple button-cards without a lot of repetitive typing, just [as suggested in the docs](https://github.com/custom-cards/button-card#configuration-templates). The problem I'm having is that some of the styles seem to be ignored.

For instance, I have a **base** template that most of my other configuration templates inherit from (I've truncated some of the non-relevant parts of the template):

```
base:
  aspect_ratio: 1/1
  show_state: true
  show_icon: false
  styles:
    name:
      - top: 57.7%
      - left: 10.1%
      - line-height: 2vw
      - position: absolute
    state:
      - top: 74%
      - left: 11%
      - line-height: 2vw
      - position: absolute
    card:
      - font-family: Sf Display
      - letter-spacing: 0.05vw
      - font-weight: 400
      - font-size: 1.34vw
      - border-radius: 0.8vw
```

Then I have other templates that inherit the base for more specific uses, like this one called **scene**:
```
scene:
  template:
    - base
  show_state: false
  tap_action:
    action: call-service
    service: scene.turn_on
    service_data:
      entity_id: >
        [[[ return entity.entity_id ]]]
  styles:
    name:
      - top: 10%
      - left: 10.1%
      - line-height: 3vw
      - position: absolute
```

I utilize this scene template on my dashboard like so:

```
- type: custom:button-card
  template:
    - scene
  entity: scene.office_high
  style:
    top: 20.35%
    left: 31.5%
    width: 10%
```

The issue is that the styles I'm trying to override for **name** are being ignored:

![image](https://user-images.githubusercontent.com/20134/112896204-1a014e80-90ac-11eb-8eda-a6be464b03b7.png)

I would expect that name to be larger, and close to the top of the card. Instead, it is still styled using the positions defined in the **base** configuration template. However, I know at least part of **scene** is being applied because the state is hidden (**scene** contains `show_state: false`). Indeed, when inspecting the HTML element for the name, I see the styles from **base**, not from **scene**:

![image](https://user-images.githubusercontent.com/20134/112896437-62b90780-90ac-11eb-9ff4-40df25d785f9.png)

Why are the styles from **scene** not being applied?
