### ISSUE TITLE
Button Shapes

### ISSUE THREAD

**Issue by Coolie1101** [custom-cards/button-card#458]
**Gratitude**
Just wanted to say a special thank you first for this amazing add-on, really appreciate it.

**Describe the solution you'd like**
The ability to customize the shape of the buttons as shown in the attached pic.

**Describe alternatives you've considered**
Added "- border-radius:" but the effect/look isn't the same..

**Additional context**
I'm hoping to achieve the buttons outlined in red.
![Ovivo_Remote](https://user-images.githubusercontent.com/28989417/113158359-b8ef8d00-9209-11eb-992a-cad591aa4a81.jpg)

This is what I have achieved so far.
![image](https://user-images.githubusercontent.com/28989417/113158866-26032280-920a-11eb-9cc1-fa78fb8b4cc9.png)

**Comment by RomRider** [comment]
You can do that using SVG and use that as your background-image.
Below an example from [here](https://www.svgbackgrounds.com/). You'll have to design your own SVG though.
```yaml
styles:
  card:
    - background-color: #487346;
    - background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='200' height='200' viewBox='0 0 200 200'%3E%3Cg %3E%3Cpolygon fill='%234c8e43' points='100 57.1 64 93.1 71.5 100.6 100 72.1'/%3E%3Cpolygon fill='%236aac5f' points='100 57.1 100 72.1 128.6 100.6 136.1 93.1'/%3E%3Cpolygon fill='%234c8e43' points='100 163.2 100 178.2 170.7 107.5 170.8 92.4'/%3E%3Cpolygon fill='%236aac5f' points='100 163.2 29.2 92.5 29.2 107.5 100 178.2'/%3E%3Cpath fill='%2389CC7C' d='M100 21.8L29.2 92.5l70.7 70.7l70.7-70.7L100 21.8z M100 127.9L64.6 92.5L100 57.1l35.4 35.4L100 127.9z'/%3E%3Cpolygon fill='%23768c3a' points='0 157.1 0 172.1 28.6 200.6 36.1 193.1'/%3E%3Cpolygon fill='%2396ac58' points='70.7 200 70.8 192.4 63.2 200'/%3E%3Cpolygon fill='%23B6CC76' points='27.8 200 63.2 200 70.7 192.5 0 121.8 0 157.2 35.3 192.5'/%3E%3Cpolygon fill='%2396ac58' points='200 157.1 164 193.1 171.5 200.6 200 172.1'/%3E%3Cpolygon fill='%23768c3a' points='136.7 200 129.2 192.5 129.2 200'/%3E%3Cpolygon fill='%23B6CC76' points='172.1 200 164.6 192.5 200 157.1 200 157.2 200 121.8 200 121.8 129.2 192.5 136.7 200'/%3E%3Cpolygon fill='%23768c3a' points='129.2 0 129.2 7.5 200 78.2 200 63.2 136.7 0'/%3E%3Cpolygon fill='%23B6CC76' points='200 27.8 200 27.9 172.1 0 136.7 0 200 63.2 200 63.2'/%3E%3Cpolygon fill='%2396ac58' points='63.2 0 0 63.2 0 78.2 70.7 7.5 70.7 0'/%3E%3Cpolygon fill='%23B6CC76' points='0 63.2 63.2 0 27.8 0 0 27.8'/%3E%3C/g%3E%3C/svg%3E");
```
