### ISSUE TITLE
Shell command 

### ISSUE THREAD

**Issue by thib5** [custom-cards/button-card#46]
Hi ! i'm trying to find the right syntax to execute a shell command...

I tried this : 

>          - type: custom:card-modder
>             card:  
>                 type: "custom:button-card"
>                 icon: 'mdi:arrow-left-bold-outline'
>                 action: service
>                 service: shell_command.kodi_salon_left
>                 color: rgb(0, 225, 255)
>                 color_off: rgb( 200, 200, 200)

**Comment by kuuji** [comment]
You likely need to use the domain and action fields.

See this example 

```
    - type: "custom:button-card"
      color_type: card
      color: rgb(223, 255, 97)
      icon: mdi:volume-plus
      action: service
      service:
        domain: media_player
        action: volume_up
        data:
          entity_id: media_player.livimg_room_speaker
```

So probably something like that for you

```
    - type: "custom:button-card"
      color: rgb(0, 225, 255)
      color_off: rgb( 200, 200, 200)
      icon: mdi:arrow-left-bold-outline
      action: service
      service:
        domain: shell_command
        action: kodi_salon_left

```
