### ISSUE TITLE
Custom Element Doesn't Exist Error

### ISSUE THREAD

**Issue by pongolo** [custom-cards/button-card#460]
I’m fairly new to HA and have run into an issue for which I can’t seem to find a solution.

I installed button-card through HACS and everything seems to be in the right folder location. I restarted HA after installing and added the following to ui-lovelace.yaml:

```
resources:
  - url: /hacsfiles/weather-card/weather-card.js
    type: module

  - url: /hacsfiles/button-card/button-card.js
    type: module


      - type: custom:button-card
        entity: light.playroom
```

Unfortunately all I get is the following error:
```
Custom element doesn't exist: button-card.

type: 'custom:button-card'
entity: light.playroom
```
It took me a while to figure out how to get the weather one working but I can’t seem to find what is wrong with the button-card. I’ve tried clearing the browser cache and used different browsers but that has not resolved the problem.  I assume it's probably something simple and not a bug but can't figure it out.

Appreciate any help!

Thanks!

**Comment by pongolo** [comment]
Someone pointed out that I need to move the resources to the configuration.yaml file as opposed to the ui-lovelace.yaml file.  It's now working.

```
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/weather-card/weather-card.js
      type: module

    - url: /hacsfiles/button-card/button-card.js
      type: module
```
