### ISSUE TITLE
add pin to lock / confirmation options

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/button-card#462]
**Is your feature request related to a problem? Please describe.**

would be very nice to be able to enter a pin on a confirmation to open a eg a garage door

**Describe the solution you'd like**

compare with restriction card:
```
          - type: custom:restriction-card
            row: true
            restrictions:
              confirm:
                text: 'Garagedeur openen?'
              pin:
                text: 'Voer Pincode in:'
                code: !secret tahoma_secret
                max_retries: 3
                max_retries_delay: 30
```

**Describe alternatives you've considered**

see above. however the restriction card will show the dialogue on both open and close, and I would rather use my button, and create a template in the confirmation field it only to show up on opening the garage door while
```
[[[ return states['cover.garage_door'].state == 'closed' ]]]
```

current code for the button:
```
type: custom:button-card
template:
  - button_summary
  - styles_summary_alert
entity: cover.garage_deur
name: Garage deur
tap_action:
  action: toggle
  confirmation:
    text: >
      [[[ return `Are you sure you want to toggle the Garage door?` ]]]
hold_action:
  action: navigate
  navigation_path: >
    [[[ return (window.location.pathname.split('/')[2] == 'covers')
      ? null : '/lovelace/covers'; ]]]
custom_fields:
  notification: >
    [[[ if (entity.state == 'open' && entity.attributes.current_position != 100)
        return entity.attributes.current_position + '%';
        return entity.state; ]]]
styles:
  icon:
    - color: >
        [[[ if (entity.state == 'closed') return 'green'; return 'red'; ]]]
  custom_fields:
    notification:
      - background-color: >
          [[[ if (entity.state == 'closed') return 'green'; return 'red'; ]]]
```

**Additional context**
<img width="433" alt="Schermafbeelding 2021-04-19 om 14 39 28" src="https://user-images.githubusercontent.com/33354141/115237639-139b4b00-a11d-11eb-8103-fa9f3ab4e828.png">
