### ISSUE TITLE
Color auto but with a color different than `var(--paper-item-icon-active-color)`

### ISSUE THREAD

**Issue by dylandoamaral** [custom-cards/button-card#463]
**Is your feature request related to a problem? Please describe.**
I would like that the color change when the brightness of my light is changing. It is the purpose of `color: auto`. However, this feature take the color `var(--paper-item-icon-active-color)` and by looking the code I don't see how to change this. I tried naively to add to the config `color_on` but it didn't work, I also try to set up these colors using state but it didn't work too.

**Describe the solution you'd like**
I would like to change the color by default.

**Comment by dcapslock** [comment]
You can template `--icon-primary-color` with `state:`.

e.g. To show a red icon when a timer is not idle

```yaml
type: custom:button-card
entity: timer.test_timer
state:
  - operator: "!="
    value: idle
    styles:
      card:
        - "--icon-primary-color": red
```
