### ISSUE TITLE
vanilla button-card using timer.mytimer always shows as active/on when idle

### ISSUE THREAD

**Issue by matthyne** [custom-cards/button-card#464]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser

**Describe the bug**
When using custom-button-card with timers the icon will always be colored as ON when idle.  This can be worked around using a state definition but then you cannot color it on when the timer starts

**Version of the card**
Version: v3.4.2

**To Reproduce**
This is the configuration I used:

type: 'custom:button-card'
tap_action:
  action: more-info
entity: timer.shower
show_state: true
show_name: false

**Screenshots**
When Idle (white is on):
![image](https://user-images.githubusercontent.com/17772672/115836210-8f1d3500-a45a-11eb-90f5-604dd3218177.png)

When running (same color):
![image](https://user-images.githubusercontent.com/17772672/115836119-7280fd00-a45a-11eb-939c-18521a55052a.png)

**Expected behavior**
When idle the timer should show the same behaviour as any other entity in the off state

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 89.*

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Lopton** [comment]
I think you can solve this using the state options. Can you try this:

```
  state:
    - value: 'idle'
      styles:
        icon:
          color: rgb(255,0,0)
    - operator: 'default'
      styles:
        icon:
          color: rgb(255,0,0)
```

This sets a default color, which is used when 'idle' is not used. I think that should color one color when the timer is on and another color when the timer is running.
