### ISSUE TITLE
Different action for turn on and off

### ISSUE THREAD

**Issue by seventhsite** [custom-cards/button-card#470]
I have two different scripts to turn on and turn off my projector. And I want to manipulate it with one button. How to realize it? 
Something like:

```
        - type: 'custom:button-card'
          entity: script.projector_on
          entity: script.projector_off
          icon: mdi:projector
          color: rgb(255, 0, 0)
          state:
            - value: 'off'
              color: rgb(0, 0, 0)
```
But it is not work.
(Next question, how to get the action run script on button push, not a script window).

**Comment by indykoning** [comment]
I'd say this is what you're looking for: https://www.home-assistant.io/integrations/switch.template/

You create a switch based on the services you run. So the turn on service would be: script.turn_on with the script id in the data

**Comment by seventhsite** [comment]
I made it with this code:

```
# configuration.yaml
switch:
  - platform: template
    switches:
      projector_power:
#        value_template: "{{ is_state('switch.projector_power', 'on') }}" # need to get state, but it not possible for me
        turn_on:
          - service: remote.send_command
            data:
              entity_id: remote.broadlink_remote
              device: projector
              command: turn on
        turn_off:
          - service: remote.send_command
            data:
              entity_id: remote.broadlink_remote
              device: projector
              command: turn off
          - delay:
              milliseconds: 600
          - service: remote.send_command
            data:
              entity_id: remote.broadlink_remote
              device: projector
              command: turn off
```

```
#  ui-lovelace.yaml

         - type: 'custom:button-card'
            entity: switch.projector_power
            color_type: card
            color: red
            name: PROJECTOR
            icon: mdi:projector
            styles:
              card:
                - --mdc-ripple-color: red
                - --mdc-ripple-press-opacity: 0.9
```
