### ISSUE TITLE
Buttons don't update their colors unless a reload is forced

### ISSUE THREAD

**Issue by forast3r** [custom-cards/button-card#473]
**Checklist**
- [x] I updated the card to the latest version available
- [X] I cleared the cache of my browser

**Describe the bug**
I configured some buttons to select the working mode of a climate device (air purifier). Each button calls a service with the corresponding preset or working mode. That works fine.

Each button has been configured to change its color when the corresponding working mode (state) is updated on the climate device.
The problem is that after updating the working mode, the button that matched the old working mode does not return to the default color.

**Version of the card**
Version: 3.4.2 (17/feb)

**To Reproduce**
This is the configuration I used for button1:
```yaml
color_type: card
entity: climate.xiaomi_miot_air_purifier
icon: 'mdi:fan-auto'
name: auto
show_name: true
type: 'custom:button-card'
styles:
  card:
    - height: 50px
state:
  - value: auto
    color: 'rgb(156,184,191)'
  - operator: default
    color: lightwhite
tap_action:
  action: call-service
  service: climate.set_preset_mode
  service_data:
    entity_id: climate.xiaomi_miot_air_purifier
    preset_mode: Auto
```
This is the configuration I used for button2:
```yaml
color_type: card
entity: climate.xiaomi_miot_air_purifier
icon: 'mdi:moon-waning-crescent'
name: sleep
show_name: true
type: 'custom:button-card'
styles:
  card:
    - height: 50px
state:
  - value: sleep
    color: 'rgb(156,184,191)'
  - operator: default
    color: lightwhite
tap_action:
  action: call-service
  service: climate.set_preset_mode
  service_data:
    entity_id: climate.xiaomi_miot_air_purifier
    preset_mode: sleep
```
Buttons3 and 4 are very similar

**Screenshots**
Result of changing to Auto to Sleep mode: both buttons are marked
![image](https://user-images.githubusercontent.com/38989444/117985948-77d6b680-b339-11eb-8fce-721b1793d6aa.png)

**Expected behavior**
When the state of the entity changes the button should refresh with the corresponding color:
![image](https://user-images.githubusercontent.com/38989444/117986009-86bd6900-b339-11eb-875a-7d216c1e09c3.png)

**Desktop (please complete the following information):**
 - Browser [Chrome]
 - Version [90.0]

**Smartphone (please complete the following information):**
n/a

**Additional context**
