### ISSUE TITLE
tap_action or hold_action problem

### ISSUE THREAD

**Issue by JPOliveGit** [custom-cards/button-card#474]
**Describe the bug**
I'm trying to make a button with custom button card when clicked toggle a switch, I copied the yaml from a button generated by the home assistant ui and when I paste the tap_action on the custom button it gives an error: fail to call service switch/toggle. sequence item 0: expected str instance, Optional found

type: button
icon: 'mdi:garage-variant'
tap_action:
  action: call-service
  service: switch.toggle
  service_data: {}
  target:
    device_id: b92d94491e208(continues)

**Version of the card**
Version: 3.4.2

**Comment by Lopton** [comment]
If you take a look at the examples it has an example of a service call. I think your syntax is off a little, try this:
```
      tap_action:
        action: call-service
        service: switch.toggle
        service_data:
          entity_id: b92d94491e208(continues)
```

**Comment by EKCJ** [comment]
I'm having a similar problem, here's the working code for a Lovelace standard button card:

```
tap_action:
  action: call-service
  service: counter.increment
  service_data: {}
  target:
    entity_id: counter.test_counter
```

And here's the non-working code for this button card:

```
tap_action:
  action: call-service
  service: counter.increment
  service_data: {}
  target:
    entity_id: counter.test_counter
```

Gives the following error:
``Failed to call service counter/increment. sequence item 0: expected str instance, Optional found``

I know the [counter services are finicky at the best of times](https://community.home-assistant.io/t/counter-component-help/28735), but would be grateful for any suggestions.
