### ISSUE TITLE
Icons disappear on state change in Safari/mobile app

### ISSUE THREAD

**Issue by aegjoyce** [custom-cards/button-card#478]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
On Mac Safari 14.1, iOS 14.5 Safari or the iOS HA Mobile App, when I click a button with dynamic icon colour (auto, auto-no-temperature etc) and cause a state change the icon disappears, rather than changing colour appropriately.

This problem does not occur using Mac Google Chrome.

**Version of the card**
Version: 3.4.2

**To Reproduce**
I have large yaml files that use templates. Examples here: https://community.home-assistant.io/t/clean-tile-based-lovelace-ui-only-2-cards-needed/184108/15?u=ajoyce

**Expected behaviour**
The icon should change colour according to state, and not disappear. This works as expected in Mac Google Chrome.

**Comment by RomRider** [comment]
Isn't it because the light is actually white (rgb(255,255,255)) and the background also white?

**Comment by aegjoyce** [comment]
I have an exception for pure white:

```
  light: #for light entities. brightness displayed in dynamic circle
    template:
      - base
      - circle_dynamic
    variables:
      circle_input: >
        [[[ return Math.round(entity.attributes.brightness / 2.54); ]]]
    color: auto-no-temperature
    hold_action:
      action: more-info
    state:
      - styles:
          card:
            - filter: opacity(50%)
          icon:
            - filter: grayscale(100%)
          label:
            - background-color: var(--card-background-color)
        value: 'off'
      - operator: template
        value: >-
          [[[ if (entity.attributes.rgb_color == "255,255,255") return true; else return false ]]]
        styles:
          icon:
            - color: var(--state-icon-active-color)
    tap_action:
      action: toggle
```

It doesn't work with a dark theme either. Again, only on Safari - works fine on Chrome. It used to be fine on Safari though... can't recall when it broke but it was in the last few months I think.

Illustrated with dark theme:
<img width="165" alt="Screenshot 2021-05-23 at 22 43 12" src="https://user-images.githubusercontent.com/47081267/119277594-83b75800-bc18-11eb-97c4-d39485d7d0c5.png">
<img width="156" alt="Screenshot 2021-05-23 at 22 43 21" src="https://user-images.githubusercontent.com/47081267/119277595-8619b200-bc18-11eb-8d9a-b9f306be5ce5.png">
<img width="158" alt="Screenshot 2021-05-23 at 22 43 29" src="https://user-images.githubusercontent.com/47081267/119277598-8a45cf80-bc18-11eb-8dda-1213482d30f1.png">

**Comment by aegjoyce** [comment]
I should add for clarity - if the icon disappears, refreshing the page results in the 'expected' look, as above

**Comment by aegjoyce** [comment]
An update on this - I think I have found the problem. Have systematically worked through my config commenting and uncommenting parts. The issue appears to happen as a result of using filters in state styles.

My current template config:

```  
  base: #this is used by most cards for base characteristics
    color: auto-no-temperature
    show_state: true
    state:
      - styles:
          card:
            - filter: opacity(50%)
          icon:
            - filter: grayscale(100%)
          label:
            - background-color: var(--card-background-color)
        value: 'off'
      - styles:
          card:
            - filter: opacity(25%)
          icon:
            - filter: grayscale(100%)
          label:
            - background-color: var(--card-background-color)
          state:
            - color: var(--card-background-color)
        value: 'unavailable'
```

If I remove the `filter` bits then the problem resolves - no more disappearing icons. As soon as I reintroduce state-dependent filters then I get disappearing icons.
