### ISSUE TITLE
Overflow does not work when the object is animated in Safari/mobile app

### ISSUE THREAD

**Issue by ai12989757** [custom-cards/button-card#480]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
On iOS14.5.1 Safari or the iOS HA Mobile App, Overflow does not work when the object is animated

**Version of the card**
Version: 3.4.2

**To Reproduce**
This is the configuration I used:
```yaml
      - type: 'custom:button-card'
        icon: 'mdi:home'
        aspect_ratio: 1/1
        extra_styles: |
          @keyframes ww {
              from {
                  -webkit-transform: rotate(0deg);
                  transform: rotate(0deg);
              }
              from {
                  -webkit-transform: rotate(360deg);
                  transform: rotate(360deg);
              }
          }
          @-webkit-keyframes ww {
              from {
                  -webkit-transform: rotate(0deg);
                  transform: rotate(0deg);
              }
              from {
                  -webkit-transform: rotate(360deg);
                  transform: rotate(360deg);
              }
          }
        custom_fields:
          test: |
            [[[
                return `<ha-icon
                icon="mdi:home"
                style="width: 240px; height: 240px; color: #1E88E5;">
                </ha-icon>`
            ]]]
        styles:
          card:
            - border-radius: 50%
          icon:
            - overflow: hidden
            - animation: ww 20s infinite linear
            - '-webkit-animation': ww 20s infinite linear
            - right: 80%
            - bottom: 20%
          custom_fields:
            test:
              - overflow: hidden
              - position: absolute
              - left: 70%
              - top: 50%
              - animation: ww 20s infinite linear
              - '-webkit-animation': ww 20s infinite linear

```

**Screenshots**
![Microsoft Edge](https://user-images.githubusercontent.com/49306315/119290704-ab8dd680-bc7f-11eb-8e1e-5e29dd444694.jpg)
![safri](https://user-images.githubusercontent.com/49306315/119290705-ad579a00-bc7f-11eb-8a5a-4aec9b5a761d.jpg)

**Expected behavior**
overflow should be work when the object is animated

**Desktop:**
 - Microsoft Edge 
 - 90.0.818.66

**Smartphone (please complete the following information):**
 -  iPhoneXs
 - iOS14.5.1
 - safari
