### ISSUE TITLE
Confirmation is opening more-info instead of executing button

### ISSUE THREAD

**Issue by cryptedx** [custom-cards/button-card#481]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
After pressing confirmation ok button more-info is opening. 

**Version of the card**
Version: 3.4.2

**To Reproduce**
This is the configuration I used:
```yaml
type: 'custom:button-card'
entity: scene.aufstehen
icon: 'hass:weather-sunset-up'
color_type: icon
color: orange
size: 48px
confirmation:
  text: '[[[ return ''Wollen sie diese Aktion sicher ausführen?'' ]]]'

```

**Screenshots**
![image](https://user-images.githubusercontent.com/20707078/119638763-41a83500-be17-11eb-9a87-bd837db70f5c.png)

![image](https://user-images.githubusercontent.com/20707078/119638798-4967d980-be17-11eb-9256-b8b158c49a6f.png)

![image](https://user-images.githubusercontent.com/20707078/119638831-51c01480-be17-11eb-8632-69480738058f.png)

**Expected behavior**
It should execute the scene and not open the more-info modal.

**Desktop (please complete the following information):**
 - Browser Chrome Version 90.0.4430.212 (x86_64)

**Comment by RomRider** [comment]
You should set the `action` and the `service` explicitely else it defaults to `more-info` for scenes.

**Comment by cryptedx** [comment]
Oh well it did work. Thank you very much!

**Comment by snakedm** [comment]
If I set my tap_action to this:
```
       confirmation:
          text: >-
            blablabla
        tap_action:
          service: button.press
          data: {}
          target:
            entity_id: button.test
```

dont work any more... why?
