### ISSUE TITLE
Styles options for units attribute

### ISSUE THREAD

**Issue by maxalbani** [custom-cards/button-card#483]
**Describe the solution you'd like**
It would be useful to have the styles options available for the **units attribute**.

```
styles:
  name:
    - xxx
    - xxx
  units:
    - xxx
    - xxx
```
Thanks!
Max
