### ISSUE TITLE
Custom cards not working in HA Version 6.0

### ISSUE THREAD

**Issue by Trackhappy** [custom-cards/button-card#484]
**Checklist**
- [X ] I updated the card to the latest version available
- [ X] I cleared the cache of my browser

**Describe the bug**
After  upgrading to Home Assistant core-2021.6.0, custom cards no longer work.
Possibly this issue:
https://developers.home-assistant.io/blog/2021/05/19/lit-2.0/

**Version of the card**
Version: button-card
v3.4.2
28476
750
53
Button Card by @RomRider

**To Reproduce**
This is the configuration I used:
```
cards:
  - type: horizontal-stack
    cards:
      - type: weather-forecast
        entity: weather.dougmanor
  - type: horizontal-stack
    cards:
      - type: 'custom:button-card'
        entity: binary_sensor.suesdoorstatus
        icon: 'mdi:garage'
        ccolor: 'rgb(255, 0, 0)'
        state:
          - value: '255'
            color: 'rgb(255, 0, 0)'
      - type: 'custom:button-card'
        entity: binary_sensor.dougsdoorstatus
        icon: 'mdi:garage'
        ccolor: 'rgb(255, 0, 0)'
        state:
          - value: '255'
            color: 'rgb(255, 0, 0)'
      - type: 'custom:button-card'
        entity: binary_sensor.innerdoorstatus
        icon: 'mdi:door'
        ccolor: 'rgb(255, 0, 0)'
        state:
          - value: '255'
            color: 'rgb(255, 0, 0)'
  - type: horizontal-stack
    cards:
      - type: 'custom:button-card'
        entity: switch.biowall
        icon: 'mdi:candle'
        ccolor: 'rgb(50, 128, 199)'
      - type: 'custom:button-card'
        entity: switch.stairwhitelights
        icon: 'mdi:candle'
        ccolor: 'rgb(50, 128, 199)'
      - type: 'custom:button-card'
        entity: switch.frontlights
        icon: 'mdi:candle'
        ccolor: 'rgb(50, 128, 199)'
  - type: horizontal-stack
    cards:
      - type: 'custom:button-card'
        entity: input_boolean.pump
        icon: 'mdi:pump'
        name: Hot Water
        ccolor: 'rgb(50, 128, 199)'
      - type: button
        tap_action:
          action: toggle
        entity: script.douggaragedoortoggle
        name: Open Doug's Door

```

**Screenshots**

**Expected behavior**
Buttons render normally

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version Version 77.0.3865.120 (Official Build) (64-bit)

**Additional context**
Update releases alerted that this may break.
