### ISSUE TITLE
Template on color has no effect?

### ISSUE THREAD

**Issue by mabahj** [custom-cards/button-card#485]
**Checklist**
- [X ] I updated the card to the latest version available
- [X ] I cleared the cache of my browser

**Describe the bug**
I am not able to use a template to change the card color. I think it is a bug, but I am not sure. If I'm doing it wrong, then I do apologize!

(Thank you again for a *great* add-on and all your work!!)

**Version of the card**
Version: 3.4.2

**To Reproduce**
This card is named "red", so I'd assume my template is correct, but the card (the color: part) not red:

  ```yaml
  type: 'custom:button-card'
  entity: sensor.load_1m
  color: |
    [[[
        return 'red';
    ]]]
  name: |
    [[[
        return 'red';
    ]]]
  ```

**Screenshots**
(I do not think it is applicable with a screenshot, it is a normal card that is not red. Please do correct me if I'm wrong.)

**Expected behavior**
I'd expect the color of the card (actually icon) to be red, like this code:
```yaml
type: 'custom:button-card'
entity: sensor.load_1m
color: red
name: |
  [[[
      return 'red';
  ]]]
```

**Desktop (please complete the following information):**
 - Vivaldi
 - Version 3.8.2259.40 (Stable channel) (64-bit)

**Smartphone (please complete the following information):**
N/A, but I did check on my iPhone with the Home Assistant app and it is not red there either.

**Additional context**

**Comment by mabahj** [comment]
It seems that color templates are maybe not supported: https://github.com/custom-cards/button-card#javascript-templates

**Comment by RomRider** [comment]
You can do that using `styles`:
```yaml
styles:
  icon:
    - color: '[[[ return "red"; ]]]'
```
