### ISSUE TITLE
State value 'unavailable' is unavailable

### ISSUE THREAD

**Issue by antisane** [custom-cards/button-card#487]
**Checklist**
- [x ] I updated the card to the latest version available
- [ x] I cleared the cache of my browser

**Describe the bug**
State values of 'on' and 'off' works as expected, but cannot use the state 'unavailable' in card setup.

**Version of the card**
Version:  3.4.2

**To Reproduce**
This is the configuration I used:
```
`type: 'custom:button-card'
tap_action:
  action: toggle
entity: switch.right_side_bed
icon: 'mdi:bed'
name: Right Side
hold_action:
  action: more-info
color_type: card
state:
  - value: 'on'
    color: maroon
    styles:
      name:
        - color: white
      icon:
        - color: white
  - value: 'off'
    styles:
      color: default
      name:
        - color: grey
      icon:
        - color: grey
  - value: 'unavailable'
    styles:
      color: black
      name:
        - color: black
      icon:
        - color: black

`

```

**Screenshots**

**Expected behavior**
I expect it to follow the rules I setup in the card...

**Desktop (please complete the following information):**
 - Chrome 
 - Version 91.0.4472.77 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy s8
 - OS: Android 9
 - Browser: HA Companion App, running under Fully Kiosk (both up to date)

**Additional context**
