### ISSUE TITLE
Add ability to set border attributes for a card

### ISSUE THREAD

**Issue by nickdevore** [custom-cards/button-card#489]
**Is your feature request related to a problem? Please describe.**
I would love to be able to set the border attributes of a card.  I think the source has it hard coded at 1px and solid, and with a color option

**Describe the solution you'd like**
Similar to setting the color of a card, in the styles attributes, be able to either set one or all of the border attributes:

```yaml
styles:
  card:
   - border-style: solid
   - border-color: red
   - border-width: 3px
```
**Describe alternatives you've considered**
As best I can tell, there are no alternatives for this

I'm more than happy to submit a pull request for this.  Would this be something you'd like to bring into the code base?
