### ISSUE TITLE
cover icon has wrong color

### ISSUE THREAD

**Issue by michalk-k** [custom-cards/button-card#493]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
If the entity is type of cover (class window) custom button card doesn't apply expected styles to icon.

What I found is:
1. common window manifests states on/off in dev tools, while for covers it is open/closed.
2. on the other hand, custom button card shows open/closed in both cases: windows and covers.
3. color of cover icon is currently always set to `var(--primary-text-color);`

**Version of the card**
Version: 3.4.2

**To Reproduce**
Here are two custom button cards with all defaults. Screenshot of this configuration is attached bellow. It's clearly seen that cover is not colored. Obviously 
```yaml
type: 'custom:button-card'
entity: cover.cube_roof_window
show_state: true
####
type: 'custom:button-card'
entity: binary_sensor.roof_window
show_state: true
```
And my cover declaration (mqtt)
```yaml
cover:
  - platform: mqtt
    name: "Cube Roof Window"
    device_class: "window"
    state_topic: "shellies/cube-window/roller/0"
    command_topic: "shellies/cube-window/roller/0/command"
    position_topic: "shellies/cube-window/roller/0/pos"
    set_position_topic: "shellies/cube-window/roller/0/command/pos"
    availability_topic: "shellies/cube-window/online"
    payload_available: "true"
    payload_not_available: "false"
    qos: 1
    retain: false
    payload_open: "open"
    payload_close: "close"
    payload_stop: "stop"
    position_open: 100
    position_closed: 0
    optimistic: false 
```

**Screenshots**
The image shows distinction between cover (entity on top) and window (bottom entity)
![obrazek](https://user-images.githubusercontent.com/7868445/122669309-018d6580-d1bd-11eb-8a9a-71e913cf851c.png)

**Expected behavior**
Colour of cover icon should has assigned values `var(--paper-item-icon-color)` or `var(--paper-item-icon-active-color)` respectively depending on its state. 
 
**Desktop (please complete the following information):**
 - Browser: all
 - Version: doesn't matter

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**
