### ISSUE TITLE
State Styles Override

### ISSUE THREAD

**Issue by LaBoss** [custom-cards/button-card#497]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
I can't overide state styles using a template

**Version of the card**
Version: 3.4.2

**To Reproduce**
Base Template
```yaml
  teste_btw:
    state:
    - value: 'on'
      styles:
        card:
          - background-color: blue
    - value: 'off'
      styles:
        card:
          - background-color: red
```
Parent Template
```yaml
  teste_brigh_btw:
    template: teste_btw
    state:
    - value: 'on'
      styles:
        card:
          - background-color: coral
```

**Expected behavior**
In the button with template  teste_brigh_btw, the background color changes to coral when the status is On

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 91.0.4472.124

**Comment by LaBoss** [comment]
Bad help reading 


Base Template
```yaml
  teste_btw:
    state:
    - value: 'on'
      id: on
      styles:
        card:
          - background-color: blue
    - value: 'off'
      id: off
      styles:
        card:
          - background-color: red
```
Parent Template
```yaml
  teste_brigh_btw:
    template: teste_btw
    state:
    - value: 'on'
      id: on
      styles:
        card:
          - background-color: coral
```
