### ISSUE TITLE
Call service not working with remote.send_command

### ISSUE THREAD

**Issue by ahmadyusuf** [custom-cards/button-card#499]
Trying to create a custom card to call the remote.send_command as below

type: custom:button-card
tap_action:
  action: call-service
  service: remote.send_command
  service_data:
    device: TV_LED
    command: power_on
  target:
    entity_id: remote.broadlink_remote
show_name: false
show_icon: true
icon: hass:power

However, I am getting the below error
Failed to call service remote/send_command. sequence item 0: expected str instance, Optional found

The exact same Yaml works if I change the card type to "button"

**Version of the card**
Version: v3.4.2

**To Reproduce**
This is the configuration I used:
```
type: custom:button-card
tap_action:
  action: call-service
  service: remote.send_command
  service_data:
    device: TV_LED
    command: power_on
  target:
    entity_id: remote.broadlink_remote
show_name: false
show_icon: true
icon: hass:power
```

**Expected behavior**
The button should not show an error when pressed and broadlink device should turn the device off

**Desktop (please complete the following information):**
 - Browser 
 - Version 91.0.4472.164 (Official Build) (64-bit)

**Additional context**
Stock home assistant button works perfectly for this, but I was to use the custom button as I want to add an entity_picture to the button which I can't do with the stock button
