### ISSUE TITLE
Service call fires when opening popup

### ISSUE THREAD

**Issue by matt8707** [custom-cards/button-card#507]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
tap action (hass.callService) executes when opening browser_mod popups

**Version of the card**
Version: 3.4.2

**To Reproduce**
```yaml
type: custom:button-card
name: test
tap_action:
  action: fire-dom-event
  browser_mod:
    command: popup
    title: popup
    card:
      type: custom:button-card
      name: test
      tap_action:
        chained: |
          [[[
            hass.callService('light', 'toggle', {
              entity_id: 'light.dator'
            });
          ]]]
```

**Screenshots**
none

**Expected behavior**
tap action shouldn't fire when opening a popup, tap action also doesn't work after that

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 92.0.4515.159

**Additional context**
none
