### ISSUE TITLE
Independent handling of template config files

### ISSUE THREAD

**Issue by bundabrg** [custom-cards/button-card#511]
**Is your feature request related to a problem? Please describe.**
When Lovelace is in `storage` mode as opposed to `yaml` you lose the ability to include an external file and instead need to enter it in directly to the raw configuration view.

This issue with this approach is that you will lose all comments and will clutter up the view with potentially huge amounts of data.

**Describe the solution you'd like**
I propose that instead of relying on `ll.config` that this component instead have the ability to parse in one or more configuration files itself and so the part added to the raw view (or top of the lovelace ui file if in `yaml` mode) is much smaller.

Example (added to top of the raw config):
```yaml
custom_button_card:
  templates:
    - include/file1.yaml
    - include/file2.yaml

views: { ... }
```
