### ISSUE TITLE
incorrect icon for device_class: switch

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/button-card#520]
**Checklist**
- [ ] I updated the card to the latest version available
- [ ] I cleared the cache of my browser

**Describe the bug**

A plain switch.tester, set with device_class switch via 
```
homeassistant:
  customize_domain:

    switch:
      device_class: switch
```

<img width="662" alt="Schermafbeelding 2021-11-09 om 16 40 48" src="https://user-images.githubusercontent.com/33354141/140955809-a08b249d-aff0-489f-bdae-2be90a0fa7d8.png">

wont show the mdi:toggle-switch  which is now set as per 2021.11.2, https://github.com/home-assistant/frontend/releases/tag/20211108.0 but still shows the mdi:flash
specifically see: https://github.com/home-assistant/frontend/pull/10475

**Version of the card**
Version: 3.4.2

**To Reproduce**
This is the configuration I used:
```yaml
      - type: custom:button-card
        template:
          - button_switch
        entity: switch.tester
        name: Tester
```

**Screenshots**

<img width="101" alt="Schermafbeelding 2021-11-09 om 16 28 30" src="https://user-images.githubusercontent.com/33354141/140954077-3bdcb595-6ce6-412c-9b63-74aacabc5de7.png">
 while an entity in an entities card does show the correct icon:

<img width="332" alt="Schermafbeelding 2021-11-09 om 16 28 53" src="https://user-images.githubusercontent.com/33354141/140954184-14f82bf7-ffde-4316-a71c-0fa72d783f19.png">

used button template only looks at formatting, not the icon:

<img width="96" alt="Schermafbeelding 2021-11-09 om 16 39 04" src="https://user-images.githubusercontent.com/33354141/140955535-ff6c9ceb-a45c-4b0b-baad-abc5625d0401.png">

**Expected behavior**

**Desktop (please complete the following information):**
 - Browser Safari or Chrome
 - Version Versie 15.1 (17612.2.9.1.20) / Versie 95.0.4638.69 (Officiële build) (x86_64)

**Smartphone (please complete the following information):**

**Additional context**
