### ISSUE TITLE
javascript templates in nested cards resolve most top card's objects

### ISSUE THREAD

**Issue by michalk-k** [custom-cards/button-card#521]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser

**Describe the bug**
Someone on forum said it's wanted behavior. Thus I could have created an FR. 
But because the behavior described below is not noted in documentation I decided to file it as a bug. Feel free to change it to FR if you want.

Javascript `entity` object refers to entity assigned to most top card. Thus there is no way to reference entity assigned to embedded custom button card in its javascript templates.

I haven't tested `this` object as well as other javascript template attributes. But it might manifest the same issue.

**Version of the card**
Version: 3.4.2

**How to reproduce**
Let's consider following nested cards, assuming there is `window` custom_field available.
Note, content of name attribute is overridden with entity friendly name just for presentation purposes, to show the behavior. 

```
type: custom:button-card
entity: binary_sensor.sensor1
show_name: true
custom_fields:
  window:
    card:
      type: custom:button-card
      show_name: true
      entity: binary_sensor.sensor2
      name: |
        [[[ return (entity.attributes.friendly_name) ]]]
```
The example will render main card with name of sensor1, and embeded sub-card with name of sensor1 (again)

**Expected behavior**
I would expect that javascript object entity will return the entity assigned to current object.
In case of example presented above, I would expect that 'entity.attributes.friendly_name' will return name of sensor2. 

Instead the object of most top card is resolved. 
In such case I would appreciate any other way to target attributes and objects of current card (hence mentioned FR as possible solution). Maybe some new object referencing current card attributes to maintain backward compatibility or so.

If already existing objects behavior will remain unchanged as of developer decision, please update documentation stating clearly, that `entity` object (and maybe others) refers to the entity assigned in the most parent card.

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All

**Additional context**
N/A
