### ISSUE TITLE
Cannot call input_datetime.set_datetime service

### ISSUE THREAD

**Issue by jtsvba** [custom-cards/button-card#523]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
I am trying to call the input_datetime.set_datetime service from a custom button and set the assigned entity (an input datetime helper) to today's date, but whenever I press the button it states: 
**Invalid service data for input_datetime.set_datetime: Could not parse date for dictionary value @ data['date']**
I have tried several combinations, e.g. by adding 'data' and not just 'date', but I can't seem to get it to work. 

**Version of the card**
Version: 3.4.2

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:button-card
entity: input_datetime.custom_date
name: Date
icon: mdi:washing-machine
show_state: true
styles:
  grid:
    - grid-template-areas: '"i" "n" "s"'
    - grid-template-columns: 1fr
    - grid-template-rows: 1fr min-content min-content
  img_cell:
    - align-self: start
    - text-align: start
  name:
    - justify-self: start
    - padding-left: 10px
    - font-weight: bold
  state:
    - justify-self: start
    - padding-left: 10px
tap_action:
  action: call-service
  service: input_datetime.set_datetime
  service_data:
    entity_id: entity
    date: '{{ (as_timestamp(now()) | timestamp_custom("%Y-%m-%d", true)) }}'

```

**Expected behavior**
Set input helper date to today's date.
