### ISSUE TITLE
Unable to get the Camera Stream working 

### ISSUE THREAD

**Issue by MiAutomations** [custom-cards/button-card#524]
Hello 

I'm not able to load or view the stream in card, I need to click in the card in order to get the image from the camera 

**Configuartion.yaml** 

stream:

**Card configuration:** 

type: custom:button-card
camera_image: camera.reolink
show_live_stream: true

Can you please help me in order to fix this ?

Thank you

**Comment by RomRider** [comment]
That is not the right configuration.
Please use:
```yaml
type: custom:button-card
entity: camera.reolink
show_live_stream: true
show_entity_picture: true # might or might not be required, I don't remember :)
```
