### ISSUE TITLE
Bottom border cut off

### ISSUE THREAD

**Issue by backslashV** [custom-cards/button-card#525]
Hi,
I am not sure this is a bug or not, but the bottom border of my card is not showing:

My config:
```
cards:
  - type: custom:button-card
    entity: switch.kitchen_up
    show_name: false
    size: 20%
    hold_action:
      action: more-info
    styles:
      icon:
        - border: solid 3px var(--primary-color)
          border-radius: 5px;
    style: |
      ha-card {
        background-color: var(--primary-background-color);
        border-radius: 15px;
        margin: 10px;
      }
  - type: custom:button-card
    entity: switch.kitchen_down
    show_name: false
    size: 20%
    hold_action:
      action: more-info
    styles:
      icon:
        - border: solid 3px var(--primary-color)
          border-radius: 5px;
    style: |
      ha-card {
        background-color: var(--primary-background-color);
        border-radius: 15px;
        margin: 10px;
      }
title: Kitchen
type: custom:vertical-stack-in-card
```

![image](https://user-images.githubusercontent.com/8752221/143967627-78eed85f-3d59-42be-bb79-453d72127cfe.png)

**Comment by backslashV** [comment]
anyone?

**Comment by chenzomo** [comment]
> anyone?

This has been driving me crazy too!!! Still not resolved.  Hopefully soon...PLEASE!!!!

**Comment by RomRider** [comment]
That is probably generated by vertical-stack-in-card. Nothing I can do here, sorry.

**Comment by backslashV** [comment]
> That is probably generated by vertical-stack-in-card or maybe the margin that you change with card-mod. Nothing I can do here, sorry.

No, the custom button card alone also displays incorrectly. You can try it yourself..

**Comment by dcapslock** [comment]
This can be addressed using the following style(s), setting `- overflow: visible` to `img_cell` and then if wished, add some padding to the card to compensate.

```yaml
type: custom:button-card
entity: switch.bed_switch
show_name: false
size: 20%
hold_action:
  action: more-info
styles:
  card:
    - padding-bottom: 20px
  img_cell:
    - overflow: visible
  icon:
    - border: solid 3px var(--primary-color)
      border-radius: 5px;

 ```

<img width="371" height="121" alt="Image" src="https://github.com/user-attachments/assets/11ffee1f-a1ef-4803-a646-912fd1544e63" />
