### ISSUE TITLE
call-service syntax doesn't allow for services that don't need entity or entity_id

### ISSUE THREAD

**Issue by scyto** [custom-cards/button-card#527]
**Checklist**
- [ X] I updated the card to the latest version available
- [ X] I cleared the cache of my browser

**Describe the bug**
when using call service can't use same service call syntax available in hass.
For example I can't use this syntax ion the card
```
service: media_player.toggle
data: {}
target:
  device_id: 40eeb2b86e2981818c4c928dc211cbe0
```
this is the syntax created by HASS itself
![image](https://user-images.githubusercontent.com/11369180/145133807-db7d13f8-9b2e-4797-a90f-ee5224b04265.png)

**Version of the card**
Version: 3.4.2

**To Reproduce**
This is the configuration I used:
```
type: custom:button-card
entity: media_player.denon
show_state: true
show_name: true
show_label: true
tap_action:
  action: call-service
  service: media_player.toggle
  service_data:
    entity_id: media_player.denon
```
the one above i expected to toggle power, but it juts brings up second screen of info

so I tried this (because removing the entity_id fails)
```
type: custom:button-card
entity: media_player.denon
show_state: true
show_name: true
show_label: true
tap_action:
  action: call-service
  service: media_player.toggle
  service_data:
    entity_id: media_player.denon
    target:
     device_id: 40eeb2b86e2981818c4c928dc211cbe0
```
i also tried other variations.
all i want is a simple button to toggle media player state

**Screenshots**

**Expected behavior**

**Desktop (please complete the following information):**
 - Browser [edge]
 - Version [Version 96.0.1054.43 (Official build) (64-bit)]

**Additional context**

**Comment by RomRider** [comment]
What you wrote below is correct. If it's not working, it might be something else.
```yaml
type: custom:button-card
entity: media_player.denon
show_state: true
show_name: true
show_label: true
tap_action:
  action: call-service
  service: media_player.toggle
  service_data:
    entity_id: media_player.denon
```
