### ISSUE TITLE
Question: how to set colour based on light brightness

### ISSUE THREAD

**Issue by jchhenderson** [custom-cards/button-card#528]
Hi,

I have a button that I want to be "background" colour" when off and "yellow" when at 30% (which is the tap_action of this button).

...I know this isn't a bug, but I am not sure where I can post a question like this.

Below is the best I have got and I know it is wrong.  Can anyone advise"

```
          - type: 'custom:button-card'
            entity: light.hallway
            color: auto-no-temperature
            color_type: card
            state:
              - value: "off"
                color: var(--paper-item-icon-color)
              - value: {{state_attr('blight.hallway','brightness_pct')}}
                operator: "="
                value: 30
                color: yellow
            styles:
              card:
                - height: 100px
            name: "Low"
            tap_action:
              action: call-service
              service: light.turn_on
              service_data:
                entity_id: light.hallway
                brightness_pct: 30
```

**Comment by jchhenderson** [comment]
OK, realised that II didn't need the "off" at all...
```
- type: 'custom:button-card'
  entity: light.hallway
  color: auto-no-temperature
  color_type: card
  state:
    #- value: "off"
    #  color: grey
    - value: "on" #{{state_attr('blight.hallway','brightness_pct')}}""
      #operator: "="
      #value: 30
      color: yellow
  styles:
    card:
      - height: 100px
  name: "Low"
  tap_action:
    action: call-service
    service: light.turn_on
    service_data:
      entity_id: light.hallway
      brightness_pct: 30
```

**Comment by jchhenderson** [comment]
...and this is the closest I have gotten for the value:

`- value: state_attr('light.hallway','brightness_pct') == 30`

**Comment by RomRider** [comment]
This card uses javascript templates, not jinja. Please read the documentation further. You can ask all the questions on the home assistant forum also, on the [thread dedicated to button-card](https://community.home-assistant.io/t/lovelace-button-card).

For what you want to achieve:
```yaml
- type: 'custom:button-card'
  entity: light.hallway
  color: auto-no-temperature
  color_type: card
  state:
    - value: "[[[ return states['light.hallway'].attributes.brightness_pct >= 30 ]]]"
      operator: template
      color: yellow
  styles:
    card:
      - height: 100px
  name: "Low"
  tap_action:
    action: call-service
    service: light.turn_on
    service_data:
      entity_id: light.hallway
      brightness_pct: 30
```

**Comment by jchhenderson** [comment]
Hi @RomRider 

Thanks for your reply.

I did work it out eventually and I swear I posted a "ion use anyone else needs the answer" post, but it clearly did not go through.

My version was this:
```
- type: 'custom:button-card'
  entity: light.hallway
  color: auto
  color_type: card
  state:
    - operator: template
      value: >
        [[[
          return states['light.hallway'].attributes
          && (states['light.hallway'].attributes.brightness+pct != 30)
        ]]]
      color: var(--card-background-color)
  styles:
    card:
      - height: 100px
  name: "Low"
  tap_action:
    action: call-service
    service: light.turn_on
    service_data:
      entity_id: light.hallway
      brightness_pct: 30
  entity: light.hallway
```

I like your version better though so will change accordingly.  I dod read the docs - several times - but I find these things quite hard to understand.

Thanks again., though!
