### ISSUE TITLE
Problem with Home Assistant Cast to Nest Hub

### ISSUE THREAD

**Issue by rubenni** [custom-cards/button-card#530]
**Checklist**
- [x ] I updated the card to the latest version available
- [x ] I cleared the cache of my browser

**Describe the bug**
I'm trying to show a picture with SVG extension on my Nest Hub using Home Assistant cast but that doesn't seem to work. Although it works in the normal webpage on PC. Showing a normal JPG file is posibble on the Nest Hub. With the regular picture card I'm able to show the SVG file. 

**Version of the card**
Version: v3.4.2

**To Reproduce**
This is the configuration I used:
```
entity_picture: /local/animated_icons/cloudy.svg
styles:
  entity_picture:
    - margin-left: 5%
    - width: 50%
```

**Screenshots**
![image](https://user-images.githubusercontent.com/47385336/145987234-9d393b09-1730-41c2-b676-090e3619f913.png)

**Expected behavior**
I expect that the SVG file shows up like on the webpage on PC.

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version 96.0.4664.110

**Smartphone (please complete the following information):**
/

**Additional context**
/
