### ISSUE TITLE
Custom card with few entity atributes

### ISSUE THREAD

**Issue by kuduacz** [custom-cards/button-card#533]
Hi there. 
I wont to make custom card for my humidifier.
my humidifier has two states on/off and few atrributes like mode.
Mode attribute is High and Silent.
And now i wont to make my icon to rotate slow (3s linear) when attribute is "Silent" and faster (1s linear) when mode is "High" and stop rotating when humidifier state is off. 
How can i make it?

**Comment by dcapslock** [comment]
You can use `state` style on `icon`. The rotating animation s defined in button-cards styles, and uses a 2s duration is the state style config of `spin: true` is given.

e.g.

```yaml
...
state:
  - value: high
    styles:
      icon:
        - animation: rotating 2s linear infinite
        - -webkit-animation: rotating 2s linear infinite;
        - -moz-animation: rotating 2s linear infinite;
        - -ms-animation: rotating 2s linear infinite;
        - -o-animation: rotating 2s linear infinite;
        - animation: rotating 2s linear infinite;
   - value: silent
    styles:
      icon:
        - animation: rotating 10s linear infinite
        - -webkit-animation: rotating 10s linear infinite;
        - -moz-animation: rotating 10s linear infinite;
        - -ms-animation: rotating 10s linear infinite;
        - -o-animation: rotating 10s linear infinite;
        - animation: rotating 10s linear infinite;
```
