### ISSUE TITLE
variables.tap_action

### ISSUE THREAD

**Issue by pex81** [custom-cards/button-card#534]
**Is your feature request related to a problem? Please describe.**

Is it possible to use the variables for the tap_action in conjunction with browser_mod? as in the example

```
button_card_template:

etc...
  tap_action:
    action: fire-dom-event
    browser_mod:
      command: popup
      title: '[[[ return entity.attributes.friendly_name ]]]'
      style:
        !include '/config/lovelace-minimalist/minimalist-templates/popup-template.yaml'
      card:
        !include '[[[ return variables.tap_action_path ]]]'
```
```
- type: custom:button-card
  template: my_template
  entity: my_entity
  variables:
    tap_action_path: '/config/lovelace-minimalist/blablabla.....'

```

**Describe the solution you'd like**

I could not find a solution, I am getting error 2 as file not found

**Describe alternatives you've considered**

**Additional context**
