### ISSUE TITLE
Custombutton card only works for a few hours then fails...

### ISSUE THREAD

**Issue by knight-yyz** [custom-cards/button-card#538]
**Checklist**
- [X ] I updated the card to the latest version available
- [ X] I cleared the cache of my browser

**Describe the bug**
I have a custom button card for a Tuya switch which turns on a fan.  The card works for a few random hours then fails.  When it fails the fan will turn on, but neither state nor color change.  The card fails after the first button press and creates an error

**Version of the card**
Version: 

**To Reproduce**
This is the configuration I used:
```
type: custom:button-card
tap_action:
  action: call-service
  service: switch.toggle
  service_data:
    entity_id: switch.smart_switch_switch_1
icon: mdi:fan
show_state: true
state:
  - value: 'on'
    spin: true
    styles:
      icon:
        - color: green
  - value: 'off'
    styles:
      icon:
        - color: red
entity: switch.smart_switch_switch_1
name: Bedroom Fan
```

**Screenshots**

**Expected behavior**
Click the button the fan toggles on, the icon spins and color is green.  Hit the button again, the switch toggles to off and the icon stops spinning and turns red. 

**Desktop (please complete the following information):**
 
 - Brave is up to date
Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)
 - Chrome is up to date
  -Version 96.0.4664.110 (Official Build) (64-bit) Chrome 
 -

**Smartphone (please complete the following information):**
 - Device: [Samsung FE 20]
 - Browser [Brave]
 - Version [ ]

**Additional context**

This is the error which pops up after a certain amount of time
Logger: frontend.js.latest.202112200
Source: components/system_log/__init__.py:189
First occurred: 10:17:41 AM (2 occurrences)
Last logged: 10:33:05 AM

https://xxxxxxxxxxxx.duckdns.org:8123/frontend_latest/a4a8710a.js:2:308 Uncaught TypeError: Cannot convert undefined or null to object
