### ISSUE TITLE
State template to replace state

### ISSUE THREAD

**Issue by michalk-k** [custom-cards/button-card#539]
**Is your feature request related to a problem? Please describe.**
My initial motivation was to replace "unavailable" provided by entity with "N/A" string which is just shorter.

I though I can use state templates. State templates allows to modify a lot of card elements including state color.  What is missing is affecting value of displayed state.

**Describe the solution you'd like**
Add "state" feature to state templates https://github.com/custom-cards/button-card#State.
State could be modified the same way as other attributes,  like label or name.

It has all benefits against alternative described below.

**Describe alternatives you've considered**
I know I can achieve that by using label instead of the state but it brings several inconveniences:
- needs of changing css grid definition and related stylying to display label section instead of state section
- creating label content based on the entity assigned to the card doesn't work for nested custom button cards (impossible to use entity object since it refers to most parent card entity)

**Additional context**
![IMG_2700](https://user-images.githubusercontent.com/7868445/147701348-a36b1453-0aa3-4ca0-a6ee-65a7b0ca71bd.jpg)
![IMG_2702](https://user-images.githubusercontent.com/7868445/147701350-86344c6e-d3f3-4d13-a4ac-d80dc38f8079.jpg)

**Comment by RomRider** [comment]
This is possible with `state_display`already

**Comment by michalk-k** [comment]
Yes indeed. But still with limitation, that entity must be explicitely referenced by name (otherwise it doesn't work for nested custom button cards) see [this ](https://github.com/custom-cards/button-card/issues/389) issue.
This is why using state template would be nicer/easier when using button templates (I know I can exploit template variables for that but it's rather ugly workaround raher than solution)

**Comment by RomRider** [comment]
No, `entity.state` contains the state of the entity associated to the button. No need to reference it by name.

**Comment by michalk-k** [comment]
...unless the card I want to use entity.state in template of, is embeded into another card.
Then entity.state references entity assigned to most parent card, instead of the current card. You confirmed this behaviour in mentioned issue #389.

**Comment by RomRider** [comment]
For that, the solution is in this [comment](https://github.com/custom-cards/button-card/issues/389#issuecomment-717125073)

**Comment by michalk-k** [comment]
Yes I know this workaround.
Still think extending state templating with this missing bit would be nice and helpful.

thank you

**Comment by RomRider** [comment]
I won't make an exception only for state, sorry.

**Comment by michalk-k** [comment]
> I won't make an exception only for state, sorry.
What exception do you mean?
The state template provides option to set content of label and name.  It allows to setup styles of all card elements including state.
It actually makes the exception not allowing to set displayed state content.

**Comment by RomRider** [comment]
That is with `state_display` and it works similarly to `label` and `name`. I don't know what you want more.

**Comment by michalk-k** [comment]
> That is with `state_display` and it works similarly to `label` and `name`. I don't know what you want more.

The point is, that state template provides operators and values to compare to the current state of assigned entity. It's the way how things on card can be manipulated without need of referencing exact entity name.

All other options, incl state_display requires to knowing the name of entity. I would like to use it like this:
```
card:
  type: custom:button-card
  entity: sensor.livingroom_temperature
  state:
    - operator: '=='
	  value: unavailable
	  state: 'N/A'
	  styles:
	    state:
		  - color: red
	    icon:
		  - color: red
```

**Comment by RomRider** [comment]
Ok, `state_display` is not available to override in the `state` array. I'll add this. But you can always do this instead:
```
button_card_templates:  
  err_handling:
    state_display: '[[[ return entity.state === 'unavailable' ? 'N/A' : undefined ]]]'
    state:
      - operator: '=='
        value: unavailable
        state: 'N/A'
        styles:
          state:
            - color: red
          icon:
            - color: red	
card:
  type: custom:button-card
  template: err_handling
  entity: sensor.livingroom_temperature
```
