### ISSUE TITLE
Numeric states

### ISSUE THREAD

**Issue by mlevit** [custom-cards/button-card#54]
Hey,

I would love to see the states accept numeric values and operators (less/greater than etc).

I want to use this for temperature sensors and change the colour of the card based on how hot it is.

**Comment by ammmze** [comment]
This seems feasible. AFAIK we can't use the home assistant jinja templates though, so we'd probably be best to have a defined set of parameters to generate the conditional. For example...

```yaml
- type: custom:button-card
  icon: mdi:thermometer
  entity: sensor.family_room_thermostat_temperature
  color_type: card
  state:
    - # state % 2 make it orange (basically even number temperatures would be orange)
      value: 2
      operator: "%"
      expect: 0
      color: orange
    - # state == 60 make it green
      value: 60
      operator: "="
      color: green
    - # state > 60 make it red
      value: 60
      operator: ">"
      color: red
    - # state < 60 make it blue
      value: 60
      operator: "<"
      color: blue
```

Not sure what operators we would want in there, but the gist is we would add a couple new parameters to the state objects...

| parameter | default | description |
| --- | --- | --- |
| `operator` | `=` | Should be one of `=`, `<`, `>`, `*`, `/`, `%` |
| `expect` | `true` | What the expected result of the conditional should be in order to consider this state as active |

And in the case where you may have overlapping states. For example in the case above, the first state overlaps all the ones below, we would probably take the first matching state.

Thoughts?
