### ISSUE TITLE
Help working around an HA issue with pet tracking button

### ISSUE THREAD

**Issue by flyize** [custom-cards/button-card#540]
I'm using a button-card to show the state of our pets as inside/outside. Along with that I've enabled 'show_last_changed' to show when they last came in/out. The problem is that on a reboot that 'last_changed' gets reset. Based on another suggestion, I was going to try to just capture the 'since' attribute into an input variable and display that in this button.

Is that the best way? If so, how would I show the value of another entity in this button (I assume that I'd use a label)?

**Comment by RomRider** [comment]
That's the right approach. You can use the label if you don't use it for anything else or define your own custom field

**Comment by flyize** [comment]
How do I display the value of a different entity in a label?

**Comment by RomRider** [comment]
With a template, for eg: `[[[ return states["sensor.my_sensor"].state ]]]

**Comment by flyize** [comment]
I must have literally figured it out while you were typing your reply. Thank you!

**Comment by flyize** [comment]
Okay, one more question. How would I use relative time here? As an example, I have this:

`[[[ return states['binary_sensor.katniss'].last_changed ]]]`

But this apparently isn't correct:

`[[[ return relative_time(states['binary_sensor.katniss'].last_changed) ]]]`

**Comment by RomRider** [comment]
For last changed, you can use `show_last_changed: true` but this will be for the main entity of the button.

If you want for another entity, best way is to embed a button-card in a custom field and assign that other entity to it.

**Comment by flyize** [comment]
So I'm having a terrible time trying to figure out how to properly get this into a custom field. Any chance you could lend a hand again? Here's the final working template that I've settled on from Dev Tools:

`{{ relative_time(strptime(state_attr('binary_sensor.katniss', 'since'), '%Y-%m-%dT%H:%M:%S%z')) }}`

I've gone over and over the examples, and I just can't figure it out.

**Comment by flyize** [comment]
And if it helps, here's the entire button

```
type: custom:button-card
entity: binary_sensor.katniss
icon: hass:cat
color: var(--paper-item-icon-color)
show_state: true
state:
  - value: 'off'
    color: var(--disabled-text-color)
hold_action:
  action: call-service
  service: input_boolean.toggle
  service_data:
    entity_id: input_boolean.katniss_state
card_mod:
  style: |
    ha-card {
      border-radius: 25px;
    }
styles:
  name:
    - font-weight: bold
  label:
    - font-size: 12px
```

**Comment by RomRider** [comment]
Given the entity of your button, you can just use `show_last_changed: true`

**Comment by flyize** [comment]
Last changed is reset upon restart though.

**Comment by RomRider** [comment]
Nothing I can do about that, this is how home assistant works.

**Comment by flyize** [comment]
That's why I'm hoping to use this.

`{{ relative_time(strptime(state_attr('binary_sensor.katniss', 'since'), '%Y-%m-%dT%H:%M:%S%z')) }}`

**Comment by flyize** [comment]
Apologies. Still banging my head om this one. Any ideas?

**Comment by schmjop** [comment]
Hi @flyize,
I am currently struggling with that as well. Did you ever figure it out?
Thanks!

**Comment by flyize** [comment]
Yes, I created a sensor that tracks the 'since' attribute.

```
  - trigger:
      - platform: time_pattern
        minutes: "*"
      - platform: state
        entity_id:
          - binary_sensor.katniss
    sensor:
      - name: katniss_since
        state: >
          {{ relative_time(as_datetime(state_attr('binary_sensor.katniss', 'since'))) }}
```
