### ISSUE TITLE
Pass a variable as an object to the button-card

### ISSUE THREAD

**Issue by bavo** [custom-cards/button-card#544]
**Is your feature request related to a problem? Please describe.**
I'm making a custom button-card template with tap_actions defined inside it.
I want to make these tap_actions accessible as variables but it is quite tricky. 
A more simple solution would be if the variables could contain objects and the button card the process these objects.

An example will hopefully make things more clear:

I have a template: 
```yaml
nested_template:
  tap_action:
    action: >
      [[[ if (variables?.tap_action?.action) return variables.tap_action.action; else return 'none'; ]]]
    entity: "[[[ return variables.tap_action.entity; ]]]"
    navigation_path: "[[[ return variables.tap_action.navigation_path; ]]]"
    url_path: "[[[ return variables.tap_action.url_path; ]]]"
    service: "[[[ return variables.tap_action.service; ]]]"
    service_data: "[[[ return variables.tap_action.service_data; ]]]"
....
  the rest of the configuration
```
And you would use the card like this: 
```yaml
- type: custom:button-card
  template:
    - some_other_template_which_uses_nested_template
  variables:
      tap_action: 
        action: toggle
```

**Describe the solution you'd like**
It would be great if I could just implement the nested card as follows:
```yaml
nested_template:
  tap_action: "[[[ return variables.tap_action ]]]"
....
  the rest of the configuration
```

**Describe alternatives you've considered**
The solution posted above works but is really cumbersome

**Additional context**
The error thrown when trying the solution is:
```
TypeError: 0 is read-only
```
