### ISSUE TITLE
layout: hinders state styling

### ISSUE THREAD

**Issue by Rover2** [custom-cards/button-card#547]
I stumbled upon the following issue with this quite basic button:
```
type: vertical-stack
cards:
  - type: horizontal-stack
    cards:
      - type: custom:button-card
        entity: sensor.hmip_dg_t2_temp
        icon: mdi:sleep
        show_state: true
        name: Attic
        layout: icon_name_state
        styles:
          state:
            - font-size: 0.65em
            - color: >-
                [[[ return states['climate.hmip_dg_r2'].state == 'auto' ? 'green' : 'orange'; ]]]
```
which results in this button without the desired styling of the state:
![grafik](https://user-images.githubusercontent.com/14306223/151950311-7fa85675-fe7f-4c76-806c-6249a2fc938c.png)

If I comment ```#        layout: icon_name_state```, the styling appears:
![grafik](https://user-images.githubusercontent.com/14306223/151950906-1d86147f-495f-4c3a-9b9d-29ba7068355c.png)

Is this a bug or rather desired behaviour?
And in case of the latter: how to circumvent it?

Interesting: with ``` layout: icon_state``` the styling gets applied:
![grafik](https://user-images.githubusercontent.com/14306223/151954512-eee2a6fc-3ab0-44ec-9896-3695533a0b67.png)

**Comment by dcapslock** [comment]
This is actually by design. 

From doco.

> icon_name_state: Everything is aligned horizontally, name and state are __concatenated__, label is centered below
> name_state: Icon sits on top of name and state __concatenated__ on one line, label below

The key here is that with these two layouts, the second element is `name` as a concatenated `name: state`, and there is no separate `state`. So in this case you style `name`

If you want separate `icon`, `name`, `state` you can use grid with row "i n s". You can style `name` and `state` as you wish. Below I have justified `name` to right and `state` to left with some padding on left of state.

```yaml
type: custom:button-card
entity: sensor.dcd_browser_browser_height
icon: mdi:sleep
show_state: true
name: Attic
styles:
  grid:
    - grid-template-areas: "\"i n s\""
    - grid-template-columns: 1fr 1fr 1fr
  state:
    - justify-self: start
    - padding-left: 1em
    - font-size: 0.65em
    - color: >
        [[[ return states['sensor.dcd_browser_browser_height'].state >= 600 ?
        'green' : 'orange'; ]]]
  name:
    - justify-self: end
```

<img width="506" height="112" alt="Image" src="https://github.com/user-attachments/assets/07e71f3a-a387-45f0-a889-4364c2fd7135" />
