### ISSUE TITLE
Button card doesn't appear inside conditional card/layout-card

### ISSUE THREAD

**Issue by Spirituss** [custom-cards/button-card#548]
**Checklist**
- [*] I updated the card to the latest version available
- [*] I cleared the cache of my browser

**Describe the bug**
Button cards inside conditional card/layout-card/custom:stack-in-card often doesn't appear on the screen. The places where it should be are just clear. Sometimes after page hard refresh (shift-F5) it appears again but not always. Such symptoms started from HA 2021.12, earlier it works fine for more than a year. 

**Version of the card**
Version: 3.4.2

**To Reproduce**
This is the configuration I used:
lovelace yaml:
```
views: 
  - title: Octoprint
    icon: mdi:printer-3d
    panel: true 
    visible:
      - user: xxxxxx 
    cards:
      - type: custom:layout-card
        layout_type: vertical
        layout:
          width: 300
          max_cols: 2
        cards:  
          - type: conditional
            show_header_toggle: false
            conditions:
              - entity: switch.connection
                state: 'on'
            card:                
                type: custom:stack-in-card
                mode: vertical
                cards: 
                  - type: horizontal-stack
                     show_name: false   
                    cards:          
                      - type: custom:stack-in-card
                        mode: vertical
                        cards:                 
                          - type: custom:button-card
                            entity: sensor.printer_status
                            template: sensor  
                          - type: custom:button-card
                            entity: sensor.temperature_3dprinter
                            template: sensor_temp  
                      - type: custom:stack-in-card
                        mode: vertical
                        cards:    
.....
```

**Screenshots**
It works often like this:
![Screen Shot 2022-02-01 at 15 44 09](https://user-images.githubusercontent.com/47206760/151976177-c3fce389-d53e-45e5-91be-d22216bbef89.jpg)

**Expected behavior**
But should work like this:
<img width="433" alt="Снимок экрана 2022-02-01 в 15 44 39" src="https://user-images.githubusercontent.com/47206760/151976249-0ea0c6f7-46f2-42e4-ae46-5be88fa26c9b.png">

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Opera 
 - Version [e.g. 22] 83.0.4254.27

**Smartphone (please complete the following information):**

**Additional context**
