### ISSUE TITLE
Incorrect timezone when displaying time sensor via button-card

### ISSUE THREAD

**Issue by Spirituss** [custom-cards/button-card#549]
**Checklist**
- [*] I updated the card to the latest version available
- [*] I cleared the cache of my browser

**Describe the bug**
Button-card shows time sensor with UTC time zone while it uses another one. You can see correct timezone in the sensor card below.

**Version of the card**
Version: 3.4.2

**To Reproduce**
This is the configuration I used:
```
                          - name: Time
                            type: custom:button-card
                            color_type: icon
                            show_state: true
                            tap_action:
                              action: more-info
                            show_icon: false  
```

**Screenshots**
Upper circle:
![Screen Shot 2022-02-01 at 15 44 55](https://user-images.githubusercontent.com/47206760/151977328-37c2ddb9-fcda-439e-9f7e-330af4d4a145.jpg)

**Expected behavior**
Lower circle:
![Screen Shot 2022-02-01 at 15 44 55](https://user-images.githubusercontent.com/47206760/151977416-bcd18477-edd5-456b-b028-464cf389f51e.jpg)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Opera
 - Version [e.g. 22] 83.0.4254.27

**Smartphone (please complete the following information):**

**Additional context**
