### ISSUE TITLE
Icon color assignment not working with special states

### ISSUE THREAD

**Issue by nzneil22** [custom-cards/button-card#550]
**Checklist**
- [ v] I updated the card to the latest version available
- [ v] I cleared the cache of my browser

**Describe the bug**
I have a problem when using a group of covers. The possible state of the group is either "Open" or "Closed". State is not changing icon color as configured. The color assignment works by default (applies the colour according to theme)  if the state is a traditional "On" or "Off".

**Version of the card**
Version: 3.4.2

**To Reproduce**
This is the configuration I used:
```
type: custom:button-card
tap_action:
  action: navigate
  navigation_path: /overview-desktop/blinds
name: Blinds
entity: group.cover
show_state: true
styles:
  state:
    - font-size: 13px
    - color: gray
    - padding: 5px
  label:
    - padding: 5px
  icon:
    - height: 45px
    - padding: 7px
state:
  - value: Open
    color: rgb(255,0,0)



```

**Screenshots**
![image](https://user-images.githubusercontent.com/88832123/152137343-ba4c35e9-1f3a-40a4-affe-65a45e6ccc62.png)

**Expected behavior**
I would expect that if the group of covers say that someof them are open, the icon colour is to be updated as expected

**Desktop (please complete the following information):**
 - Browser [Chrome]
 - Version [Version 98.0.4758.82 (Official Build) (64-bit)]

**Smartphone (please complete the following information):**
 - Device: [Samsung S21 Ultra 5G]
 - OS: [Android 12 (One UI 4.0)]
 - Browser [Home Assistant App]
 - Version [2022.1.1-full]

**Additional context**
