### ISSUE TITLE
call-service media_player.volume_mute doesnt seem to work as tap_action

### ISSUE THREAD

**Issue by u8915055** [custom-cards/button-card#551]
**Checklist**
- [ x] I updated the card to the latest version available
- [x ] I cleared the cache of my browser

**Describe the bug**
I am trying to define buttons to control mute and volume up and down on a media_player entity.  I have the volume up and down working, but the mute does not seem to work.  I find that if i mute the source directly and then click my button , it will un-mute.. but if the source is playing and i hit the button, nothing happens, it does not mute.  I have tried using the service directly in the developer tools and that works fine.  Dont know what's going on here.

**Version of the card**
Version: 3.4.2

**To Reproduce**
This is the configuration I used:
```
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            entity: '[[[ return entity.entity_id; ]]]'
            icon: mdi:volume-mute
            tap_action:
              action: call-service
              service: media_player.volume_mute
              service_data:
                entity_id: entity
                is_volume_muted: >
                  [[[ return states[entity.entity_id].attributes.is_volume_muted === 'true' ? 'false' : 'true'; ]]]
            template: icon_only

          - type: custom:button-card
            entity: '[[[ return entity.entity_id; ]]]'
            icon: mdi:volume-minus
            tap_action:
              action: call-service
              service: media_player.volume_down
              service_data:
                entity_id: entity
            template: icon_only

          - type: custom:button-card
            entity: '[[[ return entity.entity_id; ]]]'
            icon: mdi:volume-plus
            tap_action:
              action: call-service
              service: media_player.volume_up
              service_data:
                entity_id: entity
            template: icon_only

```

**Screenshots**

**Expected behavior**
I expect that each time i click the button, the mute state of the media_player entity should effectively toggle.

**Desktop (please complete the following information):**
 - Browser : Chrome
 - Version : 97.0.4692.71

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Iphone 12
 - OS: [e.g. iOS8.1] 15.2.1
 - Browser [e.g. stock browser, safari] safari

**Additional context**
