### ISSUE TITLE
Trigger hold action after period of time

### ISSUE THREAD

**Issue by fabianluque** [custom-cards/button-card#555]
**Is your feature request related to a problem? Please describe.**
Currently I'm using this piece of YAML to trigger a popup using browser_mod:

```
   hold_action:
     repeat: 250
     haptic: heavy
     action: fire-dom-event
     browser_mod:
       command: popup 
```

Of course this triggers the popup multiple times but executes the action after 250ms.

Would it be possible to implement a feature where the hold action triggers right after the 250ms has passed just once. The current behavior for hold action is to trigger when you release the tap/click.
