### ISSUE TITLE
Math functions not getting expected sensor states in call-service

### ISSUE THREAD

**Issue by LastElf** [custom-cards/button-card#561]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
I'm trying to set up an automatic shutoff for my AC in increments, and my [AC system](https://www.home-assistant.io/integrations/advantage_air) handles this via a service call with a minutes parameter (Though I may want a helper variable because of system delays calling this, at least from what I'm seeing the dev tools). The service expects a minutes value between 0-720 and I'm using HA to increment up/down in 15 minute chunks using math.max/math.min to make sure I don't call out of bounds.

The -15 button works exactly as expected, it goes down in 15 minute increments and stops at 0. The +15 button goes from 0 to 15 on the first tap, then the second one goes from 15 to 720.

**Version of the card**
Version: 3.4.2

**To Reproduce**
This is the configuration I used:
```
    - type: custom:button-card
      entity: sensor.ac_time_to_off
      show_icon: false
      name: '-15'
      tap_action:
        action: call-service
        service: advantage_air.set_time_to
        service_data:
          entity_id: entity
          minutes: >-
            [[[ return Math.max(states['sensor.ac_time_to_off'].state - 15,0)
            ]]]
    - type: custom:button-card
      entity: sensor.ac_time_to_off
      show_icon: false
      name: '+15'
      tap_action:
        action: call-service
        service: advantage_air.set_time_to
        service_data:
          entity_id: entity
          minutes: >-
            [[[ return Math.min(states['sensor.ac_time_to_off'].state + 15,720)
            ]]]

```

**Expected behavior**
It's meant to increment up by 15 each time.

**Desktop (please complete the following information):**
 - Browser Brave 
 - Version 1.35.103 (Chromium 98.0.4758.102) 64bit

**Comment by RomRider** [comment]
I know this is quite old but in case you didn't figure it out... Try to do `Number(states['sensor.ac_time_to_off'].state)`. I'm pretty sure the state is stored as a string.

**Comment by LastElf** [comment]
I haven't tried again since I posted this. It's still happening in HA 2023.5 with whatever the latest supported Card-Mod is.

Just tested and confirmed that adding Number() breaks the service call.

**Comment by RomRider** [comment]
Can you show me the updated template wirh `Number()` and the state of the entity from the developer tools, please?

**Comment by LastElf** [comment]
Doesn't work:
```
      tap_action:
        action: call-service
        service: advantage_air.set_time_to
        service_data:
          entity_id: entity
          minutes: >-
            [[[ return Math.min(Number(states['sensor.ac_time_to_off'].state) + 15,720)
            ]]]
```

Works for the first but jumps from 15 to 720 on the second tap:
```
      tap_action:
        action: call-service
        service: advantage_air.set_time_to
        service_data:
          entity_id: entity
          minutes: >-
            [[[ return Math.min(states['sensor.ac_time_to_off'].state + 15,720)
            ]]]
```

![image](https://github.com/custom-cards/button-card/assets/6188342/7863368e-aeb5-4993-ab45-45bedac951e6)
