### ISSUE TITLE
Undesirable mouseup action when moving off custom_field card onto main card

### ISSUE THREAD

**Issue by ulic75** [custom-cards/button-card#568]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
Using the card layout specified below if the light is on and I mousedown on the slider then start sliding and the mouse wanders up over the "main" button-card area and I release the mouse, the entity is toggled off.

**Version of the card**
Versions: 
- button-card v3.4.1
- slider-entity-row v17.2.0

**To Reproduce**
This is the configuration I used:
```yaml
- type: custom:button-card
  entity: light.ceiling_lights
  styles:
    grid:
      - grid-template-area: "'i' 'n' 'slider'"
      - grid-template-columns: "1fr"
  custom_fields:
    slider:
      card:
        type: custom:slider-entity-row
        entity: light.ceiling_lights
```

**Expected behavior**
I expect that the brightness percentage will simply change, but instead the main area seems to register the mouseup event and triggers a toggle on the light.

**Desktop (please complete the following information):**
 - Browser: Firefox 98, Chrome 99

**Additional context**
Oddly it works as expected in Safari 13.1.2
