### ISSUE TITLE
Help with YAML Formatting for Multiple Lock Entities

### ISSUE THREAD

**Issue by kars85** [custom-cards/button-card#569]
I am using the Valetudo code referencing this card, but am struggling to adapt the lock: segment to allow two vacuums. For example, I would like to add a _vacuum.roborocks5_ to this section. My YAML skills are subpar, but I'm hoping someone here would be so kind to assist.

```
    lock:
      enabled: >-
        [[[return states['group.vacuum_rooms'].state !== 'on' ||
        states['vacuum.dreamez10pro'].state !== 'docked']]]
      exemptions: []
```
[Full Wiki Here](https://valetudo.cloud/pages/integrations/home-assistant-integration.html)
```
type: vertical-stack
cards:
  - type: custom:auto-entities
    card:
      type: entities
      state_color: true
      title: Rooms to Vacuum
    filter:
      include:
        - group: group.vacuum_rooms
      exclude: []
    show_empty: true
    sort:
      method: friendly_name
      reverse: false
      numeric: false
  - type: custom:button-card
    tap_action:
      action: call-service
      service: script.vacuum_clean_segments
      confirmation: true
      service_data: {}
      target: {}
    lock:
      enabled: >-
        [[[return states['group.vacuum_rooms'].state !== 'on' ||
        states['vacuum.dreamez10pro'].state !== 'docked']]]
      exemptions: []
    entity: script.vacuum_clean_segments
    name: Vacuum selected segments
    show_state: false
    show_icon: false


```
