### ISSUE TITLE
0.88.0 Changes

### ISSUE THREAD

**Issue by DavidFW1960** [custom-cards/button-card#57]
Please note the breaking change for custom cards from 0.88 release notes:
```
Note for Lovelace custom card developers: if you relied on the availability of <paper-button> in your code, you will have to update it to <mwc-button> to work like before.
```

I don't know if this is a straight substitution though??

**Comment by Fma965** [comment]
doesn't appear to be a straight swap

**Comment by DavidFW1960** [comment]
it's supposed to be according to balloob but it doesn't work

**Comment by IIIdefconIII** [comment]
Same issue here on 0.88.0 i got lots of card not working anymore

**Comment by ammmze** [comment]
You can get them to at least load by changing the [first line](https://github.com/kuuji/button-card/blob/9dd6b14150832b20a116895909d1a2b0806afeb6/button-card.js#L1)...
* From `var LitElement = LitElement || Object.getPrototypeOf(customElements.get("hui-error-entity-row"));`
* To `var LitElement = LitElement || Object.getPrototypeOf(customElements.get("hui-generic-entity-row"));`

However, all my icons all smaller now :\

![home assistant 2019-02-20 20-29-53](https://user-images.githubusercontent.com/203336/53141701-561d6900-354e-11e9-83b6-a55c8654512b.png)

**Comment by ammmze** [comment]
And then switching all instances of `paper-button` for `mwc-button` tweaks it a bit more, but still is messed up. So looks like we'll probably need some additional CSS tweaking.
![home assistant 2019-02-20 20-33-13](https://user-images.githubusercontent.com/203336/53141844-efe51600-354e-11e9-97fe-17d32af52f81.png)

**Comment by ammmze** [comment]
Looks like `mwc-button` has a fixed height :\

https://github.com/material-components/material-components-web-components/issues/81

I wish they would give more explanation on the switch from `paper-button` to `mwc-button`. Seems like the `paper-button` still more/less works. Is it deprecated? 🤷‍♂️

**Comment by ammmze** [comment]
So I went back to using the `paper-button` and then made some style tweaks. I think I've got it more/less back to what it used to look like...
![home assistant 2019-02-20 21-16-26](https://user-images.githubusercontent.com/203336/53143352-d34bdc80-3554-11e9-9176-542cdcd653d0.png)

**Comment by DavidFW1960** [comment]
Yes I did the same exact thing... Did some style tweaks... but have a look at it on a mobile and it's horrible....

**Comment by ammmze** [comment]
Mine looks the same on mobile as desktop. Running Chrome on Android 9. 

https://github.com/ammmze/button-card/blob/ha-0.88/button-card.js

**Comment by ammmze** [comment]
Also just noting to create the link here, but there is currently an open PR #60 for this issue

**Comment by DavidFW1960** [comment]
Yeah aware of the PR.
Can you share the css/styling you are using? and you're using paper-button still right?

**Comment by ammmze** [comment]
Yea...still using `paper-button`. This is the version I am using successfully with 0.88 ... https://github.com/ammmze/button-card/blob/ha-0.88/button-card.js

**Comment by ammmze** [comment]
Hmm...but looks like the styles don't work for Firefox. I'll have to look at that more later

**Comment by DavidFW1960** [comment]
Yeah.. but can you share your style tweaks? (I’m using chrome anyway... but they should work with FF... pretty generic I would have thought)

I’m using this and it’s ‘ok’ but sucks on mobile.....

```
                size: 60px
                style:
                  - align-items: center
                  - text-align: center
                  - margin-left: auto
                  - margin-right: auto
                  - width: 50%
                  - margin-top: auto
                  - margin-bottom: auto
                  - height: 80px
                  - padding-top: 4%
                  - padding-right: 0px
                  - padding-bottom: 4%
                  - padding-left: 0px
                  - align-content: normal
                  - align-self: auto
                  - font-size: 1.2rem
                  - font-weight: 400
                  - position: relative
```
