### ISSUE TITLE
button-card compatible with HA button object

### ISSUE THREAD

**Issue by SeByDocKy** [custom-cards/button-card#572]
**Is your feature request related to a problem? Please describe.**
It will be a great addition "button-card" can also be linked with a HA button object where the action is button.press and not switch.turn_on/turn_off. I have some button ojects (defined in ESPhome) and I would like to use this card and its lock feature for button object

**Describe the solution you'd like**
to be defined as
```
type: custom:button-card
lock:
  enabled: true
tap_action:
  action: toggle
entity: button.pvbrain_from_solar_to_grid
icon: mdi:transmission-tower-import
name: null

````

**Describe alternatives you've considered**

**Additional context**

**Comment by mansellrace** [comment]
i have the same need

**Comment by alexsahka** [comment]
Needed too.

**Comment by webdados** [comment]
+1

**Comment by pickonedev** [comment]
+1

**Comment by RomRider** [comment]
I don't see what is the problem?

```
type: custom:button-card
lock:
  enabled: true
tap_action:
  action: call-service
  service: button.press
  service_data:
    entity_id: entity
entity: button.pvbrain_from_solar_to_grid
icon: mdi:transmission-tower-import
name: null
```
