### ISSUE TITLE
layout: icon_name_state: name style overrides name style

### ISSUE THREAD

**Issue by ghost** [custom-cards/button-card#578]
**Checklist**
- [y] I updated the card to the latest version available
- [y] I cleared the cache of my browser

**Describe the bug**
When, and only when `layout: icon_name_state ` is used, any styles for `state` gets overridden by styles for `name`.  If no name style is defined, state also has no style.

**Version of the card**
Version: 3.4.2

**To Reproduce**
This is the configuration I used:
```
- type: 'custom:button-card'
  entity: input_select.house_mode
  show_name: true
  show_state: true
  show_icon: true
  layout: icon_name_state
  color_type: icon
  #color: var(--paper-item-icon-color)
  styles:
    card:
      - font-size: 15px
      - height: 50px
      - padding: 5px
    state:
      - font-weight: bold
    name:
      - justify-self: start
  state:
    - value: "Awake"
      styles:
        card:
          - border: 2px solid DodgerBlue
          - -webkit-box-shadow: 0px 0px 9px 3px var(--button-card-light-color)
          - box-shadow: 0px 0px 9px 3px var(--button-card-light-color)
        icon:
          - color: DodgerBlue
        state:
          - color: DodgerBlue
    - value: "Asleep"
      styles:
        icon:
          - color: Chocolate
        state:
          - color: Chocolate
        card:
          - border: 2px solid Chocolate
          - -webkit-box-shadow: 0px 0px 9px 3px var(--button-card-background-color)
          - box-shadow: 0px 0px 9px 3px var(--button-card-background-color)
    - value: "Manual"
      styles:
        icon:
          - color: grey
        state:
          - color: grey
        card:
          - border: 2px solid grey
```

**Screenshots**
When `layout` is set to `icon_name_state`
![Screenshot 2022-04-15 at 13 48 18](https://user-images.githubusercontent.com/34644672/163572632-7e678db7-f265-4818-a070-b414cdd0a897.png)

When `layout` is removed (`-height: 50px` also removed to show everything)
![Screenshot 2022-04-15 at 13 51 01](https://user-images.githubusercontent.com/34644672/163572915-a25f8df1-c137-40b8-80b1-448eb220b230.png)

**Expected behavior**
The state ("Awake") should be in bold and blue.

**Desktop (please complete the following information):**
 - Browser: safari
 - Version: 15.4, but same problem in HA IOS app.

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: 15.4.1
 - Browser HA app used
 - Version ?

**Additional context**

**Comment by dcapslock** [comment]
As per doco: `icon_name_state: Everything is aligned horizontally, name and state are **concatenated**, label is centered below`. So with this layout you only havea name element to style, no state as it is part of name. To have what you want you would need to provide your own grid layout areas and rows. Then name (n) and state (s) will be separate. If you want the colon, you will need to template name to add in the colon, which is done automatically with the concantantation with `layout: icon_name_state`.

```yaml
styles:
  grid:
    - grid-template-areas: '"i n s"'
    - grid-template-columns: 1fr min-content min-content
 ```
