### ISSUE TITLE
Not possible to unlock Button with desktop PC

### ISSUE THREAD

**Issue by Alex-joomla** [custom-cards/button-card#579]
**Checklist**
- [x ] I updated the card to the latest version available
- [ x] I cleared the cache of my browser

**Describe the bug**
Lock Card. Activated the Lock option and can unlock the button with mobile devices but not on my desktop pc with my mouse.

**Version of the card**
Version: 3.4.2

**To Reproduce**
This is the configuration I used:
```yaml

type: custom:button-card
entity: switch.garage_alex
icon: |
  [[[
     var garage = states['binary_sensor.garagentorsensor_alex_door'].state    
       if (garage == 'off') return 'mdi:garage';
    else
      return "mdi:garage-open-variant";
  ]]]
name: Garagentor Alex
label: |
  [[[
     var garage = states['binary_sensor.garagentorsensor_alex_door'].state    
       if (garage == 'off') return 'Geschlossen';
    else
      return "Offen";
  ]]]
show_label: true
color: rgb(28, 128, 199)
state:
  - value: 'off'
    color: firebrick
    styles:
      card:
        - filter: opacity(50%)
      icon:
        - filter: grayscale(100%)
  - value: 'on'
    color: lawngreen
lock:
  enabled: true
  duration: 5
  unlock: double_tap
styles:
  label:
    - color: gray
    - font-size: 12px
  grid:
    - grid-template-areas: '"i" "n" "s" "l"'
    - grid-template-columns: 1fr
    - grid-template-rows: 1fr min-content min-content
  img_cell:
    - align-self: center
    - text-align: center
  name:
    - justify-self: center
    - padding-left: 0px
    - font-weight: bold
    - font-size: 12px
  state:
    - justify-self: start
    - padding-left: 10px

```

**Screenshots**

**Expected behavior**

**Desktop (please complete the following information):**
 - Browser: Safari
 - Version 15.4
