### ISSUE TITLE
tap_action call-service input_number.set_value doesn't work as expected

### ISSUE THREAD

**Issue by dhover** [custom-cards/button-card#580]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
I want to set a value of an input_number with a template. In the developer mode this works as expected.
When using the following code I got an error saying: "failed to call service input_number/set_value. expected float for dictionary value @ data['value']"
```
tap_action:
  action: call-service
  service: input_number.set_value
  service_data:
    entity_id: input_number.water_start
    value: '{{ states("sensor.water") }}'
```
also 
```
tap_action:
  action: call-service
  service: input_number.set_value
  service_data:
    entity_id: input_number.water_start
    value: '{{ states("sensor.water")|float }}'

```
doesn't work.

**Version of the card**
Version: 3.4.2

**To Reproduce**
This is the configuration I used:
```
tap_action:
  action: call-service
  service: input_number.set_value
  service_data:
    entity_id: input_number.water_start
    value: '{{ states("sensor.water") }}'
```

**Expected behavior**
When the button is pressed the input_number should be set with an entity state value.

**Desktop (please complete the following information):**
 - Browser [chrome]
 - Version [100.0.4896.127]

**Comment by RomRider** [comment]
You're using jinja2, this card uses javascript.

**Comment by dhover** [comment]
Yes, that does the job. Thanks for your help!
I changed the code to:
```
tap_action:
  action: call-service
  service: input_number.set_value
  service_data:
    entity_id: input_number.water_start
    value: '[[[ return states["sensor.water"].state ]]]'

```
