### ISSUE TITLE
getting ""undefined is not an object" in state template

### ISSUE THREAD

**Issue by ghost** [custom-cards/button-card#582]
Hi,

II cannot work out what I am doing wrong with this state template.  I am trying to set a style based on the state on the entity in the button being the same as another sensor.

The relevant yaml is:
```
- type: 'custom:button-card'
  entity: sensor.light_scene_should
...
  state:
    - operator: template
      value: >
        [[[ return entity.state === states['sensor.light_scene'].state ]]]
      styles:
        icon:
          - color: Grey
        name:
          - color: Grey

```
now, I can see in **_Developer Tools > States_** that **_sensor.light_scene_** equals **_sensor.light.scene_should_** (i.e. it does not appear undefined to me).  Why would I get this error?

thanks!

**Comment by jchhenderson** [comment]
anyone?

I have also tried replacing `entity.state `with `states['sensor.light_scene_should'].state`

cheers.

**Comment by jchhenderson** [comment]
I am having the same issue with:
```
state:
  - operator: template
    value: >
      [[[ return states['sensor.hive_heating_current_temp'].state >= states['sensor.hive_heating_target_temp'].state ]]]
    styles:
      color: var(--state-on-color)
```
again I know that this should return 'true'.
