### ISSUE TITLE
Question) Can delete space between entity picture and card?

### ISSUE THREAD

**Issue by JayChun** [custom-cards/button-card#583]
**Checklist**
- [ V] I updated the card to the latest version available
- [ V] I cleared the cache of my browser

**Describe the bug**
Not a bug, but a Question.

**Version of the card**
Version: 3.4.2

**To Reproduce**
This is the configuration I used:
```
type: custom:button-card
entity: media_player.ytube_music_player
color_type: icon
show_entity_picture: true
show_state: false
show_name: false
entity_picture: /local/images/playlist_favor_jay_2.jpg
styles:
  entity_picture:
    - height: 100%
    - width: 100%
    - border-radius: 10px
```

**Screenshots**
![image](https://user-images.githubusercontent.com/71179304/166406810-8c0d3e5e-a7e4-46d4-87df-b2a3e6a58f0a.png)

**Expected behavior**
I just delete a spacing between picture and card outline.
Is it possible to take it without Template?

**Desktop (please complete the following information):**
 - Browser [Chrome]
 - Version [Latest]
