### ISSUE TITLE
an error, when acting call-service for "media_player.select_source" 

### ISSUE THREAD

**Issue by JayChun** [custom-cards/button-card#585]
**Checklist**
- [V] I updated the card to the latest version available
- [V ] I cleared the cache of my browser

**Describe the bug**
I'm not sure this is a bug or not.
HA default Button card has no problem or error.
but Custom:button card has some error to run 'media_play.select_source' with 'call-service'.

**Version of the card**
Version: 3.4.2
HA Core Version : 2022.4.7
Supervisor : 2022.5.0
run raspberry pi os.

**To Reproduce**

This is the code of HA default Button card. and It has no error.
```
type: button
tap_action:
  action: call-service
  service: media_player.select_source
  service_data:
    source: media_player.speaker_main_sofa
  target:
    entity_id: media_player.ytube_music_player
```

This is the code of Custom button card. and It has an error.
```
type: custom:button-card
tap_action:
  action: call-service
  haptic: light
  service: media_player.select_source
  service_data:
    source: media_player.speaker_main_sofa
  target:
    entity_id: media_player.ytube_music_player
```

**Screenshots**
This error is shown when I click the custom button.
![image](https://user-images.githubusercontent.com/71179304/166720967-82cca85c-eefd-4982-85f5-cfc29c1a1d02.png)

**Desktop (please complete the following information):**
 - Browser [chrome, windows10]
 - Version [latest]
