### ISSUE TITLE
return null from JS template doesn't work

### ISSUE THREAD

**Issue by michalk-k** [custom-cards/button-card#596]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser

**Describe the bug**
While it's not officially stated in the documentation, it has been mentioned somewhere that returning null or undefined from JS template should not change an attribute value. I'm sure it was working this was for long time but recently it stopped working

See example below

**Version of the card**
Version: 

**To Reproduce**
This is the configuration I used. It applies unexpected color to the icon (black in my case) instead of yellow/blue for default styles.
```yaml
type: custom:button-card
entity: binary_sensor.washing_mashine_gui
styles:
  icon:
    - color: |
         [[[
           return undefined; // try with null too
         ]]]
```

**Screenshots**
N/A

**Expected behavior**
There should be a working way of 'escaping' from JS template without affecting the attribute the template is intended to change.

**Desktop (please complete the following information):**
 - Browser: ANY

**Smartphone (please complete the following information):**
 - Device: iPhoneX
 - OS: iOS 15.4.1
 - Browser: safari

**Additional context**
N/A

**Comment by Mariusthvdb** [comment]
This is returning a black icon because you actively Not set a color, so it reverts to HA default ?

**Comment by michalk-k** [comment]
Yes. exactly.
I just want to set specific color under specific conditions, but otherwise let the system use defaults. 
Of course, the goal is to not put those default values into JS code.

For example 

```
styles:
  icon:
    - color: |
         [[[
           if (something) return red;
           else undefined; // return colors set in CSS specific for entity states
         ]]]
```

I saw this strategy in your templates (using null). And I believe undefined worked for me too. But now neither of those two work on my.

**Comment by Mariusthvdb** [comment]
in my templates I do use things like:
```
      - border-top: >
          [[[
            return (entity.state === 'on') ? '0.5rem solid var(--icon-color-on)' : null;
          ]]]
```

but there, the null actually means 'dont show a border top'.
My advice would be to use a theme color as default in the else clause, so it always reverts to the color you need.

On the binary sensor from your opening post: why not use the core option `state_color: true` and not customize at all? (not sure if the button_card pickup the state color, so thats why I ask)

**Comment by michalk-k** [comment]
It seems that none and undefined are both just clear values for given CSS attribute. Hence the black color of the icon in my case and no border-top in your example.

IMO none and 'none' are different. For some css styles the `none` is a valid value, for example `display: none`. Coincidently if used for other styles which don't accept this value, it may visually appear as expected.
I found in my code working example of that (I guess coincidently because of the same reasons)
```
    styles:
      card:
        - display: |
            [[[ return entity == null ? 'none' : 'undefined' ]]]
```

> state_color: true and not customize at all?
Documentation doesn't mention this attribute. But the point is to override some behavior letting to behave normally when the condition is not met.

I'm still almost sure I was advised to use undefined but maybe I'm wrong. Anyway it would be usefull addition

**Comment by michalk-k** [comment]
Thank you about making me aware about `none`.
However interesting example is this one:
```
  styles:
    card:
      - display: >
          [[[ if (!entity) return 'none'; ]]]
```

It assumes that if entity exists some default value is set to display attribute.
IMHO it's not true and it works coincidently only (because setting display to nothing has to promote it to some actual value)

Let me make an analogical example with light and icon color

```
  styles:
    icon:
      - color: >
          [[[ if (entity.state == 'undefined') return 'red'; ]]]
```
In analogy to your snippet, one would expect that if the state is NOT undefined, the icon will get default colors for on and off states. 

But it won't - it will rest to black. 
And this is my point of this issue.
