### ISSUE TITLE
Detect dark mode

### ISSUE THREAD

**Issue by jake404** [custom-cards/button-card#601]
**Describe the solution you'd like**
I have buttons where I show the wind speed and set the background color based on severity. I'm using grayscale starting from white and going up to black and it looks great in light mode. But, once I change to dark mode in HA, the button background looks inverted.  It would be great to be able to use dark mode as a condition when setting certain options such as state colors. It would then be possible to have it start out at black and go up to white when in dark mode.

Light mode:
![Screenshot_20220531-164245_Home Assistant](https://user-images.githubusercontent.com/12189899/171201846-df97edb0-8bb6-44cb-8fe6-f98739816518.png)

Dark mode:
![Screenshot_20220531-164316_Home Assistant](https://user-images.githubusercontent.com/12189899/171202537-aa4a42d5-ad59-4a72-a942-8dc47473c847.png)

**Comment by jake404** [comment]
Before trying to use `hass.themes.darkMode` I setup a JavaScript template as a condition to set the color to make sure I was setting the condition in the correct place, but it doesn't work. Here's what I tried with:

```
      - type: custom:button-card
        entity: sensor.tempest_st_00045370_wind_speed
        color_type: card
        color: >
          [[[
            if (entity.state < 60) return 'lime';
            if (entity.state >= 60 && entity.state < 80) return 'orange';
            else return 'red';
          ]]]
```

```
      - type: custom:button-card
        entity: sensor.tempest_st_00045370_wind_speed
        color_type: card
        state:
          - value: 0
            operator: =>
            color: >
              [[[
                if (entity.state < 60) return 'lime';
                if (entity.state >= 60 && entity.state < 80) return 'orange';
                else return 'red';
              ]]]
```

If I set the color to a fixed color without the JavaScript Template it works fine in both of the above examples, it's when using the JavaScript template it doesn't work.

**Comment by dcapslock** [comment]
`color:` itself does not support template. Also the operator you have in the second example is incorrect. It should be ">=" and since ">" is a reserved yaml operator it needs to be quoted. So a correct way to achieve what you wish is below. Operators are evaluated in order so for your case you start with the maximum and then proceed to 'default'.

```yaml
      - type: custom:button-card
        entity: sensor.tempest_st_00045370_wind_speed
        color_type: card
        state:
          - operator: ">"
            value: 80
            color: red
          - operator: ">="
            value: 60
            color: orange
          - operator: 'default'
            color: lime
```
