### ISSUE TITLE
can't set styles for last_changed

### ISSUE THREAD

**Issue by a-bianucci** [custom-cards/button-card#614]
**Checklist**
- [X ] I updated the card to the latest version available
- [ ] I cleared the cache of my browser

**Describe the bug**
I can get the "show_last_changed: true" to function, however I can't style it in the "Styles" section by leveraging last-changed, or last_changed

**Version of the card**
Version: 3.4.2

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:button-card
entity: light.kitchen_bar
show_name: false
styles:
  card:
    - height: 100px
    - background-color: rgba(0,0,0,0.0)
    - box-shadow: 0px 0px 0.0px 0px
  grid:
    - position: absolute
  name:
    - align-self: start
    - justify-self: center
    - font-size: 24px
    - color: rgb(128,128,128)
  last_changed:
     - font-size: 10px
```

**Screenshots**

**Expected behavior**

I would expect that any styles could be applied

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
