### ISSUE TITLE
A tap_action question.

### ISSUE THREAD

**Issue by Opontios** [custom-cards/button-card#616]
Don't know if it's been already answered, but is it possible to define 2 different actions under tap_action, as 2 different call services? I tried any possible way that I could, but it isn't validated by the card editor. Thanks.

**Comment by Wombosvideo** [comment]
This is what scripts are for. The example below gives you a button to perform actions for when you are not at home, like turning off the lights and the thermostat.

**Card config:**
```yaml
type: custom:button-card
name: Not at home
tap_action:
  action: call-service
  service: script.not_at_home_actions
```

**Script:**
```yaml
alias: Not at home actions
icon: mdi:script
mode: single
sequence:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.luca
  - service: climate.turn_off
    data: {}
    target:
      entity_id: climate.luca_thermostat
```
