### ISSUE TITLE
Fade option

### ISSUE THREAD

**Issue by tenkaibr** [custom-cards/button-card#619]
Is it possible to add a fade effect when changing the state?

**Comment by dcapslock** [comment]
Sure, style card and/or icon transition depending on what `color_type` you are using. The dfeault `all 0.3s ease-out`. You could also template this in state to have different transitions for different states. The example below has a red light that fades in quickly (0.5s) but then when turned to off it fades out over 5s (default style for config).

```yaml
type: custom:button-card
entity: light.bed_light
color_type: icon
color: auto
state:
  - value: on
    color: red
    styles:
      icon:
        - transition: all 0.5s ease-out
styles:
  icon:
    - transition: all 5s ease-out
```
