### ISSUE TITLE
 Fail to call any xxx.toggle from the ui

### ISSUE THREAD

**Issue by bernardovalente** [custom-cards/button-card#644]
**Checklist**
- [x ] I updated the card to the latest version available
- [x ] I cleared the cache of my browser

**Describe the bug**

HA can't call seem to call any xxx.toggle services from the ui, only from the developer tools.
![error](https://user-images.githubusercontent.com/15112071/210096928-83bf181e-6e83-4d3e-8e6d-2187dbcedec8.png)

works on developer tools:
```
service: light.toggle
data: {}
target:
  entity_id: light.leds_laura
```

doesn't work on UI button card:
```
type: custom:button-card
tap_action:
  action: call-service
  service: light.toggle
  data: {}
  target:
    entity_id: light.leds_laura
```

**Version of the card**
Version: 3.4.2

**Solution**
```
type: custom:button-card
tap_action:
  tap_action:
    action: call-service
    service: light.toggle
    service_data:
      entity_id: light.leds_laura
```
