### ISSUE TITLE
Repeat - issue with units

### ISSUE THREAD

**Issue by BertPorter** [custom-cards/button-card#649]
**This works:**

```
type: custom:button-card
hold_action:
  action: call-service
  service: script.brightness_down
  data: {}
  target: {}
  repeat: 200ms
```

**This doesn't work:**
```
type: custom:button-card
hold_action:
  action: call-service
  service: light.turn_on
  service_data:
    entity_id: light.rgbw_04_5
    brightness_step_pct: -10
  repeat: 200ms
```

When I remove "ms" from "repeat: 200ms", the second one works also.
