### ISSUE TITLE
New display precision in entity is not taken into account...

### ISSUE THREAD

**Issue by Protoncek** [custom-cards/button-card#662]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser

**Describe the bug**
Today HA was updated to 2023.3 and with it a new function was added: possibility to set precision for entities. I have Xiaomi sensors which by default show humidity to one decimal (say: 49.1%) and temperature to two decimals (say: 23.13°C), which is too much. So i changed that into: humidity=zero decimals (=49%), temperature only one decimal (=23.1°C.
In HA, "entities card" shows correctly 49% and 23.1°C, but in "custom:button-card" it still shows original values.

**Version of the card**
Version: 3.4.2

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:button-card
entity: sensor.greenhouse_23b8_humidity
show_state: true
```

**Comment by aegjoyce** [comment]
Same here. I don't think this will be fixed though as the project appears to be abandoned.

**Comment by Protoncek** [comment]
Uh, i didn't notice that... it really seems that project is very old. That's very sad, since this card is one of the best cards in HA... you can do practically everything with it... definitely the most usefull card out there.

**Comment by pvprodk** [comment]
same problem here

**Comment by pvprodk** [comment]
A manual workaround is adding the following to the card configuration:

state_display: |
  [[[
    return Math.round((Number(entity.state) + Number.EPSILON) * 100) / 100;
  ]]]

**Comment by Protoncek** [comment]
Uau…
A bit complicated, but at least it’s a solution, many thanks!
I’d say that for occasional things it will be great, but for more frequent things it’s better to create additional sensor with less accuracy, as i have now: i have xiaomi temp/humidity sensors, which shows humidity to one decimal and temp to two decimals, which is an exaggeration, so i created template sensors with smaller resolution. Now i hoped that i’ll be able to remove them…

**Comment by Protoncek** [comment]
Thanks, i found one working command, too:
[Math.round(states['[[temperature]]'].state).toFixed(1) + '°C'](url)
(It’s template for decluttering card)
I wonder what’s difference between two…

**Comment by pejotigrek** [comment]
@Protoncek `Math.round()` rounds the number to nearest integer [which means it would make more sense for me to use it - and ditch the `.toFixed(0)`, but as I have this in lot of places with different number of decimals - it's easier for me to find all occurences of the template when I search the code; without changing the query]. so in your case - you first round the number to nearest integer and then you add one decimal to it.

`parseFloat()` tells the template to treat sensor value as float number [without rounding] and then by `toFixed()` you just tell it to cut the decimals to desired count [and rounds it as it should]

**Comment by Protoncek** [comment]
Aha… thanks for explanation. So, basically, end effecr is the same…

**Comment by pejotigrek** [comment]
if you want 0 decimals, then yes, effect should be the same, but if you want the float number with some decimals, I'd stick with .toFixed() [but also: I'm not a programmer, so maybe there's something I don't know about those both ways ;)]

**Comment by Alfamonk** [comment]
Same issue in here. All other cards take the new "Display precision" into account, but custom:button-card does not.
Please fix this!
Thanks!

**Comment by alexruffell** [comment]
What about this method I found?

```
type: custom:button-card
entity: sensor.office_multi_sensor_temperature
state_display: |
  [[[
    var result = Number(entity.state).toFixed(1);
    return result.concat("°C");
  ]]]
styles:
  card:
    - height: 100%
    - width: 58px
    - padding: 0px 0px 0px 2px
  name:
    - text-transform: uppercase
    - font-size: 12px
    - font-weight: normal
    - justify-self: center
    - letter-spacing: 2px
    - padding: 0%
tap_action:
  action: none
show_icon: false
show_name: false
show_state: true
layout: name_state
```

Sounds like it just chops the decimals to 1 without doing any rounding so 21.19 would turn into 21.1 instead of 21.2... if so, not what I want. Is that the case? I liked this method simply because it doesn't reference the entity name. Anyhow, one issue the few methods I tried have is that if the entity is deleted/name changed/etc then you get a huge burgundy error that messes up the dashboard. Is there some way to have it fail more "discretely"?

**Comment by Protoncek** [comment]
> Same issue in here. All other cards take the new "Display precision" into account, but custom:button-card does not..

Actually.. not all... i found another one who doesn't: custom:simple-thermostat. I didn't report a problem for that one (yet)...

Alexruffel: thanks, that also works!

**Comment by Mariusthvdb** [comment]
please stop posting you experience the same issue only. Of course you do, everyone does, as this now is the state of the affairs with changed HA Frontend handling not taken into account in an unchanged custom:button-card...

It causes many email/notifications without additional value for all followers of this repo.

on the rounding: simply check the js instructions you find in the various online tutorials, they all can be used inside button-card, depending on your needs. It's still the best card ever ;-)

We might be lucky Romrider would update button-card to implement the new HA Dashboard techniques.

Until that moment, we just will have to manage.

**Comment by RomRider** [comment]
This should be fixed with the latest beta 4.0.0-dev7

**Comment by Mariusthvdb** [comment]
on b8 still not seeing it:

<img width="1000" alt="Scherm­afbeelding 2023-07-24 om 23 24 35" src="https://github.com/custom-cards/button-card/assets/33354141/f5c17695-0483-4b7a-88b6-45e3e696d0cc">


also, wondering if this is for all numeric entities on the button? or just state
asking because I have quite a few buttons with more than 1 numeric entity, eg in custom fields notifications:
```
custom_fields:
  notification: >
    [[[ return Math.round(states['sensor.pond_buiten_sensor_temperature'].state); ]]]
name: >
  [[[ return 'Vijver: ' + states['sensor.vijver_thermometer_temperature'].state + ' °C'; ]]]
```

, and, use things like that name template. Would these all be influenced using that 

```
numeric_precision: 0
```
?

**Comment by RomRider** [comment]
If you're not seeing the result of numeric_precision it's because of a caching issue probably.

Also that doesn't apply to a direct access to the state, you'd have to use the new localize function on the custom_field state access (check the dev branch readme about that)

**Comment by RomRider** [comment]
Fixed in next version

**Comment by Mariusthvdb** [comment]
> If you're not seeing the result of numeric_precision it's because of a caching issue probably.
> 
> Also that doesn't apply to a direct access to the state, you'd have to use the new localize function on the custom_field state access (check the dev branch readme about that).

just for reporting that I can now use:
```
name: >
  [[[ return 'Vijver: ' + localize(states['sensor.vijver_thermometer_temperature']); ]]]
numeric_precision: 0
```

and it magically works... even adds the unit, so I can take that out of the name template.. cool

<img width="123" alt="Scherm­afbeelding 2023-07-25 om 21 23 12" src="https://github.com/custom-cards/button-card/assets/33354141/80b10862-4a79-4b0a-af1b-4785f7aa27c5">

**Comment by Mariusthvdb** [comment]
there is another issue see this custom_field:
```
  co2: >
    [[[ return `Co2:
        <span style='color: var(--text-color-sensor);'>
        ${states['sensor.co2_living'].state} ppm</span>`; ]
```

showing as

<img width="132" alt="Scherm­afbeelding 2023-07-25 om 21 27 19" src="https://github.com/custom-cards/button-card/assets/33354141/d682a10d-5e33-47d4-bba5-21af2a7c0d63">

so, with a `.0`

precision is set to be without:

<img width="562" alt="Scherm­afbeelding 2023-07-25 om 21 28 10" src="https://github.com/custom-cards/button-card/assets/33354141/a9c70c4f-d229-4e35-9fda-4df206a68d73">


which it does in the regular dashboard:

<img width="574" alt="Scherm­afbeelding 2023-07-25 om 21 28 22" src="https://github.com/custom-cards/button-card/assets/33354141/bdbc291d-4161-4e27-a9b3-4144f0833404">

**Comment by RomRider** [comment]
> precision is set to be without:

It's **displayed** without, but the state is stored with the 1 decimal after the `.`.
Accessing `states['sensor.co2_living'].state` is the raw data.

`localize` takes new parameters now in the last release (check the README in the dev branch), so you can do:
If you didn't define the `numeric_precision` in the main config:
```yaml
 co2: >
    [[[ return `Co2:
        <span style='color: var(--text-color-sensor);'>
        ${localize(states['sensor.co2_living'])} ppm</span>`; ]
```
or if you defined it, you have to force it for this value specifically:
```yaml
 co2: >
    [[[ return `Co2:
        <span style='color: var(--text-color-sensor);'>
        ${localize(states['sensor.co2_living'], undefined, 0)} ppm</span>`; ]
```

**Comment by RomRider** [comment]
> Hm... new dev version causes that this card doesn't work in browser-mod's popup - i have a popup where i change station on my internet radio. I click on one button, but nothing happens. Going back to 3.5.0 works again.

Without the config, there's not much I can do about it 🤷‍♂️ 



> then still shows too many decimals.

Expected as you access the raw state value.
For it to be as you want, you have to do:

```yaml
state_display:
  [[[
  return "outside is: " + localize(states['sensor.temperature_outside'])
  ]]]
```

> Also, as you said: card-mod styles are totally off...

The only modification in the code is on `ha-icon` vs `ha-state-icon`, so again, without the config, there's not much I can do.

Also, we can't have all the shiny new features and expect backwards compatibility forever, there's a tradeoff. 🤷‍♂️

**Comment by alexruffell** [comment]
First of all, thank you @RomRider for implementing all these fixes! I use button-card a lot and love it!

While waiting on a fix for the precision issue, I found an alternative solution which may help @Protoncek. The rounding was handled within the state_display as shown below:

```
type: custom:button-card
entity: sensor.office_multi_sensor_temperature
state_display: |
  [[[
    var result = Number(entity.state).toFixed(1);
    return result.concat("°C");
  ]]]
styles:
  card:
    - height: 100%
    - width: 58px
    - padding: 0px 0px 0px 2px
  name:
    - text-transform: uppercase
    - font-size: 12px
    - font-weight: normal
    - justify-self: center
    - letter-spacing: 2px
    - padding: 0%
tap_action:
  action: none
show_icon: false
show_name: false
show_state: true
layout: name_state
```

With your latest revision I can now use this but I wonder whether there is any way to avoid repeating the sensor name. In the example above `entity.state` enabled me to not have to write the entity twice in the card. Just helps with keeping the code as concise as possible, and when copying the YAML for all the other cards that share this code.

```
type: custom:button-card
entity: sensor.office_multi_sensor_temperature
state_display: |
  [[[
    return localize(states['sensor.office_multi_sensor_temperature'])
  ]]]
styles:
  card:
    - height: 100%
    - width: 58px
    - padding: 0px 0px 0px 2px
  name:
    - text-transform: uppercase
    - font-size: 12px
    - font-weight: normal
    - justify-self: center
    - letter-spacing: 2px
    - padding: 0%
tap_action:
  action: none
show_icon: false
show_name: false
show_state: true
layout: name_state
```
The YAML above is for the temp card shown below:

<img width="415" alt="image" src="https://github.com/custom-cards/button-card/assets/4006944/821e563b-0c1c-419c-a965-17082f2bd94b">
