### ISSUE TITLE
How to turn_on switch on tap_action?

### ISSUE THREAD

**Issue by Bagunda** [custom-cards/button-card#670]
**Checklist**
- [v] I updated the card to the latest version available
- [v] I cleared the cache of my browser

**Describe the bug**
Failed to call switch/turn_on service. must contain at least one of entity_id, device_id, area_id.

**Version of the card**
Version: 3.4.2

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:button-card
entity: switch.shtora_spalni_target_position_0
show_name: false
tap_action:
  action: call-service
  service: switch.turn_on
  service_data:
    entity_id: switch.shtora_spalni_target_position_0
color_type: card
color: rgb(66, 134, 244)
icon: mdi:eye-off-outline
```

**Screenshots**
![image](https://user-images.githubusercontent.com/16766521/228828559-c96cc48e-ddd8-4575-a0d1-624f30dfed9b.png)

**Expected behavior**
Based on the documentation and examples, this should have worked. Although this is not the case in the examples.

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version 111.0.5563.110
 - Browser: Firefox
