### ISSUE TITLE
still broken for me - cannot read properties of null (reading 'config')

### ISSUE THREAD

**Issue by loki-sft** [custom-cards/button-card#679]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser

**Describe the bug**
After updating HA and button card to latest version its still broken
still broken for me - cannot read properties of null (reading 'config')

**Version of the card**
Version: 3.5.0

**To Reproduce**
This is the configuration I used:
```
    - type: custom:button-card
      entity: light.wohn_deckenlampe
      style:
        z-index: 100
        left: 57%
        top: 53%
      template:
        - light_white


in template:

  light_white:
    template:
      - icon_main
      - circle
    show_state: false
    show_icon: true
    show_name: false
    show_label: true
    size: 70%
    color_type: icon
    color: rgb(255, 159, 0)
    color_off: rgb(255, 255, 255)
    tap_action:
      action: toggle
      haptic: light
    label: >
      [[[ return Math.round(entity.attributes.brightness / 2.54); ]]]
    styles:
      card:
        - width: 3.5vw
        - height: 3.5vw
        - borderRadius: 15vw
        - background-color: >
            [[[ return (entity.state === 'on' || entity.state === 'home') ? 'rgba(255, 255, 255, 1.0)' : 'rgba(115, 115, 115, 0.6)'; ]]]
      label:
        - color: gray
        - font-size: 9px
    variables:
      circle_input: >
        [[[ return Math.round(entity.attributes.brightness / 2.54); ]]]
    hold_action:
      action: fire-dom-event
      browser_mod:
        service: browser_mod.popup
        data:
          style:
            $: |
              s.popup-inner{
                padding: 15px 0 30px 0;
              }
              .mdc-dialog .mdc-dialog__container {
              }
              .mdc-dialog .mdc-dialog__container .mdc-dialog__surface {
                border-radius: 2vw;
              }
              ha-svg-icon {
                margin-top:-7px;
              }
            .: |
              :host {
                --mdc-dialog-scrim-color: rgba(0,0,0,0.5);
              }
              mwc-icon-button {
                color: #FFF;
              }
          title: >
            [[[ return entity.attributes.friendly_name ]]]
          content:
            type: entities
            entities:
              - type: custom:light-popup-card
                entity: >
                  [[[ return entity.entity_id ]]]
                icon: none
                hideIcon: true
                fullscreen: false
                brightnessWidth: 10vw
                brightnessHeight: 35vh
                switchWidth: 10vw
                switchHeight: 35vh
                borderRadius: 1.7em
                sliderColor: '#c7c7c7'
                sliderTrackColor: rgba(25, 25, 25, 0.9)

```

**Expected behavior**
no error message, display the card

**Desktop (please complete the following information):**
 - Browser chrome
 - Version latest

**Comment by Mariusthvdb** [comment]
please dont open issues for the same issues (that have already been fixed...)
you need to take care your browser resets cache, and actually uses the new Card. This is described all over the Community and in this Repo.

**Comment by maymaymay** [comment]
Unfortunately, there still is a bug.
I think its when you are using templates. if not, there is no problem.
I tried several different templates, including the sample ones.
Tested on Edge/FF/Chrome/iOS APP. Cache cleared.
```
              - type: 'custom:button-card'
                template: container
                color: '#EDE7B0'
                title: 'Media'
                name: Bedroom TV
                custom_fields:
                  buttons:
                    card:
                      type: vertical-stack
                      cards:
                        - type: media-control
                          entity: media_player.bedroom_google_tv

                        - type: horizontal-stack
                          cards:
                            - entity: input_boolean.bedroom_tv
                              name: Bedroom TV
                              template: standard2
                              type: 'custom:button-card'
                              size: 20%
                              hold_action:
                                action: more-info

                            - entity: switch.googletvwol
                              name: Bedroom TV WoL
                              template: standard2
                              type: 'custom:button-card'
                              size: 20%
                              hold_action:
                                action: more-info

                        - type: media-control
                          entity: media_player.bedroom_tv
```
