### ISSUE TITLE
Current button-card.js might not be compatible with pre-0.88 installs

### ISSUE THREAD

**Issue by mrand** [custom-cards/button-card#68]
I haven't upgrade to 0.88 yet (23 Feb 2019), and it looks like the version of the current button-card doesn't display any buttons.  

It seems to work fine if I fall back to this revision immediately before the 0.88 changes:
https://github.com/custom-cards/button-card/blob/9dd6b14150832b20a116895909d1a2b0806afeb6/button-card.js

I don't know that it's worth trying to fix - if others have a problem, perhaps just point them to that version?

I confirmed it by switching the button-card.js file back and forth a few times (F5 each time). 
My usage is pretty simple: a horz stack of three button cards:
```
  - path: system_status_view
    cards:
      - label: status_button_horiz_stack
        type: horizontal-stack
        cards:
          - type: "custom:button-card"
            entity: switch.garage_door_button
            icon: mdi:garage
            color: rgb(255,0,0) # color when active
            color_off: rgb(255,255,255)
            color_type: card
            show_state: false
          - type: "custom:button-card"
            color_type: blank-card
          - type: "custom:button-card"
            entity: switch.sonoff_s20_relay
            icon: mdi:power-socket-us
            color: rgb(255, 233, 128)  # color when active
            color_off: rgb(255,255,255)
            color_type: card
            show_state: false
```
