### ISSUE TITLE
Entity State displays „raw“ Informations

### ISSUE THREAD

**Issue by mcfly2283** [custom-cards/button-card#685]
With the latest Version of HA 2023.4.3 the State of a Person inside a Button-Card is displayed as state "home" and "not_home", not as usual with the corresponding German Translation "Zu Hause" or "Abwesend". Other Zones and other Native-Cards are right. 

Button-Card Version: [3.5.0] (2023-04-02) latest

In this case it seems there is a Problem related to Button-Card and not with HA.

Button-Card:
![image](https://user-images.githubusercontent.com/34608100/231828843-7f40ea29-7605-431f-a06a-dd10edfe58f6.png)

Native Card:
![image](https://user-images.githubusercontent.com/34608100/231830312-4cb39be7-01f3-414b-964d-a0a78a5963af.png)

Syntax:
      - type: custom:button-card
        entity: person.XXYY
        show_name: false
        show_state: true
        show_entity_picture: true
        styles:
          card:
            - font-size: 14px
            - padding: 10%
          icon:
            - width: 70px
            - height: 70px
            - padding: 0px 0px 0px 0px

**Comment by pejotigrek** [comment]
it's affecting all entity domains. language translations are ignored in button-card in latest HA.
it just displays "raw" state of an entity:
![image](https://user-images.githubusercontent.com/10796588/232001579-eea97ad8-5a3a-4037-9ee1-10ae1e7823a4.png)

**Comment by pejotigrek** [comment]
@mcfly2283 are you able to change the issue's topic? maybe "entity state displays raw information, not local/translated value" or something similar would be more fitting?

**Comment by Mariusthvdb** [comment]
seems identical to https://github.com/benct/lovelace-multiple-entity-row/issues/292#issuecomment-1507232575

quoting Frontend dev Paul:

> With 2023.4, HA core added support for translations attributes and name so entity state translation keys have changed too.
> The computeStateDisplay in this repository is outdated and need to be updated with new translation keys.
> 
>

**Comment by mcfly2283** [comment]
> @mcfly2283 are you able to change the issue's topic? maybe "entity state displays raw information, not local/translated value" or something similar would be more fitting?

I don‘t think so…

**Comment by mcfly2283** [comment]
> @mcfly2283 are you able to change the issue's topic? maybe "entity state displays raw information, not local/translated value" or something similar would be more fitting?

Done 👍

**Comment by jjprz** [comment]
same problem here but in spanish

**Comment by sheminasalam** [comment]
same problem here with my door binary sensors.
![image](https://user-images.githubusercontent.com/45196177/232234982-aacdbb79-21d2-4f01-b43d-f5ea6b8b4b75.png)

**Comment by gabrymed** [comment]
Same problem for me with my gas and fire binary sensors.
![Immagine](https://user-images.githubusercontent.com/57106603/232238925-5340f299-f5d3-4cc2-92a5-053f52f9421e.jpg)

**Comment by h4nnes** [comment]
> I have a similar problem. After the update, on and off are now displayed and no longer the German designation. The same applies to windows/doors as on/off. In Home Assistant, however, it is correctly displayed as open/closed.

Same here

**Comment by Scoff123** [comment]
Same with my Binary Sensors for windows and doors - previously they would show a 'state' of Open or Closed, but now they show the actual Binary state of On or Off

<img width="83" alt="image" src="https://user-images.githubusercontent.com/96984460/232427606-d27afe43-4e4f-4f7f-9f04-0ddbb7ba20b9.png">

<img width="467" alt="image" src="https://user-images.githubusercontent.com/96984460/232428270-8b5dc885-1cc4-468f-89a0-5a145c9a88fc.png">

```
Garage Door Sensor contact (binary_sensor.garage_door_sensor_contact)
MQTT discovery data:
Topic: homeassistant/binary_sensor/0x00158d00090ee999/contact/config
Payload
availability:
  - topic: zigbee2mqtt/bridge/state
    value_template: '{{ value_json.state }}'
  - topic: zigbee2mqtt/Garage Door Sensor/availability
    value_template: '{{ value_json.state }}'
availability_mode: all
device:
  identifiers:
    - zigbee2mqtt_0x00158d00090ee999
  manufacturer: Xiaomi
  model: Aqara door & window contact sensor (MCCGQ11LM)
  name: Garage Door Sensor
  sw_version: 3000-0001
device_class: door
name: Garage Door Sensor contact
payload_off: true
payload_on: false
state_topic: zigbee2mqtt/Garage Door Sensor
unique_id: 0x00158d00090ee999_contact_zigbee2mqtt
value_template: '{{ value_json.contact }}'
platform: mqtt
```

**Comment by micium** [comment]
Hi all,
waiting for an updated version that solves the problem, is it possible to apply a workaround?

Kind Regards

**Comment by mcfly2283** [comment]
> Hi all, waiting for an updated version that solves the problem, is it possible to apply a workaround?
> 
> Kind Regards

I don‘t think there is a workarounds. This issue is related to every 3rd Party Card. It is a bit courios that there was no breaking change for the devs before…

**Comment by jensrossbach** [comment]
You could use state_display as workaround.

**Comment by FieserOstfriese** [comment]
So I can't get it with the state_display somehow. No matter how I embed it, it doesn't work. There won't be an update anymore because the button card is no longer maintained, right? Maybe someone has a code example how to include state_display exactly?

**Comment by Mariusthvdb** [comment]
what are you trying to do? we cant help you if you dont give us anything.
btw, this is better suited for the Community, as there is no 'bug' here, and config questions shouldnt be littering these repo issues.

**Comment by FieserOstfriese** [comment]
> what are you trying to do? we cant help you if you dont give us anything. btw, this is better suited for the Community, as there is no 'bug' here, and config questions shouldnt be littering these repo issues.
> 
> state_display is really easy btw. just set a value to display, (template or not) and also use the `show_state: true` option of course.

I've tried everything. It just doesn't work. Only on or off is displayed. I think I'm just too stupid for that *g*


```
type: custom:button-card
template: container
name: Fenster & Türen
custom_fields:
  buttons:
    card:
      type: horizontal-stack
      cards:
        - entity: binary_sensor.fenster_kuche_contact
          label: Küche
          name: Küche
          icon: mdi:window-closed-variant
          show_state: true
          state_color: true
          show_name: false
          show_label: true
          device_class: window
          type: custom:button-card
          styles:
            grid:
              - grid-template-areas: '"l" "i" "n" "s"'
              - grid-template-rows: min-content 1fr min-content min-content
              - grid-template-columns: 1fr
            card:
              - width: 117px
              - height: 90px
        - entity: binary_sensor.fenster_kinderzimmer_contact
          label: Kinderzimmer
          name: Kinderzimmer
          icon: mdi:window-closed-variant
          show_state: true
          show_name: false
          state_color: true
          show_label: true
          type: custom:button-card
          styles:
            grid:
              - grid-template-areas: '"l" "i" "n" "s"'
              - grid-template-rows: min-content 1fr min-content min-content
              - grid-template-columns: 1fr
            card:
              - width: 117px
              - height: 90px
        - entity: binary_sensor.fenster_schlafzimmer_contact
          label: Schlafzimmer
          icon: mdi:window-closed-variant
          show_state: true
          show_name: false
          state_color: true
          show_label: true
          type: custom:button-card
          styles:
            grid:
              - grid-template-areas: '"l" "i" "n" "s"'
              - grid-template-rows: min-content 1fr min-content min-content
              - grid-template-columns: 1fr
            card:
              - width: 117px
              - height: 90px
        - entity: binary_sensor.badezimmerfenster_contact
          label: Badezimmer
          icon: mdi:window-closed-variant
          show_state: true
          show_name: false
          state_color: true
          show_label: true
          type: custom:button-card
          styles:
            grid:
              - grid-template-areas: '"l" "i" "n" "s"'
              - grid-template-rows: min-content 1fr min-content min-content
              - grid-template-columns: 1fr
            card:
              - width: 117px
              - height: 90px
        - entity: binary_sensor.garagentur_contact
          label: Garagentür
          icon: mdi:door-closed
          show_state: true
          show_name: false
          state_color: true
          show_label: true
          type: custom:button-card
          styles:
            grid:
              - grid-template-areas: '"l" "i" "n" "s"'
              - grid-template-rows: min-content 1fr min-content min-content
              - grid-template-columns: 1fr
            card:
              - width: 117px
              - height: 90px
        - entity: binary_sensor.haustur_contact
          label: Haustür
          icon: mdi:door-closed
          show_state: true
          show_name: false
          state_color: true
          show_label: true
          type: custom:button-card
          styles:
            grid:
              - grid-template-areas: '"l" "i" "n" "s"'
              - grid-template-rows: min-content 1fr min-content min-content
              - grid-template-columns: 1fr
            card:
              - width: 117px
              - height: 90px
        - entity: binary_sensor.terassentur_contact
          label: Terassentür
          icon: mdi:door-closed
          show_state: true
          show_name: false
          state_color: true
          show_label: true
          type: custom:button-card
          styles:
            grid:
              - grid-template-areas: '"l" "i" "n" "s"'
              - grid-template-rows: min-content 1fr min-content min-content
              - grid-template-columns: 1fr
            card:
              - width: 117px
              - height: 90px
        - entity: binary_sensor.garagentor_contact
          label: Garagentor
          icon: mdi:garage
          show_state: true
          show_name: false
          state_color: true
          show_label: true
          type: custom:button-card
          styles:
            grid:
              - grid-template-areas: '"l" "i" "n" "s"'
              - grid-template-rows: min-content 1fr min-content min-content
              - grid-template-columns: 1fr
            card:
              - width: 117px
              - height: 90px
```
