### ISSUE TITLE
Unable to use template variable for input_select entity values

### ISSUE THREAD

**Issue by cyr123** [custom-cards/button-card#686]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
I'm trying to use a number of button cards to display and select the options in an input_select helper. I managed to get it working, but I want to use a template to avoid a lot of code duplication. I'm trying to use a variable to map each button to a specific value as shown below, but neither the state indication (color) or tap_action works.

I tried a number of things that do work:

* Not using a template or a variable.
* Using an input_text helper instead (changing the service call)
* Hard coding a value in the template (e.g. [[[ return "1.66:1"; ]]])

Disclaimer: Although I am a software developer, I have next to zero JS or web development experience and YAML makes me go cross-eyed so I may be missing something obvious... 

**Version of the card**
Version: 3.5.0

**To Reproduce**
This is the configuration I used:
```yaml
button_card_templates:
  selector:
    color_type: label-card
    name: '[[[ return variables.value; ]]]'
    state:
      - value: '[[[ return variables.value; ]]]'
        color: green
    tap_action:
      action: call-service
      service: input_select.select_option
      service_data:
        entity_id: entity
        option: '[[[ return variables.value; ]]]'
views:
  - title: Home
    cards:
      - type: custom:button-card
        template: selector
        entity: input_select.home_theater_aspect_ratio
        variables:
          value: '1:43.1'
      - type: custom:button-card
        template: selector
        entity: input_select.home_theater_aspect_ratio
        variables:
          value: '1:66.1'
      - type: custom:button-card
        template: selector
        entity: input_select.home_theater_aspect_ratio
        variables:
          value: '1:78.1'

```
(the input_select helper does exist, and includes these values as valid options)

**Expected behavior**
* Each button highlighted when the value of the input_select helper matches
* The value of the input_select helper changes value when button is clicked

**Desktop (please complete the following information):**
 - Browser: Firefox
 - Version: 111.0.1

**Comment by pejotigrek** [comment]
don't know if my problem is totally related, but I guess there's something wrong going on with variables.
I am trying to utilize variables just to save a lot of typing and use them in different templates, buttons etc., but variables are always "undefined".

I tried with the simplest code possible:

```yaml
- type: custom:button-card
  entity: update.0_sts_zamel
  variables:
    test_var: "this-is-test"
  name: "[[[ return variables.test_var; ]]]"
```

and still - instead of default button with "this-is-test" as name, I can see the entity's name anyway..

button card: 3.5.0, homeassistant: 2023.04.4, browser: latest chrome
