### ISSUE TITLE
tap_action executed despite being in lock state

### ISSUE THREAD

**Issue by arifroni** [custom-cards/button-card#688]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
When I press the button, whether it is locked or not locked, tap_action executes.

**Version of the card**
Version: 3.5

**To Reproduce**
This is the configuration I used:
```
- type: custom:button-card
  entity: sensor.deebot_kajer_beti_ronbot_queue
  icon: mdi:play-pause
  name: '[[[ if (entity.state === "") return "Select Rooms"; else return "Start Clean" ]]]'
  aspect_ratio: 2.6/1
  triggers_update: 
    - vacuum.kajer_beti_ronbot
  lock:
    enabled: |
      [[[ 
        return !entity.state || 
          entity.state.length === 0 ||
          states['vacuum.kajer_beti_ronbot'].state !== 'docked'
      ]]]
    exemptions: []
  tap_action:
    action: call-service
    # service: script.deebot_clean
    service: notify.persistent_notification
    service_data:
      message: msg
      title: title
  styles:
    icon:
      - width: 1.8em
    card:
      - color: var(--disabled-text-color)
    lock:
      - color: var(--primary-text-color)
      - width: 2em
  state:
    - operator: template
      value: |
        [[[ return states['vacuum.kajer_beti_ronbot'].state === 'returning' ]]]
      name: Returning...
      icon: mdi:toilet
      spin: true
    - operator: template
      value: |
        [[[ return states['vacuum.kajer_beti_ronbot'].state !== 'docked' ]]]
      name: Cleaning...
      icon: mdi:cog
      spin: true
    - operator: template
      value: |
        [[[ return (entity.state || entity.state.length > 0) ]]]
      styles:
        card:
          - color: var(--text-color)
        icon:
          - color: var(--text-color)
```

**Screenshots**
![msedge_2023-04-26_15-33-48](https://user-images.githubusercontent.com/59896374/234592198-3ef7ce91-d304-439a-8360-cfd272930c69.gif)

**Expected behavior**
When the icon is locked, i expect nothing happens when i click the button

**Desktop (please complete the following information):**
 - Browser: Microsoft Edge
 - Version 112.0.1722.58

Home Assistant 2023.5.2
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230503.3 - latest
