### ISSUE TITLE
Lock icon shows above all layers and dialogs

### ISSUE THREAD

**Issue by chertvl** [custom-cards/button-card#694]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser

**Describe the bug**
In 2023.05 something changed in frontend, and now card Lock icon (lock:  enabled: true) displays above all layers and windows.

**Version of the card**
Version: 3.5.0

**To Reproduce**
Place card with `lock: enabled: true`  and open any more-info dialog.
```
    type: custom:button-card
    entity: sensor.home_energy
    lock:
      enabled: true
```

**Screenshots**
![image](https://user-images.githubusercontent.com/38353584/236263607-56968425-e7a7-4d71-b7e0-7527b22d3537.png)

**Expected behavior**
This has not happened before
