### ISSUE TITLE
Failed to call switch/turn_on service. must contain at least one of entity_id, device_id, area_id.

### ISSUE THREAD

**Issue by francesc0s** [custom-cards/button-card#709]
**Checklist**
- [x ] I updated the card to the latest version available
- [x ] I cleared the cache of my browser

**Describe the bug**
Receiving the error below even when an entity_id is present

_Failed to call switch/turn_on service. must contain at least one of entity_id, device_id, area_id._

**Version of the card**
Version: 3.5.0

**To Reproduce**
This is the configuration I used:
```yaml
                            - type: custom:button-card
                              entity_id: light.light_entry_corner_hue
                              name: 'Off'
                              show_name: true
                              show_icon: false
                              tap_action:
                                action: call-service
                                service: light.turn_off
                                target:
                                  entity_id: >-
                                    light.light_entry_lamp
                                    light.light_entry
                                    light.kitchen
```

**Screenshots**

**Expected behavior**
Lights to turn off

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 114.0.5735.134

**Smartphone (please complete the following information):**
 - Device: Pixel 7
 - OS: Android 13
 - Browser Companion App
 - Version 2023.6.0

**Additional context**
