### ISSUE TITLE
New Action : Assist

### ISSUE THREAD

**Issue by neilimixamo** [custom-cards/button-card#711]
Hi, would it be possible to incorporate the new "assist" action that has been introduced in HA version 2023.7  ? 
Thank you so much for this amazing card.

![image](https://github.com/custom-cards/button-card/assets/43101688/8ccb36df-81fe-4c04-8c95-26e4c271a6b3)

**Comment by ndom91** [comment]
Yeah looking to use this here as well. Currently only seems to be supported by the built-in `Button`

**Comment by smartqasa** [comment]
Plus 1

**Comment by skank01** [comment]
+1
Tried using it with custom button card, but it seems it doenst work

**Comment by Mariusthvdb** [comment]
There’s a developers blog post on the subject of adding the new hass-action

https://developers.home-assistant.io/blog/2023/07/07/action-event-custom-cards/

**Comment by Mariusthvdb** [comment]
thanks for adding, and I can confirm it to work correctly! Magic.

1 caveat: there seems to be a discrepancy using the theme colors on this button

```
show_name: true
show_icon: true
type: custom:button-card
tap_action:
  action: assist
  start_listening: true
entity: input_button.assist
show_state: false
name: Assist
```

<img width="440" alt="Scherm­afbeelding 2023-07-24 om 07 50 48" src="https://github.com/custom-cards/button-card/assets/33354141/ff111d61-03df-479e-985e-1460f0bd3176">

while the exact same card:
```
show_name: true
show_icon: true
type: button
tap_action:
  action: assist
  start_listening: true
entity: input_button.assist
show_state: false
name: Assist
```

shows 
<img width="425" alt="Scherm­afbeelding 2023-07-24 om 07 50 43" src="https://github.com/custom-cards/button-card/assets/33354141/565954b0-fa5d-41b9-8bda-9fa30e852c37">

according to my theme.
Minor thingy, made user error, just mentioning for reference in this new development.

Thanks again!

**Comment by Mariusthvdb** [comment]
separate, just for the fun of it:
```
type: custom:button-card
aspect_ratio: 1
show_name: true
show_icon: false
tap_action:
  action: assist
  start_listening: true
entity: input_button.assist
show_state: false
name: Assist
styles:
  card:
    - background-image: |
        [[[ return  `url("/local/images/yotv.png")`; ]]]
    - background-size: cover
    - background-repeat: no-repeat
    - color: blue
  name:
    - font-size: 20px
    - font-weight: bold
    - position: absolute
    - top: 5%
    - left: 42%
```

<img width="395" alt="Scherm­afbeelding 2023-07-24 om 11 43 45" src="https://github.com/custom-cards/button-card/assets/33354141/047bc7b7-79c3-454c-bc34-8061004b97ee">

so nice we can now do this!
