### ISSUE TITLE
Fails to call service: connection lost

### ISSUE THREAD

**Issue by Zynth-dev** [custom-cards/button-card#715]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser

**Describe the bug**
When calling a service from the tap_action, the connection to that service seems to be lost.
The given error: "Failed to call service remote/send_command. Connection lost"
When I change the type from "type: custom:button-card" to "type: button" it does work.

**Version of the card**
Version: 3.5.0

**To Reproduce**
This is the configuration I used:
Reminder: changing type from "custom:button-card" to "button" makes the tap_action complete successfully
So 
```
      - color_type: card
        aspect_ratio: 1.8
        tap_action:
          action: call-service
          service: remote.send_command
          target:
            device_id: e582b91dd1f7f655ed06c587fa78f41e
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            command: power
            device: duux
        entity: script.do_nothing
        icon: mdi:fan
        name: Power
        template: defaultcard
        type: custom:button-card

```

**Screenshots**

**Expected behavior**

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version 114.0.5735.198 (Official Build) (x86_64)

**Smartphone (please complete the following information):**

**Additional context**
