### ISSUE TITLE
Please add option for mqtt.send service

### ISSUE THREAD

**Issue by hristo-atanasov** [custom-cards/button-card#72]
I tried:

>       - service:
>           domain: mqtt
>           action: publish
>           data:
>             topic: cmnd/kitchenBlaster/IRsend
>             payload: '{"Protocol":"NEC","Bits": 32,"Data":"0x20DF23DC"}'
>         icon: 'mdi:leaf'
>         style:
>           - '--disabled-text-color': white
>         type: 'custom:button-card'

Also tried:

>       - service:
>           domain: mqtt
>           action: publish
>           data: {'topic': 'cmnd/kitchenBlaster/IRsend', 'payload': '{"Protocol":"NEC","Bits": 32,"Data":"0x20DF23DC"}'
>         icon: 'mdi:leaf'
>         style:
>           - '--disabled-text-color': white
>         type: 'custom:button-card'

Well I tried a lot of variants, but no one worked ..

**Comment by PlatoNL** [comment]
Just do:
```
             service:
              domain: script
              action: some_script_name
```
In your lovelace-ui.yaml

and then:
```
some_script_name:
  sequence:
  - data:
      payload: button_pushed
      topic: some/topic
    service: mqtt.publish
```
in your scripts.yaml
