### ISSUE TITLE
Sony Bravia Tv controls

### ISSUE THREAD

**Issue by gozdagno** [custom-cards/button-card#720]
**Is your feature request related to a problem? Please describe.**
Hi. I want to make a simple Remote for Sony Bravia TV. When I create the normal button to call the service, it works ok, but I can't get it to work with Custom buttons. I need it for placing buttons in the array, so they look similar to real life remote. When I press the custom button with code pasted from working normal button, it says _required key not provided @ data 'command'_. Any help would be great.

**Describe the solution you'd like**
I would just be happy if the remote.send_command action works with Custom buttons.

**Describe alternatives you've considered**
Custom buttons would be the best solution, as they are fully customiseable. There are some other remote integrations, but i want my custom one.

**Additional context**

- Sony Bravia Home Assistant integration: [https://www.home-assistant.io/integrations/braviatv/](url)
- Code copied from working normal button (for turning the TV on and off): 
```
show_name: true
show_icon: true
type: button
tap_action:
  action: call-service
  service: remote.send_command
  data:
    command: TvPower
  target:
    entity_id: remote.sony_xr_75x92j
entity: remote.sony_xr_75x92j
name: ON/OFF
```
- Code for Custom button (for turning the TV on and off) that I can't get to work:
```
type: custom:button-card
tap_action:
  action: call-service
  service: remote.send_command
  data:
    command: TvPower
  target:
    entity_id: remote.sony_xr_75x92j
entity: remote.sony_xr_75x92j
show_name: false
```

**Comment by xZetsubou** [comment]
Don't use target and data keys insert all data into `service_data`
this should work for you:
```yaml
type: custom:button-card
tap_action:
  action: call-service
  service: remote.send_command
  service_data:
    command: TvPower
    entity_id: remote.sony_xr_75x92j
entity: remote.sony_xr_75x92j
show_name: false
```
