### ISSUE TITLE
state: wont override core icon

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/button-card#726]
**Checklist**
- [ X] I updated the card to the latest version available
- [X ] I cleared the cache of my browser

**Describe the bug**

since the new state icon calculation is taken from core HA in version 4 (dev), the following config wont set the icon anymore, even though it is places last in the config

**Version of the card**
Version: 
400dev5
**To Reproduce**
This is the configuration I used:
```yaml
type: custom:button-card
show_name: true
entity: input_boolean.override_cover_dorm

state:
  - value: 'on'
    id: on-picture
    icon: mdi:window-shutter-alert
  - value: 'off'
    id: off-picture
    icon: cil:shutter-0
```

**Screenshots**
<img width="136" alt="Scherm­afbeelding 2023-07-24 om 10 06 59" src="https://github.com/custom-cards/button-card/assets/33354141/a9708921-fdaf-4b52-a393-f2766a7f3bc1">

**Expected behavior**
have the `state:` config override the icon

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

I can override the icon with:
```
icon: >
  [[[ return (entity.state === 'on') ? 'mdi:window-shutter-alert' : 'cil:shutter-0'; ]]]
# state:
#   - value: 'on'
#     id: on-picture
#     icon: mdi:window-shutter-alert
# #            entity_picture: /local/modes/spike_on.png
#   - value: 'off'
#     id: off-picture
#     icon: cil:shutter-0
```
<img width="130" alt="Scherm­afbeelding 2023-07-24 om 10 16 14" src="https://github.com/custom-cards/button-card/assets/33354141/5e286437-9fd2-4bc7-9fe8-946f3cf57196">
<img width="140" alt="Scherm­afbeelding 2023-07-24 om 10 16 47" src="https://github.com/custom-cards/button-card/assets/33354141/439866a9-5298-4297-9a19-1f1ddb67b470">

which is perfectly fine of course. It's just a bit unexpected the `state:` wont work anymore

**Comment by RomRider** [comment]
It works well on my side, so there's maybe something in the button-card templates you're using that breaks it?
```yaml
              - type: 'custom:button-card'
                color_type: card
                entity: switch.skylight
                state:
                  - value: 'on'
                    icon: mdi:alert
                  - value: 'off'
                    icon: mdi:flash
```
![image](https://github.com/custom-cards/button-card/assets/21064206/a49c3e21-bb28-4ca3-bfe2-71a21c0d9810)![image](https://github.com/custom-cards/button-card/assets/21064206/8f60df68-7045-4625-8f1a-e0a0eff02272)
