### ISSUE TITLE
animated icon not centered on mobile

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/button-card#727]
**Checklist**
- [X ] I updated the card to the latest version available
- [ X] I cleared the cache of my browser

**Describe the bug**

somehow an animated icon is way off center when displayed in the iOS app. Maybe it's because of the size of the button (always use grid: 4 aspect_ratio: 1 buttons?

**Version of the card**
Version: 
400-b8
**To Reproduce**
This is the configuration I used:
```yaml
        - type: custom:button-card
          template:
            - button_switch
            - spin

          entity: switch.vijverpomp_links
          triggers_update: sensor.vijverpomp_links_actueel
          name: Pomp left
          icon: mdi:turbine

# spin template:


spin:
  state:
    - value: 'on'
      id: state-on
      spin: true

# might be relevant part of the bigger template used:
styles_img_cell:
  styles:
    img_cell:
      - align-items: start
      - justify-content: start
```

**Screenshots**

https://github.com/custom-cards/button-card/assets/33354141/bc6c106f-bfda-45cf-98f7-e256bf12e73a

https://github.com/custom-cards/button-card/assets/33354141/711efeed-1f0c-4148-a7d1-4c106b6a876a

compared to desktop, which seems rather ok..

![Jul-25-2023 10-29-14](https://github.com/custom-cards/button-card/assets/33354141/9056e5dc-9415-4f8d-90ba-3fe8dc363710)
![Jul-25-2023 10-31-26](https://github.com/custom-cards/button-card/assets/33354141/897d3d8f-4cc6-4391-a452-0c9414c0bff1)

**Expected behavior**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

This has always been around in some form, but now is showing rather unacceptably off-center...

as I have picked the most centered icon in the library (...), we have to assume it's not that, and must be a matter of the card handling css in some way?

**Comment by RomRider** [comment]
Nothing I can do about that, I think. Seems like the icon is not "centered". Is it a `mdi` icon?

**Comment by Mariusthvdb** [comment]
yes it is.
what I dont get is why it is near perfect on desktop, but so off on app mobile

**Comment by Mariusthvdb** [comment]
Ive found tha final template causing this:
```
state_display_switch:
  template: styles_state_default

#   show_state: true

  state_display: >
    [[[ var id = entity.entity_id.split('.')[1];
        var power = states['sensor.' + id + '_actueel'].state;
        var fakestate = `<span style="color: var(--active-color);"> ${localize(entity)}</span>`;
        var fakestateOff = `<span style="color: var(--active-background-color);"> ${localize(entity)}</span>`;
        var powerState = `<span style="color: var(--power-color);"> ${power} W</span>`;
        return (entity.state === 'on') ? fakestate +': ' + powerState :
        (entity.state === 'off' && power > 0) ? fakestateOff +': ' + powerState : null; ]]]

styles_state_default:
  template: styles_state_default_auto
  state:
    - value: 'on'
      styles:
        icon:
          - color: var(--icon-color-on)
      id: state-on
```

so if I comment the `show_state: true`, the icon is fixed as can be....

ofc this only stop the state_display template from showing, so I need to dig deeper. At least this is a step closer to a solution...

**Comment by RomRider** [comment]
So I found why but I can't do anything about it as I can style the shadow root of the ha-state-icon (which wraps a ha-icon inside...)

Maybe you can try with card-mod like that:
```yaml
card-mod:
  "#container #img-cell ha-state-icon$": |
    ha-icon {
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
    }
```

**Comment by RomRider** [comment]
Even better it seems...

```yaml
            card_mod:
              style:
                '#container #img-cell ha-state-icon#icon$':
                  ha-icon$: |
                    ha-svg-icon {
                      display: inline;
                    }
```
