### ISSUE TITLE
ha-state-icon change requiring config change?

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/button-card#728]
**Checklist**
- [X ] I updated the card to the latest version available
- [X ] I cleared the cache of my browser

**Describe the bug**

Sorry if this is more of a question than an issue, but not biggie enough for a first discussion:...

[since b2 follows ha-state-icon](https://github.com/custom-cards/button-card/releases/tag/v4.0.0-dev.2), do we need to change that in our configs too?:
in other words, do we need to change:
```
  custom_fields:
    icon: >
      [[[ return `<ha-icon icon='mdi:lock-alert'></ha-icon>`; ]]]
```
to

```
  custom_fields:
    icon: >
      [[[ return `<ha-state-icon icon='mdi:lock-alert'></ha-state-icon>`; ]]]
```

ofc, I did first try this before posting, and both seem to work, without any errors in the log. So just asking for confirmation, and generic guideline.

**Version of the card**
Version: 

**To Reproduce**
This is the configuration I used:
```yaml
  custom_fields:
    icon: >
      [[[ return `<ha-icon icon='mdi:lock-alert'></ha-icon>`; ]]]
  styles:
    custom_fields:
      icon:
        - position: absolute
        - left: 70%
        - top: 5%
        - z-index: 5
        - height: 22px
        - width: 22px
        - color: red
```

**Screenshots**

<img width="135" alt="Scherm­afbeelding 2023-07-25 om 11 22 33" src="https://github.com/custom-cards/button-card/assets/33354141/9136e5e3-30e4-4666-bb79-939c19495b07">

**Expected behavior**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

before you ask why I dont use the lock config option: these are buttons where the lock is permanent, so no option to unlock is allowed. `-alert` indicating that, and setting those buttons apart from the other un unlockable buttons in my config

<img width="520" alt="Scherm­afbeelding 2023-07-25 om 11 24 26" src="https://github.com/custom-cards/button-card/assets/33354141/32e6248f-d193-41fb-9027-dbaca5fa71e2">
