### ISSUE TITLE
Some files left from Button-Card doesn't allow for fresh install

### ISSUE THREAD

**Issue by dawidblum** [custom-cards/button-card#729]
**Checklist**
- [ ✅ ] I updated the card to the latest version available
- [ ✅ ] I cleared the cache of my browser

**Describe the bug**
Uninstalling 3.5.0 version of Button-card leaves files in HA that affect new installs.
![Button-card](https://github.com/custom-cards/button-card/assets/87432265/047a87ed-3e2f-49c2-8fdd-656c3d3c25cf)

**Version of the card**
Version: 4.0.0 Dev.10

**To Reproduce**
Install 3.5.0 version, remove it after that it stays in web browers console. Orange text "Button Card". When installing 4.0.0 after that (or any other version) console provides this information:
```
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "button-card-action-handler" has already been used with this registry
```

This is the configuration I used:
```yaml

homeassistant:
  customize: !include customize.yaml
  auth_providers:
  - type: homeassistant
  whitelist_external_dirs:
  - /data/data/com.termux/files/home/AIS/www/


http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
    

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


input_number: !include input_number.yaml
input_select: !include input_select.yaml


panel_iframe:
  coder:
    title: Code
    icon: mdi:microsoft-visual-studio-code
    url: "http://192.168.1.3:8088"


frontend:
  themes: !include_dir_merge_named themes


sensor:
  - platform: template
    sensors:
      count_lights:
        friendly_name: Włączone światła
        value_template: >
            {% set lights = [
              states.light.salon_1,
              states.light.salon_2,
              states.light.salon_3,
              states.light.kuchnia,
              states.light.hue_lightstrip_plus_1,
              states.light.korytarz,
              states.light.sypialnia,
              ] %}
            {{ lights | selectattr('state','eq','on') | list | count }}
  - platform: template
    sensors:
      count_sockets:
        friendly_name: Włączone gniazdka
        value_template: >
            {% set lights = [
              states.switch.gniazdko_5,
              states.switch.gniazdko_5_2,
              states.switch.gniazdko_3,
              states.switch.gniazdko,
              states.switch.tasmota,
              states.switch.gniazdko_zmywarka
              ] %}
            {{ lights | selectattr('state','eq','on') | list | count }}

```

**Screenshots**
https://imgur.com/a/rhSxHr9

**Expected behavior**
Button Card not appearing in console logs after uninstalling and clearing browser cache.

**Desktop:**
 - Browser Opera Gx

**Smartphone:**
 - Device: Samsung A52s
 - OS: Android 11
