### ISSUE TITLE
Prevent Notification overflowing card

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/button-card#732]
**Is your feature request related to a problem? Please describe.**

Since this probably isnt an issue, but user error, please let me post it as FR..

Having a notification with dynamic text strings possibly overflow the card, especially when on mobile.

https://github.com/custom-cards/button-card/assets/33354141/f0d99546-6f95-4e5c-9709-616ca8f8f287

note it does respect the card padding on the right, but not on the left

**Describe the solution you'd like**

Would love to have some default setting for these custom_fields to never overflow the card, maybe even use newline or some other clever way of preventing it.

**Describe alternatives you've considered**

Ive tried to prevent it by setting a max-width, but that is a bit silly in 2 ways:
first it is not required on the desktop card, only on the mobile card, since that is smaller

second, it truncates the text with ending ... replacing the text it would otherwise show ;-)

![20230726_092742000_iOS](https://github.com/custom-cards/button-card/assets/33354141/fa361598-7504-4256-8070-18aec3b8616a)

Ive alsof tried:
```
      - word-break: break-all
```

but it does exactly nothing, even though [W3 states](https://www.w3schools.com/cssref/css3_pr_word-break.php):

_To prevent overflow, word may be broken at any character_

which is exactly what I am after...

**Additional context**

Nevermind the notification showing over the icon, that is on purpose/not an issue.

**Comment by andyblac** [comment]
have you tried using `%` as font size instead of `px`, this should then scale the font by the card size.

like I did here.

From Mac
<img width="90" alt="Screenshot 2023-08-15 at 10 09 03" src="https://github.com/custom-cards/button-card/assets/77936/addfb76a-c32b-4af8-af87-0369a61792d6">

From iPhone
<img width="99" alt="Screenshot 2023-08-15 at 10 09 16" src="https://github.com/custom-cards/button-card/assets/77936/91f33663-f0e1-49d0-a5ca-faba0a75d778">

**Comment by Mariusthvdb** [comment]
not scaling the font, but I didnt see this anymore, and I've added some text-overflow on the type field.

I also notice I didn't add the cards code I use..
let me fix the for reference, focussed on the notification:

```
type: custom:button-card
visibility:
  - condition: state
    entity: binary_sensor.meteoalarm_brabant
    state: 'on'
template:
  - button_body
  - styles_cf_notification
entity: binary_sensor.meteoalarm_brabant
name: MeteoAlarm

styles:

  grid:
    - grid-template-areas: '"i alert" "n n" "type type" "level level" "severity severity"'
    - grid-template-columns: 1fr 1fr
    - grid-template-rows: 1fr min-content min-content min-content min-content

  custom_fields:
    notification:
      - border-color: '[[[ return variables.meteo_color; ]]]'
      - color: >
          [[[ return entity.state === 'on' ? 'variables.meteo_color' : 'ivory'; ]]]
      - background: >
         [[[ return entity.state === 'on' ? 'rgb(226,239,248)' : 'green'; ]]]
      - animation: >
         [[[ return entity.state === 'on' ? 'blink 2s ease infinite' : 'none'; ]]]
      - max-width: 85px
      - word-break: normal

custom_fields:
  notification: >
    [[[ return entity.state == 'on' ? entity.attributes.headline.split(' -')[0] : 'noti'; ]]]

```

while this is the template for the styles_cf_notification:

```
styles_cf_notification:
  styles:
    custom_fields:
      notification:
        - border: 1px solid var(--text-color-on)
        - box-sizing: border-box
        - border-radius: 12px
        - font-size: 12px
        - font-weight: bold
        - line-height: 20px
        - min-width: 20px
        - min-height: 20px
        - padding: 0px 6px
        - position: absolute
        - top: 10%
        - text-align: center
        - right: 5%
```
