### ISSUE TITLE
Entity bug in V4.0b15

### ISSUE THREAD

**Issue by andyblac** [custom-cards/button-card#734]
**Checklist**
- [ x] I updated the card to the latest version available
- [x ] I cleared the cache of my browser

**Version of the card**
Version: 4.0b15

**Describe the bug**

```
  tap_action:
    action: "more-info"
    entity: "[[[ return variables.ulm_card_person_entity; ]]]"
  name: "[[[ return states[variables.ulm_card_person_entity].attributes.friendly_name ]]]"
  entity: "[[[ return variables.ulm_card_person_entity; ]]]"
  icon: "[[[ return variables.ulm_card_person_icon; ]]]"
  show_entity_picture: "[[[ return variables.ulm_card_person_use_entity_picture ]]]"
  entity_picture:
    "[[[ return variables.ulm_card_person_use_entity_picture ? states[variables.ulm_card_person_entity].attributes.entity_picture\
    \ : null ]]]"
```

in V3.5 the above code works fine, but in v4.0b12, when you set an entity in the tap_action and then tap on it in the dashboard you see the following error.
<img width="651" alt="Screenshot 2023-07-27 at 09 52 33" src="https://github.com/custom-cards/button-card/assets/77936/1ffe593f-65f1-4922-a1fb-164fb8abe964">

in the example above the action entity and the main entity, both use the same entity variable.

**Expected behavior**
it should show the person enity

**Comment by RomRider** [comment]
Can you share the relevant main card config please?
The code has changed on the custom_fields part on those new versions

**Comment by RomRider** [comment]
This works well:
```yaml
          - type: custom:button-card
            variables:
              entity: light.test_light
            styles:
              grid:
                - grid-template-areas: "'test' 'icon'"
            custom_fields:
              test:
                card:
                  icon: mdi:fan
                  type: custom:button-card
                  entity: '[[[ return variables.entity; ]]]'
                  tap_action:
                    action: more-info
                    entity: '[[[ return variables.entity; ]]]'
```
So there's something else going on with your code

**Comment by andyblac** [comment]
```
          - type: "custom:button-card"
            template:
              - custom_card_andyblac_person
            entity: person.christine_leek
            variables:
              ulm_card_person_entity: person.christine_leek
              ulm_card_person_use_entity_picture: false
              ulm_card_person_icon: mdi:face-woman
              ulm_card_person_battery: sensor.christines_iphone_icloudv3_battery
              ulm_address: sensor.christines_iphone_icloudv3_zone_name
              ulm_card_person_eta: sensor.christines_iphone_icloudv3_zone_distance
```

thats the dashbaord code, I have also attached the entier YAML for the template.
[custom_card_andyblac_person.yaml.zip](https://github.com/custom-cards/button-card/files/12181586/custom_card_andyblac_person.yaml.zip)

**Comment by RomRider** [comment]
Yeah, so what you are doing has never been possible, as state in my last comment, you can't template `entity` or `show_entity_picture` in the main button-card. This never worked so it's unrelated to the latest beta.

**Comment by andyblac** [comment]
this is strange because it works in 3.5 and Minimalist project use it all over.

**Comment by andyblac** [comment]
like here https://github.com/UI-Lovelace-Minimalist/UI/blob/main/custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_person.yaml

**Comment by RomRider** [comment]
Yes, but if you look here https://ui-lovelace-minimalist.github.io/UI/usage/cards/card_person/#usage, you'll see they redefine the entity in the main config + on the variables.

**Comment by andyblac** [comment]
just like i do in my above code.

**Comment by RomRider** [comment]
What is this, then `entity: "[[[ return variables.ulm_card_person_entity; ]]]"` ?

**Comment by andyblac** [comment]
from the template line 14

https://github.com/UI-Lovelace-Minimalist/UI/blob/main/custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_person.yaml#L14

**Comment by RomRider** [comment]
I was speaking about this:
```yaml
  tap_action:
    action: "more-info"
    entity: "[[[ return variables.ulm_card_person_entity; ]]]"
  name: "[[[ return states[variables.ulm_card_person_entity].attributes.friendly_name ]]]"
  entity: "[[[ return variables.ulm_card_person_entity; ]]]" # <<<<<<<<< THIS HERE
  icon: "[[[ return variables.ulm_card_person_icon; ]]]"
  show_entity_picture: "[[[ return variables.ulm_card_person_use_entity_picture ]]]"
  entity_picture:
    "[[[ return variables.ulm_card_person_use_entity_picture ? states[variables.ulm_card_person_entity].attributes.entity_picture\
    \ : null ]]]"
```
