### ISSUE TITLE
helpers.relativeTime(date) doesn't capitalize

### ISSUE THREAD

**Issue by basbruss** [custom-cards/button-card#735]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
The string is not capitalized at the start like it does with other helpers like for example `helpers.localize()`

**Version of the card**
Version:  v4.0.0-dev17

**To Reproduce**
This is the configuration I used:
```yaml
      - type: custom:button-card
        template: card_title
        label: "test relative time"
        name: >
          [[[
            return helpers.relativeTime(states['sensor.sun_next_dawn'].state)
          ]]]
```

**Screenshots**
<img width="202" alt="image" src="https://github.com/custom-cards/button-card/assets/68892092/5ebd3a57-50aa-45a9-bfa0-8a7854c28443">

**Expected behavior**
Capitalized string like is done in this card with pure JS
<img width="251" alt="image" src="https://github.com/custom-cards/button-card/assets/68892092/3f6b3cd4-343b-4d48-a24a-be8c259068d0">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
