### ISSUE TITLE
helpers.relativeTime(date) doesn't work in variable

### ISSUE THREAD

**Issue by basbruss** [custom-cards/button-card#736]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
```yaml
return helpers.relativeTime(entity.state)
```
It only works when it is used directly in a YAML key as `name` or `label`
It does not work when it's included in a variable.

**Version of the card**
Version: 

**To Reproduce**
This is the configuration I used:
```yaml
      - type: custom:button-card
        template: card_title
        entity: sensor.sun_next_dawn
        label: "test relative time"
        name: >
          [[[
            return helpers.relativeTime(entity.state)
          ]]]
      - type: custom:button-card
        template: card_title
        entity: sensor.sun_next_dawn
        label: "test relative time"
        name: >
          [[[
            return variables.test
          ]]]
        variables:
          test: >
            [[[
              return helpers.relativeTime(entity.state)
            ]]]
```
It renders the error
```error
TypeError: e.trim is not a function
    at ki._getTemplateOrValue (button-card.js?hacstag=14619432540017:440:2813)
    at button-card.js?hacstag=14619432540017:440:2770
    at Array.forEach (<anonymous>)
    at ki._getTemplateOrValue (button-card.js?hacstag=14619432540017:440:2747)
    at button-card.js?hacstag=14619432540017:440:2770
    at Array.forEach (<anonymous>)
    at ki._getTemplateOrValue (button-card.js?hacstag=14619432540017:440:2747)
    at button-card.js?hacstag=14619432540017:440:2770
    at Array.forEach (<anonymous>)
    at ki._getTemplateOrValue (button-card.js?hacstag=14619432540017:440:2747)
```

**Screenshots**

**Expected behavior**
Both cards should return the same values

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
