### ISSUE TITLE
How to use colors in 4.0.0?

### ISSUE THREAD

**Issue by fxxer** [custom-cards/button-card#737]
**Is your feature request related to a problem? Please describe.**
I had a simple template card, for all lights and switches. It worked like a charm. After upgrade I can't find the rigth configuration, to get to previous setup. Please help.

```
button_card_templates:
  switch:
    hold_action:
      action: more-info
    tap_action:
      action: toggle
    type: custom:button-card
    color: auto
    color_type: card
```
<img width="829" alt="Screenshot 2023-07-29 at 21 44 37" src="https://github.com/custom-cards/button-card/assets/4021387/0bcca088-c0bb-4e6b-88f7-2308903d2128">

After update. TV lamp is on and water is on, it's confusing.

<img width="831" alt="Screenshot 2023-07-29 at 21 48 19" src="https://github.com/custom-cards/button-card/assets/4021387/da5eb2e4-bafc-4b7f-a9a2-4205e706600d">

**Describe the solution you'd like**
How can I replicate this behaviour in 4.0.0? I tried styles, different colours setting using var(--paper .. with no luck.

**Comment by pergolafabio** [comment]
Same question, all my card icons are white, not sure how need to define colors again, if you have more info, pls post

**Comment by pickonedev** [comment]
```
state:
  - value: 'on'
    styles:
      name:
        - color: '#850016'
      card:
        - background-color: '#fdd835'
  - value: 'off'
    styles:
      name:
        - color: '#44739e'
```

**Comment by pergolafabio** [comment]
and for the icons? how can i reperesent the real color of the icon based on its state?

**Comment by pickonedev** [comment]
This is how I done in the past, because some entities won't give the color to the addon...
So... For the you can add like this:

```
state:
  - value: 'on'
    styles:
      name:
        - color: '#fdd835'
      icon:
        - color: '#fdd835'
  - value: 'off'
    styles:
      name:
        - color: '#44739e'
      icon:
        - color: '#44739e'
```

**Comment by pergolafabio** [comment]
yes, but thats a fixed color for the ON state, i want to represent the real color, i also have leds, wheni have for example the led on "green", i also want the icon to be green

**Comment by pickonedev** [comment]
Maybe a helper which represent the value of the led and regarding this, will change the color as well... But yeah, this is not ok... Just a workaround, I'm not the developer of the addon :-|

**Comment by Mariusthvdb** [comment]
this must be a regression introduced in the later stages of the beta testing, as I had not seen it before and can comfort the light cards no linger show a color icon, or other color elements according to the color attribute of the light. IN fact, I dont see an icon at all...

otoh, I am on beta 2023.8.x now and also see the sliders on those lights are no longer coloring, so it might very well be a core issue..?

**Comment by fxxer** [comment]
> ```
> state:
>   - value: 'on'
>     styles:
>       name:
>         - color: '#850016'
>       card:
>         - background-color: '#fdd835'
>   - value: 'off'
>     styles:
>       name:
>         - color: '#44739e'
> ```

This is quick solution, but I am afraid not optimal for light / dark themes.

**Comment by pergolafabio** [comment]
> Maybe a helper which represent the value of the led and regarding this, will change the color as well... But yeah, this is not ok... Just a workaround, I'm not the developer of the addon :-|

So the icon not getting the real color maybe a bug?

**Comment by Mariusthvdb** [comment]
Yes seems to be.
No use continuing here if it's a core bug...

Please see https://discord.com/channels/330944238910963714/427516175237382144/1135166058752376872 and add your findings if they are the same . It will help prevent this bug from being released Wednesday

**Comment by pergolafabio** [comment]
Hmm, for me the slider changes when I change color, it's just in this button card I don't see the icon changing colors...

Probably for me a misconfiguration? Can you post your config? Or do you use "color: auto"

![Screenshot_20230730-140107](https://github.com/custom-cards/button-card/assets/43251136/1dbec6f9-1df9-4000-bce1-5bf4b6b7f23c)

**Comment by Mariusthvdb** [comment]
https://github.com/custom-cards/button-card/assets/33354141/ea325d16-fd00-4b38-a4f3-461226167ffe

**Comment by Mariusthvdb** [comment]
wait, I did some cache refreshing and gave it a restart, and now see the color back on the border top, and the core button card. and Tile card.

not so much the custom:button-card:

<img width="139" alt="Scherm­afbeelding 2023-07-30 om 15 08 11" src="https://github.com/custom-cards/button-card/assets/33354141/cf85fed9-9d5b-42cc-bf05-951bbff02240">


pure cards:

<img width="572" alt="Scherm­afbeelding 2023-07-30 om 15 11 47" src="https://github.com/custom-cards/button-card/assets/33354141/0b74b779-5c38-4131-a470-8af90ccccdb3">

seems a clear issue: custom:button-card no longer sets the correct color to the icon.

**Comment by pergolafabio** [comment]
ok, thnx for confirming :-)

**Comment by Mariusthvdb** [comment]
this is a bug, and shouldnt be phrased as a config question imho, could op change that please?

**Comment by RomRider** [comment]
Sorry 🙏 Fixing it right now

**Comment by pergolafabio** [comment]
Thnx for fast fix!

**Comment by fxxer** [comment]
If you are using color_type: card , the colors are in my opinion reverted between dark / light theme :( 
![Screenshot 2023-07-30 at 16 52 59](https://github.com/custom-cards/button-card/assets/4021387/3745a9f4-f0d7-4e3d-81e7-727d89324ecc)

**Comment by RomRider** [comment]
The off color is different than before, now it's `--state-inactive-color` (following exactly what HA does) so for color_type: card, you might want to redefine that maybe?

```
states:
  - value: 'off'
    styles:
      card:
        - background: "whatever you want" 
```

**Comment by RomRider** [comment]
I'll try something for color_type: card... Hold on

**Comment by RomRider** [comment]
Is this what you expect? Or would expect the icon when off to be the same as the default button?
* OFF
  ![image](https://github.com/custom-cards/button-card/assets/21064206/c2a78dcf-fb4a-4297-9e85-2925683deb75)

* ON
  ![image](https://github.com/custom-cards/button-card/assets/21064206/ec254cf0-ed47-4af3-95e3-30d66174f915)

**Comment by fxxer** [comment]
> Is this what you expect? Or would you also expect the icon when off to be the same as the default button?
> 
> `HA Button` is the default button from HA and `custom` is `custom:button-card`:
> 
> * OFF
>   ![image](https://user-images.githubusercontent.com/21064206/257070427-c2a78dcf-fb4a-4297-9e85-2925683deb75.png)
> * ON
>   ![image](https://user-images.githubusercontent.com/21064206/257070451-ec254cf0-ed47-4af3-95e3-30d66174f915.png)

Pretty much, what I am going for :) is it working correctly in light theme?

**Comment by Sethenor** [comment]
For me it's still showing the wrong colors. Like mentioned in the documentation:
`Setting this to auto-no-temperature will behave like home-assistant's default, ignoring the temperature of the light. By default, if the entity state is off, the color will be var(--paper-item-icon-color), for on it will be var(--paper-item-icon-active-color)`

Yet if I use `auto-no-temperature` it still shows the wrong color:
![image](https://github.com/custom-cards/button-card/assets/2983567/8f76aeef-0bd8-432f-9fc9-fa5bef47c308)

But if I define the color specifically for the first button like the documentation says (`var(--paper-item-icon-active-color)`) it should do, it works:
![image](https://github.com/custom-cards/button-card/assets/2983567/c24b943f-5bb8-4fae-8a45-d11863d4cec6)

**Comment by RomRider** [comment]
Sorry, forgot to update the documentation.
For `on` it will use whatever HA uses as `on` color for your entity's domain, this is how it's done:
```js
  properties.push(
    `--state-${domain}-${stateKey}-color`,
    `--state-${domain}-${activeKey}-color`,
    `--state-${activeKey}-color`,
  );
```

If you want to replace the color, you'll have to define it in the card itself for the `on` state.

**Comment by Mariusthvdb** [comment]
sorry if I missed the obvious change in the latest cupola of updates, but I can not get the icon color to work for lights anymore. No

 matter what I try, the icon only uses the default on/off colors:

<img width="578" alt="Scherm­afbeelding 2023-08-03 om 11 26 12" src="https://github.com/custom-cards/button-card/assets/33354141/91c7b968-714a-4634-9857-7a144632c091">

<img width="567" alt="Scherm­afbeelding 2023-08-03 om 11 26 30" src="https://github.com/custom-cards/button-card/assets/33354141/31927b01-7f54-43b4-8b5f-0e6818514aed">

```
type: custom:button-card
entity: light.kayon
name: 'custom button: Kayon'
color: auto-no-temperature
```

above is a Hue light (which integration seems to have an issue with the colors) so I also tested a Tradfri light:

<img width="559" alt="Scherm­afbeelding 2023-08-03 om 11 32 04" src="https://github.com/custom-cards/button-card/assets/33354141/9f99e3f5-9d32-41fa-803d-1adc192c2e57">
<img width="563" alt="Scherm­afbeelding 2023-08-03 om 11 32 17" src="https://github.com/custom-cards/button-card/assets/33354141/51373b9f-2bd6-4ff9-976e-ba0516d4844c">

same thing....

more sophisticated buttons show the button-card-color is actually correct (see the top border and other elements I use those on)

<img width="128" alt="Scherm­afbeelding 2023-08-03 om 11 33 43" src="https://github.com/custom-cards/button-card/assets/33354141/71edcb67-8e88-4a53-9b80-6b67e05ea397">
<img width="128" alt="Scherm­afbeelding 2023-08-03 om 11 33 50" src="https://github.com/custom-cards/button-card/assets/33354141/e327740a-98a6-4eb2-afe9-271d212dcfb4">

it's the icon that doesnt get colored anymore

**Comment by RomRider** [comment]
Alright, let me review that again... Could you please open a separate issue for that?

**Comment by RomRider** [comment]
Alright, I found the issue... don't create a new issue, it's fine

**Comment by Mariusthvdb** [comment]
have to +1 on it not being fixed unfortunately 

4.1.0:

<img width="563" alt="Scherm­afbeelding 2023-08-03 om 15 21 05" src="https://github.com/custom-cards/button-card/assets/33354141/3fa19b5b-b2f7-420c-bb12-348ea397aca2">

**Comment by Mariusthvdb** [comment]
4.1.1: fixed!

<img width="549" alt="Scherm­afbeelding 2023-08-03 om 15 31 54" src="https://github.com/custom-cards/button-card/assets/33354141/293ead05-2ca8-44aa-b4db-0b175c79d22b">


thank you very much!

**Comment by spider7611** [comment]
Working, thank you!

**Comment by Mariusthvdb** [comment]
you shouldnt be using those paper colors anymore really, cant you follow the new state colors used in HA?

**Comment by fxxer** [comment]
> you shouldnt be using those paper colors anymore really, cant you follow the new state colors used in HA?

Ok, but it should work with color as rgb(0, 122, 255) or this shouldn't be used anymore?

I changed it like this. My aim was to have lights buttons in auto color and buttons for switch in blue..

```
button_card_templates:
  switch:
    hold_action:
      action: more-info
    tap_action:
      action: toggle
    type: custom:button-card
    color: auto
    color_type: card
    state:
      - value: 'on'
        color: rgb(0, 122, 255)
        styles:
          icon:
            - color: white
          name:
            - color: white
```

**Comment by Mariusthvdb** [comment]
its a bit odd, because you have 2 color options set. (auto and the rgb) 

why not create 2 different templates for switch and light. hen have the light template follow the light, so set that to auto

for the switch, use the state: option if you want, and, set a card background to the color you desire in the styles object.

**Comment by fxxer** [comment]
I have 2 different templates for switch and light .. I was just lazy to copy both :) what I am trying to say is when using color as rgb, the card background color is reverted as mentioned before.

For example:

```
button_card_templates:
  switch:
    hold_action:
      action: more-info
    tap_action:
      action: toggle
    type: custom:button-card
    color: rgb(0, 122, 255)
    color_type: card
```


> Light Mode ![Screenshot 2023-08-03 at 19 33 07](https://user-images.githubusercontent.com/4021387/258190477-edb3faf7-bc07-45c3-84d9-f8eeb05f3dfb.png)
> 
> Dark Mode ![Screenshot 2023-08-03 at 19 33 50](https://user-images.githubusercontent.com/4021387/258190622-bebdcfa3-1fa1-4dac-9d28-b217eb0dd45f.png)
>
