### ISSUE TITLE
"lock" option not working on mobile devices since update to 4.0.0

### ISSUE THREAD

**Issue by TheBToby** [custom-cards/button-card#740]
**Checklist**
- I updated the card to the latest version available
- I cleared the cache of my browser

**Describe the bug**
The "lock" option is not working on my mobile devices (iOS) after upgrading to 4.0.0 (app and browser). Works with no issue on the desktop browser version (Windows). The button still works (action), but does not respect the lock functionality and also does not show the lock icon.

**Version of the card**
Version: 4.0.0

**To Reproduce**
This is the configuration I used:
```yaml
show_name: true
show_icon: true
type: custom:button-card
tap_action:
  action: toggle
entity: input_boolean.all_off
icon: mdi:power
lock:
  enabled: true
  duration: 5
```

**Screenshots**

**Expected behavior**
Lock functionality working on the mobile version is the same as before upgrading to 4.0.0 (as described in the config reference and working on the desktop version)

**Desktop (please complete the following information):**
 - Browser [chrome]
 - Version [115.0.5790.110]

**Smartphone (please complete the following information):**
 - Device: [iPhone 14]
 - OS: [iOS 16.5.1]
 - Browser [chrome]
 - Version [115.0.5790.130]

**Additional context**

**Comment by RomRider** [comment]
I don't have a iDevice to test :( But as always apple is doing their own interpretation of HTML/CSS... It's always a PITA.
Will see what I can do

**Comment by Mariusthvdb** [comment]
All of my locks are working as before and confirmation (if configured also)

**Comment by TheBToby** [comment]
Funny thing: just checked with my wife’s Android phone… no issue there 🤔

**Comment by TheBToby** [comment]
double-checked on my MacBook... no issue there as well...

**Comment by RomRider** [comment]
Did you clear the cache of the ios app?

**Comment by TheBToby** [comment]
Yes, I did. I also rebooted the iPhone, Besides the official Home Assistant app for iOS and Chrome I also checked with Safari. Same issue but only on my iOS device (and on my son's iPhone XR, where I double-checked).

**Comment by Mariusthvdb** [comment]
could you try this:
```
lock:
  tap_action:
    action: more-info
    haptic: light
  lock:
    enabled: true
    unlock: hold
    exemptions:
      - username: !secret button_unlock_name_1
      - username: !secret button_unlock_name_2
  confirmation:
    text: >
      [[[ return `Wil je ${entity.attributes.friendly_name} schakelen?`; ]]]
# [[[ return 'Are you sure you want to toggle ' + entity.attributes.friendly_name + '?'; ]]]
  styles:
    lock:
      - color: red
      - icon: mdi:lock-alert
      - z-index: 1
 ```

which is what I use and see working correctly on all iOS devices
