### ISSUE TITLE
nested template in variables  confusion in 4.1.0. dev.1

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/button-card#743]
**Checklist**
- [ X] I updated the card to the latest version available
- [X ] I cleared the cache of my browser

**Describe the bug**

not this is a bug, or a user misconception of the new feature introduces in 410 dev-1 (pull https://github.com/custom-cards/button-card/pull/741)

have a nested variable ( binary == 'on') with a card external  entity used as state inside the second throws no error, but doesnt do anything either. 

Not sure if the 'evaluate once' of this new feature is referring to the loading of the card config, or, as it seems now, also pertains to the actual entity being evaluated or not after loading of the card.

**Version of the card**
Version: 

**To Reproduce**
This is the configuration I used:

original working config, without secondary variable (but repeated entity in the config templates on several spots)
```yaml
type: custom:button-card
template: button_body
entity: sensor.last_motion_triggered #variable.last_motion
variables:
  action_color: >
    [[[ return states['binary_sensor.motion_sensors_all'].state === 'on' ? 'red' : 'grey'; ]]]
tap_action:
  action: more-info
hold_action:
  action: navigate
  navigation_path: >
    [[[ return (window.location.pathname.split('/')[2] != 'beweging')
        ? '/ui-instellingen/beweging' : null; ]]]
icon: >
  [[[ return states['binary_sensor.motion_sensors_all'].state === 'on'
        ? 'mdi:motion-sensor' : 'mdi:motion-sensor-off'; ]]]
name: >
  [[[ var location = `<span style="color:${variables.action_color};font-size:11px;word-wrap:break-word;">
      ${entity.state}</span>`;
      return 'Last motion' + '<br>' + location; ]]]
show_state: false
show_last_changed: true
styles:
  card:
    - color: grey
  icon:
    - color: >
        [[[ return variables.action_color; ]]]
```

added the binary == 'on' as a second variable, and used it inside the action_color variable. This no longer updates that color variable. It does work correctly for the animation and changing the icon:

```
type: custom:button-card
template:
  - button_body
  - extra_styles
entity: sensor.last_motion_triggered
variables:
  trigger_on: >
    [[[ return states['binary_sensor.motion_sensors_all'].state === 'on'; ]]]
  action_color: >
    [[[ return (variables.trigger_on) ? 'red' : 'grey'; ]]]
tap_action:
  action: more-info
hold_action:
  action: navigate
  navigation_path: >
    [[[ return (window.location.pathname.split('/')[2] != 'beweging')
        ? '/ui-instellingen/beweging' : null; ]]]
icon: >
  [[[ return (variables.trigger_on)
        ? 'mdi:motion-sensor' : 'mdi:motion-sensor-off'; ]]]
name: >
  [[[ var location = `<span style="color:${variables.action_color};font-size:11px;word-wrap:break-word;">
      ${entity.state}</span>`;
      return 'Last motion' + '<br>' + location; ]]]
show_state: false
show_last_changed: true
styles:
  card:
    - color: grey
    - animation: >
        [[[ if (variables.trigger_on) return 'wiggle 2s ease infinite';
            return 'none'; ]]]
  icon:
    - color: >
        [[[ return variables.action_color; ]]]
```

**Screenshots**
working state without wiggle

<img width="133" alt="Scherm­afbeelding 2023-07-31 om 09 44 33" src="https://github.com/custom-cards/button-card/assets/33354141/7b6088d9-3a34-4d1a-99ab-c6d6760ba461">

with second variable

<img width="138" alt="Scherm­afbeelding 2023-07-31 om 09 43 40" src="https://github.com/custom-cards/button-card/assets/33354141/70133d78-e02d-4aa0-b062-6aa899d455d2">

ofc we can use both the color and the wiggle ;-)

<img width="139" alt="Scherm­afbeelding 2023-07-31 om 09 46 46" src="https://github.com/custom-cards/button-card/assets/33354141/349a8d61-838d-48bf-b520-3ae5f1c70c2c">

but this requires to verbosely repeat the condition on all places,  which was the reason to try the new variable option:

```
variables:
  action_color: >
    [[[ return (states['binary_sensor.motion_sensors_all'].state === 'on') ? 'red' : 'grey'; ]]]
tap_action:
  action: more-info
hold_action:
  action: navigate
  navigation_path: >
    [[[ return (window.location.pathname.split('/')[2] != 'beweging')
        ? '/ui-instellingen/beweging' : null; ]]]
icon: >
  [[[ return (states['binary_sensor.motion_sensors_all'].state === 'on')
        ? 'mdi:motion-sensor' : 'mdi:motion-sensor-off'; ]]]
name: >
  [[[ var location = `<span style="color:${variables.action_color};font-size:11px;word-wrap:break-word;">
      ${entity.state}</span>`;
      return 'Last motion' + '<br>' + location; ]]]
show_state: false
show_last_changed: true
styles:
  card:
    - color: grey
    - animation: >
        [[[ if (states['binary_sensor.motion_sensors_all'].state === 'on') return 'wiggle 2s ease infinite';
            return 'none'; ]]]
  icon:
    - color: >
        [[[ return variables.action_color; ]]]
```

**Expected behavior**

Nothing 'expected' here, merely hoping this would be possible, so please close if this cant be done after all.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Working alternative: use the same binary in both variable declarations:
```
variables:
  trigger_on: >
    [[[ return states['binary_sensor.motion_sensors_all'].state === 'on'; ]]]
  action_color: >
    [[[ return (states['binary_sensor.motion_sensors_all'].state === 'on') ? 'red' : 'grey'; ]]]
```

saves some code repetition in the button config. This however might be the purest illustration of what I was hoping to do.
