### ISSUE TITLE
Bug when hold action is actioned

### ISSUE THREAD

**Issue by andyblac** [custom-cards/button-card#747]
**Checklist**
- [*] I updated the card to the latest version available
- [*] I cleared the cache of my browser

**Describe the bug**
after you have long tapped on a button the icon and labels moves position. This only happens in Saferi web browser, it does not happen if I use Chrome on macOS.

**Version of the card**
Version: 4.1.1

**To Reproduce**
This is the configuration I used:
```
  styles:
    label:
      - font-weight: "bold"
      - font-size: "90%"
      - border-radius: "50%"
      - position: "absolute"
      - right: "6%"
      - top: "0%"
      - height: "30%"
      - width: "30%"
      - margin-top: "7%"
      - margin-bottomt: "5px"
      - line-height: "24px"
      - color: "rgba(var(--color-theme),0.2)"
      - background-color: "rgba(var(--color-theme),0)"
    icon:
      - color: "rgba(var(--color-theme),0.2)"
    state:
      - justify-self: "start"
      - font-weight: "bold"
      - font-size: "12px"
      - filter: "opacity(40%)"
      - margin-left: "6px"
    img_cell:
      - background-color: "rgba(var(--color-theme),0.05)"
      - border-radius: "50%"
      - width: "100%"
      - height: "100%"
      - max-width: "none"
      - max-height: "none"
      - position: "absolute"
      - left: "60%"
      - top: "54%"
      - transform: "translate(-50%,-50%)"
      - margin-top: "15%"
      - margin-left: "-28%"
    card:
      - border-radius: "20px"
      - box-shadow: "var(--box-shadow)"
      - padding: "5px"

```

**Screenshots**
before tap action in performed.
<img width="159" alt="Screenshot 2023-08-06 at 14 02 40" src="https://github.com/custom-cards/button-card/assets/77936/ae7870da-87b6-4c1a-ba2a-8ac0ab2c0dfb">

after long tap, and action has run.
<img width="906" alt="Screenshot 2023-08-06 at 14 02 56" src="https://github.com/custom-cards/button-card/assets/77936/62d3e769-7968-4a79-b337-a4b2a990cb85">

after closing the more info popup
<img width="202" alt="Screenshot 2023-08-06 at 14 03 07" src="https://github.com/custom-cards/button-card/assets/77936/6169efb8-dcd5-4897-981e-f004a6d7266b">

if you refresh the page the bottum returns to normal.

**Expected behavior**
the button icon etc shoudl not move position.

**Desktop (please complete the following information):**
 - Browser: [Safari]
 - Version: [16.6]

**Additional context**
if you need more info please just ask. I have attached the full yaml file

[custom_card_andyblac_status_icon_only.yaml.zip](https://github.com/custom-cards/button-card/files/12269674/custom_card_andyblac_status_icon_only.yaml.zip)

yaml to use template
```
          - type: "custom:button-card"
            name: Doors
            entity: sensor.number_of_doors_open
            template:
              - custom_card_andyblac_status_icon_only
            variables:
              ulm_card_status_color: blue
              ulm_card_status_badge_bg: true
```

**Comment by Mariusthvdb** [comment]
have to ask again, could you please provide a minimal config (without having to dl external files) so we can get an idea of what causes this. Just delete any line you have, and still reproduce the issue.

also, and this might be me, I cant spot the issue in your screenshots. please tighten that to only showing the issue?

**Comment by andyblac** [comment]
before hold_action (more info) is performed, how it should look.
<img width="159" alt="Screenshot 2023-08-06 at 14 02 40" src="https://github.com/custom-cards/button-card/assets/77936/ae7870da-87b6-4c1a-ba2a-8ac0ab2c0dfb">

after closing the more info popup
<img width="202" alt="Screenshot 2023-08-06 at 14 03 07" src="https://github.com/custom-cards/button-card/assets/77936/6169efb8-dcd5-4897-981e-f004a6d7266b">

as you can see the button contents has shifted upwards, it should not have moved.

I will try to reduce code to the minimum till bug remains and report back.

**Comment by andyblac** [comment]
still happens with this code, it also happens with `tap_action` when set to `more-info`

```
- type: "custom:button-card"
  name: Doors
  entity: sensor.number_of_doors_open
  color: "var(--google-grey-500)"
  size: "45%"
  aspect_ratio: "1/1"
  show_icon: true
  show_label: false
  show_name: false
  tap_action:
    action: "more-info"
    entity: "[[[ return entity.entity_id; ]]]"
  hold_action:
    action: "more-info"
    entity: "[[[ return entity.entity_id; ]]]"
  styles:
    icon:
      - color: "rgba(var(--color-theme),0.2)"
    img_cell:
      - background-color: "rgba(var(--color-theme),0.05)"
      - border-radius: "50%"
      - width: "100%"
      - height: "100%"
      - max-width: "none"
      - max-height: "none"
      - position: "absolute"
      - left: "60%"
      - top: "54%"
      - transform: "translate(-50%,-50%)"
      - margin-top: "15%"
      - margin-left: "-28%"
    card:
      - border-radius: "15px"
      - box-shadow: "var(--box-shadow)"
      - padding: "5px"
```

**Comment by andyblac** [comment]
managed to reduce it down even further.

```
          - type: "custom:button-card"
            name: Doors
            entity: sensor.number_of_doors_open
            size: "45%"
            aspect_ratio: "1/1"
            show_icon: true
            show_label: false
            show_name: false
            tap_action:
              action: "more-info"
              entity: "[[[ return entity.entity_id; ]]]"
            hold_action:
              action: "more-info"
              entity: "[[[ return entity.entity_id; ]]]"
            styles:
              img_cell:
                - background-color: "rgba(var(--color-theme),0.05)"
                - border-radius: "50%"
                - position: "absolute"
                - left: "-20%"
                - top: "20%"
              card:
                - border-radius: "15px"
                - box-shadow: "var(--box-shadow)"
                - padding: "5px"
```

still happens.

<img width="103" alt="Screenshot 2023-08-07 at 09 34 36" src="https://github.com/custom-cards/button-card/assets/77936/8b2d02bd-9238-4c5c-8616-40ebc3562c91">

<img width="103" alt="Screenshot 2023-08-07 at 09 34 49" src="https://github.com/custom-cards/button-card/assets/77936/07d02f0b-dde9-4fb0-98f6-c056146e6059">

**Comment by Mariusthvdb** [comment]
this can probably be further reduced, leaving out all non 'size' elements, like color etc.

find out when this doe Not happen anymore... ;-) which is what we are looking for. 

also, does this happen on all buttons you use, or only this one?

**Comment by andyblac** [comment]
got it down to

```
          - type: "custom:button-card"
            entity: sensor.number_of_doors_open
            # aspect_ratio: "1/1"
            show_icon: true
            show_label: false
            show_name: false
            tap_action:
              action: "more-info"
              entity: "[[[ return entity.entity_id; ]]]"
            styles:
              img_cell:
                - left: "-20%"
                - top: "20%"
```
still happends, although a smaller amount as card is no longer square. (1/1). It happens even if I create a new bashboard, with only this code in it.

**Comment by andyblac** [comment]
> also, does this happen on all buttons you use, or only this one?

just this type where the imagecell, icon etc are shifted down and left.

**Comment by Mariusthvdb** [comment]
yes, I can reproduce, but its not 100% hit. every now and then, when returning from the more info, and the focus has returned to the card, it slides up. even with this:

```
    - type: custom:button-card
      entity: input_boolean.test
      aspect_ratio: 1
      show_icon: true
#       show_label: false
#       show_name: false
      tap_action:
        action: more-info
      styles:
        img_cell:
#           - left: '-20%'
          - top: '20%'
```

it also moves up the name.
