### ISSUE TITLE
Card color in off state is reverted, when color is defined with RGB

### ISSUE THREAD

**Issue by fxxer** [custom-cards/button-card#754]
**Checklist**
- [ x ] I updated the card to the latest version available
- [ x ] I cleared the cache of my browser

**Describe the bug**
I have one more issue with card color, if I define color as var(--paper-item-icon-color), then the color of the card in off state is reverted. It should be as the color of covers buttons in screenshot. Same applies for color defined as rgb(0, 122, 255). More info in the previous ticket https://github.com/custom-cards/button-card/issues/737

Light Mode
![Screenshot 2023-08-03 at 19 33 07](https://github.com/custom-cards/button-card/assets/4021387/edb3faf7-bc07-45c3-84d9-f8eeb05f3dfb)

Dark Mode
![Screenshot 2023-08-03 at 19 33 50](https://github.com/custom-cards/button-card/assets/4021387/bebdcfa3-1fa1-4dac-9d28-b217eb0dd45f)

```
button_card_templates:
  switch:
    hold_action:
      action: more-info
    tap_action:
      action: toggle
    type: custom:button-card
    color: var(--paper-item-icon-active-color)
    color_type: card
    state:
      - value: 'on'
        styles:
          icon:
            - color: white
          name:
            - color: white
```
