### ISSUE TITLE
Button loses action, not able to click on it

### ISSUE THREAD

**Issue by tonyp740613** [custom-cards/button-card#759]
**Checklist**
- [ X] I updated the card to the latest version available
- [ X] I cleared the cache of my browser

**Describe the bug**
After upgrading from 3.5.0 to 4.1.1 the button is not able to be used as a button no longer, clicking on the button no longer performs any actions.
This happens with version 4.0.0-4.1.1 and reverting to 3.5.0 the button performs the action.
Same problem occurs with the Home Assistant Companion app on my phone.

After checking the config of the button I discovered that when I **_remove_** the _**state**_ conditions the action returns to the button.
```yaml
state:
  - value: Line
    color: cyan
    icon: mdi:transmission-tower
    custom_fields:
      voltage: |
        [[[
          return `<span>${states['sensor.grid_voltage'].state}V<br>${states['sensor.ac_output_active_power'].state}W</span>`
        ]]]
  - value: Battery
    color: lime
    icon: mdi:car-battery
    custom_fields:
      voltage: |
        [[[
          return `<span>${states['sensor.battery_voltage'].state}V<br>${states['sensor.battery_capacity'].state}%<br>${states['sensor.ac_output_active_power'].state}W</span>`
        ]]]
```

**Version of the card**
Version: 4.0.0 - 4.1.1

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:button-card
tap_action:
  action: navigate
  navigation_path: /lovelace-inverter/mecer-axpert-inverter
entity: sensor.mode
show_state: false
name: Inverter
styles:
  icon:
    - height: 50px
    - margin-left: 4%
  grid:
    - position: relative
  custom_fields:
    voltage:
      - position: absolute
      - left: 47%
      - top: 10%
      - height: 40px
      - font-size: 12px
      - line-height: 13px
state:
  - value: Line
    color: cyan
    icon: mdi:transmission-tower
    custom_fields:
      voltage: |
        [[[
          return `<span>${states['sensor.grid_voltage'].state}V<br>${states['sensor.ac_output_active_power'].state}W</span>`
        ]]]
  - value: Battery
    color: lime
    icon: mdi:car-battery
    custom_fields:
      voltage: |
        [[[
          return `<span>${states['sensor.battery_voltage'].state}V<br>${states['sensor.battery_capacity'].state}%<br>${states['sensor.ac_output_active_power'].state}W</span>`
        ]]]
```

**Expected behavior**
When clicking on the button it should perform the action, it no longer does this.

**Desktop (please complete the following information):**
 - Browser [chrome, edge, vivaldi]
 - Version [115.0.5790.173, 115.0.1901.203, 6.1.3035.302]

**Smartphone (please complete the following information):**
 - Device: [Samsung]
 - OS: [Android 13]
 - Browser [Home Assistant Companion]
 - Version [e.g. 2023.7.5-full]
