### ISSUE TITLE
Card seems to change size on click in Firefox

### ISSUE THREAD

**Issue by aleksandar-todorovic** [custom-cards/button-card#76]
My entities look like this:

![Screenshot from 2019-03-16 19-54-57](https://user-images.githubusercontent.com/4890548/54480174-7aa2f300-4825-11e9-8bcc-dacaeedafdf8.png)

However, when I click on each individual card, they seem to reduce their height:

![Screenshot from 2019-03-16 19-55-09](https://user-images.githubusercontent.com/4890548/54480215-061c8400-4826-11e9-881e-dd560ee5d54c.png)

There's really nothing complicated in my config:

```
type: horizontal-stack
cards:
  - type: 'custom:button-card'
    icon: 'mdi:radio'
    action: service
    name: Radio station
    service:
      domain: script
      action: radio538
  - type: 'custom:button-card'
    icon: 'mdi:record-player'
    action: service
    name: Radio show
    service:
      domain: script
      action: radioshows538
```

Second row:

```
type: horizontal-stack
cards:
  - type: 'custom:button-card'
    icon: 'mdi:volume-plus'
    action: service
    service:
      domain: media_player
      action: volume_up
      data:
        entity_id: media_player.XXX
  - type: 'custom:button-card'
    icon: 'mdi:volume-minus'
    action: service
    service:
      domain: media_player
      action: volume_down
      data:
        entity_id: media_player.XXX
  - type: 'custom:button-card'
    icon: 'mdi:stop'
    action: service
    service:
      domain: media_player
      action: media_stop
      data:
        entity_id: media_player.XXX
```

I've spent a fair amount of time making sure that there's nothing wrong with my config, only to discover that this issue doesn't happen in Chrome, only in Firefox (version 66.0b14).

There are no errors in the console related to this module, and my configuration is valid.

If there's any additional data that could be of help, I'll be happy to provide.
