### ISSUE TITLE
Haptic on mobile app/browser doesn't work when combine with "action: navigate"

### ISSUE THREAD

**Issue by vu-the-dung** [custom-cards/button-card#760]
**Checklist**
- [v ] I updated the card to the latest version available
- [v ] I cleared the cache of my browser

**Describe the bug**
When i set tap_action as "action: navigate", haptic doesn't work, i tried with all haptic options

**Version of the card**
Version: v4.1.1

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:button-card
entity: fan.bedroom_fan
tap_action:
  haptic: light
  action: navigate
  navigation_path: /lovelace/fan
hold_action:
  action: toggle
  haptic: light
```

**Screenshots**

**Expected behavior**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S23 Ultra
 - OS: Android 13
 - Browser: Chrome, Home Assistant Companion
 - Version: Chrome 116.0.5845.92; Home Assistant 2023.8.2-full

**Additional context**
