### ISSUE TITLE
[Question] tap(s) actions using a single variable

### ISSUE THREAD

**Issue by SiriosDev** [custom-cards/button-card#770]
## **Not FR**

it is possible to put an entire block of "instructions" into a variable?

Like this: 

```yaml
#yaml editor/lovelace.yaml
#...
variables:
  tap_var: null
#...
```

```yaml
#card yaml:
#...
type: custom:button-card
template: example_template
variables:
  tap_var:
    action: navigate
    navigation_path: /hassio/dashboard
#...
```
