### ISSUE TITLE
DateTime helpers do not accept additional characters or helpers

### ISSUE THREAD

**Issue by pedolsky** [custom-cards/button-card#772]
**Checklist**
- [ x ] I updated the card to the latest version available
- [ x ] I cleared the cache of my browser

**Describe the bug**
I can only use a single DateTime helper, the use of additional helpers or characters results in [object Object]

**Version of the card**
Version: 4.1.1

**To Reproduce**
This is the configuration I used:
```

type: custom:button-card
entity: input_datetime.datetime 
show_icon: false
name: >
  [[[ return helpers.formatDate(entity.state) + "<br>" +
  helpers.relativeTime(entity.state); ]]]
show_label: true
label: >
  [[[ return helpers.formatDate(entity.state) +
  helpers.relativeTime(entity.state); ]]]

```

**Screenshots**

![IMG_0196](https://github.com/custom-cards/button-card/assets/71203830/e9586c07-b7cd-4205-b48c-2dacc35f5427)

**Expected behavior**
I expected/hoped that it is possible to use multiple helpers in one.

**Desktop (please complete the following information):**
 - Browser [Safari 16.6.1]

**Smartphone (please complete the following information):**
 - Device: [iPad Air 3]
 - OS: [16.6.1]
 - Browser [Safari]
 - Version [16.6.1]

**Additional context**
Home Assistant Supervised core-2023.9.1

**Comment by Grrzzz** [comment]
*bump* Same issue as with latest version

**Comment by En3myNightmare** [comment]
+1

**Comment by wynandtredoux** [comment]
Same issue, but I found a workaround. The object returned by `helpers.relativeTime()` has a `values` array. The date string is stored the 2nd element that array. So if you want to add to the string you can do for example: 

```
[[[ return "Relative Time:<br>" +
  helpers.relativeTime(entity.state).values[1]; ]]]
```

But I'm not sure if the `helpers.relativeTime(entity.state).values` array is always the same.

**Comment by mycroftsnm** [comment]
+1, the .values[1] workaround is pretty ugly. 
I would like to have "Mi custom text: 4 hours ago" 
with '4 hours ago' being the text displayed by helpers.relativeTime(entity.state)

**Comment by swaggerino** [comment]
I can't get helpers.relativeTime() to work at all.. can somebody give me a hint at what's wrong?
As a test I try this simple card:
```
type: custom:button-card
custom_fields:
  text: >
    [[[
      return 'Relative Time: ' + 
      helpers.relativeTime('2024-08-18T07:15:00+00:00').values[1]
    ]]]
```
But my output is this:
![image](https://github.com/user-attachments/assets/b0b528e3-6192-42d2-a5f9-c15e54a88873)

**Comment by NikolasRupp** [comment]
I have the same problem as @swaggerino. If i use the values[1] workaround i will get the iso format of the date

**Comment by saurus** [comment]
I also wanted the relative time formatting, while customizing the output. After digging a bit in the code, my workaround is generating the html in my template. This is an example of displaying both changed and updated timestamps:
```
state_display: |
  [[[
    return html`updated:
        <ha-relative-time
          .hass="${hass}"
          .datetime="${entity.last_updated}"
        ></ha-relative-time>
        <br>changed:
        <ha-relative-time
          .hass="${hass}"
          .datetime="${entity.last_changed}"
        ></ha-relative-time>`
  ]]]
```

result:
![image](https://github.com/user-attachments/assets/6e5fcd61-9ea9-439e-b45f-a6dca346c94d)

I don't know how much a workaround is this solution, `ha-relative-time` is implemented in lovelace, so should be pretty stable...

**Comment by ngocjohn** [comment]
> I don't know how much a workaround is this solution, `ha-relative-time` is implemented in lovelace, so should be pretty stable...

button card has the `ha-relative-time` as builtin function, you can use like this.. 
```
  - type: 'custom:button-card'
    entity: light.entrance_color_white_lights
    show_label: true
    label: >
      [[[
        let lastChanged = new Date(entity.last_changed),
            relativeTime = this._relativeTime(lastChanged);
        return relativeTime;
      ]]]
```

![CleanShot 2024-12-14 at 22 20 13](https://github.com/user-attachments/assets/faa4f930-9df5-4dd7-ac21-d999f8d6909a)

**Comment by parautenbach** [comment]
I'd like to offer another way of doing this natively in the card:

<img width="171" alt="Image" src="https://github.com/user-attachments/assets/7d3f89b6-73f2-4c40-9199-90fbc16ec7c4" />

```
      - type: custom:button-card
        name: "Test"
        entity: input_boolean.test
        show_label: true
        size: 20%
        label: "Label:"
        custom_fields:
          t: "[[[ return helpers.relativeTime(entity.last_changed) ]]]"
        styles:
          card:
            - font-size: 12px
          grid:
            - grid-template-areas: '"n n" "i i" "l t"'
            - grid-template-rows: 1fr
            - grid-template-columns: 1fr 1fr
          label:
            - align-self: right
            - justify-self: end
            - padding-right: 1ex
          custom_fields:
            t:
              - align-self: left
              - justify-self: start
```
