### ISSUE TITLE
Borders are overlapped and in a different color

### ISSUE THREAD

**Issue by Sergiodiaz53** [custom-cards/button-card#777]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser

**Describe the bug**
The borders for the buttons are overlapped and showed in a different color.

**Version of the card**
Version: v4.1.2-dev.1

**To Reproduce**
This is the configuration I used:
```yaml
          - type: "custom:button-card"
            template: card_light
            entity: light.bedroom_2
            variables:
              ulm_card_light_enable_slider: true
              ulm_card_light_enable_color: true
              ulm_card_light_force_background_color: true
```

**Screenshots**
![imagen](https://github.com/custom-cards/button-card/assets/6660257/bc123012-a6c4-42ba-b8a9-bbecd8c90b05)
