### ISSUE TITLE
background color is incorrect according to the digital color picker

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/button-card#782]
**Checklist**
- [X ] I updated the card to the latest version available
- [X ] I cleared the cache of my browser

**Describe the bug**

**Version of the card**
Version: 

**To Reproduce**
This is the configuration I used:
```yaml
  - type: custom:button-card
    template: button_default_title
    styles:
      card:
        - background: rgb(33,100,194) #'#2164c2' 

```

**Screenshots**

main view section, clearlyy showing the discrepancy between the button card header card, and the contained solar panel cards:

<img width="535" alt="Scherm­afbeelding 2023-10-05 om 10 17 52" src="https://github.com/custom-cards/button-card/assets/33354141/d4430b0b-8c4c-4bd1-91a2-a4319f5deb06">

a bit difficult to screenshot the color picker while selecting the area.... but here goes, selecting the actual color of the image I want to get the color from

<img width="571" alt="Scherm­afbeelding 2023-10-05 om 10 13 54" src="https://github.com/custom-cards/button-card/assets/33354141/1bd7cf8a-32f7-49b0-a0af-0834514992b8">

but is shows this in the button card, when using that exact same rgb value, or hex value, doesnt matter
<img width="533" alt="Scherm­afbeelding 2023-10-05 om 10 14 27" src="https://github.com/custom-cards/button-card/assets/33354141/394c9f57-b64f-49bd-aac9-bd82d7159334">

**Expected behavior**

use the color code set in the config

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

must confess this is a first for me, never encountered the issue before. SO maybe I am not doing it right, and it's a user error. I figured it couldnt be the calibration of the monitor because its all in one single view, card even.

for reference this is the file used in the grid:

![solarpanel2](https://github.com/custom-cards/button-card/assets/33354141/2226a604-efd7-4a1c-a122-35ed860cff19)

changing the header button card to use the image as background
```
  - type: custom:button-card
    template: button_default_title
    styles:
      card:
        - background-image: |
            [[[ return  `url("/local/images/solarpanel2.png")`; ]]]
        - background-size: contain
#         - background: rgb(33,100,194) #'#2164c2' #rgb(33,100,194)
```
does make it show correctly:

<img width="653" alt="Scherm­afbeelding 2023-10-05 om 10 32 33" src="https://github.com/custom-cards/button-card/assets/33354141/2634978c-80c8-48a9-8536-60d8799ec961">

<img width="501" alt="Scherm­afbeelding 2023-10-05 om 10 32 57" src="https://github.com/custom-cards/button-card/assets/33354141/5d882c0c-4c49-4a22-b44f-c1b80c05fc18">

this is actually a cool config, so maybe Ill end up with this, I would love to understand/fix the original issue though
