### ISSUE TITLE
Haptic feedback lost on button

### ISSUE THREAD

**Issue by Acdz9** [custom-cards/button-card#784]
**Checklist**
- [OK] I updated the card to the latest version available
- [OK] I cleared the cache of my browser

**Describe the bug**
There's no haptic feedback on popup buttons with browser mod 2.

**Version of the card**
Version: 4.1.1 and 4.1.2-dev.1

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:button-card
entity: sensor.sensor
tap_action:
  haptic: success
  action: fire-dom-event
  browser_mod:
    command: call-service
    service: browser_mod.popup
    data:
      title: Title
      content:
```

**Screenshots**

**Expected behavior**
Recover vibrations on popup buttons

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Browser [home assistant IOS app]
 - Version [2023.7]

**Additional context**
