### ISSUE TITLE
Layout option not working

### ISSUE THREAD

**Issue by TwoPlayer** [custom-cards/button-card#786]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
I don't know, if I missunderstand the configuration, but I created a button with the layout `icon_name`, but the button don't formatted the way it should. The icon is still above the name instead aligned horizontal.

**Version of the card**
Version: 4.1.1

**To Reproduce**
This is the configuration I used:
```yaml
type: button
name: Karte
icon: mdi:map
show_name: true
show_icon: true
show_state: false
layout: icon_name
tap_action:
  action: navigate
  navigation_path: '#map'
```

**Screenshots**
![grafik](https://github.com/custom-cards/button-card/assets/2150354/9ebd519d-9a7e-4c86-bd0f-80ab96576b98)

**Expected behavior**
The icon and the name are aligned horizontal.

**Desktop (please complete the following information):**
 - Browser: Firefox, Chrome
 - Version: 118.0.2 (64-Bit), 117.0.5938.152 (64-Bit)

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: 17.0.3
 - Browser: Home Assistant App
 - Version: 2023.7
