### ISSUE TITLE
Text only buttons became too small to press on latest release using v90.2 hass

### ISSUE THREAD

**Issue by scstraus** [custom-cards/button-card#79]
I have a bunch of buttons defined as below which used to create a quite useful sized button. They don't have icons because there aren't really any I want there. As of the latest update running on v90.2, they have gotten really really short, just barely enough to hold the text. Is there some way to make them taller again (ie, add a border above and below the text)?

```
        - type: "custom:button-card"
          name: Jazz
          action: service
          service:
            domain: media_player
            action: play_media 
            data:
              entity_id: "media_player.itunes"
              media_content_id: "best-jazz"
              media_content_type: "playlist"
```

**Comment by RomRider** [comment]
Can you try again with the latest version and also screenshot if it doesn't work please?

**Comment by scstraus** [comment]
Okay, will get back to you when I get a chance.

**Comment by scstraus** [comment]
Latest version (1.20) has improved the situation a bit over what I was running before (1.0?), but I still prefer the old versions prior to 1.0- see below:

Old version (my favorite):
![image](https://user-images.githubusercontent.com/7644023/56869137-d358d480-69fc-11e9-9089-358e865d41f7.png)

1.0 or something around there (my least favorite):
![image](https://user-images.githubusercontent.com/7644023/56869146-056a3680-69fd-11e9-9922-4554ec4bebff.png)

1.2 (better than ~1.0 but not as good as older versions)
![image](https://user-images.githubusercontent.com/7644023/56869164-45311e00-69fd-11e9-8b77-0a7e4a4b021d.png)

**Comment by RomRider** [comment]
You can change the style of each button, the latest screenshot is the correct what is expected.
Add something like this to each button:
```yaml
style:
- text-transform: uppercase
- padding: 10px 0px #play with the numbers here. First is top and bottom, second is left and right padding
```
Or wait for this PR #132 which will enable you to override properly the height of each button.
