### ISSUE TITLE
Confirmation showing up when not configured?

### ISSUE THREAD

**Issue by Onepamopa** [custom-cards/button-card#790]
**Checklist**
- [V] I updated the card to the latest version available
- [V] I cleared the cache of my browser

**Describe the bug**
Calling a scene (toggle button) shows a confirmation popup while no such is configured.

**Version of the card**
Version: 4.1.1

**To Reproduce**
This is the configuration I used:
```yaml
type: horizontal-stack
cards:
  - type: custom:button-card
    action: toggle
    entity: scene.scene_leave_home
    show_last_changed: false
    icon: mdi:exit-run
    show_name: false
    size: 50px
  - type: custom:button-card
    action: toggle
    entity: scene.scene_welcome_home
    show_last_changed: false
    icon: mdi:home-account
    show_name: false
    size: 50px
```

**Screenshots**
-

**Expected behavior**
Not show a confirmation ?!

**Desktop (please complete the following information):**
 - Browser - Happens on all - Opera, Chrome, Safari, HA App @ android...
 - Version - current versions

**Smartphone (please complete the following information):**
--

**Additional context**
--
