### ISSUE TITLE
Button order in masonry

### ISSUE THREAD

**Issue by dusan-ivanco** [custom-cards/button-card#795]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
Difference in button order between "Hass Button Card" and "Custom Button Card"

**Version of the card**
Version: 4.1.1

**To Reproduce**
This is the configuration I used:
```yaml
  - type: masonry
    path: hass
    title: Hass Button
    cards:
      - type: button
        name: ESP
        icon: mdi:chip
        icon_height: 48px
        tap_action:
          action: navigate
          navigation_path: /hassio/ingress/5c53de3b_esphome
      - type: button
        name: Zigbee
        icon: mdi:zigbee
        icon_height: 48px
        tap_action:
          action: navigate
          navigation_path: /hassio/ingress/45df7312_zigbee2mqtt
      - type: button
        name: Z-Wave
        icon: mdi:z-wave
        icon_height: 48px
        tap_action:
          action: navigate
          navigation_path: /hassio/ingress/a0d7b954_zwavejs2mqtt
      - type: button
        name: SSH
        icon: mdi:console
        icon_height: 48px
        tap_action:
          action: navigate
          navigation_path: /hassio/ingress/a0d7b954_ssh
      - type: button
        name: File Editor
        icon: mdi:file-document-edit
        icon_height: 48px
        tap_action:
          action: navigate
          navigation_path: /hassio/ingress/a0d7b954_vscode
      - type: button
        name: Node RED
        icon: mdi:vector-polyline
        icon_height: 48px
        tap_action:
          action: navigate
          navigation_path: /hassio/ingress/a0d7b954_nodered

  - type: masonry
    path: custom
    title: Custom Button
    cards:
      - type: custom:button-card
        name: ESP
        icon: mdi:chip
        template: link
        tap_action:
          action: navigate
          navigation_path: /hassio/ingress/5c53de3b_esphome
      - type: custom:button-card
        name: Zigbee
        icon: mdi:zigbee
        template: link
        tap_action:
          action: navigate
          navigation_path: /hassio/ingress/45df7312_zigbee2mqtt
      - type: custom:button-card
        name: Z-Wave
        icon: mdi:z-wave
        template: link
        tap_action:
          action: navigate
          navigation_path: /hassio/ingress/a0d7b954_zwavejs2mqtt
      - type: custom:button-card
        name: SSH
        icon: mdi:console
        template: link
        tap_action:
          action: navigate
          navigation_path: /hassio/ingress/a0d7b954_ssh
      - type: custom:button-card
        name: File Editor
        icon: mdi:file-document-edit
        template: link
        tap_action:
          action: navigate
          navigation_path: /hassio/ingress/a0d7b954_vscode
      - type: custom:button-card
        name: Node RED
        icon: mdi:vector-polyline
        template: link
        tap_action:
          action: navigate
          navigation_path: /hassio/ingress/a0d7b954_nodered
```

**Screenshots**
Hass Button Card
<img width="1257" alt="Hass Button Card" src="https://github.com/custom-cards/button-card/assets/4436584/d03babea-9654-4ff5-9337-aced49e324b1">

Custom Button Card
<img width="1258" alt="Custom Button Card" src="https://github.com/custom-cards/button-card/assets/4436584/e34a6772-54ce-42c0-8506-a2c54829a7ea">

**Expected behavior**
I would like it if the buttons were arranged as is customary, from left to right and from top to bottom. Exactly the same as the "Hass Button Card" has it.

**Comment by dcapslock** [comment]
The difference is card_size. A standard button with icon and text is [5](https://github.com/home-assistant/frontend/blob/4dcf2287ce069f938d5de6e68347dd8accd48ad2/src/panels/lovelace/cards/hui-button-card.ts#L130). If not defined in config, a button-card is 3. So you can set `card_size: 5` on your button-cards and then the masonary logic of assigning by size will be the same.

```yaml
  - type: masonry
    path: custom
    title: Custom Button
    cards:
      - type: custom:button-card
        name: ESP
        icon: mdi:chip
        template: link
        card_size: 5
        tap_action:
          action: navigate
          navigation_path: /hassio/ingress/5c53de3b_esphome
...
```

While one could suggest that button-card size logic follow standard button size logic (so size of 5 with icon and name), button-card has so many options that using the more default of 3 was chosen, and if this were to change it would definitely be a breaking change.
