### ISSUE TITLE
Filter styles for states

### ISSUE THREAD

**Issue by piotrmarczewski** [custom-cards/button-card#797]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
When using style for a state, the filter it applies (to change the color of the entity_picture) does not automatically work. They only work after refreshing the browser or entering YAML editing and saving again. If I use a filter with the opacity([X]) value, they work without any problems.

**Version of the card**
Version: v4.1.1

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:button-card
entity: switch.uruchom_uspij
show_name: true
show_icon: false
show_entity_picture: true
show_state: true
tap_action:
  action: toggle
state:
  - value: 'on'
    styles:
      entity_picture:
        - filter: >-
            invert(85%) sepia(15%) saturate(6043%) hue-rotate(351deg)
            brightness(101%) contrast(104%) opacity(100%);
  - value: 'off'
    styles:
      entity_picture:
        - filter: >-
            invert(37%) sepia(76%) saturate(343%) hue-rotate(167deg)
            brightness(96%) contrast(88%)

```

**Expected behavior**
I expected that the button color changes when the button state changes.

**Desktop:**
 - Browser: chrome
 - Version: 119.0.6045.124

**Smartphone:**
 - Device: Samsung S21 FE
 - OS: Android 13
 - Browser: HomeAsisstant App
 - Version: 2023.10.2-full
