### ISSUE TITLE
Problem to call scene turn_on

### ISSUE THREAD

**Issue by Truble187** [custom-cards/button-card#800]
### Discussed in https://github.com/custom-cards/button-card/discussions/799

<div type='discussions-op-text'>

<sup>Originally posted by **Truble187** November 12, 2023</sup>
Hey guys,
if I want to call a scene turn on service, I get alway an error and I don't know why.
```
tap_action:
action: call-service
service: scene.turn_on
target:
  entity_id: scene.diningroom_scene2

```

Error:
![image](https://github.com/custom-cards/button-card/assets/79580773/2e478703-a4f9-4a4c-984c-d91a92e5cd50)

The scene works, if I call it over the developer setting.
</div>

**Comment by Mariusthvdb** [comment]
you are using the incorrect syntax:

use:

```
  tap_action:
    action: call-service
    service: scene.turn_on
    data:
      entity_id: entity
```

if your button-card holds a scene as entity, or replace `entity` in the entity_id line with your actual scene entity_id

**Comment by Truble187** [comment]
> you are using the incorrect syntax:
> 
> use:
> 
> ```
>   tap_action:
>     action: call-service
>     service: scene.turn_on
>     data:
>       entity_id: entity
> ```
> 
> if your button-card holds a scene as entity, or replace `entity` in the entity_id line with your actual scene entity_id

Thanks but the error is the same ;(

**Comment by Mariusthvdb** [comment]
Please post full button-card yaml

**Comment by Truble187** [comment]
Hey,
here is the yaml:
`
  type: custom:button-card
  entity: scene.diningroom_scene1
  name: Pandemonium
  show_name: false
  layout: name_state
  tap_action:
    action: call-service
    service: scene.turn_on
    data:
      entity_id: scene.diningroom_scene1
  styles:
    card:
      - background-image: url("/local/img/scene/scene1.png")
      - background-size: cover
`

**Comment by Mariusthvdb** [comment]
just tested this:

```
type: custom:button-card
entity: scene.dining_table_gedimd
tap_action:
  action: call-service
  service: scene.turn_on
  data:
    entity_id: entity
```

and it works as expected.

are you sure your scene has the correct entity_id there?
