### ISSUE TITLE
entity variable is undefined name JS template despite card having valid entity configured

### ISSUE THREAD

**Issue by CalamarBicefalo** [custom-cards/button-card#818]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
The entity object is undefined in a javascript template in the name attribute even though:
- The entity attribute is defined
- The entity attribute value is correct and exists. In fact, if I remove the name template, it renders the friendly name of the target attribute

**Version of the card**
Version: 4.1.1

**To Reproduce**
This is the configuration I used:
```yaml
type: "custom:button-card"
template: card_title
entity: "[[[ return 'input_select.'+variables.room_key+'_activity' ]]]"
name: [[[ return entity.state ]]]
```
