### ISSUE TITLE
last_triggered

### ISSUE THREAD

**Issue by werbi64** [custom-cards/button-card#821]
hello,

I want to display last_triggered as a label, Here's my code:

        - type: custom:button-card
          entity: automation.alarme_ext_matin
          name: désactivation alarme matin extérieure
          template:
            - base_bouton
            - liste
          state:
            - value: 'on'
              styles:
                icon:
                  - color: white
                img_cell:
                  - box-shadow: 1px 1px 12px 0px white
            - value: 'off'
              styles:
                icon:
                  - color: rgba(51,153,255,0.3)
                img_cell:
                  - box-shadow: 1px 1px 12px 0px black
          layout: icon_name_state2nd
          show_label: true
          label: >
            [[[return helpers.relativeTime(states['automation.alarme_ext_matin'].attributes.last_triggered)]]]
          tap_action:
            action: toggle

I'm getting an error message:
![Capture d’écran du 2024-01-16 22-23-30](https://github.com/custom-cards/button-card/assets/118385034/d19de7e1-af4c-4554-99d9-03f4ab8bac04)

Thank you for everything, your code is fantastic

**Comment by Mariusthvdb** [comment]
this works:
```
    - type: custom:button-card
      entity: automation.afval_morgen
      show_state: true
      show_name: false
      show_label: true
#       state_display: |
#         [[[ return helpers.formatDateTime(entity.attributes.last_triggered); ]]]
      label: |
        [[[ return helpers.formatDateTime(entity.attributes.last_triggered); ]]]
```

**Comment by werbi64** [comment]
That's how it works : 
type: custom:button-card
entity: automation.alarme_ext_matin
name: Alarme Extérieure
template:
  - base_bouton
  - liste
state:
  - value: 'on'
    styles:
      icon:
        - color: white
      img_cell:
        - box-shadow: 1px 1px 12px 0px white
  - value: 'off'
    styles:
      icon:
        - color: rgba(51,153,255,0.3)
      img_cell:
        - box-shadow: 1px 1px 12px 0px black
layout: icon_name_state2nd
show_state: true
show_name: true
show_label: true
state_display: |
  [[[ return helpers.formatDateTime(entity.attributes.last_triggered); ]]]
label: |
  [[[ return helpers.relativeTime(entity.attributes.last_triggered); ]]]
![Capture d’écran du 2024-01-17 12-25-36](https://github.com/custom-cards/button-card/assets/118385034/d9ea3989-f8bd-479e-8589-f90764c5077b)


But when I integrate it into the whole, I get the same error message : 

type: custom:button-card
show_label: true
show_icon: false
show_name: false
show_state: false
template:
  - base_carte
state:
  - value: 'on'
    styles:
      card:
        - background: rgba(0,102,0,0.5)
  - value: 'off'
    styles:
      card:
        - background: rgba(0,53,0,0.3)
  - value: unavailable
    styles:
      card:
        - background: rgba(255,0,0,0.1)
tap_action:
  action: more-info
styles:
  grid:
    - grid-template-areas: '"bouton"'
custom_fields:
  bouton:
    card:
      type: horizontal-stack
      cards:
        - type: custom:button-card
          entity: automation.alarme_ext_matin
          name: Alarme Extérieure
          template:
            - base_bouton
            - liste
          state:
            - value: 'on'
              styles:
                icon:
                  - color: white
                img_cell:
                  - box-shadow: 1px 1px 12px 0px white
            - value: 'off'
              styles:
                icon:
                  - color: rgba(51,153,255,0.3)
                img_cell:
                  - box-shadow: 1px 1px 12px 0px black
          layout: icon_name_state2nd
          show_state: true
          show_name: true
          show_label: true
          state_display: |
            [[[ return helpers.formatDateTime(entity.attributes.last_triggered);
            ]]]
          label: >
            [[[ return helpers.relativeTime(entity.attributes.last_triggered);
            ]]]

What am I doing wrong ?

**Comment by werbi64** [comment]
It's better ?

type: custom:button-card
entity: automation.alarme_ext_matin
show_label: true
show_icon: false
show_name: false
show_state: false
tap_action:
  action: more-info
styles:
  grid:
    - grid-template-areas: '"bouton"'
    - grid-template-columns: auto
    - grid-template-rows: min-content
custom_fields:
  bouton:
    card:
      type: horizontal-stack
      cards:
        - type: custom:button-card
          entity: automation.alarme_ext_matin
          name: Alarme Extérieure
          layout: icon_name_state2nd
          show_state: true
          show_name: true
          show_label: true
          state_display: |
            [[[ return helpers.formatDateTime(entity.attributes.last_triggered);
            ]]]
          label: >
            [[[ return helpers.relativeTime(entity.attributes.last_triggered);
            ]]]

**Comment by Mariusthvdb** [comment]
no, you need to format your code using the <> in the toolbar, select all of the code and then press the button

![Uploading Scherm­afbeelding 2024-01-17 om 12.53.59.png…]()

**Comment by werbi64** [comment]
```
type: custom:button-card
entity: automation.alarme_ext_matin
show_label: true
show_icon: false
show_name: false
show_state: false
tap_action:
  action: more-info
styles:
  grid:
    - grid-template-areas: '"bouton"'
    - grid-template-columns: auto
    - grid-template-rows: min-content
custom_fields:
  bouton:
    card:
      type: vertical-stack
      cards:
        - type: custom:button-card
          entity: automation.alarme_ext_matin
          name: Alarme Extérieure
          layout: icon_name_state2nd
          show_state: true
          show_name: true
          show_label: true
          state_display: |
            [[[ return helpers.formatDateTime(entity.attributes.last_triggered);
            ]]]
          label: >
            [[[ return helpers.relativeTime(entity.attributes.last_triggered);
            ]]]
```
