### ISSUE TITLE
help to lock if another switch and has 1

### ISSUE THREAD

**Issue by Eucliwood090** [custom-cards/button-card#824]
I would like to lock a button if another button is already activated but I get errors and I don't understand why

`
type: custom:button-card
entity: switch.lum_tvlum_tv
icon: mdi:floor-lamp
lock:
  enabled: '[[[ if (states['switch.cuisine1'].state == "on") ;  ]]]'
  duration: 3
  unlock: hold
use_light_color: true
collapsible_controls: true

`

**Comment by joeidea** [comment]
I don't see any indentation; but that my be a result of your copy/paste or typing.  I would also try returning the state without the "if".

  type: custom:button-card
  entity: switch.lum_tvlum_tv
  icon: mdi:floor-lamp
  lock:
    enabled: '[[[ return states[switch.cusisine.state ]]]'
    duration: 3
    unlock: hold

**Comment by joeidea** [comment]
Yikes, Missing "]" should be -->  enabled: '[[[ return states[switch.cusisine].state ]]]'
You probably had indentation. I dod; but leading blanks are stripped out here.

**Comment by Eucliwood090** [comment]
![image](https://github.com/custom-cards/button-card/assets/64365981/8c9be112-b32d-404e-99ce-7d7878ccd019)

Unfortunately it doesn't work.

```
type: custom:button-card
variables:
  cuisine: switch.cuisine1
entity: switch.lum_tvlum_tv
icon: mdi:floor-lamp
lock:
  enabled: '[[[ return states[switch.cusisine1].state ]]]'
  duration: 3
  unlock: hold
use_light_color: true
collapsible_controls: true
```
