### ISSUE TITLE
Button card with custom_fields disappear when refreshing the page

### ISSUE THREAD

**Issue by mitsu98** [custom-cards/button-card#836]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
Button card with custom_fields disappear when refreshing the page
HA 2024.3.0

**To Reproduce**
This is the configuration I used:
```yaml
views:
  - title: Home
    cards:
      - type: custom:button-card
        name: Test
        label: Test
        custom_fields:
          camera:
            card:
              type: picture
              image: https://demo.home-assistant.io/stub_config/t-shirt-promo.png
    theme: Metro Slate
    path: home
    subview: false
```
```
button-card.js?hacstag=146194325412:426  TypeError: Cannot read properties of undefined (reading 'style')
    at button-card.js?hacstag=146194325412:426:18867
    at Ti._createCard (button-card.js?hacstag=146194325412:426:19038)
    at button-card.js?hacstag=146194325412:445:213
    at Array.forEach (<anonymous>)
    at Ti._buildCustomFields (button-card.js?hacstag=146194325412:445:30)
    at Ti._gridHtml (button-card.js?hacstag=146194325412:524:25)
    at Ti._buttonContent (button-card.js?hacstag=146194325412:506:454)
    at Ti._cardHtml (button-card.js?hacstag=146194325412:486:18)
    at Ti.render (button-card.js?hacstag=146194325412:426:19509)
    at Ti.update (button-card.js?hacstag=146194325412:1:14818)
button-card.js?hacstag=146194325412:426  Uncaught (in promise) TypeError: e.setConfig is not a function
    at Ti.render (button-card.js?hacstag=146194325412:426:19640)
    at Ti.update (button-card.js?hacstag=146194325412:1:14818)
    at Ti.performUpdate (button-card.js?hacstag=146194325412:1:6145)
    at Ti.scheduleUpdate (button-card.js?hacstag=146194325412:1:5792)
    at Ti._$Ej (button-card.js?hacstag=146194325412:1:5700)

```

**Screenshots**
![vid (1)](https://github.com/custom-cards/button-card/assets/87440954/b9c78410-2a2b-4069-8354-d11787f50116)
