### ISSUE TITLE
text goes into the icons on Android HA-app

### ISSUE THREAD

**Issue by steffen-le** [custom-cards/button-card#843]
**Checklist**
- [ ] I updated the card to the latest version available
- [ ] I cleared the cache of my browser

**Describe the bug**
I use the app on several phones. Since February the text goes under the icons. On Firefox and on Other systems also I-OS it is ok. Please have a lock for the screenshot. I used custom-button-card. There seems to be a problem working between the app and this template.

**Version of the card**
Version: 4.1.2

**To Reproduce**
This is the configuration I used:
```yaml
type: vertical-stack
cards:
  - type: custom:button-card
    color_type: label-card
    color: rgb(200, 200, 214)
    name: Schalter
  - type: horizontal-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            entity: switch.kellerwand_1
            icon: mdi:lightbulb
            state:
              - value: 'on'
                icon: mdi:lightbulb
                color: orange
              - value: 'off'
                icon: mdi:lightbulb-outline
                color: lightgrey
            aspect_ratio: 1/1
            show_name: false
            show_label: true
            label: Schuppen
            layout: custom
            styles:
              grid:
                - display: flex
                - position: relative
              label:
                - position: absolute
                - left: 0
                - right: 0
                - top: 0
                - bottom: 0
                - text-align: center
                - padding: 0px 5px
              img_cell:
                - align-items: center
                - justify-content: center
          - type: custom:button-card
            entity: switch.lt_pavillon
            icon: mdi:lightbulb
            state:
              - value: 'on'
                icon: mdi:lightbulb
                color: orange
              - value: 'off'
                icon: mdi:lightbulb-outline
                color: lightgrey
            aspect_ratio: 1/1
            show_name: false
            show_label: true
            label: Pavillon
            layout: custom
            styles:
              grid:
                - display: flex
                - position: relative
              label:
                - position: absolute
                - left: 0
                - right: 0
                - top: 0
                - bottom: 0
                - text-align: center
                - padding: 0px 5px
              img_cell:
                - align-items: center
                - justify-content: center
          - type: custom:button-card
            entity: switch.terrasse_nord_2
            icon: mdi:lightbulb
            state:
              - value: 'on'
                icon: mdi:lightbulb
                color: orange
              - value: 'off'
                icon: mdi:lightbulb-outline
                color: lightgrey
            aspect_ratio: 1/1
            show_name: false
            show_label: true
            label: Nord Terrasse
            layout: custom
            styles:
              grid:
                - display: flex
                - position: relative
              label:
                - position: absolute
                - left: 0
                - right: 0
                - top: 0
                - bottom: 0
                - text-align: center
                - padding: 0px 5px
              img_cell:
                - align-items: center
                - justify-content: center
          - type: custom:button-card
            entity: switch.terrasse_sued
            icon: mdi:lightbulb
            state:
              - value: 'on'
                icon: mdi:lightbulb
                color: orange
              - value: 'off'
                icon: mdi:lightbulb-outline
                color: lightgrey
            aspect_ratio: 1/1
            show_name: false
            show_label: true
            label: Süd Terrasse
            layout: custom
            styles:
              grid:
                - display: flex
                - position: relative
              label:
                - position: absolute
                - left: 0
                - right: 0
                - top: 0
                - bottom: 0
                - text-align: center
                - padding: 0px 5px
              img_cell:
                - align-items: center
                - justify-content: center
![Screenshot_2024-04-04-08-54-32-30_c3a231c25ed346e59462e84656a70e50](https://github.com/custom-cards/button-card/assets/133641084/aa2c0de0-d7d3-48f9-8b5f-2059fbde0a88)


```

**Screenshots**

**Expected behavior**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by steffen-le** [comment]
already sent the information to the makers of the app. support@nabucasa.com told me to report the problem here.

**Comment by steffen-le** [comment]
![Screenshot_2024-04-04-08-54-32-30_c3a231c25ed346e59462e84656a70e50](https://github.com/custom-cards/button-card/assets/133641084/89b8399c-6a62-4b5c-a93f-9228a93a50f2)

**Comment by steffen-le** [comment]
The upload did not succeed at the first place. Here is it now...
![Screenshot_2024-04-04-08-54-32-30_c3a231c25ed346e59462e84656a70e50](https://github.com/custom-cards/button-card/assets/133641084/eb9ad425-2d8d-4b6e-a379-9bf9619fe519)

**Comment by dcapslock** [comment]
Hi, below is a correct configuration for button-card to achieve what you are after. Your config while it may have worked at some stage, it is not the best way to achieve your layout. Using grid CSS is the correct way to work with button-card, then style from there. As you will see below, only the label padding style remains from what you had. 

```yaml
type: vertical-stack
cards:
  - type: custom:button-card
    color_type: label-card
    color: rgb(200, 200, 214)
    name: Schalter
  - type: horizontal-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            entity: switch.bed_switch
            icon: mdi:lightbulb
            state:
              - value: "on"
                icon: mdi:lightbulb
                color: orange
              - value: "off"
                icon: mdi:lightbulb-outline
                color: lightgrey
            aspect_ratio: 1/1
            show_name: false
            show_label: true
            label: Schuppen
            styles:
              grid:
                - grid-template-areas: "\"i\" \"l\""
                - grid-template-rows: 1fr min-content
              label:
                - padding: 5px 5px
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            entity: switch.bed_switch
            icon: mdi:lightbulb
            state:
              - value: "on"
                icon: mdi:lightbulb
                color: orange
              - value: "off"
                icon: mdi:lightbulb-outline
                color: lightgrey
            aspect_ratio: 1/1
            show_name: false
            show_label: true
            label: Schuppen
            styles:
              grid:
                - grid-template-areas: "\"i\" \"l\""
                - grid-template-rows: 1fr min-content
              label:
                - padding: 5px 5px
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            entity: switch.bed_switch
            icon: mdi:lightbulb
            state:
              - value: "on"
                icon: mdi:lightbulb
                color: orange
              - value: "off"
                icon: mdi:lightbulb-outline
                color: lightgrey
            aspect_ratio: 1/1
            show_name: false
            show_label: true
            label: Schuppen
            styles:
              grid:
                - grid-template-areas: "\"i\" \"l\""
                - grid-template-rows: 1fr min-content
              label:
                - padding: 5px 5px
```

<img width="479" height="228" alt="Image" src="https://github.com/user-attachments/assets/81ef6a37-129d-4d4f-90a2-b863b81d2bae" />
