### ISSUE TITLE
Can I template / if else in tap action ? 

### ISSUE THREAD

**Issue by thib5** [custom-cards/button-card#849]
Hi i Tried things like that but none work. Am I supposed to be able to do it ? if so how ? 
```

  type: 'custom:button-card'
  entity: automation.mudroom_light_motionday_night
  name: Mudroom Light
  icon: mdi:lightbulb
  state:
    - value: 'on'
      icon: mdi:lightbulb-on
    - value: 'off'
      icon: mdi:lightbulb-off
  tap_action:
    action: call-service
    service: >
      {% if is_state('automation.mudroom_light_motionday_night', 'on') %}
        - service: automation.trigger
          metadata: {}
          data:
            skip_condition: true
          target:
            entity_id: automation.killswitch_mudroom_light_motion
      {% else %}
        - service: automation.turn_on
          metadata: {}
          data: {}
          target:
            entity_id: automation.mudroom_light_motionday_night
      {% endif %}
```
