### ISSUE TITLE
State-dependent actions

### ISSUE THREAD

**Issue by hilburn** [custom-cards/button-card#850]
I have a button which I would like to call different services on `tap_action` depending on state. 

Ideally the current action format could be implemented in the state list, along with color, icon, styles etc

Current;y I have implemented the following with templates for which service/targets to use:
```
tap_action:
  action: call-service
  service: >-
    [[[ if (variables.boost_on) return "schedule_state.clear_overrides"; else
    return "input_button.press" ]]]
  data: {}
  target:
    entity_id: >-
      [[[ if (variables.boost_on) return "sensor.heating_schedule"; else return
      "input_button.heating_boost" ]]]
```

Which works ok for the moment, but could see getting rather unwieldy with more than 2 states, or more difficult if e.g. wanting to target a label rather than an entity in one of the states

**Comment by beringtom** [comment]
2nd this! Using a toggle action on blinds with tilt needs a script or automation to trigger it,

**Comment by lduesing** [comment]
That's why 
`                tap_action: |
                  [[[ 
                      if (states['binary_sensor.dishwasher.status_doorstate'].state === 'on') {
                        return 'action: none';
                      } else {
                        return 'action: toggle';
                      }
                  ]]]
`
doesn't work?
even if documentation tells:
`Those are the configuration fields which support templating:
[...]
* Everything field in *_action
[...]
`

**Comment by Mariusthvdb** [comment]
but it has been working since forever:
```
   action: >
     [[[ return variables.z_wave ? 'call-service' : 'call-service'; ]]]
   service: >
     [[[ return variables.z_wave ? 'zwave_js.refresh_value' : 'script.turn_on'; ]]]
   data:
     entity_id: >
       [[[ return variables.z_wave ? 'sensor.' + variables.id + '_actueel' : 'script.' + variables.id + '_meterget_power'; ]]]
     refresh_all_values: >
       [[[ return variables.z_wave ? true : null; ]]]

```

**Comment by hilburn** [comment]
@Mariusthvdb - no I won't close the FR as I specifically mention that the js template solution does work, it's just ugly and unintuitive compared to bringing it into the state structure used for conditional everything else

**Comment by Mariusthvdb** [comment]
ok I see, missed that bit...

well in the case, don't hold your breath, as this card is on a strictly keep alive if possible status, and no new features will be added.

**Comment by hilburn** [comment]
The title is fine.

**Comment by Mariusthvdb** [comment]
your making double here.

the title 'State-dependent actions' is not fine at all, it says exactly nothing. Is this an issue, is this a FR. nothing.

You could help your self, and more importantly the community that gets notified of these new issues (because that is what this is in the repo) not waste their time by describing what the issue is.

**Comment by hilburn** [comment]
It has a FR label and has had it for the last... 7 months.
Nothing in the "Submit a FR" form suggests anything else is needed.
You've also just told me the entire project is in "limp along" mode, uninterested in actually adding any new features - making this whole thread a waste of time regardless of the title.

**Comment by dcapslock** [comment]
> * Everything field in *_action

This means that each field/object in each *_action is templatable, which is correct and for which examples have been given.

> tap_action: | [[[ if (states['binary_sensor.dishwasher.status_doorstate'].state === 'on') { return 'action: none'; } else { return 'action: toggle'; } ]]]

This won't waork as `tap_action:` is processed as a yaml object, expecting sub objects like `action:`. Currently the code naiivley processes the given string as an object (char by char) so this is where it falls down. Even so, if this were processed as a string, you would need to return an object as the config at this point is a javascript object (not yaml) e.g. `{ return { action: "none" } }`.

I will submit a PR that makes the following two examples work. These do the same action, which is to allow the light to be turned off, but not on.

I have not shown `button_card_templates:` example but this would easily extend to having action inline/variables stored in a `button_card_template`.

### Inline

```yaml
type: custom:button-card
entity: light.bed_light
tap_action: |
  [[[
      if (entity.state == "on") 
        return { 
          action: "perform-action", 
          perform_action: "light.turn_off", 
          target: { entity_id: entity.entity_id }
        }
      else return { action: "none" }
  ]]]
```

### Using variable

```yaml
type: custom:button-card
variables:
  my_action_object: |
    [[[
      if (entity.state == "on") 
        return { 
          action: "perform-action", 
          perform_action: "light.turn_off", 
          target: { entity_id: entity.entity_id }
        }
      else return { action: "none" }
    ]]]
entity: light.bed_light
tap_action: "[[[ return variables.my_action_object ]]]"
```

NOTE: The idea to put in `state:` requires more work as `state:` is about output display. `*_action` are independent from display.
