### ISSUE TITLE
helpers.relativeTime(date) doesn't work 

### ISSUE THREAD

**Issue by MelleD** [custom-cards/button-card#852]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
Error on function helpers.relativeTime(date)

**Version of the card**
Version: 4.1.2

**To Reproduce**
This is the configuration I used:
```yaml
     - type: custom:button-card
        template: card_title
        label: "test relative time"
        name: >
          [[[
            return helpers.relativeTime(states['sensor.sun_next_dawn'].state)
          ]]]
```

**Screenshots**

![Bildschirmfoto 2024-05-29 um 15 38 01](https://github.com/custom-cards/button-card/assets/6340898/57cfe9fa-201d-4b7c-932d-f57bdc306611)

**Expected behavior**
No error ;)

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 125.0.6422.78
