### ISSUE TITLE
Next Card in Sequence Overlapping onto Custom Card

### ISSUE THREAD

**Issue by Adrian281701** [custom-cards/button-card#853]
**Checklist**
- [ Y] I updated the card to the latest version available
- [ Y] I cleared the cache of my browser

**Describe the bug**
When using custom buttons the next card in the sequence overlaps/overlays the created custom buttons, preventing use. In the attached image brekdown is as follows:
1) Mushroom slider card
2) Horizontal Stack card, containing 2 custom cards (code below)
3) Standard Lovelace Area Card

Issue occurs both through the browser and the HA companion app on my phone

**Version of the card**
Version: 4.1.2

**To Reproduce**
This is the configuration I used: (for the horizontal stack only, no. 2 from above)
```
type: horizontal-stack
cards:
  - type: custom:button-card
    color: '#7F00FF'
    color_type: icon
    aspect_ratio: 1/1
    icon: mdi:light-switch
    name: Office Light
    size: 50%
    styles:
      card:
        - height: 100px
        - width: 100px
      name:
        - font-size: 14px
        - color: white
        - padding-bottom: 12px
    entity: script.office_light_contro
    tap_action:
      action: toggle
    state:
      - value: 'off'
        styles:
          icon:
            - color: '#7F00FF'
  - type: custom:button-card
    color: '#7F00FF'
    color_type: icon
    aspect_ratio: 1/1
    icon: mdi:light-switch
    name: Office Light
    size: 50%
    styles:
      card:
        - height: 100px
        - width: 100px
        - left: 105px
```

**Screenshots**
![Screenshot 2024-06-04 180040](https://github.com/custom-cards/button-card/assets/85187305/d9841068-13ea-4718-bdd5-c25a81b24629)

**Expected behavior**
i would expect to see the next card in the sequence appear after the custom button card

**Desktop (please complete the following information):**
 - Browser [MS Edgei] As an APP
 - Version [Version 125.0.2535.79 (Official build) (64-bit)]

**Smartphone (please complete the following information):**
 - Device: [Samsung S21]
 - OS: [Android]
 - Browser [Home Assistant Companion App]
 - Version [2024.4.1-full]

**Additional context**

Thanks
