### ISSUE TITLE
Section Support

### ISSUE THREAD

**Issue by oerix** [custom-cards/button-card#854]
Would be great if you could add 'Section' support in the view. 
At the moment, we can't put cards side by side, only 1x1 using sections.

Thanks

**Comment by aLAN-LDZ** [comment]
its true :(

**Comment by aLAN-LDZ** [comment]
I found the solution, set horizontal stack

![image](https://github.com/custom-cards/button-card/assets/33158372/3959eca1-3c2c-4795-b380-91bd0976c76d)

**Comment by guimatheus92** [comment]
> I found the solution, set horizontal stack
> 
> ![image](https://private-user-images.githubusercontent.com/33158372/337414724-3959eca1-3c2c-4795-b380-91bd0976c76d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MjU3MDAsIm5iZiI6MTcxNzcyNTQwMCwicGF0aCI6Ii8zMzE1ODM3Mi8zMzc0MTQ3MjQtMzk1OWVjYTEtM2MyYy00Nzk1LWIzODAtOTFiZDA5NzZjNzZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDAxNTY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZTc1Mjg4NTdhYjU4MDZkNGQ3MzkwMjc4NzBkYjI0MWY0YWRjYzY1NjUxNWFlNWNhMjE4ZTRiM2UzMWZjOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7zEgiLzcMcO-lxGUTIGeulx7AQ_6q9RiLKLz44vMDIE)

@aLAN-LDZ could you share your solution please? I am having the same issue on 1x1, because of card size:

![image](https://github.com/custom-cards/button-card/assets/11640754/e72de2d7-77d1-47bc-9574-c31cdbcc17e1)

**Comment by aLAN-LDZ** [comment]
use the horizontal stack as the base card and place the button card in it

**Comment by guimatheus92** [comment]
> use the horizontal stack as the base card and place the button card in it

Yeah, but that is not set as individual card as a tile for example:

![image](https://github.com/custom-cards/button-card/assets/11640754/a4a305f1-7773-4762-8f8e-aaf0a35ed991)

 The section support is still needed.

**Comment by aLAN-LDZ** [comment]
yes I agree, I only provided a temporary solution

**Comment by Kanecaine** [comment]
I asked me the same question and investigated the problem further. First i used normal tile card.

```yaml
type: tile
entity: light.essen
vertical: true
layout_options:
  grid_columns: 4
  grid_rows: 2
```
With layout options you can define about how many colums and rows the card should span. 4 columns is actually the maximum per section. This leads to this (left side):

<img width="757" alt="Bildschirmfoto 2024-06-12 um 00 21 20" src="https://github.com/custom-cards/button-card/assets/99053167/96a99ef8-708c-49e2-acf2-dcaf184abe95">

3 tile cards, the first spans all 4 columns, the second and third card are spanning 2 columns each.

Then i tried to achieve the same with the custom-button-card (right side in picture above). Here the layout options don't work. To get it right, i have to overwrite some css:

```yaml
type: custom:button-card
entity: light.bad
layout_options:
  grid_columns: 4
  grid_rows: 2
card_mod:
  style: |
    :host {
      height: 100% !important;
      width: 100% !important;
    }
    ha-card {
      height: 100% !important;
      width: 100% !important;
    }
```
By setting width and height (i suppose setting height would be enough) to 100% the custom-button-card follows the specified layout options.

So there is a problem that the custom-button-card does not use all the available space of a section grid cell. Maybe the author could add an option e.g. "use_card_in_section: true" to overwrite the default behavior and setting the height to 100% by the card itself, so that card_mod is not neccessary.

**Comment by esand** [comment]
You can use the `extra_styles` attribute to define those custom styles without using card_mod. It's not 100% perfect - the label seems to be pushed down to the bottom vs being close to the icon, but the icon size is set correctly.

```yaml
extra_styles: |
  :host {
    height: 100% !important;
    width: 100% !important;
  }
  ha-card {
    height: 100% !important;
    width: 100% !important;
  }
```

**Comment by tfoote000** [comment]
I was able to solve it, with dynamic section support, by adding a height style value to the card (see example). I found this height value from the `.card.fit-rows` class. With that, height value, you can use the `layout_options.grid_columns` and `layout_options.grid_rows` and it will dynamically size the button to the section.

```yaml
type: custom:button-card
icon: mdi:warehouse
color_type: card
entity: <entity_name>
show_state: true
show_name: false
tap_action:
  action: call-service
  service: mqtt.publish
  data:
    qos: '2'
    topic: topic
    payload: FIRE
    retain: false
color: rgb(10, 162, 192)
state:
  - color: rgb(165, 173, 206)
    value: Complete
  - color: rgb(112, 166, 67)
    value: Ready
styles:
  card:
    - height: "calc((var(--row-size,1) * (var(--row-height) + var(--row-gap))) - var(--row-gap))"
layout_options:
  grid_columns: 1
  grid_rows: 1
```

Version Details:
HA Core: 2024.7.2
Frontend: 20240710.0
Button-Card: 4.1.2

**Comment by esand** [comment]
> ```yaml
> styles:
>   card:
>     - height: "calc((var(--row-size,1) * (var(--row-height) + var(--row-gap))) - var(--row-gap))"
> ```

That seems to work better for a 1x1 grid with no name, but if you try to apply that to an icon with a name displayed in a x2 height or more grid, the name gets put all the way at the bottom. To fix it, it seems that you'd need something along the lines of this CSS:

```CSS
#container {
    justify-content: center;
    display: flex;
    flex-direction: column;
}
#img-cell {
    height: 48px;
}
#img-cell + * {
    margin-top: 8px;
}
```

And `#img-cell` height needs to be the height you set for the icon size (I couldn't figure out if it's defined in a variable or not). I've got a testing dashboard set up for this, so if anyone comes up with more workarounds, I'm willing to see how it works.

**Comment by Kanecaine** [comment]
Sorry guys, i don’t get it.

(1) Calculating the height as @tfoote000 did, results in the same as setting the height to 100% via extra-styles. Cannot see any difference

(2) The styles for #container and #img-cell which have @esand mentioned: without them everything seems ok. With them a simple custom button card (as posted above from me - only type and entity declaration) is broken. The icon takes up the whole space and entity name is cropped.

Maybe you can give some images to illustrate what (1) and (2) should fix with a simple custom button card yaml?

**Comment by RomRider** [comment]
I'll have a look at this next week, in the meantime there should be a way to fix it with some styling config.

**Comment by esand** [comment]
![image](https://github.com/user-attachments/assets/ee2b0c43-e01d-4011-bddf-5f075142e2aa)
In the image attached, from top left to right:
* Custom 2x2 button with name using the style card height from @tfoote000 
* Custom 2x2 button with name using the extra_styles from @esand 
* Standard 1x1 button w/o name
* Custom 1x1 button w/o name using the style card height from @tfoote000 
* Custom 1x1 button with name using the style card height from @tfoote000 
* Custom 1x1 button with name using the extra_styles from @esand 

As you can see, @tfoote000's fix works well for 1x1 buttons, but when you go bigger with a name, the spacing is off. The issue seems to just be with the computed height of the svg image. using @tfoote000's stuff it seems that it takes the max height which throws off the alignment to any text elsewhere - but for only an icon it will look fine.

**Comment by Kanecaine** [comment]
Hey, thanks for the examples. But i cannot confirm the false alignment - please look at this:

![IMG_0498](https://github.com/user-attachments/assets/13d6c3a0-e952-498e-83aa-c9cbe82ff95c)

On the right side there a 1x1 and 2x2 square, left 2x3 and 1x3.

- green: calculating height (tfoote000)
- orange: my origin 100% height using card mod
- red: 100% height using extra styles (esand)

These are all custom button cards with nothing more than this:

```yaml
type: custom:button-card
entity: light.bad
layout_options:
  grid_columns: 2
  grid_rows: 3

```
