### ISSUE TITLE
The overflow-wrap property does not work in styles

### ISSUE THREAD

**Issue by il77781** [custom-cards/button-card#859]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
Hello!
The names of some entities can be quite long, but I would like them to be fully displayed on the card. For example, in several lines, and the transfer to the next line should occur at the end of the word. The only remedy I've found is the overflow-wrap property, but unfortunately it doesn't work at all!

**Version of the card**
Version: 4.1.2

**To Reproduce**
This is the configuration I used:
Initial condition:
```yaml
type: custom:button-card
entity: fan.dmaker_p44_7a6c_fan
styles:
  card:
    - height: 250px
    - width: 200px
```
The name is displayed like this:
![Screenshot_2024-07-27-22-14-27-224_io homeassistant companion android](https://github.com/user-attachments/assets/e5848226-a368-4e79-ab9c-5524d72a121a)

Next, add the overflow-wrap property:
```yaml
type: custom:button-card
entity: fan.dmaker_p44_7a6c_fan
styles:
  card:
    - height: 250px
    - width: 200px
  name:
    - overflow-wrap: break-word
```
The name is displayed like this:
![Screenshot_2024-07-27-22-13-43-291_io homeassistant companion android](https://github.com/user-attachments/assets/74c2b582-8f3d-443f-84ad-c1635f9042c1)
Nothing has changed!

Let's explicitly limit the size of the text container (block):
```yaml
type: custom:button-card
entity: fan.dmaker_p44_7a6c_fan
styles:
  card:
    - height: 250px
    - width: 200px
  name:
    - height: 70px
    - width: 120px
    - overflow-wrap: break-word
```
The name is displayed like this:
![Screenshot_2024-07-27-22-12-54-941_io homeassistant companion android](https://github.com/user-attachments/assets/86219071-a46b-4bb7-acb6-a9802a7e887a)

That is, in any case, word wrapping on the next line does not work, although there is clearly a place for this! 
I also tried using different values of the overflow, position, text-overflow, text-align properties, however, nothing changed - the words were not transferred to the next line!

**Expected behavior**
I really want the text to be transferred to the next line when its length exceeds the width of the card.

**Smartphone (please complete the following information):**
 - Android App Version 2024.7.3-full on several different devices.

**Additional context**
Tell me, please, what is the problem here? Maybe I'm doing something wrong?

**Comment by ngocjohn** [comment]
```yaml
      - type: custom:button-card
        entity: fan.ceiling_fan
        name: ABBCBCB BDBDBDB BDBDKJDBDBB
        styles:
          card:
            - height: 250px
            - width: 200px
          name:
            - height: 70px
            - width: 120px
            - display: flex
            - overflow: visible
            - text-wrap: wrap
```
