### ISSUE TITLE
Styles Card Height 100% not working

### ISSUE THREAD

**Issue by StevenBrs** [custom-cards/button-card#861]
**Checklist**
- [x] I updated the card to the latest version available
- [o] I cleared the cache of my browser
   —> IOS companion app

**Describe the bug**
Since update to HA 2024.7.4 the card height property 100% isn’t working anymore inside a grid.

**Version of the card**
Version: v4.1.2

**To Reproduce**
This is the configuration I used:
```yaml
type: grid
square: true
columns: 3
cards:
  …
  - type: custom-button
    show_name: true
    show_icon: true
    entity: binary_sensor.xxx
    name: Status
    show_state: false
    styles:
      card:
        - height: 100%
    state
      - value: 'on'
        icon: mdi:check-circle
        styles:
          icon:
            - color: green
      - value: 'off'
        icon: mdi:cancel
        styles:
          icon:
            - color: red
```

**Screenshots**
![image](https://github.com/user-attachments/assets/c641fd52-14c5-4f28-9588-94f56f7f77e3)

**Expected behavior**
![image](https://github.com/user-attachments/assets/a93b5bb8-1750-4342-bcda-770e4dbd92e3)

**Smartphone (please complete the following information):**
 - Device: iPhone13 mini
 - OS: 17.5.1
 - Browser: HA companion app
 - Version: 2024.730

**Additional context**
- also in safari on IOS
- I always update HA in docker the first day of the month, to the highest minor version of the month before.
- Maybe the structure of the grid card in HA changed ?

**Comment by ngocjohn** [comment]
`aspect_ratio: 1/1`

```yaml
      - type: grid
        square: true
        columns: 3
        cards:
          - &test_btn
            type: custom:button-card
            show_name: true
            show_icon: true
            aspect_ratio: 1/1
            entity: binary_sensor.developer
            name: Status
            show_state: false
            styles:
              card:
                - height: 100%
            state:
              - value: 'on'
                icon: mdi:check-circle
                styles:
                  icon:
                    - color: green
              - value: 'off'
                icon: mdi:cancel
                styles:
                  icon:
                    - color: red
          - *test_btn
```
![CleanShot 2024-08-02 at 03 00 11@2x](https://github.com/user-attachments/assets/d5b4201b-9d65-4aa4-b163-c34663fc4021)

**Comment by mateuszdrab** [comment]
In my case, my button card is in a `horizontal-stack` and I am not able to get it to fill the available space. I don't want to hard code an aspect ratio, I just want the card to do what the default cards do. Height 100% does nothing.

![image](https://github.com/user-attachments/assets/4a91ff1c-deb5-47c0-b934-82ad90b1ec68)

**Comment by ngocjohn** [comment]
Post your config code here, I'll try to help you if I can.

**Comment by mateuszdrab** [comment]
Hey @ngocjohn 

This is the config:

```
type: horizontal-stack
cards:
  - type: conditional
    conditions:
      - entity: switch.dehumidifier_power
        state_not: unavailable
    card:
      entity: switch.dehumidifier_power
      type: custom:button-card
      show_state: true
      show_label: true
      name: Dehumidifier
      tap_action:
        action: toggle
        confirmation:
          text: Are you sure you want to press this button?
      hold_action:
        action: navigate
        navigation_path: /config/devices/device/68f2928dc83a50e24f2b54b63396d046
      styles:
        state:
          - color: var(--secondary-text-color)
          - font-size: 0.9rem
        label:
          - color: var(--secondary-text-color)
          - font-size: 0.9rem
      label: |
        [[[
          if (entity.state == 'on') { 
            if (states['binary_sensor.dehumidifier_compressor'].state == 'on') { 
               return "Dehumidifying";
             } 
             else 
             {
               return "Not Dehumidifying";
             }
          }
        ]]]
  - features:
      - type: target-temperature
    type: tile
    entity: climate.toshiba_ac_living_room
    vertical: true
    hide_state: false
    name: AC
    state_content: state
    hold_action:
      action: navigate
      navigation_path: /config/devices/device/03783981df3c7e6faa8bc362d639115f
  - features:
      - type: fan-speed
    type: tile
    entity: fan.floor_fan
    name: Fan
    vertical: true
```

**Comment by mateuszdrab** [comment]
> @mateuszdrab button-card is the whole grid, you can modify styles for grid-template..
> https://github.com/custom-cards/button-card?tab=readme-ov-file#advanced-styling-options
> 
> https://css-tricks.com/snippets/css/complete-guide-grid/
> 
> ```yaml
> styles:
>   grid:
>     - grid-gap: 1rem
>     - padding: 1rem
> ```
> 
> ![CleanShot 2024-08-02 at 18 47 20](https://github.com/user-attachments/assets/23101448-0c70-4c23-8566-24b77e8b24af)
> 

Thanks, this is much better.

There are two small issues though:
- large gaps between the lines
- looks like the bottom edge does not lay in line with the other two buttons

**Comment by ngocjohn** [comment]
Because they are not the same type of card, you have a different font size in styles than the other one, then of course it doesn't look good.... button-card is custom. I've just shown you other ways to work with the card. You have to edit it yourself, that's why many people have only one base universal button template. Which has common parameters and you insert entities or variables. One little tip, don't use too much card mod with custom button card. It's a custom itself, which can be used to do a lot of magic... Check out my config in my repo, you might get inspired. 😃

**Comment by Mariusthvdb** [comment]
> Check out my config in my repo, you might get inspired. 😃

well.... I did, and got inspired by this:https://github.com/ngocjohn/hass-config/blob/c219b7081ef10313d1b14cea47daea336bd81045/config/dashboards/templates/button_card_templates/tpl_chips.yaml#L58C22-L58C69

can I reach out to you somewhere to have side chat? maybe in my community topic on using media aspects for an animation [here](https://community.home-assistant.io/t/how-to-make-scroll-time-speed-and-translatex-string-length-dependent-in-css-animation/754407/4?u=mariusthvdb)? 

Thanks if you could have a look

**Comment by StevenBrs** [comment]
> `aspect_ratio: 1/1`

Thanks! Works like a charm :-)

**Comment by DanDixon** [comment]
I've also run into this issue.

This used to work:
```
    styles:
      card:
        - height: 100%
```

As of 2024.7.x, height as a percentage in custom card mod no longer works.

**Comment by ngocjohn** [comment]
Again like the example above, create a base template for a button for example called square_button and apply with different entities.
```yaml
      - type: custom:button-card
        entity: light.ceiling_lights
        template:
          - square_button
      - type: custom:button-card
        entity: fan.ceiling_fan
        template:
          - square_button
      - type: custom:button-card
        entity: switch.ceiling_switch
        template:
          - square_button
```

**Comment by DanDixon** [comment]
> Again like the example above, create a base template for a button for example called square_button with modified css for the grid and apply with different entities.

I appreciate the help with the workaround, but that does not address the issue of height % not working anymore.

**Comment by Mariusthvdb** [comment]
I just discovered something alike:

using a button-card-template :

```
round_button:
  show_entity_picture: true
  aspect_ratio: 1
  size: 100%
  show_name: false
  tooltip: >
    [[[ return entity.attributes.friendly_name; ]]]
  styles:
    card:
      - border-radius: 100%
      - padding: 0
  ```

works for me in the normal cards section of a view. I use those for my camera streams.

however, using the same buttons in the badge section of the new Ha 2024.8 (which allows us to use custom cards as badges, the size no longer functions, nor does the aspect_ratio for that matter.

As a mater of fact, the only thing that changes the button is using the height and width on the card styles....

but alas, the stream of the video doesn't  follow along:

<img width="1015" alt="Scherm­afbeelding 2024-08-21 om 17 20 47" src="https://github.com/user-attachments/assets/b5ac091b-bd3e-414d-8874-02076d3b0bc8">

[post in the community](https://community.home-assistant.io/t/2024-8-beautiful-badges/757395/481)

its weird to see this happen, and I am not yet convinced this is a button-card issue, and fear it is caused by the way the new badges are implemented. Cant correct it yet either using card-mod, or any of the built-in styling features of button-card.

golven this is an issue specific to the badges section for me, I believe I should hop over to [the dedicated thread in the community](https://community.home-assistant.io/t/new-badges-and-card-mod-customisation/757488), but just letting you know here as a FYI.
