### ISSUE TITLE
Icon_size is not working with a conditional card

### ISSUE THREAD

**Issue by WallyDW** [custom-cards/button-card#863]
**Checklist**
- [ X ] I updated the card to the latest version available
- [ X ] I cleared the cache of my browser

**Describe the bug**
When using icon_size the set size is not taken into consideration of a conditional card.
This cause the grow of the flex-box for the conditional card to be set as it original would.

**Version of the card**
Version: 4.1.2

**To Reproduce**
This is the configuration I used (change the entity line to a light of your choice):
```
type: custom:stack-in-card
mode: horizontal
cards:
  - type: markdown
    content: "Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test"
  - type: conditional
    conditions:
      - condition: state
        entity: light.hallway
        state: "on"
    card:
      type: custom:button-card
      show_icon: false
      name: Hide
      styles:
        card:
          - width: 75px
          - height: 30px
```

**Screenshots**
The YAML code is better

**Expected behavior**
If it is possible I would expect the conditional card to take the card size into consideration when it grows (reveal itself)

**Desktop (please complete the following information):**
```
- Browser: Firefox
  Version: 128.0.3
- Browser: Google Chrome
  Version: 127.0.6533.89
```
**Smartphone (please complete the following information):**
- Device: Android
- OS: 8 & 13
- Browser: Companion App
- Version: 2024.7.3

**Comment by dcapslock** [comment]
This is not a button card issue. The button-card is correct in size. It is the containing card  (stack-in-card) that sets the container width. 

If you wanted to have a horizontal layout where the `hide` element takes a size of what I think you are expecting, you can use the following (tested in masonry view).

```yaml
type: custom:button-card
section_mode: false
styles:
  card:
    - padding: 0px
    - border: 0px
    - background: none
  grid:
    - grid-template-areas: "\"markdown hide\""
custom_fields:
  markdown:
    card:
      type: markdown
      content: >-
        Test Test Test Test Test Test Test Test Test Test Test Test Test Test
        Test Test Test
  hide:
    card:
      type: conditional
      conditions:
        - condition: state
          entity: light.kitchen_lights
          state: "on"
      card:
        type: custom:button-card
        show_icon: false
        name: Hide
        styles:
          card:
            - width: 75px
            - height: 30px
```
<img width="426" height="102" alt="Image" src="https://github.com/user-attachments/assets/a4f0f423-69a8-48b5-9424-c7a51dd53189" />
