### ISSUE TITLE
- display: none leaves a gap where the card was

### ISSUE THREAD

**Issue by warmfire540** [custom-cards/button-card#866]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
I have a card that hides itself when not needed using the state/styles option.

**Version of the card**
Version: 4.1.2

**To Reproduce**
This is the configuration I used:
```yaml
state:
  - operator: "template"
    value: "[[[ return variables.optional && entity.state != variables.on_state && (isNaN(entity.state) || entity.state == 0); ]]]"
    styles:
      card:
        - display: none
```

**Screenshots**
![image](https://github.com/user-attachments/assets/d97c1568-e9a5-4719-af9b-140e29fa6eb2)

![image](https://github.com/user-attachments/assets/a08063f4-928a-4d76-89c5-d540f07c05a1)

**Expected behavior**
I would like their to not be a gap, or a way to apply styles to the parent `hui-card` element to have that display: none

**Desktop (please complete the following information):**
 - Latest version of Chrome

**Smartphone (please complete the following information):**
 - Same on my iPhone 14 Max on the HA app.

**Additional context**

**Comment by warmfire540** [comment]
nevermind - this was a problem w/ the horizontal-stack.  fixed w/ following yaml

```yaml
- type: custom:mod-card
      style:
        hui-horizontal-stack-card$: |
          #root { 
            justify-content: center;
            --stack-card-gap: 0;
          }
      card:
        type: horizontal-stack
        cards:
```
