### ISSUE TITLE
Getting error when more-info is used

### ISSUE THREAD

**Issue by Hadatko** [custom-cards/button-card#877]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser

**Describe the bug**
Got:
```json
{"event_type":"system_log_event","event":{"name":"frontend.js.modern.202410023","message":["Uncaught error from Chrome 130.0.0.0 on Linux x86_64\nTypeError: Cannot assign to read only property '0' of string 'more-info'\n/hacsfiles/button-card/button-card.js:559:2693\nl (/hacsfiles/button-card/button-card.js:559:2641)\nTi._evalActions (/hacsfiles/button-card/button-card.js:559:3033)\nTi._handleAction (/hacsfiles/button-card/button-card.js:559:3845)\nX.handleEvent (/hacsfiles/button-card/button-card.js:1:14121)\nyt (/hacsfiles/button-card/button-card.js:1:19699)\nt.actionHandler.e.disabled.t.actionHandler.end (/hacsfiles/button-card/button-card.js:1:23627)"],"level":"ERROR","source":["components/system_log/__init__.py",331],"timestamp":1729808085.8408139,"exception":"","count":1,"first_occurred":1729808085.8408139},"origin":"LOCAL","time_fired":"2024-10-24T22:14:45.841270+00:00","context":{"id":"01JB09HCTHVQETMHEKZVNW2W4M","parent_id":null,"user_id":null}}
```

**Version of the card**
Version: 
![image](https://github.com/user-attachments/assets/a0e534ad-84ab-4807-839c-988220ee0363)

**To Reproduce**
This is the configuration I used:
```yaml
type: vertical-stack
cards:
  - type: horizontal-stack
    cards:
      - type: custom:button-card
        entity: input_boolean.active_rpr
        icon: mdi:home-account
        show_state: false
        show_name: false
        tap_action: more-info
```

**Screenshots**

**Expected behavior**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
