### ISSUE TITLE
Templated expressions not updated in browser_mod popup window

### ISSUE THREAD

**Issue by mosave** [custom-cards/button-card#880]
Issue description:

button-card displayed in browser_mod popup window properly reacts to triggering entities according to styling/states configuration but NOT updates templated expression. It looks like templates calculated only once after I open/reopen browser_mod popup window.

Exactly same button-card definition placed directly to dashboard trigger updates as expected both with styling/states definition and templated expressions

Button-card version: 4.1.2
browser-mod version: 2.3.1

**To Reproduce**
This is the configuration I used:
```yaml
        - type: custom:button-card
          entity: binary_sensor.17_heater_error
          icon: mdi:water-boiler-alert
          color: rgb(192,0,0)
          name: "Water heater mode"
          state_display: '[[[ return states["binary_sensor.17_heater_error"].state; ]]]'
          show_name: true
          show_icon: true
          show_state: true
          triggers_update: all
          tap_action:
            action: more-info
            entity: binary_sensor.17_heater_error
          state:
            - value: 'off'
              icon: 'mdi:water-boiler'
              color: 'var(--paper-item-icon-active-color)'
              styles:
                name:
                  - color: 'var(--paper-item-icon-active-color)'
                state:
                  - color: 'var(--paper-item-icon-active-color)'
          styles:
            card:
              - margin: 0
              - padding: 0
              - border: none
              - box-shadow: none
            icon:
              - margin: 0
              - padding: 0
            grid:
              - grid-template-areas: "'i n s'"
              - grid-template-columns: 1fr 6fr 3fr
            name:
              - justify-self: start
              - margin: 0
              - padding: 0
              - color: "rgb(192,0,0)"
            state:
              - margin: 0
              - color: "rgb(192,0,0)"

```

**Desktop (please complete the following information):**
 - Browser: MS Edge 
 - Version 130.0.2849.56 (Official build) (64-bit)
