### ISSUE TITLE
Uptime unit bug.

### ISSUE THREAD

**Issue by Ainndy** [custom-cards/button-card#894]
![image](https://github.com/user-attachments/assets/71cea806-bafd-4fa7-a300-efce0c66a751)
![image](https://github.com/user-attachments/assets/0f9f543f-5e73-4855-b669-ef5376fa4782)

**Comment by ngocjohn** [comment]
This is not a bug, use helpers to format datetime.. 
https://github.com/custom-cards/button-card?tab=readme-ov-file#javascript-templates
![CleanShot 2025-01-03 at 15 30 08@2x](https://github.com/user-attachments/assets/a210aaf4-c5aa-4d10-98e5-a8e4898e14ba)

**Comment by Ainndy** [comment]
> This is not a bug, use helpers to format datetime.. 
> 
> https://github.com/custom-cards/button-card?tab=readme-ov-file#javascript-templates
> 
> ![CleanShot 2025-01-03 at 15 30 08@2x](https://github.com/user-attachments/assets/a210aaf4-c5aa-4d10-98e5-a8e4898e14ba)

Which one should I choose for this format [* d * h]. thanks

**Comment by ngocjohn** [comment]
Can you show me the state via dev tools template? 
![CleanShot 2025-01-03 at 15 40 43](https://github.com/user-attachments/assets/38e96b12-93fe-4d92-b5ae-d48ef57e6d54)

**Comment by Ainndy** [comment]
> Can you show me the state via dev tools template? 
> 
> ![CleanShot 2025-01-03 at 15 40 43](https://github.com/user-attachments/assets/38e96b12-93fe-4d92-b5ae-d48ef57e6d54)
> 
> 
![image](https://github.com/user-attachments/assets/bb148f88-9dab-4d92-bd0e-7839dc35ee22)

![image](https://github.com/user-attachments/assets/989f6dca-b506-4c17-a8f3-9a2abfabf9ed)

**Comment by ngocjohn** [comment]
@Ainndy use correct template ..
```
{{ states.sensor.uptime.state }}
```
change with your sensor entity..

**Comment by Ainndy** [comment]
> @Ainndy use correct template ..
> 
> ```
> 
> {{ states.sensor.uptime.state }}
> 
> ```
> 
> change with your sensor entity.. 

My entity is the sensor.water_server_uptime_sensor ..

**Comment by ngocjohn** [comment]
I know, but you have to know what its state shows.. use this in template and send screen..  
```
{{ states.sensor.water_server_uptime_sensor.state }}
```

**Comment by ngocjohn** [comment]
Ok, so it's not a date time object... how do you have the button-card set?

**Comment by Ainndy** [comment]
> 好的，所以它不是一个日期时间对象......你是如何设置按钮卡的？



> Ok, so it's not a date time object... how do you have the button-card set?

The entity is esphome uptime, homeassistant supports displaying the day time unit, but the button card does not support displaying it.
https://esphome.io/components/sensor/uptime.html

type: custom:button-card
entity: sensor.water_server_uptime_sensor
color: lightgreen
show_icon: false
show_name: true
show_state: true
styles:
  card:
    - background-color: lightgreen
    - border-radius: 18px
    - box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.2)
    - width: 80px
    - height: 30px
    - padding: 15px
    - border: none
  name:
    - font-size: 11px
    - color: gray
    - margin-bottom: "-1px"
  state:
    - font-size: 12px
    - color: black
    - margin-bottom: "-1px"
style:
  z-index: 3
  top: 95%
  left: 87.5%
  transform: translate(-50%, -50%)

**Comment by ngocjohn** [comment]
use this to change the state to format d:h, its just calculated to total whole day and hours..
```
state_display: >
  [[[
    let days = entity.state;
    const wholeDays = Math.floor(days); // Extract the full days
    const hours = Math.round((days - wholeDays) * 24);
    return `${wholeDays}d:${hours}h`;
  ]]]
```

**Comment by Ainndy** [comment]
> use this to change the state to format d:h, its just calculated to total whole day and hours..
> 
> ```
> 
> state_display: >
> 
>   [[[
> 
>     let days = entity.state;
> 
>     const wholeDays = Math.floor(days); // Extract the full days
> 
>     const hours = Math.round((days - wholeDays) * 24);
> 
>     return `${wholeDays}d:${hours}h`;
> 
>   ]]]
> 
> ```
> 
>       

OK, thank you very much

**Comment by Ainndy** [comment]
> use this to change the state to format d:h, its just calculated to total whole day and hours..
> 
> ```
> state_display: >
>   [[[
>     let days = entity.state;
>     const wholeDays = Math.floor(days); // Extract the full days
>     const hours = Math.round((days - wholeDays) * 24);
>     return `${wholeDays}d:${hours}h`;
>   ]]]
> ```

Hello, how to make a single button and three buttons in a grid card have the same height?
![image](https://github.com/user-attachments/assets/2e08ab8f-2273-4114-9f29-707edfc7a997)
```
type: horizontal-stack
cards:
  - square: true
    type: grid
    cards:
      - type: custom:button-card
        name: Living Room
        icon: mdi:sofa
        entity: sensor.wi_fizhi_neng_yao_kong_temperature
        show_state: true
        custom_fields:
          btn:
            card:
              type: vertical-stack
              cards:
                - type: custom:button-card
                  tap_action:
                    action: toggle
                  icon: mdi:lamp
                  entity: switch.water_server_ring_switch
                  show_name: false
                  show_state: false
                  styles:
                    card:
                      - width: 36px
                      - height: 36px
                      - border-radius: 50%
                      - background-color: red
                      - display: flex
                      - justify-content: center
                      - align-items: center
                    icon:
                      - width: 18px
                      - height: 18px
                - type: custom:button-card
                  tap_action:
                    action: toggle
                  icon: mdi:lamp
                  entity: switch.water_server_ring_switch
                  show_name: false
                  show_state: false
                  styles:
                    card:
                      - width: 36px
                      - height: 36px
                      - border-radius: 50%
                      - background-color: red
                      - display: flex
                      - justify-content: center
                      - align-items: center
                    icon:
                      - width: 18px
                      - height: 18px
                - type: custom:button-card
                  tap_action:
                    action: toggle
                  icon: mdi:lamp
                  entity: switch.water_server_ring_switch
                  show_name: false
                  show_state: false
                  styles:
                    card:
                      - width: 36px
                      - height: 36px
                      - border-radius: 50%
                      - background-color: red
                      - display: flex
                      - justify-content: center
                      - align-items: center
                    icon:
                      - width: 18px
                      - height: 18px
        styles:
          grid:
            - grid-template-areas: "\"n btn\" \"s btn\" \"i btn\""
            - grid-template-columns: 1fr min-content
            - grid-template-rows: min-content min-content 1fr;
          card:
            - padding: 22px
          custom_fields:
            btn:
              - justify-content: end
              - align-self: start
          name:
            - justify-self: start
            - align-self: start
            - fonr-size: 18px
            - font-weight: 500
            - color: black
          icon:
            - justify-self: start
            - align-self: start
            - fonr-size: 14px
            - opacity: "0.6"
          state:
            - min-height: 80px
            - justify-self: start
            - align-self: start
            - fonr-size: 14px
          img_cell:
            - justify-content: start
            - position: absolute
            - width: 130px
            - height: 130px
            - left: 0
            - bottom: 0
            - margin: 0 0 -30px -30px
            - background: red
            - border-radius: 500px
      - type: custom:button-card
        name: Living Room
        icon: mdi:sofa
        entity: sensor.wi_fizhi_neng_yao_kong_temperature
        show_state: true
        custom_fields:
          btn:
            card:
              type: vertical-stack
              cards:
                - type: custom:button-card
                  tap_action:
                    action: toggle
                  icon: mdi:lamp
                  show_name: false
                  show_state: false
                  styles:
                    card:
                      - width: 36px
                      - height: 36px
                      - border-radius: 50%
                      - background-color: red
                      - display: flex
                      - justify-content: center
                      - align-items: center
                    icon:
                      - width: 18px
                      - height: 18px
        styles:
          grid:
            - grid-template-areas: "\"n btn\" \"s btn\" \"i btn\""
            - grid-template-columns: 1fr min-content
            - grid-template-rows: min-content min-content 1fr;
          card:
            - padding: 22px
          custom_fields:
            btn:
              - justify-content: end
              - align-self: start
          name:
            - justify-self: start
            - align-self: start
            - fonr-size: 18px
            - font-weight: 500
            - color: black
          icon:
            - justify-self: start
            - align-self: start
            - fonr-size: 14px
            - opacity: "0.6"
          state:
            - min-height: 80px
            - justify-self: start
            - align-self: start
            - fonr-size: 14px
          img_cell:
            - justify-content: start
            - position: absolute
            - width: 130px
            - height: 130px
            - left: 0
            - bottom: 0
            - margin: 0 0 -30px -30px
            - background: red
            - border-radius: 500px
    columns: 2
```

**Comment by ngocjohn** [comment]
Remove the horizontal-stack, put buttons to grid? 
```
square: false
type: grid
cards:
  - type: custom:button-card
    entity: sun.sun
  - type: custom:button-card
    entity: sun.sun
columns: 2
```

**Comment by Ainndy** [comment]
> sun.sun

![image](https://github.com/user-attachments/assets/59eeb9f7-dc78-4dc3-9971-2935ffd698c5)
```
square: false
type: grid
cards:
  - square: true
    type: grid
    cards:
      - type: custom:button-card
        name: Living Room
        icon: mdi:sofa
        entity: sun.sun
        show_state: true
        custom_fields:
          btn:
            card:
              type: vertical-stack
              cards:
                - type: custom:button-card
                  tap_action:
                    action: toggle
                  icon: mdi:lamp
                  entity: sun.sun
                  show_name: false
                  show_state: false
                  styles:
                    card:
                      - width: 36px
                      - height: 36px
                      - border-radius: 50%
                      - background-color: red
                      - display: flex
                      - justify-content: center
                      - align-items: center
                    icon:
                      - width: 18px
                      - height: 18px
                - type: custom:button-card
                  tap_action:
                    action: toggle
                  icon: mdi:lamp
                  entity: sun.sun
                  show_name: false
                  show_state: false
                  styles:
                    card:
                      - width: 36px
                      - height: 36px
                      - border-radius: 50%
                      - background-color: red
                      - display: flex
                      - justify-content: center
                      - align-items: center
                    icon:
                      - width: 18px
                      - height: 18px
                - type: custom:button-card
                  tap_action:
                    action: toggle
                  icon: mdi:lamp
                  entity: sun.sun
                  show_name: false
                  show_state: false
                  styles:
                    card:
                      - width: 36px
                      - height: 36px
                      - border-radius: 50%
                      - background-color: red
                      - display: flex
                      - justify-content: center
                      - align-items: center
                    icon:
                      - width: 18px
                      - height: 18px
        styles:
          grid:
            - grid-template-areas: "\"n btn\" \"s btn\" \"i btn\""
            - grid-template-columns: 1fr min-content
            - grid-template-rows: min-content min-content 1fr;
          card:
            - padding: 22px
          custom_fields:
            btn:
              - justify-content: end
              - align-self: start
          name:
            - justify-self: start
            - align-self: start
            - fonr-size: 18px
            - font-weight: 500
            - color: black
          icon:
            - justify-self: start
            - align-self: start
            - fonr-size: 14px
            - opacity: "0.6"
          state:
            - min-height: 80px
            - justify-self: start
            - align-self: start
            - fonr-size: 14px
          img_cell:
            - justify-content: start
            - position: absolute
            - width: 130px
            - height: 130px
            - left: 0
            - bottom: 0
            - margin: 0 0 -30px -30px
            - background: red
            - border-radius: 500px
      - type: custom:button-card
        name: Living Room
        icon: mdi:sofa
        entity: sun.sun
        show_state: true
        custom_fields:
          btn:
            card:
              type: vertical-stack
              cards:
                - type: custom:button-card
                  tap_action:
                    action: toggle
                  icon: mdi:lamp
                  show_name: false
                  show_state: false
                  styles:
                    card:
                      - width: 36px
                      - height: 36px
                      - border-radius: 50%
                      - background-color: red
                      - display: flex
                      - justify-content: center
                      - align-items: center
                    icon:
                      - width: 18px
                      - height: 18px
        styles:
          grid:
            - grid-template-areas: "\"n btn\" \"s btn\" \"i btn\""
            - grid-template-columns: 1fr min-content
            - grid-template-rows: min-content min-content 1fr;
          card:
            - padding: 22px
          custom_fields:
            btn:
              - justify-content: end
              - align-self: start
          name:
            - justify-self: start
            - align-self: start
            - fonr-size: 18px
            - font-weight: 500
            - color: black
          icon:
            - justify-self: start
            - align-self: start
            - fonr-size: 14px
            - opacity: "0.6"
          state:
            - min-height: 80px
            - justify-self: start
            - align-self: start
            - fonr-size: 14px
          img_cell:
            - justify-content: start
            - position: absolute
            - width: 130px
            - height: 130px
            - left: 0
            - bottom: 0
            - margin: 0 0 -30px -30px
            - background: red
            - border-radius: 500px
columns: 2
```
