### ISSUE TITLE
HA 2025.0 custom_fields not working anymore

### ISSUE THREAD

**Issue by Ricks88** [custom-cards/button-card#896]
After the upgrade to HA 2025.0 the Button Card the custom_fields: are not styling anymore:

```
name: Oven
icon: mdi:toaster-oven
color_type: card
show_state: true
show_entity_picture: true
custom_fields:
  Percentage:
    card:
      type: custom:button-card
      entity: sensor.oven_programma_voortgang
      tap_action:
        action: none
      show_name: false
      show_state: true
      show_icon: false
      show_entity_picture: false
      color_type: card
      color: rgba(255,255,255,0.8)
      card_mod:
        class: card-custom-field-info
card_mod:
  style: |
    ha-card:hover {
      {% if( is_state('switch.oven_inschakelen', 'on') ) %}
        box-shadow: var(--my-custom-button-card-hover-on) !important;
      {% else %}
        box-shadow: var(--my-custom-button-card-hover-off) !important;
      {% endif %};
    }
styles:
  card:
    - width: 155px
    - height: 155px
    - margin: "-185px 5px 5px 13px"
  name:
    - display: block
    - position: absolute
    - left: 8px
    - bottom: 21px
    - font-weight: bold
    - font-size: 16px
    - font-family: Sans-serif
  img_cell:
    - margin: 0px
    - padding: 0px
  state:
    - display: block
    - position: absolute
    - bottom: 5px
    - left: 12px
    - font-size: 14px
    - font-family: Sans-serif
    - text-transform: capitalize
  icon:
    - width: 100px
    - margin: 0px 0px 5px 0px
  custom_fields:
    Percentage:
      - width: 50px
      - display: block
      - position: absolute
      - top: 8px
      - right: 8px
      - font-size: 14px
      - font-family: Sans-serif
      - text-transform: capitalize
      - overflow: hidden
```
color and fonts are not applying anymore:

![field](https://github.com/user-attachments/assets/bea8fcf6-b650-4360-953a-80053f3a0c1e)

**Comment by Mariusthvdb** [comment]
there must be some config error, as 2025.1 didnt change button-cards as far as I can see

<img width="141" alt="Scherm­afbeelding 2025-01-07 om 14 44 55" src="https://github.com/user-attachments/assets/9732a228-1d78-4ec6-994b-72df425c4364" />

all of my custom fields are populated and styled accordingly.

could it be the
```
  custom_fields:
    Percentage:
```

using the capital P (long shot)

**Comment by Dluis** [comment]
My cards also got unformatted after the update because the Styles are not being applyed: 
example:
```
      card_mod:
        style: |
          ha-card { 
            background-color: transparent;
            border: none;
          }
```

**Comment by Ricks88** [comment]
> My cards also got unformatted after the update because the Styles are not being applyed: example:
> 
> ```
>       card_mod:
>         style: |
>           ha-card { 
>             background-color: transparent;
>             border: none;
>           }
> ```
> 


Seems that some styles from button_card are overruled by elements in HA.

for my example it is all the fonts/texts:

ha-card.button-card-main

probably also with borders, background, colors, in the custom_fields.

![font1](https://github.com/user-attachments/assets/51c1acd1-8e3b-4d67-b442-041b68adefbc)
![font2](https://github.com/user-attachments/assets/6e0d4bbd-46b7-4cf1-b4fe-4a92addeb7ff)

@RomRider 

Can you please have a look and maybe fix it? My whole dashboard rests on your Button Card.

**Comment by RuneNyhuus** [comment]
I have same issue... card_mod: styling is not being applied anymore.
Happen to me also after 2025 update.

**Comment by Mariusthvdb** [comment]
you guys have to please do:

- **not tag the author of this repo**. at all times. issues are relayed to the author, and tagging comes across as demanding/rude
-  **add the type of troubled card** to your post, and **minimize the yaml**. 
- **Not post only a mere 'I have the same issue'** as that is only wasting everyones time, getting notified, and there is no additional info to look at....

also, the title of this issue is not very succint.
just for illustration: I have not a single custom_field that does not work.

Some of you use card_mod in those custom_fields, so maybe you updated/downgraded that resource and it is now stuck in cache...?


fwiw, several people have reported that **downgrading card_mod to 3.4.3, and next updating again to 3.4.4** brings all modifications back.

Other than that, Id **strongly suggest to not use card_mod in the button-card, and use  its own powerful styling options**. Only in rare cases card_mod is required, so please have another look?

**Comment by Dluis** [comment]
@Mariusthvdb you are right and thanks because downgrading card mod and then upgrading it again worked.

**Comment by RuneNyhuus** [comment]
@Mariusthvdb Yeah you are absolutely right.

@Dluis nice trick! it worked for me aswell

**Comment by Ricks88** [comment]
I have to disagree, the project has 250.000 downloads and i saw that the status Project Maintenance is no as of 2023.
I would like to know if there really will be no more updates and so the button card will stop working someday.
They should make it public so others can continue the work of it.. 

as you said, "downgrading card_mod to 3.4.3, and next updating again to 3.4.4" will work. But this is because CARD MOD can be used again to overrule the BUTTON CARD. 

The problem is button card, not card_mod. Some styles set in the "style" option from the button_card do not work anymore.
The issue is simple: ha-card.button-card-main, has default values for "fonts" "witdh" "padding". All the values in you want te edit/set in the custom_fields do not work anymore. inside custom_fields the button_card styles always stay the default values that are in ha-card.button-card-main. 

This means someday, the other "styles" in button_card will also not work anymore. 

The  "fix" @RuneNyhuus and you are talking about is only possible because there is a card_mod. That has the power to overrule this again. Still means button_card is broken.

version 3.5 from card_mod did NOT overrule them anymore. Version 3.4.4 does overrule them again.

**Comment by ngocjohn** [comment]
> This means someday, the other "styles" in button_card will also not work anymore.

Except that it's not true at all... I don't understand why people use card_mod together with button-card... When button-card has so many options, including js etc... By the way, read the documentation of the extra_styles section. 

Check my config, you can edit all css changes via extra_styles. When you create templates for it, for each button custom_fields has its own div id, then you can customize it specifically for a particular element.  

https://github.com/ngocjohn/hass-config/blob/main/config/dashboards/templates/button_card_templates/tpl_base.yaml#L196-L1171


> Than we use card_mod for the values that do not work anymore in the style from button_card

Because you have been using it wrong from the beginning. For styles, manimuplate with ha-card contaier in styles card.. 
```yaml
styles:
 card:
  - background: etc..
  - --ha-card-background-color: red # simple change HA css vars.. 
```
Or via the extra_styles I mentioned above.
```
extra_styles:
  return `
    #card {
      background: red;
    }
```

button-card can work alone, without card-mod...  👍

**Comment by Mariusthvdb** [comment]
believe there even is a famous and ancient example in the docs for the cpu overview, which still works properly on all of the custom fields options.

**Comment by Ricks88** [comment]
Thank you! I will try to, but as far as I see I am indeed not capable to do this.
html/ccs was 15 years ago for me. 

I did copy the example from extra_fields 
```
- type: custom:button-card
  [...]
  custom_fields:
    test_element: My test element
  styles:
    custom_fields:
      test_element:
        - color: red
        - font-size: 13px
```
That dit not work for me anymore. 
I will try to do it with extra_styles or from your example.

Thanks 

PS. Opening the screenshots will give me an error 404 "Kan deze private-user-images.githubusercontent.com pagina niet vinden"

**Comment by Mariusthvdb** [comment]
> Thank you! I will try to, but as far as I see I am indeed not capable to do this. html/ccs was 15 years ago for me.
> 
> I did copy the example from custom_fields

> That dit not work for me anymore. I will try to do it with extra_styles or from your example.

well, what can we tell you.

<img width="150" alt="Scherm­afbeelding 2025-01-10 om 14 42 57" src="https://github.com/user-attachments/assets/1b3e7755-44c1-42ba-9a7b-9bba47c45622" />

**Comment by Ricks88** [comment]
> > Thank you! I will try to, but as far as I see I am indeed not capable to do this. html/ccs was 15 years ago for me.
> > I did copy the example from custom_fields
> 
> > That dit not work for me anymore. I will try to do it with extra_styles or from your example.
> 
> well, what can we tell you.
> 
> <img alt="Scherm­afbeelding 2025-01-10 om 14 42 57" width="150" src="https://private-user-images.githubusercontent.com/33354141/402025349-1b3e7755-44c1-42ba-9a7b-9bba47c45622.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY1MTc0MTUsIm5iZiI6MTczNjUxNzExNSwicGF0aCI6Ii8zMzM1NDE0MS80MDIwMjUzNDktMWIzZTc3NTUtNDRjMS00MmJhLTlhN2ItOWJiYTQ3YzQ1NjIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEwVDEzNTE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MmZmMGUxNWZkODBlZjY2YzUyNmUwNGU1N2YxNmE1MDY1NzJjNmI1Njk4Yjc0ZjE5OTliMTlmODJiMTU4NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GNB4uByVix5S_TeVVgJrrWpgg6zN1G0SsvvHIMI4SaM">
> all working just fine

Is this the right way of using it?

```
type: custom:button-card
entity: binary_sensor.temperatuur_sensor_toilet_moisture_alarm
hold_action:
  action: none
name: Temp/Vocht Meter
icon: mdi:thermometer
color_type: card
show_state: true
show_entity_picture: true
custom_fields:
  temp: |
    [[[
      return `
        <ha-card style="width: 50px; height: 40px; color: red; font-size: 20px;">
        <span>${states['sensor.temperatuur_sensor_badkamer_air_temperature_round'].state}</span>`
    ]]]
styles:
  card:
    - width: 155px
    - height: 155px
    - margin: 0px
  name:
    - display: block
    - position: absolute
    - bottom: 21px
    - left: 8px
    - font-weight: bold
    - font-size: 16px
    - font-family: Sans-serif
  img_cell:
    - margin: 0px
    - padding: 0px
  state:
    - display: block
    - position: absolute
    - bottom: 5px
    - left: 12px
    - font-size: 14px
    - font-family: Sans-serif
    - text-transform: capitalize
  icon:
    - width: 45px
    - margin: 0px 0px 5px 0px
  custom_fields:
    temp:
      - width: 65px
      - display: block
      - position: absolute
      - top: 8px
      - right: 8px
```

![temp](https://github.com/user-attachments/assets/4d2ced8b-b87c-40ca-86b7-6d5dc4ab5d52)

**Comment by Mariusthvdb** [comment]
no....

the 
```
custom_fields:
  temp: |
    [[[
      return `
        <ha-card style="width: 50px; height: 40px; color: red; font-size: 20px;">
        <span>${states['sensor.temperatuur_sensor_badkamer_air_temperature_round'].state}</span>`
    ]]]
```

need to be under styles too!

**Comment by Mariusthvdb** [comment]
I Guess yes...

change the font-size and it works here

**Comment by Ricks88** [comment]
This is working: <ha-card style="width: 50px; height: 40px; color: red; font-size: 20px;"> if I set the size it changes indeed :D 
But is the use of <ha-card ... here the correct way?

and this is not using card_mod anymore inside button_card now.

now i need to find out how to do these things I had in the custom_field before:

```
custom_fields:
  PercentageL:
    card:
      type: custom:button-card
      entity: sensor.temperatuur_sensor_toilet_humidity
      tap_action:
        action: none
      show_name: false
      show_state: true
      show_icon: false
      show_entity_picture: false
      color_type: card
      color: rgba(255,255,255,0.8)
```
Color is also in the <ha card 
Icon must me i think: 

``
<ha-icon icon="" width="0px">

Also, must we nog close the <ha-card etc with "/>" instead of just ">" ?

Sorry for al the questions
