### ISSUE TITLE
trigger button not working anymore

### ISSUE THREAD

**Issue by Niiikoc** [custom-cards/button-card#897]
I’m experiencing an issue after the latest updates to Home Assistant. I have several button cards, and they are no longer working. I haven’t changed the code in a long time, but I noticed the problem after the 2025.1.0 update.

```- type: "custom:button-card"
                template:
                  - yellow_on
                  - card_esh_room
                name: Kitchen
                entity: switch.kitchen_light
                action: toggle
                icon: mdi:knife
                tap_action:
                  action: navigate
                  navigation_path: kitchen
                variables:
                  ulm_custom_card_esh_room_light_entity: switch.kitchen_light
                  ulm_card_esh_room_light_icon_on: mdi:lightbulb-on
                label: >
                  [[[
                    return "🌡️ " + states['sensor.kitchen_thermometer_temperature'].state + " °C" + " 💧 " + states['sensor.kitchen_thermometer_humidity'].state + " %"
                  ]]]
```
This is the code i use for my ui. 

![image](https://github.com/user-attachments/assets/7fb7b70b-d55e-45b7-bc48-3381b819af71)

**Comment by ngocjohn** [comment]
```
  action: toggle
  icon: mdi:knife
  tap_action:
    action: navigate
    navigation_path: kitchen
```
This is a problem with the ulm card, not the custom button.. you can use the toggle in tap_action.. and navigate with hold
```yaml
  tap_action
    action: toggle
  icon: mdi:knife
  hold_action:
    action: navigate
    navigation_path: kitchen
```
