### ISSUE TITLE
FR: Spin Animation

### ISSUE THREAD

**Issue by SeanPM5** [custom-cards/button-card#90]
I've long wanted to be able to make certain icons spin, mainly `mdi:fan` to mimic how fan looks both in real life and also how Apple's HomeKit app does it - [4:34 in this video for an example](https://youtu.be/ZRiDWIHKuz8?t=274). 

When @RomRider added the nice blink animation to this card yesterday it reminded me of this item on my wishlist and I tried to see if I could add a spin animation too.

In line 158 of `button-card.js` I added the following:

```
        @keyframes spin {
          from {transform:rotate(0deg);}
          to {transform:rotate(360deg);}
        }
```

And then for my button I was using this code (last line is the important one).
```
          - type: "custom:button-card"
            entity: switch.fan
            # name: Fan
            icon: mdi:fan
            color_type: card
            tap_action:
              action: toggle
            state:
              - value: 'on'
                color: gray #"#ffc845"
                icon: mdi:fan
                style:
                  - animation: spin .7s linear infinite
```

Here is how it looked: https://gfycat.com/BarePoisedConey

Obviously it needs some further refinement, the state is not supposed to spin alongside the icon for starters. I know absolutely nothing about CSS or javascript though, it took me several hours to even get this far.  So I am hoping someone who also likes this idea can take it over the finish line and add this feature perhaps?

Thanks.
