### ISSUE TITLE
Button confirmation not working on the whole button

### ISSUE THREAD

**Issue by Akilarounet** [custom-cards/button-card#917]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser

**Describe the bug**
Hi, when I add a confirmation option on a button according to the underlying button-card component https://github.com/custom-cards/button-card?tab=readme-ov-file#confirmation, but this works only on the most outer part of the button, not for the icon or name.

I also tried with tap_action, but still the same behaviour.

**Version of the card**
Version: 4.1.2

**To Reproduce**
This is the configuration I used:
```
- type: "custom:button-card"
   template: card_power_outlet
   variables:
     ulm_card_power_outlet_name: Clim
     ulm_card_power_outlet_consumption_sensor: sensor.prise_clim_titi_power
     ulm_card_power_outlet_color: blue
     ulm_card_power_outlet_force_background_color: true
   entity: switch.prise_clim_titi
   confirmation: true
```

same for this method for another button :
```
- type: "custom:button-card"
   template: card_power_outlet
   variables:
     ulm_card_power_outlet_name: Ecrans
     ulm_card_power_outlet_consumption_sensor: sensor.prise_ecrans_titi_power
     ulm_card_power_outlet_force_background_color: true
   entity: switch.prise_ecrans_titi
   tap_action:
     action: more-info
     confirmation:
       text: "[[[ return `Are you sure you want to toggle ${entity.attributes.friendly_name}?` ]]]"
```

**Screenshots**
![Image](https://github.com/user-attachments/assets/779d2cd3-b420-49ed-90a7-6555ba957466)

**Expected behavior**
When I click on the Icon or Name, the switch doesn't show confirmation before toggling my switch.
When I click near the outer part of the button, the confirmation shows up.

**Desktop (please complete the following information):**
 - Browser Firefox
 - Version 136.0.2

**Smartphone (please complete the following information):**
 - Device: Samsung S23U
 - OS: Android 15 | One UI 6.1
 - Home Assistant app
 - Version Core : 2025.3.3
 - Version Superviso 2025.03.3
 - Version OS : 15.0

This bug was originally opened here (https://github.com/UI-Lovelace-Minimalist/UI/issues/1498) but it seems it should be opened here.
