### ISSUE TITLE
Label added to Layout

### ISSUE THREAD

**Issue by DaveTiff** [custom-cards/button-card#923]
**Is your feature request related to a problem? Please describe.**
I have a label which I want on the same line as the name & state

**Describe the solution you'd like**
layout: name_state_label, also be able to click on the label entity

**Describe alternatives you've considered**
None

**Additional context**
This is my code its the return state I want on the same line
`type: custom:button-card
entity: input_datetime.heating_ch_ur_p1_time
show_state: true
show_icon: false
show_label: true
name: P1
layout: name_state
label: |
  [[[
    return  states['input_number.heating_ch_ur_p1_temp'].state + " °C"
  ]]]
styles:
  card:
    - height: 45px
    - width: 150px
    - font-size: 14px
`

**Comment by dcapslock** [comment]
Hi, you can template the state to have what you wish.

e.g. (Used some a basic light entity and its brightness for exampel similar to what you want to achieve).

```yaml
type: custom:button-card
entity: light.bed_light
show_state: true
show_icon: false
show_label: false
name: P1
layout: name_state
state_display: >
  [[[ return helpers.localize(entity) + " " + states['light.bed_light'].attributes.brightness +
  " °C"; ]]]
styles:
  card:
    - height: 45px
    - width: 150px
    - font-size: 14px
```

<img width="162" height="52" alt="Image" src="https://github.com/user-attachments/assets/b65c4f86-a34e-4e60-838c-b1ca5d6b662c" />
